### ISSUE TITLE
Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.

### ISSUE THREAD

**Issue by pwneyy** [galnir/Master-Bot#100]
**Describe the bug**
Error while trying to play music, Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
**To Reproduce**
Install on Repl.it
Run the bot
Type {prefix}play url

**Expected behavior**
The bot plays the music after it joins the voice Channel

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Node Version(Should be v12 atleast): v12.16.3
 - Are python 2.7 and Ffmpeg installed?: Yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): On repl.it, but also tried on PC

**Additional context**
The bot joins the voice channel, does nothing for 15 seconds, then leaves.

**Comment by galnir** [comment]
As far as I know ffmpeg cannot be installed on repl.it so there's that...
Also this error may be emitted because of a bad network connection

**Comment by galnir** [comment]
Will reopen if you respond..

**Comment by pwneyy** [comment]
Yeah it was repl.it, thanks
I have a new issue, see [https://github.com/galnir/Master-Bot/issues/102](url)
