### ISSUE TITLE
Property is undefined

### ISSUE THREAD

**Issue by PeteZionDev** [galnir/Master-Bot#102]
My current issue is that commands like play q or etc give me a property of length is undefined. I am using discord.js version 12 V12 of node and v10 of commando . Your pinned message seems to say that I should be using version 11 but commando does not seem to have an eleventh version . I also made no changes to the index like delete any code etc but I don't really know how to fix it

**Comment by galnir** [comment]
Can you take a screenshot of the error you're getting? Did you clone this repo and then ```npm i```?

**Comment by PeteZionDev** [comment]
wait my bad the issue is  TypeError: Cannot read property 'length' of undefined
 at PlayCommand.run  
However as i mentioned before , i  have run npm i and also have the required versions , and run it on debian 9

**Comment by pwneyy** [comment]
I'm having the same issue

**Comment by pwneyy** [comment]
When I enter a youtube URL, i get this, TypeError: Cannot read property 'hours' of undefined

**Comment by PeteZionDev** [comment]
Quick update , i did not get to fix the error yet but for those who have downloaded the disocrd.js-commando v 11 using npm install discordjs/Commando and run npm view discord-commando version and it says v10 it is because of the nodejs registry , are actually using v11-dev you can check within the node_modules/discord.js-commando/package.json and you shall see that u are using the correct version - But ye as i said still has the issue

**Comment by pwneyy** [comment]
Could be something to do with API limitation

**Comment by galnir** [comment]
@PeteZionDev you don't need to install the dependencies one by one. All you need to do after cloning this repo is simply run 'npm i' as the readme says.
I also want to address what @pwneyy said because this came up in another issue. When using the search function of the play command(!play something and then choose from 1 to 5), the bot uses the YouTube Data API. Your daily quota limit is 10k per day. The search function costs 100 units, so using it too much makes your API key hit its daily quota limit which can throw errors. I'm looking into what can be done but it doesn't look promising. I contacted YouTube and got my quota raised to 1m

**Comment by PeteZionDev** [comment]
> @PeteZionDev you don't need to install the dependencies one by one. All you need to do after cloning this repo is simply run 'npm i' as the readme says.
> I also want to address what @pwneyy said because this came up in another issue. When using the search function of the play command(!play something and then choose from 1 to 5), the bot uses the YouTube Data API. Your daily quota limit is 10k per day. The search function costs 100 units, so using it too much makes your API key hit its daily quota limit which can throw errors. I'm looking into what can be done but it doesn't look promising. I contacted YouTube and got my quota raised to 1m

So do you know what could have caused the property issue ?

**Comment by galnir** [comment]
Yes like I said, either quota limit which you can check on google API console or some failure in installation

**Comment by PeteZionDev** [comment]
interesting , because i just made a complete new folder with the repo run npm with fresh config.json and  i get TypeError: Cannot read property 'length' of undefined. So yep i do not know whats causing it , i havent hit the quota limit either

**Comment by PeteZionDev** [comment]
wait nvm u were right it was the api

**Comment by Oplikk** [comment]
How did you fix your issue?

**Comment by pwneyy** [comment]
@PeteZionDev where did you know that it was the API?

**Comment by pwneyy** [comment]
I didn't pass my quota

**Comment by galnir** [comment]
@pwneyy Make sure the api key you're placing in config.json is the correct one, if that won't work please open an issue so I can help you :)
