### ISSUE TITLE
i have problem

### ISSUE THREAD

**Issue by Mr5ecret** [galnir/Master-Bot#104]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'discord.js-commando'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v14.4.0
4 verbose npm-session b79ea6eb5a02c9dd
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for discord.js-commando@github:discordjs/Commando Error while executing:
7 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/discordjs/Commando.git
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData spawn git ENOENT
8 timing stage:rollbackFailedOptional Completed in 0ms
9 timing stage:runTopLevelLifecycles Completed in 102ms
10 verbose stack Error: spawn git ENOENT
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
10 verbose stack     at onErrorNT (internal/child_process.js:468:16)
10 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
11 verbose cwd C:\Users\hendr\Desktop\music_bot
12 verbose Windows_NT 10.0.18363
13 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "discord.js-commando"
14 verbose node v14.4.0
15 verbose npm  v6.14.5
16 error code ENOENT
17 error syscall spawn git
18 error path git
19 error errno -4058
20 error enoent Error while executing:
20 error enoent undefined ls-remote -h -t ssh://git@github.com/discordjs/Commando.git
20 error enoent
20 error enoent
20 error enoent spawn git ENOENT
21 error enoent This is related to npm not being able to find a file.
22 verbose exit [ -4058, true ]

**Comment by galnir** [comment]
Do you have Git installed?

**Comment by Mr5ecret** [comment]
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/discordjs/Commando.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by galnir** [comment]
You don't have Git installed..

**Comment by Mr5ecret** [comment]
it doesnt let me install git

**Comment by galnir** [comment]
Git is not installed via npm, follow the README before opening an issue
