### ISSUE TITLE
TypeError: Cannot read property 'result' of undefined

### ISSUE THREAD

**Issue by PeteZionDev** [galnir/Master-Bot#105]
**Describe the bug**
I use the play command to play a song and after some time it automatically leaves the voice channel and gives me that error in console , after that i have to restart the bot for it to fully wok, i also run a really fast iconnection on my vps so ther eis no way its on the speed the error i get is TypeError: Cannot read property 'result' of undefined
the api is also good and has no issue , last but not least i noitced that the leave command after u pause or stop the bot tends to reproduce the error i jsut reported

**Comment by galnir** [comment]
Can you take a screenshot of the error as displayed in console?

**Comment by PeteZionDev** [comment]
This is what happens when u stop or pause the q and then run leave . And the bot never leave the VC and just crashes 
![IMG_20200705_122414](https://user-images.githubusercontent.com/55034920/86529609-9fa7f300-beba-11ea-91eb-fb7806045a0c.jpg)

**Comment by galnir** [comment]
Pull the new changes and let me know if that fixed it for you

**Comment by PeteZionDev** [comment]
i play a song , then i use stop and then leave and the bot is in the voice channel , basically when i run  stop it stops aand on leave it plays the track for 300ms an then ye it stops and doesnt leave the voice channel

**Comment by galnir** [comment]
Weird I tested it extensively and on 2 operating systems.. Are you pulling changes via Git or copying code?

**Comment by PeteZionDev** [comment]
Wait no basically it does not disconnect once i have run the leave comand , the dispatcher ends but it just doesnt disconnect

**Comment by galnir** [comment]
Alright what about my question?

**Comment by PeteZionDev** [comment]
I went to check the change log and manually made the code changes since they werent that many

**Comment by galnir** [comment]
Then I can't figure out why this is happening since you may have copied something wrong, not necessarily this commit maybe some older one. When cloning a repo all you gotta do is run 'git pull' whenever I commit a change

**Comment by PeteZionDev** [comment]
Okay sure , i cloned the repo now and i still get the same issue with my leave command , it stops the sonf but doesnt make the bot leave the voice channel

**Comment by galnir** [comment]
And you're not getting any error in console?

**Comment by PeteZionDev** [comment]
nope , thats the thing , the console is logging no errors which is confusing me

**Comment by galnir** [comment]
I honestly have no idea what can cause it, as I said I tested it and if you clone the repo and not modify anything related to that it should work. I'll try to think what can cause it

**Comment by PeteZionDev** [comment]
I appreciate the help , by the way i wanted to suggest an improvement 
on the index.js 
client.on('voiceStateUpdate', async(___, newState) => {
    newState.guild.me.voice.setSelfDeaf(true)

to reduce resource usage and privacy matters

**Comment by galnir** [comment]
Great suggestion, why not open a pull request? :)

**Comment by PeteZionDev** [comment]
honestly i do not even know how to use github , lmao ye idk what i did with the request  , merged it i think lmao idk my bad

**Comment by PeteZionDev** [comment]
fixed

**Comment by galnir** [comment]
@PeteZionDev How did you fix it?
