### ISSUE TITLE
Issue regarding cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by pwneyy** [galnir/Master-Bot#106]
Hi Nir,

As you know, I was in a issue today by peteziondev, you asked me to make an issue if my token wasn't invalid, and it isn't

Thanks 
Pwn

**Comment by galnir** [comment]
Please provide a screenshot of the error message you're getting

**Comment by pwneyy** [comment]
TypeError: Cannot read property 'length' of undefined
2|pwn      |     at PlayCommand.run (/root/pwn/commands/music/play.js:148:51)
2|pwn      |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2|pwn      |     at async CommandoMessage.run (/root/pwn/node_modules/discord.js-commando/src/extensions/message.js:235:20)
2|pwn      |     at async CommandDispatcher.handleMessage (/root/pwn/node_modules/discord.js-commando/src/dispatcher.js:143:19)
2|pwn      | TypeError: Cannot read property 'queue' of undefined
2|pwn      |     at PlayCommand.run (/root/pwn/commands/music/play.js:181:31)
2|pwn      |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2|pwn      |     at async CommandoMessage.run (/root/pwn/node_modules/discord.js-commando/src/extensions/message.js:235:20)
2|pwn      |     at async CommandDispatcher.handleMessage (/root/pwn/node_modules/discord.js-commando/src/dispatcher.js:143:19)
2|pwn      | TypeError: Cannot read property 'queue' of undefined
2|pwn      |     at PlayCommand.run (/root/pwn/commands/music/play.js:96:33)
2|pwn      |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2|pwn      |     at async CommandoMessage.run (/root/pwn/node_modules/discord.js-commando/src/extensions/message.js:235:20)
2|pwn      |     at async CommandDispatcher.handleMessage (/root/pwn/node_modules/discord.js-commando/src/dispatcher.js:143:19)

**Comment by galnir** [comment]
There's no length property on line 148, did you delete or add code?

**Comment by pwneyy** [comment]
Sorry one sec, could have been a wrong error

**Comment by pwneyy** [comment]
Ok, now im getting An error has occured when trying to get the video ID from youtube

**Comment by pwneyy** [comment]
TypeError: Cannot read property 'queue' of undefined

**Comment by galnir** [comment]
You still haven't answered my question. The errors related to YouTube like the one you just got usually imply that your API key is not valid. They are thrown when sending a request to YouTube and getting nothing or an API token error in response

**Comment by pwneyy** [comment]
Will I try regenerating my api key?

**Comment by pwneyy** [comment]
> There's no length property on line 148, did you delete or add code?
nvm, i sent you the wrong error :D

**Comment by galnir** [comment]
Follow [this](https://developers.google.com/youtube/v3/getting-started). Only the first 3 steps and make sure you do step 3b .
Also if you modify/delete/add code I can't help you because I don't know what you did

**Comment by pwneyy** [comment]
I am still getting that error, unfortunately

**Comment by galnir** [comment]
Take a screenshot of the error, don't send it as a message I need to see the full log

**Comment by pwneyy** [comment]
Ok

**Comment by pwneyy** [comment]
hmm, it doesn't output the error to the console
only to the chat, ill send it here

**Comment by pwneyy** [comment]
![sfdsdfsdf](https://user-images.githubusercontent.com/53976867/86338822-b6e0a980-bc4a-11ea-8475-bed22bcbc75d.PNG)

**Comment by galnir** [comment]
It doesn't make sense that you're getting different errors, have you modified anything in code? You still haven't answered that

**Comment by pwneyy** [comment]
No, I promise I haven't!

**Comment by galnir** [comment]
When searching for a song, do you see 5 results?

**Comment by pwneyy** [comment]
Yes

**Comment by pwneyy** [comment]
It is definitely something with my code.

**Comment by pwneyy** [comment]
I just did a git pull
and it works fine!

**Comment by pwneyy** [comment]
Sorry for the trouble dude, is it ok if i use some of your commands in my bot?

**Comment by galnir** [comment]
Alright please do the following:
Around like 212 you'll have the return statement which returns the message you're seeing to chat. In the line before the return statement add this line:
console.error(err);

Before that line you'll also have an if statement and before that if statement there's this line:
.catch(function() {

Change that line to this:
.catch(function(err) {

After you do that try to play a song and take a screenshot of the error that will appear in your console

**Comment by pwneyy** [comment]
Ok

**Comment by galnir** [comment]
You can't just copy commands to your bot and expect them to work they rely on info received from index.js

**Comment by pwneyy** [comment]
Yes, I am getting the error now.

**Comment by pwneyy** [comment]
Sorry. I am gonna get the full error now, I just added the code

**Comment by pwneyy** [comment]
By the way, I also copied the functions for the queue into my index.js

**Comment by pwneyy** [comment]
hmm, it doesn't output the error to the console

**Comment by pwneyy** [comment]
`     .catch(function(err) {
        if (songEmbed) {
          songEmbed.delete();
        }
        console.error(err);
        return message.say(
          'Please try again and enter a number between 1 and 5 or exit'
        );
      });
  }`

**Comment by galnir** [comment]
What am I debugging here? I mentioned before I can't help you if you **copy** into an existing bot. I can help you if you **clone** this repository

**Comment by pwneyy** [comment]
Alright, thanks anyways...

**Comment by galnir** [comment]
Copying code from this repo to your bot or whatever will make the features not work as expectdd

**Comment by pwneyy** [comment]
Yeah, im sure ill figure it out

**Comment by galnir** [comment]
I don't mean to offend you but you need to understand this is like taking parts out of a Honda and placing them into a Ford or whatever and then wondering why your car doesn't work as expected

**Comment by galnir** [comment]
If you want to enjoy these features you need to clone this repository, not copy code into your bot and wonder why it doesn't work

**Comment by pwneyy** [comment]
Yeah, I did

**Comment by pwneyy** [comment]
Thanks
