### ISSUE TITLE
while playing music,  it stops until I use command 'skip'

### ISSUE THREAD

**Issue by iwbkwi** [galnir/Master-Bot#109]
**Describe the bug**
The bot works, but has problem playing music .

As you can see in the title, I can play music but it stops after playing music a few minutes .

I used the 'play' command like below

![image](https://user-images.githubusercontent.com/45188218/86690923-53d48580-c043-11ea-94e6-c386a49898e8.png)
(It seems to search music from YT )

It is hard to specifiy the case. Sometimes it works properly, but it stops almost case. 

So the next(queued) music is not played. it Just stucks..

The only way I can make it play the next music is using the command 'skip'.

I'd like to know if I can get any log or usable information from shell.(I don't think it provides any logs..)

Thank you

**Desktop (please complete the following information):**
 - OS: Raspbian10
 - Node Version : v14.5.0 
 - Are python 2.7 and Ffmpeg installed?: yes
 - How are you hosting the bot : Using my own Rpi

**Additional context**

**Comment by galnir** [comment]
It's also hard for me to point at the problem. As far as I know this can happen as a result of a bad network connection. If it were to happen because of an error, you'd get an error message in console. So first of all how's your connection?

**Comment by iwbkwi** [comment]
> It's also hard for me to point at the problem. As far as I know this can happen as a result of a bad network connection. If it were to happen because of an error, you'd get an error message in console. So first of all how's your connection?


All connection is good, no problem. I'm using wired direct connection between home router and rpi.
How can I get error message in console?.

**Comment by galnir** [comment]
There's no way, if there was an error it wouldn't let you skip a song. Try to add the line I removed in 7d6c0e232bf2f89a8b39481dd5ec9bc461ef7486 and let me know if it worked

**Comment by iwbkwi** [comment]
> There's no way, if there was an error it wouldn't let you skip a song. Try to add the highWaterMark line I removed in [7d6c0e2](https://github.com/galnir/Master-Bot/commit/7d6c0e232bf2f89a8b39481dd5ec9bc461ef7486) and let me know if it worked

It works :) though I tested just 2 songs..

Can you briefly tell me what the 'highWaterMark's role is ?

**Comment by galnir** [comment]
"How much of the video download to buffer into memory". Basically how much to download before playing. I removed it because it would prevent videos longer than 2 hours to play. I'll see what can be done to solve both issues

**Comment by iwbkwi** [comment]
> Basically how much to download before playing. I removed it because it would prevent videos longer than 2 hours to play. I'll see what can be done to sol

Thanks! I've also checked that description in README file.
Are you going to close this issue? or should I?

**Comment by galnir** [comment]
Doesn't matter ;)

**Comment by iwbkwi** [comment]
Closed, Thanks!
