### ISSUE TITLE
Faild to locate video 

### ISSUE THREAD

**Issue by PeteZionDev** [galnir/Master-Bot#110]
I am trying to play a song but it seems like it fails to play any video (even if i provide it with a link or use the search )
I know you do not work for youtube but , i was wondering if u knew of any possible reasons that could have caused this , the google console gives me the current issue 
![image](https://user-images.githubusercontent.com/55034920/86726317-1ec03700-c033-11ea-9927-1b19efeefb89.png) 
And i do not know what to do . 
At first i thought it had to do with the quota but i have only used 400 requests and my quota is limited to 1.000.000 since i raised it like a week ago

**Comment by galnir** [comment]
What error does the bot throw?

**Comment by PeteZionDev** [comment]
The console ? None

**Comment by galnir** [comment]
Not even in chat? How's that possible? If no song data is returned it must throw some sort of an error

**Comment by PeteZionDev** [comment]
at runMicrotasks (<anonymous>)
    |     at processTicksAndRejections (internal/process/task_queues.js:9                                                                                                             7:5) {
   |   method: 'post',
   |   path: '/channels/729739138840133662/messages',
    |   code: 50007,
    |   httpStatus: 403
    | }
 | TypeError: connection.play is not a function
    |     at /root/k/commands/music/play.js:246:22
    |     at runMicrotasks (<anonymous>)
   |     at processTicksAndRejections (internal/process/task_queues.js:9                                                                                                             7:5)
    | Unhandled promise rejection: TypeError: Cannot read property 'leave                                                                                                             ' of null
 |     at /root/k/commands/music/play.js:288:55
   |     at runMicrotasks (<anonymous>)
    |     at processTicksAndRejections (internal/process/task_queues.js:9

**Comment by PeteZionDev** [comment]
o by the way i get this  Cannot read property 'leave ' of null issue quite often

**Comment by galnir** [comment]
You're not supposed to get such error, and there's no leave call in line 288. If you modify/delete/add code I can't tell why you're getting the error you're getting

**Comment by PeteZionDev** [comment]
I see , i have modified the file with the modifications being that i ussed embeds  so within the message.say('instead of')
passing a string i used an embed , now on line 288
`.catch(function(e) {
                console.error(e);
    //line 288            return message.guild.me.voice.channel.leave();
            });`

**Comment by galnir** [comment]
Can you clear things up and fill the issue template? Explain what's happening when you're doing X
