### ISSUE TITLE
Stays silent when "playing music" in vc

### ISSUE THREAD

**Issue by Natemo6348** [galnir/Master-Bot#112]
**Describe the bug**
Every time I try to play music it stays silent while in the vc and logs a VC timeout

**To Reproduce**
Simply try to play music

**Expected behavior**
Should start playing music

**Screenshots**
![PicsArt_07-10-04 11 07](https://user-images.githubusercontent.com/64607128/87203360-0caaf680-c2c8-11ea-9908-2605637b10ee.png)

**Desktop (please complete the following information):**
 Hosting on repl.it with modules installed as well as latest node and python 2.7

**Comment by galnir** [comment]
As far as I know ffmpeg cannot be installed on repl.it, hence it won't play audio

**Comment by Natemo6348** [comment]
Oh ok, well I guess I'll have to try hosting elsewhere, somewhere it will stay online

**Comment by Natemo6348** [comment]
Well I switched back to glitch.com and it's working fine now, guess I just have to keep the tab open now, thanks
