### ISSUE TITLE
Cant Install the node modules 

### ISSUE THREAD

**Issue by SureLucky12** [galnir/Master-Bot#115]
I got a problem installing the node modules with the npm i command.

Its just a error, i dont understand what it means ( not installing the resoruces)

**Expected behavior**
Do install the resources what it needs, i cant install it manual

**Screenshots**
(https://user-images.githubusercontent.com/62520818/87229064-7b11b680-c3a5-11ea-909c-de4cd4959166.PNG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...] - Windows 10 Pro
 - Node Version(Should be v12 atleast):  v12.17.0.
 - Are python 2.7 and Ffmpeg installed?: python 3.8 and python 2.7 and yes ffmpeg is installed
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): over localhost

Error Log:
[Error.txt](https://github.com/galnir/Master-Bot/files/4907194/Error.txt)

**Comment by galnir** [comment]
It's a problem with Git, probably means that it is not installed. Git is listed as a requirement in the instructions.

**Comment by SureLucky12** [comment]
and what can i do now?

**Comment by galnir** [comment]
Install [Git](https://git-scm.com/downloads)

**Comment by SureLucky12** [comment]
![5](https://user-images.githubusercontent.com/62520818/87229647-202e8e00-c3aa-11ea-9260-1898230307c2.PNG)
Am i Stupid or am i doing something wrong?

**Comment by galnir** [comment]
Have you installed Git..?

**Comment by SureLucky12** [comment]
Github desktop ? yes

**Comment by SureLucky12** [comment]
how git works ?

**Comment by galnir** [comment]
All I instructed you to do is to install Git using the provided link and install the dependencies again like you did with ```npm i```

**Comment by SureLucky12** [comment]
yeah it works thanks man

**Comment by galnir** [comment]
No problem, enjoy :)

**Comment by galnir** [comment]
If you only want to use the music functions get the youtube token and the lyrics token
