### ISSUE TITLE
Got a problem with Musictrivia

### ISSUE THREAD

**Issue by SureLucky12** [galnir/Master-Bot#116]
**Describe the bug**
When i change the default of numberofsongs( 5 to 10) the minigame is not working as fine what it should, maybe you know why? or could describe how to change it?

**Expected behavior**
I hoped to get more rounds and a longer time. 

**Screenshots**
There is no error in the console and endtrivia dont works after you change time and etc.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...] Windows 10 pro
 - Node Version(Should be v12 atleast):  v12.17.0.
 - Are python 2.7 and Ffmpeg installed?: yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): localhost

**Comment by galnir** [comment]
Did you clone this repo or copy code to another bot?

**Comment by SureLucky12** [comment]
i cloned it

**Comment by galnir** [comment]
Changing the number doesn't do anything except fetch more songs from the json file. Does it work for any other number? And what did you change exactly? If you changed more stuff I can't figure out why this is happening. Does the regular play command work? Give me more information

**Comment by SureLucky12** [comment]
i think i found my problem, i wrote : 
{
      "url": " --- link ---",
      "singer": "Travis Scott" , " Kid Cudi",
      "title": "The Scotts"
     }
  ]
}
i dont got a solution to write 2 singers

**Comment by galnir** [comment]
Ok so is the problem you opened the issue for solved?
