### ISSUE TITLE
Error: read ECONNRESET  error while listening to music

### ISSUE THREAD

**Issue by SureLucky12** [galnir/Master-Bot#117]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. 

**Describe the bug**
After some bass boost music that just pop in the console: 
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
But after that everything worked that bot is working fine but what econreset means and is there a way to fix?

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...] Windows 10 pro
 - Node Version(Should be v12 atleast): v12.17
 - Are python 2.7 and Ffmpeg installed?: yep
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): localhost

**Additional context**

**Comment by galnir** [comment]
This isn't related to the bot, it implies there's a network problem. Either your internet is unstable or slow
