### ISSUE TITLE
Error when i want to play music

### ISSUE THREAD

**Issue by razvandamian** [galnir/Master-Bot#123]
**Describe the bug**
A clear and concise description of what the bug is: An error occurred while running the command: TypeError: Cannot read property 'length' of undefined
You shouldn't ever receive an error like this.
Please contact Petre Ispirescu#0060.

**To Reproduce**
1. Use 'x' command
2. provide 'y' argument

**Expected behavior**
A clear and concise description of what you expected to happen: when i want to play something i get that error over there...

**Screenshots**
![image](https://user-images.githubusercontent.com/67657296/88239378-ec4a4700-cc8c-11ea-99b4-b38e428fb47d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version(Should be v12 atleast): 12
 - Are python 2.7 and Ffmpeg installed?: Yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): heroku

**Additional context**

**Comment by galnir** [comment]
Why did you open the same issue 2 times then closed then opened this one? 
As far as I know there is no way to install ffmpeg on heroku and it's essential for playing music, so how did you install it as you say its installed?

**Comment by razvandamian** [comment]
> Why did you open the same issue 2 times then closed then opened this one?
> As far as I know there is no way to install ffmpeg on heroku and it's essential for playing music, so how did you install it as you say its installed?

don't know, i was thinking its installed on heroku, but that its not working too on my pc, and i have ffmpeg, and when i uploaded my first time on heroku the bot was working, after 1-2 days im getting this error...

**Comment by razvandamian** [comment]
> Why did you open the same issue 2 times then closed then opened this one?
> As far as I know there is no way to install ffmpeg on heroku and it's essential for playing music, so how did you install it as you say its installed?

yea look sir, don't know why but now its working, yesterday 
![image](https://user-images.githubusercontent.com/67657296/88288073-e9d30600-ccfb-11ea-82da-2768307254a2.png)

**Comment by galnir** [comment]
Yesterday it didn't work, and now it's working and you didn't change anything?

**Comment by razvandamian** [comment]
![image](https://user-images.githubusercontent.com/67657296/88288130-ff483000-ccfb-11ea-9df3-831c1e1098be.png)

2 AM in the morning its not working if you can see, and today its working

**Comment by razvandamian** [comment]
> Yesterday it didn't work, and now it's working and you didn't change anything?

yes

**Comment by galnir** [comment]
> > Yesterday it didn't work, and now it's working and you didn't change anything?
> 
> yes

well I have no clue why, if it doesn't work again open a new issue and I'll try to figure out :)

**Comment by razvandamian** [comment]
> > > Yesterday it didn't work, and now it's working and you didn't change anything?
> > 
> > 
> > yes
> 
> well I have no clue why, if it doesn't work again open a new issue and I'll try to figure out :)

ok, thanks for getting your time!
