### ISSUE TITLE
Vote Skip

### ISSUE THREAD

**Issue by Zeroo000** [galnir/Master-Bot#125]
It would be cool if you could vote skip when there's a multiple users joined in a voice channel.

**Comment by Lebyy** [comment]
Yes true

**Comment by razvandamian** [comment]
and a force skip only for a role or smth if a user with these feature its on the channel

**Comment by galnir** [comment]
@Zeroo000 How come you ask for features here, then ofc use them in your public bot and you don't disclose source? 
Also in your bot's README:
''Begging/Asking for the main bot's source code is not possible''?

**Comment by Chief-Queef** [comment]
Galnir: https://www.youtube.com/watch?v=e9ViAIsWdVI

**Comment by galnir** [comment]
> Galnir: https://www.youtube.com/watch?v=e9ViAIsWdVI

Using code is not a problem at all. All that needs to be done is to disclose source
