### ISSUE TITLE
how to make the !help command gives invite link of the bot too

### ISSUE THREAD

**Issue by himekichi** [galnir/Master-Bot#127]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs.

**Describe the bug**

**To Reproduce**
1. Use 'x' command
2. provide 'y' argument

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...]
 - Node Version(Should be v12 atleast): 
 - Are python 2.7 and Ffmpeg installed?:
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...):

**Additional context**

**Comment by ThaddeusKKR** [comment]
#120

**Comment by galnir** [comment]
The help command comes with Commando. In order to modify it you need to first disable it then write a new one, please read the issue @ThaddeusKKR mentioned above :)
