### ISSUE TITLE
Im gettin this issue again... (TypeError: Cannot read property 'length' of undefined)

### ISSUE THREAD

**Issue by razvandamian** [galnir/Master-Bot#129]
TypeError: Cannot read property 'length' of undefined

![image](https://user-images.githubusercontent.com/67657296/88488700-abf20e00-cf97-11ea-92f6-7299a9d197df.png)

**Comment by galnir** [comment]
Did you clone this repo or copy commands?

**Comment by razvandamian** [comment]
> Did you clone this repo or copy commands?

Clone, but it dosen't work with your original as well...

**Comment by razvandamian** [comment]
I've opened another issue ticket 3 day's ago, and i have again the same issue, its possible to do that couse that "Music 1, 2, 3, 4, 5", and u need to choose? that's where i see .length

**Comment by razvandamian** [comment]
U got something?

**Comment by galnir** [comment]
What do you mean by cloned but it doesn't work with my original?
After dozens of "cannot read property 'xyz' of undefined" issues, one thing I've learned is that it always happens because code was changed or the user copied code from this repo to an existing bot. If you clone this repo and not change anything important in music commands this should never happen

**Comment by razvandamian** [comment]
> What do you mean by cloned but it doesn't work with my original?
> After dozens of "cannot read property 'xyz' of undefined" issues, one thing I've learned is that it always happens because code was changed or the user copied code from this repo to an existing bot. If you clone this repo and not change anything important in music commands this should never happen

I mean its not working with the original play command

**Comment by Oplikk** [comment]
Make sure you clone the repo (I used GitHub Desktop app) to a Clean folder, then open your command prompt / vs there, and install all dependencies by using command `npm i`
Everytime this problem occured to me was when i did not cloned the repo to a clean folder or coppied / added another files into the folder.

**Comment by razvandamian** [comment]
> Make sure you clone the repo (I used GitHub Desktop app) to a Clean folder, then open your command prompt / vs there, and install all dependencies by using command `npm i`
> Everytime this problem occured to me was when i did not cloned the repo to a clean folder or coppied / added another files into the folder.

So, you has the problem too, clone the repo again, npm i in console, put all my files back in the new repo copyed and its works?

**Comment by Oplikk** [comment]
> > Make sure you clone the repo (I used GitHub Desktop app) to a Clean folder, then open your command prompt / vs there, and install all dependencies by using command `npm i`
> > Everytime this problem occured to me was when i did not cloned the repo to a clean folder or coppied / added another files into the folder.
> 
> So, you has the problem too, clone the repo again, npm i in console, put all my files back in the new repo copyed and its works?

Yep. Just make sure you clone the repo correctly, install dependencies and needed apps (node.js, git, python 2.7).

**Comment by razvandamian** [comment]
> > > Make sure you clone the repo (I used GitHub Desktop app) to a Clean folder, then open your command prompt / vs there, and install all dependencies by using command `npm i`
> > > Everytime this problem occured to me was when i did not cloned the repo to a clean folder or coppied / added another files into the folder.
> > 
> > 
> > So, you has the problem too, clone the repo again, npm i in console, put all my files back in the new repo copyed and its works?
> 
> Yep. Just make sure you clone the repo correctly, install dependencies and needed apps (node.js, git, python 2.7).

Ok i will try it, now again i don't have the problem, it tooks few hours and after it works perfectly, if i get this again i will try your option, thanks!
