### ISSUE TITLE
the bot wont play

### ISSUE THREAD

**Issue by himekichi** [galnir/Master-Bot#130]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs.

**Describe the bug**

**To Reproduce**
1. Use 'x' command
2. provide 'y' argument

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...]
 - Node Version(Should be v12 atleast): 
 - Are python 2.7 and Ffmpeg installed?:
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...):

**Additional context**

Error [VOICE_CONNECTION_TIMEOUT]: Connection not established within 15 seconds.
    at VoiceConnection.authenticateFailed (G:\master electric\node_modules\discord.js\src\client\voice\VoiceConnection.js:303:26)
    at G:\master electric\node_modules\discord.js\src\client\voice\VoiceConnection.js:324:61     
    at Timeout.<anonymous> (G:\master electric\node_modules\discord.js\src\client\BaseClient.js:83:7)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7) {
  [Symbol(code)]: 'VOICE_CONNECTION_TIMEOUT'
the bot voice wont play any song

**Comment by galnir** [comment]
The issue template is meant to be filled, please fill it (answer the questions) it's important
