### ISSUE TITLE
Ban/Kick results in an error

### ISSUE THREAD

**Issue by Oplikk** [galnir/Master-Bot#132]
**Describe the bug**
When using the ban or kick command, and specifying the user and a reason, i will get an error

**To Reproduce**
Simply use the kick or ban command, but i believe that this is a specific problem on my side, but iam unable to fix it myself

**Expected behavior**
Banning or kicking a user

**Screenshots**
![image](https://user-images.githubusercontent.com/67639836/88695125-c0521a00-d101-11ea-98c7-216986d8f640.png)

**Desktop (please complete the following information):**
 - OS: **Windows 10**
 - Node Version(Should be v12 atleast): **V14.4**
 - Are python 2.7 and Ffmpeg installed?: **properly installed, music commands working normally**
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): **Local hosting - running in VS Code**

**Additional context**
When trying any of these commands, it also spits out an error into the console:
`(node:23916) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
user_id: Value "<@!297016342052077579>" is not snowflake.
    at RequestHandler.execute (C:\Users\marti\Desktop\Master-Bot\node_modules\discord.js\src\rest\RequestHandler.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23916) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I should also add that the bot is set as and administrator, third highest role on the server, and the user is a normal user with default rights, bottom of the roles

**Comment by Oplikk** [comment]
Issue folow up:
To mention, i did make some changes to the code, but that was only deleting ''Resources'' folder, some commands from ''Others'' section (only left there Cat, Uptime, Whomademe, and say commands), and added ''Help command'' in guild folder (I deactivated the default Help command which is in commandu using another issue where this was discussed). 
The problem is present with a cloned repo with no changes too, so i guess these things does not make any difference

**Comment by razvandamian** [comment]
you tried to mention the user or copy his id?

**Comment by Oplikk** [comment]
> you tried to mention the user or copy his id?

Tried both, the result is always the same

**Comment by razvandamian** [comment]
> > you tried to mention the user or copy his id?
> 
> Tried both, the result is always the same

I have no idea, i deleted the folder with ban etc and added an another bot to do it, u can do that too

**Comment by galnir** [comment]
I'm aware of the issue, will try to commit a fix today

**Comment by galnir** [comment]
@Oplikk Solved 7c8de01 , thanks for reporting this bug!

**Comment by Oplikk** [comment]
Hello galnir!
Thank you for the quick fix.
However, this exact error is present in both Ban and Kick command, so you still have to edit the Kick command in the main branch! 
Thank you for your time, have a good day!
