### ISSUE TITLE
Added to the playlist not working

### ISSUE THREAD

**Issue by razvandamian** [galnir/Master-Bot#133]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**

**To Reproduce**
1. Use 'x' command
2. provide 'y' argument

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/67657296/88723892-51d98000-d132-11ea-8646-8e7949dad359.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version: 12.18.3
 - Are python 2.7 and Ffmpeg installed?: Yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): Heroku

**Additional context**
When i play a playlist from youtube, i don't get any info message to tell me its a playlist, in play command i changed a little bit the play embed and the queue, i will try now to reclone original and play a playlist to try finding what's the problem, or if you know u can help me...

**Comment by galnir** [comment]
My bot doesn't send an embed that looks like that... If you modified my code and added features I can't help you because I don't know what you did and how you did it. The issue template says "Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs."

**Comment by razvandamian** [comment]
> My bot doesn't send an embed that looks like that... If you modified my code and added features I can't help you because I don't know what you did and how you did it. The issue template says "Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs."
> I'll be glad to help you but you haven't provided any information at all. I don't know what OS you're running the bot on, what node version, what code you added/removed/changed etc.. The issue template is meant to be filled

done.

**Comment by galnir** [comment]
You said you've changed things about the queue, I can't figure out what's wrong because I don't know what you did. I can assure you that all features are working fine when you clone the repo and follow the instructions
