### ISSUE TITLE
[Suggestion] Add a limit to the loop command.

### ISSUE THREAD

**Issue by Lebyy** [galnir/Master-Bot#135]
Some people who like to troll just keep the bot playing music and loop it a million times which is just a wastage of ram and cpu.

**Comment by galnir** [comment]
So what's your suggestion? It barely takes cpu and ram from my observations. The bot is meant to be self hosted on small "friends and family" servers, hence why I didn't put much effort in moderation features

**Comment by Lebyy** [comment]
Alright.
