### ISSUE TITLE
YouTubeAPI Quota

### ISSUE THREAD

**Issue by NoahLavelle** [galnir/Master-Bot#136]
This probably isn't the place to ask, but how did you get around the quota usage for the YouTubeAPI? I was testing some music features and managed to use all of it.

**Comment by galnir** [comment]
Your daily YouTube API quota is 10k units. Searching for a song (!play something and then choose from 1 to 5) costs 100 units. Providing a url instead of a name costs around 5-10 units.
Sadly all you can do is ask YouTube to increase your quota

**Comment by NoahLavelle** [comment]
Thanks. Unfortunately I cannot apply for a quota increase because I am an individual and business details are required.

**Comment by galnir** [comment]
@NoahLavelle you can apply, I did and received an increase. Just write your name or smt instead of a business name

**Comment by NoahLavelle** [comment]
Oh, nice. I didn't know that. I'll give it a go.
