### ISSUE TITLE
[ Question ] How do I get the song number in the queue when it is added

### ISSUE THREAD

**Issue by ThaddeusKKR** [galnir/Master-Bot#137]
When I use the `play` command, a song is added to queue. How do I get the song number in the queue?

**Comment by galnir** [comment]
!queue

**Comment by ThaddeusKKR** [comment]
No, as in the code. Like for a `playskip` command that adds the song to the queue and skips to it.

**Comment by galnir** [comment]
@ThaddeusKKR message.guild.musicData.queue is an Array, you can read its length

**Comment by ThaddeusKKR** [comment]
Okay thanks!
