### ISSUE TITLE
Music cuts out half way through 

### ISSUE THREAD

**Issue by daneleo** [galnir/Master-Bot#138]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
When using the play command, the music plays then half way through the song the music just stops completely.  I then receive this issue 
`Error: input stream: Status code: 416 at ClientRequest.<anonymous> (C:\Users\Dane\musicbot\node_modules\miniget\dist\index.js:156:27) at Object.onceWrapper (events.js:422:26) at ClientRequest.emit (events.js:315:20) at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27) at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17) at TLSSocket.socketOnData (_http_client.js:469:22) at TLSSocket.emit (events.js:315:20) at addChunk (_stream_readable.js:295:12) at readableAddChunk (_stream_readable.js:271:9) at TLSSocket.Readable.push (_stream_readable.js:212:10)`
After that I have to restart the bot to get it working again 

**To Reproduce**
!play URL

**Expected behavior**
should play the entire song 

**Screenshots**
Currently at work so cannot take a picture of the error, however posted above

**Desktop (please complete the following information):**
 - OS: windows
 - Node Version(Should be v12 atleast): node 12
 - Are python 2.7 and Ffmpeg installed?: yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): locally while I'm testing it then to the vps 

**Additional context**
Just that the error appears and the music cuts out

Sorry for the long reply BTW, work came up, and totally forgot about reposting

**Comment by galnir** [comment]
@daneleo Add this line in play.js after line 233: ```highWaterMark: 1024 * 1024 * 10```, so it'll look like the left side of [this commit](https://github.com/galnir/Master-Bot/commit/7d6c0e232bf2f89a8b39481dd5ec9bc461ef7486) and don't forget the comma.
ytdl-core can be unexpected sometimes, the reason I removed that line was because it would stop playing a long video or mix after it reached 4 hours of playing. 
Do that and tell me if that worked :)

**Comment by daneleo** [comment]
Yer that fixed it thank you!
