### ISSUE TITLE
error with commands

### ISSUE THREAD

**Issue by EpicZapraki** [galnir/Master-Bot#139]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
ok so when i tried to run the bot and an error code appeared but the bot successfully turned online! then i tred the .play command (it didntwork)and on terminal on vscode an error code appeared again pls somebodyy help

**To Reproduce**
1. Use 'x' command
2. provide 'y' argument

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit 2004 VERSION
 - Node Version(Should be v12 atleast): 12.18.2
 - Are python 2.7 and Ffmpeg installed?:yeahhhh
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...):heroku 

**Additional context**

**Comment by galnir** [comment]
Okay so what error appeared...?
