### ISSUE TITLE
Bot disconnect randomly

### ISSUE THREAD

**Issue by razvandamian** [galnir/Master-Bot#141]
When i play music, about at half of the song, the bot disconnect randomly, after i can put another song and works normal, and it happends pretty often

**Comment by galnir** [comment]
Try the solution I suggested in #138

**Comment by razvandamian** [comment]
> Try the solution I suggested in #138
> Edit: Nevermind, just pull the new changes I committed and tell me if that worked(commit [f9fddac](https://github.com/galnir/Master-Bot/commit/f9fddacf7d357368f5574a612e92b349d17eeff5))

For now, it solved, if it happens again, i will reopen, thanks!
