### ISSUE TITLE
Lyrics command can't find any music

### ISSUE THREAD

**Issue by effe777** [galnir/Master-Bot#142]
**Describe the bug**
When you try to search for the lyrics of any song, even the one you previously found. Find nothing

**To Reproduce**
1. Play Music
2. Search a music name

**Expected behavior**
Tells you to be more specific or try again

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Node Version(Should be v12 atleast):  v12
 - Are python 2.7 and Ffmpeg installed?: yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): Vps

**Comment by galnir** [comment]
Can you provide screenshots and error message if one appears?

**Comment by effe777** [comment]
It does not give any error in the console

**Comment by galnir** [comment]
What message appears in chat?

**Comment by effe777** [comment]
This: Something when wrong, please try again or be more specific

**Comment by galnir** [comment]
Did it ever find lyrics? What song are you trying to find? I can't figure out what's happening without information

**Comment by effe777** [comment]
Yes, he almost always found the lyrics. For a few days now it has not worked. I tried to change the api key, but nothing.

**Comment by galnir** [comment]
The bot uses Genius for getting the lyrics and their API is really bad. I'm looking into alternatives, thanks for opening this issue

**Comment by galnir** [comment]
@effe777 Actually I've tried it now and it works fine for me, what song's lyrics did you search for?

**Comment by effe777** [comment]
Like Lovely Billie eilish

**Comment by effe777** [comment]
Maybe is for the vps ip. I think trigger the captcha

**Comment by galnir** [comment]
It's an API there's no captcha. The api is inconsistent, sometimes it returns lyrics sometimes it doesn't. The alternatives don't look great either so I'm still searching

**Comment by effe777** [comment]
Yeah np, if u need help i have maked a limit for the loop request. Cuz if request like 1250 loops, the bot crash. I put a limit on 999, if u want i can give to u

**Comment by effe777** [comment]
And if u wont i have found the solutions for the lyrics

**Comment by effe777** [comment]
https://docs.ksoft.si/api/lyrics-api

**Comment by galnir** [comment]
I know that API but don't trust them enough to replace Genius with them. I'm working on making working with Genius more consistent

**Comment by alias-rahil** [comment]
Sorry for commenting on a closed issue but, this npm package of mine might help you: https://github.com/alias-rahil/lyrics-finder.git/

No API keys are needed.
