### ISSUE TITLE
Little suggestion...

### ISSUE THREAD

**Issue by razvandamian** [galnir/Master-Bot#146]
Hello, i suggest you to make the loop command work like, if i type "!loop", it will be 1 time, and if i type again i will be again only one, try to make if you can if you type two times loop to loop two times, i know you can !loop 2, but why not, and i have one more question, i can get the author name from youtube with ytdl? if you know, what's the command, thanks!

**Comment by galnir** [comment]
The loop command already works like you suggest if I understand what you mean. When you hit '!loop' it's the same as '!loop 1'.
About getting the author name from youtube with ytdl, I never did that so I don't know, the bot only gets the song name which usually includes the singer/band. You can read [ytdl-core's docs](https://github.com/fent/node-ytdl-core) and find what you're looking for

**Comment by razvandamian** [comment]
> The loop command already works like you suggest if I understand what you mean. When you hit '!loop' it's the same as '!loop 1'.
> About getting the author name from youtube with ytdl, I never did that so I don't know, the bot only gets the song name which usually includes the singer/band. You can read [ytdl-core's docs](https://github.com/fent/node-ytdl-core) and find what you're looking for

![image](https://user-images.githubusercontent.com/67657296/89667142-4af5fe80-d8e4-11ea-9db3-3de2289a7f6e.png)
, i mean, when you type once loop, and loop again, to be 2 times, not 1, like (loop, after again loop) and to be repeted 2 times

**Comment by galnir** [comment]
@razvandamian I read your messages multiple times and still don't get what you mean. If you enter !loop and then again !loop it will loop twice, and you can see that when using !queue

**Comment by razvandamian** [comment]
> @razvandamian I read your messages multiple times and still don't get what you mean. If you enter !loop and then again !loop it will loop twice, and you can see that when using !queue

forget it, im dump, check the suggestion from the other guy.
