### ISSUE TITLE
I cannot do npm install 

### ISSUE THREAD

**Issue by mihirgarg01** [galnir/Master-Bot#147]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
When I do npm install discordjs/discord.js discordjs/Commando ffmpeg-static node-opus simple-youtube-api ytdl-core, It gives me a ton of warnings and then at the end like 20 errs. It wont let me use the Commando library without importing this so I am kind of stuck.

**To Reproduce**
1. Download the zip file from github
2. Unzip the file and open it in Visual Studio Code
3. Open a terminal and type npm install discordjs/discord.js discordjs/Commando ffmpeg-static node-opus simple-youtube-api ytdl-core

**Expected behavior**
It should import all the libraries.

**Screenshots**
https://imgur.com/v6WKuVC
https://imgur.com/v8yN9dR

**Desktop (please complete the following information):**
 - Windows 64bit
 - Node Version: v12
 - Are python 2.7 and Ffmpeg installed?: Yes
 - How are you hosting the bot: My Computer 😭

**Additional context**
Luv the help 💖

**Comment by ThaddeusKKR** [comment]
There was an NPM outage yesterday, it might be related to that. Can you provide the error log?
[Status](status.npmjs.org)

**Comment by mihirgarg01** [comment]
> There was an NPM outage yesterday, it might be related to that. Can you provide the error log?
> [Status](status.npmjs.org)

Yes Sure!:
npm WARN deprecated node-opus@0.3.3: This project is unmaintained. See @discordjs/opus for an alternative.
npm WARN deprecated ffmpeg-static@2.7.0: ffmpeg-static@2 won't be updated with new ffmpeg binaries anymore. Use ffmpeg-static@latest.
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/discordjs/discord.js.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shai\AppData\Roaming\npm-cache\_logs\2020-08-07T06_00_19_013Z-debug.log

**Comment by mihirgarg01** [comment]
When I do node . The err msg is this:
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'discord.js-commando'
Require stack:
- C:\Users\shai\Desktop\Master-Bot-master\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\shai\Desktop\Master-Bot-master\index.js:1:28)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\shai\\Desktop\\Master-Bot-master\\index.js' ]
}

**Comment by galnir** [comment]
All you need to do is follow the instructions. Clone the repo and hit 'npm i' that's it. No need to install the dependencies individually

**Comment by mihirgarg01** [comment]
How do you clone the repository? I haven’t coded in a while....

**Comment by galnir** [comment]
@mihirgarg01 `git clone https://github.com/galnir/Master-Bot.git` in console

**Comment by galnir** [comment]
Clone the repo and follow the instructions in the readme. If that doesn't work open a new issue :)
