### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by SaegusaMayumi1234** [galnir/Master-Bot#148]
can you make loop is not only loop(numberofloop)? like loop the entire queue or even toggle loop on/off
!loop (numberofloop for 1 song)/(on/off)
!loop queue (numberofloop)/(on/off)

sorry if my english is bad, but I hope you understand what I mean.

**Comment by razvandamian** [comment]
agreed, please make it

**Comment by Oplikk** [comment]
+1, a good idea that would be nice to see

**Comment by galnir** [comment]
Added a loopqueue command in commit 4676207021ffdfff12303549ab7cf38f5079094e
if there are any bugs, please report them :)
