### ISSUE TITLE
Playlists not works

### ISSUE THREAD

**Issue by NhProGamer** [galnir/Master-Bot#149]
**Playlists not works**

@NhPro, An error occurred while running the command: TypeError: playlist.getVideos is not a function
You shouldn't ever receive an error like this.
Please contact NhPro#2800.

**Comment by galnir** [comment]
Fill the issue template

**Comment by NhProGamer** [comment]
Describe the bug
the bot can't play playlist (the error appears if the url is a private playlist) or if the playlist is public it only plays the first sound
To Reproduce
Steps to reproduce the behavior:
Type {prefix}play (url of a private playlist or url of a public playlist)

Expected behavior
An error occurred while running the command: TypeError: playlist.getVideos is not a function

Screenshots
If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

OS: Ubuntu
Node Version(Should be v12 atleast): v12.16.3
Are python 2.7 and Ffmpeg installed?: Yes
How are you hosting the bot(Locally, on a vps, heroku, glitch...): on a vps

**Comment by galnir** [comment]
Make sure the url is actually a playlist url, there's an option you're providing a video url that looks similar

**Comment by galnir** [comment]
A playlist link looks like this:
https://www.youtube.com/playlist?list=PL3oW2tjiIxvQ60uIjLdo7vrUe4ukSpbKl

also make sure you follow the instructions in the readme. If you do, there's no reason you'd get that error. Comment here if the issue persists after cloning again and following the instructions
