### ISSUE TITLE
[ Question ] How can I get the length of all the songs in queue?

### ISSUE THREAD

**Issue by ThaddeusKKR** [galnir/Master-Bot#151]
Hello, I would like to find out how i can get the length of all the songs that are in queue.
Thanks!

**Comment by galnir** [comment]
Length of the queue or duration of each song?

**Comment by ThaddeusKKR** [comment]
Duration of all the songs in queue combined. Also, is there a way I can save who requests each song and put it in the queue command maybe?

**Comment by galnir** [comment]
Each object in the queue array represents a song. It has a formatted duration which you can use to get the total duration. 
You can get the information of the user who requests a song from the 'message' parameter. 
Read [discord.js docs](https://discord.js.org/#/docs/main/master/class/Message) for further info
