### ISSUE TITLE
Song Not Playing

### ISSUE THREAD

**Issue by sahhas16** [galnir/Master-Bot#152]
It says added to playlist but it isn't playing the song plus the bot isn't even joining.

**Comment by galnir** [comment]
Please fill the issue template

**Comment by sahhas16** [comment]
where is that

**Comment by sahhas16** [comment]
Describe the bug
the bot is not playing any song, even after it says added to queue
To Reproduce
Steps to reproduce the behavior:
Type {prefix}play (song)

Screenshots
If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

OS: Windows
Node Version(Should be v12 atleast): v14.00
Are python 2.7 and Ffmpeg installed?: Yes
How are you hosting the bot(Locally, on a vps, heroku, glitch...): on a vps

**Comment by sahhas16** [comment]
is that fine

**Comment by galnir** [comment]
The VPS's OS is Windows? If yes that's odd.
Anyway that issue usually happens as a result of a failure in node-opus build. That means that when you installed the dependencies one of them failed.
Try to ```npm install node-opus``` and tell me if that fails

**Comment by sahhas16** [comment]
vps os is debain sorry

**Comment by sahhas16** [comment]
Imagine Dragons - Believer added to queue, it says this but deosn't play. when  i put queue command it only shows one comand

**Comment by galnir** [comment]
did the ```npm i node-opus``` fail?

**Comment by sahhas16** [comment]
one sec trying it

**Comment by sahhas16** [comment]
no but it did say err at some places

**Comment by sahhas16** [comment]
stil not working

**Comment by sahhas16** [comment]
it works on one server but not on another

**Comment by galnir** [comment]
Are you sure there's no error either in chat or in console? I can't figure out what's wrong without more information

**Comment by sahhas16** [comment]
hold on i kicked the bot and invited him again. Did the Trick

**Comment by sahhas16** [comment]
thanks
