### ISSUE TITLE
Suggestion for bot leaveing the voicechannel

### ISSUE THREAD

**Issue by razvandamian** [galnir/Master-Bot#153]
I've made something, but once a 2-3 songs, the bot restarts with an error, TypeError: Cannot read property 'leave' of null, and i've think if you can make it better, it would be nice for people who listen to music, to have the bot more 10-15 minutes in the channel, to not make him join  again after every song finish, hope you understand.

.on('finish', function() {
            if (queue.length >= 1) {
              return classThis.playSong(queue, message);
            } else {
              message.guild.musicData.isPlaying = false;
              message.guild.musicData.nowPlaying = null;
              message.guild.musicData.songDispatcher = null;
              if (message.guild.me.voice.channel) {
			    setTimeout(function(){
                   message.guild.me.voice.channel.leave()
              }, 600000);
              }
            }

**Comment by galnir** [comment]
I don't encounter this error on 2 instances (2 operating systems). Your suggestion will make the bot leave the channel after 10 minutes even if there will be a song playing since this is a timer
