### ISSUE TITLE
 An error occurred while running the command: TypeError: Cannot read property 'length' of undefined You shouldn't ever receive an error like this.

### ISSUE THREAD

**Issue by Krunkistic** [galnir/Master-Bot#154]
i get error when playing a song , this  An error occurred while running the command: TypeError: Cannot read property 'length' of undefined
You shouldn't ever receive an error like this. 

And this too ,  An error occurred while running the command: TypeError: Cannot read property 'hours' of undefined
You shouldn't ever receive an error like this.

**Comment by galnir** [comment]
Can you fill the issue template?

**Comment by Oplikk** [comment]
https://github.com/galnir/Master-Bot/issues/14

**Comment by galnir** [comment]
Clone the repo again and make sure you follow the instructions in the README. If you do those steps and don't alter anything in code you're good to go
