### ISSUE TITLE
Playlist shuffle implementation request

### ISSUE THREAD

**Issue by Oplikk** [galnir/Master-Bot#155]
Hello! The code is great, but i got a feature request i would love to see implemented.
Most of the time someone will `/play {Playlist url}`, they will do `/shuffle ` afterwards, because who wan't to listen to the songs in the same order everytime right?
Im talking about implementing the shuffle function somewhere inside the `/play` command, so the bot will automaticaly shuffle the queue, if there is a playlist inserted.
The function should be  ''` // // can be uncommented` '', so it will be optional for the bot owner/hoster to enable/disable automatic shuffling. 
Cheers, have a great day!

**Comment by galnir** [comment]
Why not play a playlist and then !shuffle?

**Comment by galnir** [comment]
implemented in 45ea87d

**Comment by Oplikk** [comment]
Thank you! awesome work!
