### ISSUE TITLE
Permission Bot

### ISSUE THREAD

**Issue by darkpologang777** [galnir/Master-Bot#156]
**Describe the bug**
If the bot is not allowed to enter that channel, it no longer works

**To Reproduce**
1. Get the bot into a channel you can't
2. Look at the error on the console

**Expected behavior**
To make it work tap restart the bot or get it out of discord

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Node Version(Should be v12 atleast):  v12
 - Are python 2.7 and Ffmpeg installed?: yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): vps

**Comment by galnir** [comment]
The bot will not be able to join a channel if it doesn't have the permission to enter that channel, that's all. 
Is that the case?

**Comment by darkpologang777** [comment]
Yes, because if the bot don't have the permissions gets bug and doesn't work anymore.

**Comment by Oplikk** [comment]
make sure that in the channel settings you want him to join, is a bot role asigned to it and with enabled 'Join permission'

**Comment by galnir** [comment]
I'll test this myself and fix if I get that too
