### ISSUE TITLE
Error on console

### ISSUE THREAD

**Issue by darkpologang777** [galnir/Master-Bot#157]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
I get this error: 
```
              if (message.guild.me.voice.channel) {
                                   ^

TypeError: Cannot read property 'voice' of null
    at StreamDispatcher.<anonymous> (/root/Soundy/commands/music/play.js:269:36)

```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Node Version(Should be v12 atleast): v12
 - Are python 2.7 and Ffmpeg installed?: yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): vps

**Comment by Oplikk** [comment]
Clone the repository to a folder and try again. Seems like you did not cloned the bot correctly (use Github Desktop)

**Comment by darkpologang777** [comment]
It only happens sometimes in some discord guild

**Comment by galnir** [comment]
When does that happen? What do you do to get that?

**Comment by darkpologang777** [comment]
I don't know. I only get this error on my console

**Comment by galnir** [comment]
I can't really do anything or figure out anything based on the little information you're providing..

**Comment by galnir** [comment]
Pull the new changes and open a new issue if this error persists.
Remember that if you change code I can't help you with errors because I don't know what you did
