### ISSUE TITLE
UnhandledPromiseRejectionWarning [TOKEN_INVALID]

### ISSUE THREAD

**Issue by 1abking** [galnir/Master-Bot#16]
Added config.json and changed user id in index.js
when compiling this is the error i get.
i have all the correct dependencies installed and didnt even change anything

--------------------------------------------------------------------------------------------------------

(node:23408) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (D:\eoic-bot\Master-Bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:132:26)
    at CommandoClient.login (D:\eoic-bot\Master-Bot\node_modules\discord.js\src\client\Client.js:210:21)
(node:23408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23408) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by galnir** [comment]
Check carefully if the bot token in your config.json is correct

**Comment by 1abking** [comment]
I regenerated my discord token, and also retried and I am still getting the same errors. Is there anything else that could be wrong?

When I go into the file system for WebSocketManager.js
this is the line of code highlighted. "new" is the start of 132:26.
const invalidToken = new DJSError(WSCodes[4004]);

**Comment by galnir** [comment]
Well the error says it the token you're providing is wrong.
Did you copy the token like explained in step 4 in this guide? https://www.writebots.com/discord-bot-token/
