### ISSUE TITLE
leave 

### ISSUE THREAD

**Issue by zero59344** [galnir/Master-Bot#163]
I am having trouble using the command: " leave " , do not exit the audio room ?

**Comment by galnir** [comment]
Please fill the issue template

**Comment by zero59344** [comment]
> Please fill the issue template

Where do I do that?

**Comment by galnir** [comment]
When you open an issue there's a template

**Comment by zero59344** [comment]
> When you open an issue there's a template
I do not see it, ok is my problem above it difficult?

**Comment by zero59344** [comment]
> When you open an issue there's a template

I do not see it, ok is my problem above it difficult?

**Comment by galnir** [comment]
New Issue > Get Started
Both green buttons

**Comment by zero59344** [comment]
![Capture](https://user-images.githubusercontent.com/69620603/90176476-49777b00-dda9-11ea-99de-cbba93d76f9b.PNG)
Where are all the green buttons ?

**Comment by zero59344** [comment]
Ok, can I contact you via Discord?

**Comment by galnir** [comment]
You know what let's do this in another way.
Did you follow the instructions in the README and install python 2.7 and ffmpeg? How are you hosting the bot(vps, locally, heroku, glitch)?

**Comment by zero59344** [comment]
> You know what let's do this in another way.
> Did you follow the instructions in the README and install python 2.7 and ffmpeg? How are you hosting the bot(vps, locally, heroku, glitch)?

Yes, I also want to communicate with you via Discord in order to try the bot.

**Comment by galnir** [comment]
I don't have much time to help you via Discord. Setting up the bot isn't hard, all you need to do is follow the instructions in the README and make sure ffmpeg and python 2.7 are installed, that's all. I'm asking again, how are you running the bot?

**Comment by zero59344** [comment]
> I don't have much time to help you via Discord. Setting up the bot isn't hard, all you need to do is follow the instructions in the README and make sure ffmpeg and python 2.7 are installed, that's all. I'm asking again, how are you running the bot?

It works on a server

**Comment by zero59344** [comment]
Now I had a mistake in the bot, how do I solve it : 

(node:17909) UnhandledPromiseRejectionWarning: TypeError [INVALID_TYPE]: Supplied options is not an object.

at CommandoMessage.delete (/home/ogp_agent/OGP_User_Files/3/node_modules/discord.js/src/structures/Message.js:501:44)

at /home/ogp_agent/OGP_User_Files/3/index.js:93:22

at runMicrotasks (<anonymous>)

at processTicksAndRejections (internal/process/task_queues.js:97:5)

(Use `js --trace-warnings ...` to show where the warning was created)

(node:17909) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

(node:17909) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by galnir** [comment]
I've never seen this error... This means you didn't clone this repo and probably copied code over to another codebase instead..
From your messages I assume you're not familiar with coding and Git overall and I can't really do anything without you co operating and giving me more information.
Did you clone this repo?

**Comment by zero59344** [comment]
> I am having trouble using the command: " leave " , do not exit the audio room ?

I wanted to know how to make the leave command exit from the audio ROM in case I made a file: play.js that it never comes out of the audio ROM, which is shown in the picture ... I mean very briefly: “I want if you use the * play * command, install the bot in the ROM To whom I summoned him and he never goes out unless I use the * leave * command, which comes out of the ordinary rum.
![Capture](https://user-images.githubusercontent.com/69620603/90320944-a27c1600-df45-11ea-97ba-cde1f09b02be.PNG)

**Comment by galnir** [comment]
Then all you need to do is remove the . leave () call in the finish event

**Comment by zero59344** [comment]
> Then all you need to do is remove the . leave () call in the finish event

No, you don't understand me, I want to use the leave command, but if I play a song, the robot will be installed in the voice room that I've summoned it to and it will never come out of it, and if it uses the leave command, it will leave the sound room like I want.

**Comment by galnir** [comment]
You want the bot not to leave the room after it finishes playing songs?

**Comment by zero59344** [comment]
> You want the bot to not leave the room after it finishes playing songs?

Exactly

**Comment by galnir** [comment]
So you need to do what I told you in my last comment which after you said I don't understand you...
