### ISSUE TITLE
429 errors in music

### ISSUE THREAD

**Issue by ThaddeusKKR** [galnir/Master-Bot#165]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
I keep getting status code 429 errors while either 1) the music is playing or 2) when trying to add music.
The bot returns in the channel `cannot play song`. Idk how YouTube api works, i know 429 is ratelimit but just restarting the bot fixes this. Still pretty annoying though

**To Reproduce**
1. play something, happens occasionally

**Expected behavior**
Uninterrupted music

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ~~
 - Node Version(Should be v12 atleast): 12.18.2 i think
 - Are python 2.7 and Ffmpeg installed?: yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): heroku

**Additional context**

**Comment by galnir** [comment]
This problem is related to ytdl-core, read this issue:
https://github.com/fent/node-ytdl-core/issues/635
