### ISSUE TITLE
Add spotify.

### ISSUE THREAD

**Issue by johna3212** [galnir/Master-Bot#17]
Hey, Add spotify and also can i get your discord name with tag, I want to ask something important

**Comment by galnir** [comment]
hyperzone#1185

I'll look into adding Spotify, but I think that in order to play songs from Spotify or get an API key you need to be a premium user, I'll look into it.

**Comment by galnir** [comment]
@johna3212 
I looked into adding Spotify, and it seems like unlike Youtube, Spotify does not allow "public streaming".
You're welcome to add me on Discord tho :)

**Comment by johna3212** [comment]
Okay, I saw various bots which allow streaming from spotify, try checking soundcloud
