### ISSUE TITLE
Genius lyrics not working

### ISSUE THREAD

**Issue by thetechguy-cpu** [galnir/Master-Bot#171]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
I copied my client secret key to the config.json as shown in the ReadMe. When that did not work, I tried coppying my client ID instead, but that also didn't work. It always says cannot find lyrics.
**To Reproduce**
1. Use !lyrics song name.

**Expected behavior**
It was supposed to return lyrics of that song.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Node Version(Should be v12 atleast): v12
 - Are python 2.7 and Ffmpeg installed?: yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): VPS

**Additional context**

**Comment by galnir** [comment]
I said on previous issues that I'm looking into alternatives to Genius because their API is really bad. I already started rewriting the command so expect it in the upcoming days(I don't have much time so might take longer)

**Comment by alias-rahil** [comment]
Hi @galnir. I have made this npm package that could help you.

https://github.com/alias-rahil/lyrics-finder.git.

**Comment by galnir** [comment]
@alias-rahil I'll look into it, thanks :)

**Comment by darkpologang777** [comment]
I have tried. But not work :/

**Comment by galnir** [comment]
> I have tried. But not work :/

What did you try? I test on 2 operating systems and it works. Do you pull changes via Git?

**Comment by darkpologang777** [comment]
I just replace the code

**Comment by galnir** [comment]
@darkpologang777 That's bad practice, you should work with Git. Nevertheless, as I wrote here make sure the key is

**Comment by darkpologang777** [comment]
Yeah, i used git now but the same

**Comment by thetechguy-cpu** [comment]
Hi.
Sorry for opening this issue again. However, it doesn't work for me. When I put in my genious access token, it says "There was a problem fetching lyrics for this song, please try again". In the redirect URL fields, do I need to put discord, or will a random website do?

**Comment by galnir** [comment]
> Hi.
> Sorry for opening this issue again. However, it doesn't work for me. When I put in my genious access token, it says "There was a problem fetching lyrics for this song, please try again". In the redirect URL fields, do I need to put discord, or will a random website do?

random website

**Comment by thetechguy-cpu** [comment]
In that case, it doesn't work. I'm getting the same error above.

**Comment by galnir** [comment]
> In that case, it doesn't work. I'm getting the same error above.

doesn't work at all? not even 1 of a 10?

**Comment by thetechguy-cpu** [comment]
Unfortunately, no.

**Comment by galnir** [comment]
Okay I'll look into it

**Comment by galnir** [comment]
@thetechguy-cpu let me know if d903ed4 fixes this for you. I finally found the reason why it's inconsistent

**Comment by galnir** [comment]
Also @darkpologang777 you reported the same problem. Please let me know if the new commit solved that for you

**Comment by darkpologang777** [comment]
Same, don't work. Still get "there was a problem fetching ..."

**Comment by galnir** [comment]
> Same, don't work. Still get "there was a problem fetching ..."

What is the input you're providing to the command?

**Comment by darkpologang777** [comment]
?lyrics lovely billie eilish

**Comment by galnir** [comment]
> ?lyrics lovely billie eilish

That works for me, if you don't use Git just replace the file with the file from the repo. If you edit stuff you might make it not work

**Comment by darkpologang777** [comment]
I just replace only the lyrics code but still nothing

**Comment by galnir** [comment]
Also again make sure the key is the 'CLIENT ACCESS TOKEN' which you need to click on to generate in:
https://genius.com/api-clients

**Comment by galnir** [comment]
there's no reason it won't work I test it on seperate systems, your key must be wrong then

**Comment by darkpologang777** [comment]
Same, nothing. Idk

**Comment by darkpologang777** [comment]
Can u provide me ur genius token? Maybe is this idk

**Comment by galnir** [comment]
> Can u provide me ur genius token? Maybe is this idk

It doesn't matter your key should work, and I honestly don't know why it doesn't work

**Comment by darkpologang777** [comment]
Uhm...

**Comment by galnir** [comment]
> Uhm...

Try to clone this repo without changing anything and make a new client in the genius api page

**Comment by razvandamian** [comment]
i can confirm, it works better, nice work for a genius api 👍

**Comment by thetechguy-cpu** [comment]
> @thetechguy-cpu let me know if [d903ed4](https://github.com/galnir/Master-Bot/commit/d903ed4aa2a5e6f15a1ba3f7c003b196d5700575) fixes this for you. I finally found out why it's inconsistent

No it didn't work. Still the same error. I am doing /lyrics bohemian rhapsody. No console output.

**Comment by galnir** [comment]
> > @thetechguy-cpu let me know if [d903ed4](https://github.com/galnir/Master-Bot/commit/d903ed4aa2a5e6f15a1ba3f7c003b196d5700575) fixes this for you. I finally found out why it's inconsistent
> 
> No it didn't work. Still the same error. I am doing /lyrics bohemian rhapsody. No console output.

If it doesn't work **at all**, then I'm certain that there's a problem with your key. Before this commit it would work 6-7 out of 10 times. Make sure the key you placed in config.json is the 'access token', and not the 'client secret' or 'client id'.

**Comment by thetechguy-cpu** [comment]
> > > @thetechguy-cpu let me know if [d903ed4](https://github.com/galnir/Master-Bot/commit/d903ed4aa2a5e6f15a1ba3f7c003b196d5700575) fixes this for you. I finally found out why it's inconsistent
> > 
> > 
> > No it didn't work. Still the same error. I am doing /lyrics bohemian rhapsody. No console output.
> 
> If it doesn't work **at all**, then I'm certain that there's a problem with your key. Before this commit it would work 6-7 out of 10 times. Make sure the key you placed in config.json is the 'access token', and not the 'client secret' or 'client id'.

No it still doesn't work. I made sure to copy my access token with ctrl + A. It just says there was a problem fetching lyrics for this song. Can you make errors appear in the console so I can trase what's happening?

**Comment by galnir** [comment]
@thetechguy-cpu I added console log statements in commit 94a0d64

pull the new changes and let me know what appears in your console

**Comment by thetechguy-cpu** [comment]
@galnir Nothing seems to be appearing in my console. It just says ready. I pulled the new changes.

**Comment by galnir** [comment]
@thetechguy-cpu okay, so the problem is narrowed down to the getLyrics function. Since no error was thrown I suspect it may be something related to cheerio. Try to install the package again using: npm i cheerio

**Comment by thetechguy-cpu** [comment]
@galnir  I did, and ran the command again. There was still no output. When installing it, this appeared. is this normal?

 npm WARN discord.js-commando@0.11.0-dev requires a peer of @types/better-sqlite3
 @^5.0.0 but none is installed. You must install peer dependencies yourself.     
 npm WARN discord.js-commando@0.11.0-dev requires a peer of better-sqlite3@^5.0.0
  but none is installed. You must install peer dependencies yourself.            
 npm WARN discord.js-commando@0.11.0-dev requires a peer of sqlite@^3.0.0 but non
 e is installed. You must install peer dependencies yourself.                    
 npm WARN master-bot@1.0.0 No repository field.                                  
                                                                                 
 + cheerio@1.0.0-rc.3                                                            
 updated 1 package and audited 348 packages in 4.563s                            
                                                                                 
 12 packages are looking for funding                                             
   run `npm fund` for details                                                    
                                                                                 
 found 0 vulnerabilities

**Comment by galnir** [comment]
@thetechguy-cpu Yeah this is normal. To be honest I ran out of ideas on what could cause this issue.. Your key is fine because it doesn't fail at the first invoked function. Something happens when your bot tries to extract lyrics from genius. My only guess at this point is that your vps' ip is blocked on their part.
If you could try on a different operating system (maybe locally on windows?) , I'm quite certain it would work

**Comment by galnir** [comment]
@thetechguy-cpu Let me walk you through how this command works so you won't get the wrong impression:

1. Query the Genius API with the provided song name, and expect the api song path. 
2. Query the API again and provide it with the api song path from step 1, and expect the lyrics web page.
3. Fetch the page and extract the lyrics from it.

Steps 1 and 2 don't fail, since you're not getting the possible early error messages, so that leaves us with step 3. At this point I'd say the issue is with node-fetch/cheerio, or something related to the VPS' IP

Honestly I'd love to solve this issue but it may be out of my reach

**Comment by thetechguy-cpu** [comment]
@galnir  is there a way to know if genius has blocked you? like doesn't the API return an error 403?

**Comment by galnir** [comment]
@thetechguy-cpu Step 3 doesn't involve the api, basically accessing a webpage

**Comment by thetechguy-cpu** [comment]
What i mean is that is there a way for the bot to get the lyrics from the API? so it doesn't need to do step 3?

**Comment by galnir** [comment]
@thetechguy-cpu nope the API doesn't provide lyrics

**Comment by thetechguy-cpu** [comment]
@galnir  thanks for trying to help. I know this is a bit off topic, but I dont want to create a seperate issue for it. How can I customize the help message? I dont see a help.js file in the commands folder.

**Comment by galnir** [comment]
> @galnir thanks for trying to help. I know this is a bit off topic, but I dont want to create a seperate issue for it. How can I customize the help message? I dont see a help.js file in the commands folder.

Read #120

**Comment by galnir** [comment]
I'm closing this issue. Hopefully you can solve it because I ran out of ideas :/
