### ISSUE TITLE
(Suggestion) Add a message when the bot don't have permissions to join

### ISSUE THREAD

**Issue by darkpologang777** [galnir/Master-Bot#172]
**Describe the bug**
If fhe bot don't have the permissions get a bug

**To Reproduce**
1. Use a command for join the bot in the voice channel where the bot can't
2. The bot don't work anymore

**Expected behavior**
If is possible, to add a message when the bot can't join in a voice channel for the permission

**Comment by plengeh69** [comment]
Error: Cannot find module 'discord.js-commando'

**Comment by galnir** [comment]
@darkpologang777 It shouldn't even be a problem because you need to make the bot Administrator in order to make full usage of its features

**Comment by darkpologang777** [comment]
Yeah but can u make it please? Because i removed the admin features

**Comment by galnir** [comment]
I can't commit this only for you it will affect everyone, and everyone(except few like you) gives the bot Admin perms.

Anyway if we're looking at the [play command as it is in this url](https://github.com/galnir/Master-Bot/blob/master/commands/music/play.js), all you need to do is add a line after line 312, something like:
```message.say('I have no permission to join this channel!');```

and change line 320 so it will only have the return statement so your console will not get spammed with the error:
```return```

**Comment by galnir** [comment]
commited in 2d86e9d

pull the new changes
