### ISSUE TITLE
Command leave is bugged

### ISSUE THREAD

**Issue by SaegusaMayumi1234** [galnir/Master-Bot#175]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
when I try to !loopqueue then !leave the bot is not leaving the voice channel and playing the next queue

**To Reproduce**
1. Play any song in discord voice channel min 2 or 3 song
2. then do !loopqueue
3. then do !leave

**Expected behavior**
when do !leave the bot is disconnect from voice channel.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version(Should be v12 atleast): 12.18
 - Are python 2.7 and Ffmpeg installed: yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): Locally

**Additional context**

**Comment by razvandamian** [comment]
do skipall instead

**Comment by galnir** [comment]
I'll look into it today, thanks for reporting this

**Comment by SaegusaMayumi1234** [comment]
> do skipall instead

tbh skipall and leave command almost has same code. in leave command it has:
else if (message.guild.musicData.songDispatcher.paused) {
      message.guild.musicData.songDispatcher.resume();
      setTimeout(() => {
        message.guild.musicData.songDispatcher.end();
      }, 100);

when the queue end the bot is automatically disconnect is the base how leave command written. So I think basically leave command is only delete all the queue then the bot will disconnect when there is no queue. But this maybe conflict with loopqueue command. when doing the command the bot will think they will added new queue like copying the entire queue. then it cause the glitch when trying clear the entire queue.

**Comment by galnir** [comment]
fixed in 83c8cda
