### ISSUE TITLE
Error while using Play Command. TypeError: Cannot read property 'length' of undefined. 

### ISSUE THREAD

**Issue by irfanfreaky10** [galnir/Master-Bot#177]
I've been using your Source Code for my bot since 10 days. I added my own features (mostly embeds for everything) and the problem is not with that. Since this morning I keep on Encountering with this Error when i try to play Music using music queries, I mean search strings and it shows error no matter what and it shows TypeError: Cannot read property 'length' of undefined.
I even tired playing it with URL and it shows TypeError: Cannot read property 'duration' of undefined. What i thought is maybe there is something wrong with my addition of Codes thats why its showing me error. I'm using Visual Studio Code and the Console is completely fine. Just says 'Ready!'. Other commands are fine ig. Because i tried the trivia and others and they are fine. Then i came here and downloaded your latest code and tried running with my test bot. But same result. The same errors again. So i thought I should let you know this. I know finding and fixing errors like these are time consuming. So i hope for a quick update. Thanks for making !!! And i hope for a reply from you !

**Describe the bug**
Error while using Play Command using Search Strings (Song Name). TypeError: Cannot read property 'length' of undefined.
Another Error while using Play Command using URL. TypeError: Cannot read property 'duration' of undefined

**To Reproduce**
Use the Play Command with Search strings (Song Name) and for the Latter Use the Play Command with an URL

**Expected behavior**
I expect the bot to show the 5 videos and Ask to choose between 1 to 5 and after entering the bot should play the Song.
For the latter I expect the bot to play the Song from the URL

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...] Windows 10
 - Node Version(Should be v12 atleast): Yes latest
 - Are python 2.7 and Ffmpeg installed?: Yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): Heroku

**Additional context**

**Comment by razvandamian** [comment]
when i get this, i just wait a few hours, about 4-6 and after it works normal, dk why it does that but yea...

**Comment by galnir** [comment]
First of all, I have no way of knowing what code you added/removed/changed, that's why when you open an issue it says 'do not open an issue if you changed code'.
Anyway my guess is that you hit the daily YouTube API rate limit, so you're not getting any results back from the API, hence the errors you get. Your API key is limited to 10k 'units' a day, and if I remember correctly any time you search a song(!play something and then choose from 1-5), it uses 100 units.
Sadly we have no control over how many units the API uses so unless you ask them to increase your quota, there's nothing to be done :/

**Comment by irfanfreaky10** [comment]
> First of all, I have no way of knowing what code you added/removed/changed, that's why when you open an issue it says 'do not open an issue if you changed code'.
> Anyway my guess is that you hit the daily YouTube API rate limit, so you're not getting any results back from the API, hence the errors you get. Your API key is limited to 10k 'units' a day, and if I remember correctly any time you search a song(!play something and then choose from 1-5), it uses 100 units.
> Sadly we have no control over how many units the API uses so unless you ask them to increase your quota, there's nothing to be done :/
> I asked YouTube to increase mine and they did, so they might increase yours if you ask

well.. i thought the same at first and i created a new api key and then tried.. But same result. Then i was browsing your closed issues and that issue had the same title like "TypeError: Cannot read property 'xyz' of undefined" and there you said to check the package.json for the discord.js-commando version. I checked and there was only a version number. So i downloaded your repo again and the replaced the commands and Index files with mine (ofc the config.json is mine xP) and hit node . and BAAM lol it worked. Also now i have github in the discord.js-commando line in my package.json file. I dont know how and why it worked and  theni created a new API Key and now my bot works nice and clean !!. Thanks for the code :D.

**Comment by galnir** [comment]
Glad it works, enjoy :)
