### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by emergenitro** [galnir/Master-Bot#179]
I'd rather discuss this on discord please... Contact me at MrSkully#4374

**Comment by galnir** [comment]
I don't have the time to chat with you, this is a side project not my job..
Best I can do is help you through GitHub, just fill the issue template

**Comment by emergenitro** [comment]
Describe the bug
I can't seem to find the help command file... Please help me find as to where it is

To Reproduce
Steps to reproduce the behavior:
N/A

Screenshots
If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

OS: Windows
Node Version(Should be v12 atleast): 12.18
Are python 2.7 and Ffmpeg installed: yes
How are you hosting the bot(Locally, on a vps, heroku, glitch...): Locally
Additional context
Add any other context about the problem here.

**Comment by galnir** [comment]
Read #120
