### ISSUE TITLE
No Audio While Trying To Use The Bot.

### ISSUE THREAD

**Issue by Tpelaaja** [galnir/Master-Bot#18]

**Comment by galnir** [comment]
I can't really tell what's wrong with no info. What os are you running? Have you installed ffmpeg correctly?(this is crucial)

**Comment by Tpelaaja** [comment]
Ubuntu

**Comment by galnir** [comment]
This is _probably_  related to ffmpeg, can you install it again by following this guide? https://tecadmin.net/install-ffmpeg-on-linux/

**Comment by Tpelaaja** [comment]
yes its installed
but discord commando is giving errors

**Comment by galnir** [comment]
@Tpelaaja Alright then post the full error message so I can figure out what causes it

**Comment by Tpelaaja** [comment]
yeah i was stupid
I had one line missing

**Comment by Tpelaaja** [comment]
but no audio playing on the bot rn

**Comment by Tpelaaja** [comment]
as its on¨

**Comment by galnir** [comment]
Can you add me on Discord? hyperzone#1185
I'll try to figure out why it is happening
