### ISSUE TITLE
The bot is unable to access voice channel .

### ISSUE THREAD

**Issue by samrth012** [galnir/Master-Bot#180]
PLs help me ASAP
After making the bot alive connecting to my ids and tokens
It says unable to connect to voice channel

**Comment by galnir** [comment]
Fill the issue template

**Comment by samrth012** [comment]
Like what ?

**Comment by galnir** [comment]
When you open an issue there's a template to be filled which you ignored

**Comment by samrth012** [comment]
ok can you tell where to fill it now ?

**Comment by galnir** [comment]
Like I said, when you open an issue it's there. Open a new issue and fill it

**Comment by samrth012** [comment]
ok
