### ISSUE TITLE
The Bot is unable to access the voice channels

### ISSUE THREAD

**Issue by samrth012** [galnir/Master-Bot#181]
I am unable to see any template option

**Comment by galnir** [comment]
Seriously? You click open issue > bug report and then answer the questions in the text..

**Comment by samrth012** [comment]
OS - windows 10 
Hosting - Local 
Python is installed v 2.7^ and node latest version 
And screenshot will be sening in a minute

**Comment by galnir** [comment]
Did you give the bot Admin when you invited it?

**Comment by samrth012** [comment]
Yes

**Comment by galnir** [comment]
Then there's no reason it wouldn't have access to voice channels since Admin has access to all vcs. Make sure it has Admin role

**Comment by samrth012** [comment]
And also on the channel, I double-checked the permissions were granted.

**Comment by galnir** [comment]
Can you send the error? You're giving me little information I can't possibly figure out what's the problem with no info

**Comment by samrth012** [comment]
like yes 
![image](https://user-images.githubusercontent.com/63335952/91392400-8e92b700-e857-11ea-8ff5-76158803df80.png)
there is the file

**Comment by samrth012** [comment]
it connectes for a sec 
then says this

**Comment by samrth012** [comment]
![image](https://user-images.githubusercontent.com/63335952/91393981-006b0080-e858-11ea-9646-3818cabb270b.png)
see the permissions

**Comment by galnir** [comment]
In line 313 in play.js (assuming you didn't change anything) instead of an empty function call change it to: function(e) 
And add another line after the line that says cannot join your channel:
console.log(e)

Then try again and send me the error that the console shows

**Comment by samrth012** [comment]
ok

**Comment by samrth012** [comment]
check the edit 
![image](https://user-images.githubusercontent.com/63335952/91398270-64da8f80-e859-11ea-8b6d-bad11a0531ba.png)

**Comment by samrth012** [comment]
And this is the console 
![image](https://user-images.githubusercontent.com/63335952/91398452-b7b44700-e859-11ea-80ef-f6ff0643c5b5.png)

**Comment by samrth012** [comment]
it connects for a minute and then shows 
After the command - ![image](https://user-images.githubusercontent.com/63335952/91398730-4cb74000-e85a-11ea-904b-bf6ade4d2761.png)
After a second - 

![image](https://user-images.githubusercontent.com/63335952/91398738-504ac700-e85a-11ea-9f04-3806b339c661.png)

**Comment by samrth012** [comment]
Error in console 
![image](https://user-images.githubusercontent.com/63335952/91398887-96a02600-e85a-11ea-96de-386f6956eb00.png)
![image](https://user-images.githubusercontent.com/63335952/91398907-9ef86100-e85a-11ea-8a99-293976e75ebf.png)
![image](https://user-images.githubusercontent.com/63335952/91398922-a61f6f00-e85a-11ea-8591-41b0f91d77c1.png)

**Comment by samrth012** [comment]
Hey bro thanks for help i found the error with opusscript 
i reinstalled it 
and it is working thanks for your help
