### ISSUE TITLE
An error occurred while running the command: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by dhairya137** [galnir/Master-Bot#182]
When I tried to pla song than I get this error.

**Comment by galnir** [comment]
Fill the issue template

**Comment by razvandamian** [comment]
change the youtube api

**Comment by dhairya137** [comment]
> Fill the issue template

Which template??

**Comment by dhairya137** [comment]
> change the youtube api 

I made the new api and then I tried

**Comment by galnir** [comment]
@dhairya137 the one you deleted when you opened this issue

**Comment by dhairya137** [comment]
> @dhairya137 the one you deleted when you opened this issue

Ok

**Comment by dhairya137** [comment]
@galnir how I will get that template again?
bcaz I deleted that

**Comment by galnir** [comment]
Try reading #177 and tell me if that worked

**Comment by dhairya137** [comment]
I cloned yout bot today and followed every steps

**Describe the bug**
An error occurred while running the command: TypeError: Cannot read property 'length' of undefined

**To Reproduce**
Use the Play Command with Search strings (Song Name).

**Screenshots**

**Desktop (please complete the following information)**:

OS: [e.g. Windows, Ubuntu...] Linux Mint 20
Node Version(Should be v12 atleast): Yes latest
Are python 2.7 and Ffmpeg installed?: Yes
How are you hosting the bot(Locally, on a vps, heroku, glitch...): Aws vps

**Comment by dhairya137** [comment]
@galnir is this correct

**Comment by dhairya137** [comment]
![Screenshot from 2020-08-27 19-26-09](https://user-images.githubusercontent.com/40421470/91451764-5e6d0780-e89b-11ea-9ffa-13e5b453867a.png)

**Comment by galnir** [comment]
Usually that error gets thrown if you didn't place a correct api key in the config.json file. Make sure it's the correct API key and not another key that's not related

**Comment by dhairya137** [comment]
> Usually that error gets thrown if you didn't place a correct api key in the config.json file. Make sure it's the correct API key and not another key that's not related

I added right keys

**Comment by galnir** [comment]
> > Usually that error gets thrown if you didn't place a correct api key in the config.json file. Make sure it's the correct API key and not another key that's not related
> 
> I added right keys

in line 150 in play.js add an 'error' parameter inside the async catch function, then add a console.log(error) line inside that function and take a pic of the error that will appear in console

**Comment by dhairya137** [comment]
Solved thank you.
It was saying my api key is expired I create dnew api and I am good to go xD
