### ISSUE TITLE
24 Hour Livestream

### ISSUE THREAD

**Issue by cavanbecksmith** [galnir/Master-Bot#186]
I tried modifying the code to include a way to do a 24 hour livestream and I noticed ytdl-core is only valid for 6 hours then cuts out.
I tried setting a timeout to run "playSong" again and it still cuts out after 6 hours.
Can this be done or am I wasting time on this?

**Comment by galnir** [comment]
I don't know if this can be done since this is a ytdl-core thing. You should ask the dev on their discord server or open an issue on ytdl-core's GitHub repo

**Comment by galnir** [comment]
Hope that answered your question
