### ISSUE TITLE
musictrivia

### ISSUE THREAD

**Issue by razvandamian** [galnir/Master-Bot#189]
how can i add more singers to a song at musictrivia?

**Comment by Chief-Queef** [comment]
`{
      "url": "Song url here",
      "singer": "Name of singer here",
      "title": "Title of the song here"
    }`

**Comment by galnir** [comment]
There is no way having more than 1 singer. Having more would require adding more code and going through the entire json file

**Comment by razvandamian** [comment]
ok thanks!

**Comment by ModoSN** [comment]
@galnir this would be nice though, for artists like Kesha/Ke$ha and Pink/P!nk for example
