### ISSUE TITLE
Can't read property "length" of undefined

### ISSUE THREAD

**Issue by Jovantri10** [galnir/Master-Bot#191]
When am using play commands, i getting the error like 
```js 
cant read property "length" of undefined
```
fix this pls 😫😔

**Comment by galnir** [comment]
What's the full error?

**Comment by Jovantri10** [comment]
the error just that :/

**Comment by galnir** [comment]
Can you fill the issue template? You basically give no info so I can't do anything. This issue is on your end

**Comment by redbrain** [comment]
You may want to look at #14 .

**Comment by galnir** [comment]
Please try reading #14 like redbrain suggested above. If that won't do it, open a new issue and make sure to fill the template
