### ISSUE TITLE
Feature Request: Ability to queue a song earlier

### ISSUE THREAD

**Issue by Ncech99** [galnir/Master-Bot#192]
So say if you have a playlist of songs queued but you want to put a song up next but don't want to skip the entire playlist. Is this possible?

**Comment by galnir** [comment]
@Ncech99 You mean moving song number 10 for example to be the next song?

**Comment by Ncech99** [comment]
That, or maybe a special play command that will let you que a new song to the front right away. Either one will work.

**Comment by galnir** [comment]
@Ncech99 I wrote a 'move' command. Pull the new changes and let me know if that's what you meant

**Comment by galnir** [comment]
@Ncech99 If that's not what you meant comment here and I'll reopen the issue
