### ISSUE TITLE
music-trivia does not leave the audio of the music

### ISSUE THREAD

**Issue by MuskyKanne** [galnir/Master-Bot#194]
the music-trivia command is not working properly, it starts the trivia, but the bot does not play the music

**Comment by galnir** [comment]
Can you fill the issue template? Also include the error message if you get one

**Comment by MuskyKanne** [comment]
when the trivia starts, the message "Starting Music Quiz appears
Get ready! There are 5 songs, you have 30 seconds to guess either the singer / band or the name of the song. Good luck!
You can end the trivia at any point by using the end-trivia command "the bot enters the channel and then does nothing else
