### ISSUE TITLE
Volume starting at maximum when first joining and playing a song.

### ISSUE THREAD

**Issue by Lysergic-Acid** [galnir/Master-Bot#195]
Any way to prevent this? Been resorting to lowering my volume, playing a song, and then using the volume command to lower the volume. Would be nice if there was a way to set it to start at a specific level.

**Comment by galnir** [comment]
You can edit line 15 in index.js
1 means 100%, so you can change it to smt like 0.4(40%)

**Comment by Lysergic-Acid** [comment]
I probably should've know that, but thanks! I appreciate the fast response.
