### ISSUE TITLE
Wont open any music

### ISSUE THREAD

**Issue by mokakuw** [galnir/Master-Bot#197]
.

**Describe the bug**
= icant play any music 

**Expected behavior** 

= play music normally 

**Screenshots**
=
![8AB3005B-FD50-40F1-8AD0-5F6BA2321AC0](https://user-images.githubusercontent.com/71259297/93441433-6cc9a480-f8d8-11ea-99b1-9379c6da5182.jpeg)

**Desktop (please complete the following information):**

 - OS: [safari ios 13.4.1]
 - Node Version(Should be v12 atleast):  yes
 - Are python 2.7 and Ffmpeg installed?: Only ffmpeg is installed
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): yes on uptime robot

**Additional context**
 
= nah

**Comment by galnir** [comment]
Update your Node.js version to v12 at least
You answered the question which asks which version is installed with "yes"

**Comment by mokakuw** [comment]
How can i update node and install python on rebl.it

**Comment by galnir** [comment]
I have no idea, hosting on rebl.it is not recommend btw

Unless you install python 2.7 and update node, music features won't work

**Comment by redbrain** [comment]
repl.it is running on node.js v12.16.1, however you can't run python alongside it. you'll need to look for a different way to host your bot.

**Comment by galnir** [comment]
Thanks for the info @redbrain :)

**Comment by mokakuw** [comment]
Can u guys give me good hosting website idont want repl.it or glitch iwant somthing new for ios cause ihave bot that in 60 server and every 1h he goes offline iwant somthing good

**Comment by galnir** [comment]
@mokakuw There are no good sites to host the bot. Best options are locally on your PC or a vps

**Comment by redbrain** [comment]
I run my instance on my own computer, you can try using heroku's service although I haven't heard the best about them @mokakuw
