### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by razvandamian** [galnir/Master-Bot#198]
TypeError: Cannot read property 'leave' of null
 at Timeout.onTimeOut [as _onTimeout] (/app/commands/music/play.js:347:52)
at listOnTimeout (internal/timers.js:549:17)   at processTimers (internal/timers.js:492:7)

im getting this error

**Comment by galnir** [comment]
Did you force the bot to leave the voice channel before he disconnected automatically?

**Comment by razvandamian** [comment]
> .on('finish', function() {
            queue = message.guild.musicData.queue;
            if (queue.length >= 1) {
              classThis.playSong(queue, message);
              return;
            } else {
              message.guild.musicData.isPlaying = false;
              message.guild.musicData.nowPlaying = null;
              message.guild.musicData.songDispatcher = null;
              if (message.guild.me.voice.channel) {
                setTimeout(function onTimeOut() {
                  if (message.guild.musicData.isPlaying == false) {
                    message.guild.me.voice.channel.leave();
                  }
                }, 300000);
              }
            }
          })
          .on('error', function(e) {
            message.say('Cannot play song');
            console.error(e);
            message.guild.musicData.queue.length = 0;
            message.guild.musicData.isPlaying = false;
            message.guild.musicData.nowPlaying = null;
            message.guild.musicData.songDispatcher = null;
            message.guild.me.voice.channel.leave();
            return;
          });
      })
      .catch(function() {
        message.say('Nu am permisia necesara pentru a intra pe canal!');
        message.guild.musicData.queue.length = 0;
        message.guild.musicData.isPlaying = false;
        message.guild.musicData.nowPlaying = null;
        message.guild.musicData.songDispatcher = null;
        if (message.guild.me.voice.channel) {
          message.guild.me.voice.channel.leave();
        }
        return;
      });
  }

> 

this was i pasted on my code

**Comment by galnir** [comment]
pull the new changes
I recommend you to work with Git not with copy-pasting btw

**Comment by razvandamian** [comment]
yup its good now, thanks!
