### ISSUE TITLE
[Bug] !leave does not immediately disconnect the bot

### ISSUE THREAD

**Issue by redbrain** [galnir/Master-Bot#199]
## Issue
When the !leave command is issued, the bot immediately stops playing music but does not leave the channel for about 90 seconds. I'm assuming this is related to the commit "make the bot wait 2 minutes before leaving vc after music is over".

## Steps
Connect to a voice channel and start playing a song.
Then issue the leave command.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version(Should be v12 atleast): v12 lts
 - Are python 2.7 and Ffmpeg installed?: yes
 - How are you hosting the bot: locally

**Comment by razvandamian** [comment]
``		var voiceChannel = message.member.voice.channel;
		const connection = this.client.voice.connections.get(message.guild.id);
		if (!message.guild.voice || !message.guild.voice.channel) return message.channel.send(`⚠️ Im not connected on any voice channels`); // Checking if the bot is connected to any voice channels.
        if (!message.member.voice || !message.member.voice.channel) return message.channel.send(`⚠️ You are not connected on any voice channels!`); // Checking if the message author is conencted to a voice channel.
        if (message.member.voice.channelID !== message.guild.voice.channelID) return message.channel.send(`⚠️ You must be on ${message.guild.voice.channel} to execute that command.`); // Checking if the bot's voice channel is the same as message author's channel.

        message.channel.send(`Am iesit din voice channel-ul **__${message.guild.voice.channel}__**`); // Execut comanda ca un caine.
		connection.channel.leave();
	}
};``

try this

**Comment by razvandamian** [comment]
var voiceChannel = message.member.voice.channel;
const connection = this.client.voice.connections.get(message.guild.id);
if (!message.guild.voice || !message.guild.voice.channel) return message.channel.send(⚠️ Im not connected on any voice channels); // Checking if the bot is connected to any voice channels.
if (!message.member.voice || !message.member.voice.channel) return message.channel.send(`⚠️ You are not connected on any voice channels!`); // Checking if the message author is conencted to a voice channel.
if (message.member.voice.channelID !== message.guild.voice.channelID) return message.channel.send(`⚠️ You must be on ${message.guild.voice.channel} to execute that command.`); // Checking if the bot's voice channel is the same as message author's channel.

    message.channel.send(`Am iesit din voice channel-ul **__${message.guild.voice.channel}__**`); // Execut comanda ca un caine.
	connection.channel.leave();


try this it should work

**Comment by razvandamian** [comment]
var voiceChannel = message.member.voice.channel;
const connection = this.client.voice.connections.get(message.guild.id);
if (!message.guild.voice || !message.guild.voice.channel) return message.channel.send(⚠️ Im not connected on any voice channels); // Checking if the bot is connected to any voice channels.
if (!message.member.voice || !message.member.voice.channel) return message.channel.send(⚠️ You are not connected on any voice channels!); // Checking if the message author is conencted to a voice channel.
if (message.member.voice.channelID !== message.guild.voice.channelID) return message.channel.send(⚠️ You must be on ${message.guild.voice.channel} to execute that command.); // Checking if the bot's voice channel is the same as message author's channel.

message.channel.send(`Am iesit din voice channel-ul **__${message.guild.voice.channel}__**`); // Execute the command.
connection.channel.leave();
    }
};

**Comment by razvandamian** [comment]
https://pastebin.com/jwGDsFmz, this github doesnt want to accept my (`)...

**Comment by galnir** [comment]
Fixed in c7efaa4
