### ISSUE TITLE
Failed at the node-opus@0.3.2 install script.

### ISSUE THREAD

**Issue by keanuplayz** [galnir/Master-Bot#20]
I'm having issues when executing `npm i` or `npm install`.
It installs everything fine, up until this point.
The full log can be found here: https://pastebin.com/t2hLSvA8

**Comment by galnir** [comment]
@keanuplayz Did you install python 2.7 correctly? From [here](https://www.python.org/downloads/)

**Comment by keanuplayz** [comment]
I did install it. Followed the instructions you provided.

**Comment by galnir** [comment]
Well by reading the log and a quick google search I can somehow infer that you have 2 python versions installed and it tries to use your python 3.5 instead of 2.7. So you need to find a way to uninstall that version 3.5

**Comment by keanuplayz** [comment]
Alright, I'll try to do that. Thanks for the help.
