### ISSUE TITLE
Feature request: use toggles for !loop and !loopqueue

### ISSUE THREAD

**Issue by redbrain** [galnir/Master-Bot#201]
Rather than the loop command copying the current song or queue to the back of the queue, instead have a toggle for looping the song or queue. This is the style of some other bots (like Octave) and it would be a bit easier to use for the user, not to mention taking up less memory in the event that something would want to be looped for multiple hours. This seems to have come up before, in issues such as #184 , but the closing response seems unrelated.

**Comment by galnir** [comment]
Please test the new loop command and let me know if there are some bugs I missed when I tested it. I'll commit a new loopqueue command soon

**Comment by galnir** [comment]
@redbrain lemme know if you encounter bugs
