### ISSUE TITLE
TypeError: fields.flat is not a function

### ISSUE THREAD

**Issue by Kf637** [galnir/Master-Bot#202]
I got the error "TypeError: fields.flat is not a function" and I don't know what to do, there are no errors in the output
![182fd5b6c7ef71a13629d025cdba4ff0](https://user-images.githubusercontent.com/43268197/94836093-da1a2100-0412-11eb-8479-28edb5fc1825.png)
![5aa8d5e2f50948a40e928dd822094992](https://user-images.githubusercontent.com/43268197/94836116-e56d4c80-0412-11eb-9858-24f0aeeae151.png)

**Comment by galnir** [comment]
Update your Node.js to v12 atleast

**Comment by Kf637** [comment]
I've updated it to v14.13.0 bot I get the same error.

**Comment by Kf637** [comment]
![b4500588124e9b3f056a27c8a6e2b122](https://user-images.githubusercontent.com/43268197/94855576-05ab0480-042f-11eb-886b-f1502795ca2c.png)

**Comment by redbrain** [comment]
You can't update node.js this way on Glitch. instead, add
```
  "engines": {
    "node": "12.x"
  },
```
before the packages in your `package.json` file.

**Comment by Kf637** [comment]
Where do I add the script?

**Comment by redbrain** [comment]
your `package.json` file

**Comment by galnir** [comment]
I have no experience with hosting bots on Glitch, I know that it's not recommended since Glitch is mainly for hosting static web pages. 
Node.js is not installed via npm, see [this](https://nodejs.org/en/)

**Comment by Kf637** [comment]
Glitch is a very good hosting service for hosting a lot of think and I use glitch to host 7 bots and it’s a good hosting service

**Comment by galnir** [comment]
> Glitch is a very good hosting service for hosting a lot of think and I use glitch to host 7 bots and it’s a good hosting service

Nevertheless I suggest you look up on their forums how to use the latest Node.js version. The issue is that the discord.js library requires v12 at least
