### ISSUE TITLE
work about

### ISSUE THREAD

**Issue by z3h1r** [galnir/Master-Bot#206]
I could not run the bot anyway, can u explain how to do it?

**Comment by galnir** [comment]
You can follow my setup guide on [dev.to](https://dev.to/galnir/how-to-make-a-discord-music-bot-3c0p)

**Comment by z3h1r** [comment]
I applied everything but now these problems have arisen
i try   node index.js  -  npm start ;
![e12e](https://user-images.githubusercontent.com/52961754/95684817-c33ab200-0bfc-11eb-9892-06b738298b1b.PNG)
![Ekran Alıntısı54](https://user-images.githubusercontent.com/52961754/95684819-c46bdf00-0bfc-11eb-8d63-10fcdeff7342.PNG)

**Comment by galnir** [comment]
That error says you didn't install the dependencies required. If you read the guide it says to type ```npm install``` in the console after cloning this repository

**Comment by z3h1r** [comment]
Yes I already did it, now I tried again and that's the result
![jtr](https://user-images.githubusercontent.com/52961754/95685566-4827ca80-0c01-11eb-96ec-3afe79f60c3b.PNG)
![lıuşu](https://user-images.githubusercontent.com/52961754/95685570-49f18e00-0c01-11eb-81f9-9942f386a2ba.PNG)

**Comment by galnir** [comment]
Again, if you follow the guide it says to install Git. Without Git you can't install the dependencies..
Just follow the guide and it will work
