### ISSUE TITLE
Play not working

### ISSUE THREAD

**Issue by jerryop** [galnir/Master-Bot#208]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**

**To Reproduce**
1. Use 'x' command
2. provide 'y' argument

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...]
 - Node Version(Should be v12 atleast): 
 - Are python 2.7 and Ffmpeg installed?:
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...):

**Additional context**

**Comment by jerryop** [comment]
When i write prefix + play song name 
It reply  An error occurred while running the command: TypeError: fields.flat is not a function
Please say how to solve

**Comment by galnir** [comment]
Your Nodejs version needs to be v12 or greater
This error usually comes up as a result of that

**Comment by galnir** [comment]
If you update your nodejs version to v12 and it still doesnt work, open a new issue
