### ISSUE TITLE
Setup problem

### ISSUE THREAD

**Issue by jerryop** [galnir/Master-Bot#209]
When i start index.js  it shows this error.
![Screenshot_20201015-122543](https://user-images.githubusercontent.com/72891716/96087554-a8f52280-0ee1-11eb-8ccd-ad0618d9dcac.jpg)

Help me Asap...

**Comment by Natemo6348** [comment]
you have to install the dependencies by running `npm i`

**Comment by galnir** [comment]
Like Natemo said, you need to install the dependencies. Please follow the readme for instructions
