### ISSUE TITLE
About discord.js

### ISSUE THREAD

**Issue by gtagamermods** [galnir/Master-Bot#211]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**

**To Reproduce**
1. Use 'x' command
2. provide 'y' argument

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...]
 - Node Version(Should be v12 atleast): 
 - Are python 2.7 and Ffmpeg installed?:
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...):

**Additional context**

**Comment by gtagamermods** [comment]
Please help me
When I done all the formats then it's showing that index.js has a error in line 4.please help me out
![Uploading IMG_20201020_225816.jpg…]()

**Comment by galnir** [comment]
You didn't fill the template. Edit the issue and fill the questions

**Comment by gtagamermods** [comment]
> You didn't fill the template. Edit the issue and fill the questions

Can you please help me by getting a discord link if you can so that I can communicate

**Comment by galnir** [comment]
Hey @gtagamermods.
Please read this [guide](https://dev.to/galnir/how-to-make-a-discord-music-bot-3c0p) I wrote. If you follow it step by step you should get the bot running with no problems. If it won't work after carefully following the guide, please open a new issue and **fill** the template, you left it empty.
