### ISSUE TITLE
Music trivia bug

### ISSUE THREAD

**Issue by ModoSN** [galnir/Master-Bot#217]
**Describe the bug**
The music trivia seems to get stuck/confused sometimes.

**To Reproduce**
1. Type !music-trivia
2. Type !stop-trivia

**Expected behavior**
For it to start and stop when i use the command

**Screenshots**
![image](https://user-images.githubusercontent.com/13785654/97092166-8b3e6080-1639-11eb-8058-d8a1345b7cbc.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version(Should be v12 atleast): 12.0.0
 - Are python 2.7 and Ffmpeg installed?: yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): local and on a ubuntu vps, happens on both

**Additional context**

**Comment by Grivel-l** [comment]
You need to update `ytdl-core` to the latest version

**Comment by galnir** [comment]
I'll push a new commit soon

**Comment by galnir** [comment]
Try pulling the new changes and hitting ```npm i``` in console

**Comment by galnir** [comment]
Please open a new issue if pulling the new changes and updating the dependencies don't work

**Comment by ModoSN** [comment]
@galnir still happening 
![image](https://user-images.githubusercontent.com/13785654/97494282-023b6800-195e-11eb-9626-ea2d652d5174.png)

**Comment by Grivel-l** [comment]
I believe it is another error, you need to catch it by adding an error event on the `collector` or `dispatcher` object in `commands/music/musictrivia.js` if I remember correctly

**Comment by galnir** [comment]
I'll look into it

**Comment by Natemo6348** [comment]
weird, i don't get that error

**Comment by ModoSN** [comment]
After looking into this a bit, I believe this happens when the bot gets stuck trying to play a song but the YouTube video has been removed 

Perhaps some sort of error or it checking if all the songs are playable before it starts? 

Maybe if unable to play then skip song? Not sure

**Comment by galnir** [comment]
I replaced 4 broken urls in the latest commit. Pull the new changes and lemme know if it persists

**Comment by ModoSN** [comment]
![image](https://user-images.githubusercontent.com/13785654/97788445-db28a480-1bb0-11eb-8ec4-ebb9c7762fe1.png)

Still persists

**Comment by Grivel-l** [comment]
As @ModoSN pointed out, this issue will persist until we do some error checking in the code.
Shouldn't we keep this issue open until this is fixed ?

**Comment by galnir** [comment]
@ModoSN What's the next message in chat? What did the bot respond to the !stop-trivia call?

**Comment by ModoSN** [comment]
@galnir no message shows, had to kill the bot to get any response

**Comment by galnir** [comment]
Please try pulling the new changes(most importantly is the ytdl-core version update) and install the dependencies again. Updating to ytdl-core@4.0.2 may solve this issue

**Comment by Bacon-Fixation** [comment]
anyone still having this bug? 
i ran 10k rounds today and only had 12 errors (API limit) which i feel isacceptable failure rate

Much Love
-Bacon
