### ISSUE TITLE
Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by xRoier** [galnir/Master-Bot#22]
C:\botBounceGaming\Master-Bot\index.js:6
Structures.extend('Guild', Guild => {
           ^

TypeError: Cannot read property 'extend' of undefined
    at Object.<anonymous> (C:\botBounceGaming\Master-Bot\index.js:6:12)
[90m    at Module._compile (internal/modules/cjs/loader.js:956:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:812:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:724:14)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m

**Comment by galnir** [comment]
Did you install discord.js master and discord.js/commando master?
Did you clone the repo or copy code into existing codebase?

**Comment by A7U** [comment]
I'm having the same issue, I did everything I could possibly do

**Comment by galnir** [comment]
@xRoier 
I will reopen the issue if the solution above doesn't work for you.
