### ISSUE TITLE
DiscordAPIError: Missing Permissions

### ISSUE THREAD

**Issue by mkgaming54** [galnir/Master-Bot#256]
whenever im trying to play a song it 
![3F428495-9714-4A67-80B8-E45880E55299_4_5005_c](https://user-images.githubusercontent.com/68937935/97733355-bb847400-1afd-11eb-9265-4f3097931b44.jpeg)
sends a msg like

**Comment by Bacon-Fixation** [comment]
what permissions did you set on DJ Fab when you invited him to your server needs Speak and Connect to play music

**Comment by Bacon-Fixation** [comment]
try with 
- Send Message
- Embed Links 
- View Channels
- Connect
- Speak
- Manage Messages

**Comment by mkgaming54** [comment]
> what permissions did you set on DJ Fab in the dashboard of the discord dev portal when you invited him to your server needs Speak and Connect to play music
> 
> * **Demonstration Only** (just a visual aid)
>   ![permissions](https://user-images.githubusercontent.com/12632936/97736210-5737c500-1aa9-11eb-8036-6032de4d6798.PNG)
> 
> Screenshot is from https://discordpy.readthedocs.io/en/latest/discord.html
> 
> try with
> 
> * Send Message
> * Embed Links
> * View Channels
> * Connect
> * Speak
> * Manage Messages
> 
> ***Optional**
> 
> * Kick Members
> * Ban Members
> 
> you can always kick your bot and re-invite him with new permissions
> 
> Much Love
> -Bacon

i gave adminstrator

**Comment by mkgaming54** [comment]
btw im unable to find genius lyrics api :(

**Comment by galnir** [comment]
You need to make sure the role the bot has is at the top of the hierarchy in the server settings. About the genius lyrics, make sure you generated an api key and it is the correct key

**Comment by Bacon-Fixation** [comment]
for genius lyrics you can try https://genius.com/api-clients if you have made a token

**Comment by galnir** [comment]
@mkgaming54 Did you manage to solve these issues with the solutions we provided?

**Comment by galnir** [comment]
The solutions above should fix your issue, I know cause I had it before. Open a new issue if they don't work(follow them carefully before tho)
