### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Happyman001144** [galnir/Master-Bot#257]
Upon running a play command I get this error "@GamingWay, An error occurred while running the command: TypeError: Cannot read property 'length' of undefined
You shouldn't ever receive an error like this.
Please contact GamingWay#9629."

**Comment by galnir** [comment]
Can you fill the issue template? It appears when you open an issue

**Comment by galnir** [comment]
closed because you opened a new one
