### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by eryycr** [galnir/Master-Bot#258]
**Describe the bug**
When i try to do /p or /play it make a issues, but that only with play command, there aren't problem with other commands 

**To Reproduce**
1. Use play command
2. "ping", An error occurred while running the command: TypeError: Cannot read property 'length' of undefined
You shouldn't ever receive an error like this.

**Expected behavior**
i install your bot fo fun and i do 'npm i' command and all config with all api, i start the bot with 'node .' and do '/p (song name)' but it doesn't work!
![issues](https://user-images.githubusercontent.com/66038700/97781991-3ba6ea00-1b8f-11eb-958f-abf0f08ab78d.jpg)

**Screenshots**
Evident issues

**Desktop (please complete the following information):**
 - Windows 10 
 - Node Version 12.19.0
 - python 2.7+ and Ffmpeg are installed. 
 - SomethingCP Hosting (but when there are some issues i use Visual Studio Terminal)

**Additional context**

**Comment by galnir** [comment]
Because of the error you're getting, I'm pretty sure your API key is invalid. Make sure you generated and placed the correct key in the config.json file

**Comment by ModoSN** [comment]
Duplicate issue of https://github.com/galnir/Master-Bot/issues/257

**Comment by eryycr** [comment]
> Duplicate issue of #257

yha but the issue isn't explane so...

**Comment by eryycr** [comment]
> Because of the error you're getting, I'm pretty sure your API key is invalid. Make sure you generated and placed the correct key in the config.json file

idk what api key is invalid! 
i recreate all of them, but tysm for help i'll recreate all key...

**Comment by galnir** [comment]
You don't need to regenerate them all, only the youtube one and make sure you put in the correct youtube key, because it generates 3 keys
