### ISSUE TITLE
2 errors

### ISSUE THREAD

**Issue by A7U** [galnir/Master-Bot#26]
Structures.extend('Guild', Guild => {
           ^
and,

TypeError: Cannot read property 'extend' of undefined
at Object.<anonymous> (/app/index.js:6:12)

**Comment by galnir** [comment]
Did you clone this repo?

**Comment by A7U** [comment]
yes I did

**Comment by galnir** [comment]
This error is emitted when the master branch of discord.js isn't installed
Try npm install discordjs/discord.js

**Comment by A7U** [comment]
I'm using glitch.com so umm I did that but showed me like 22 vuranabilities need fix and I did try to fix but didn't work

**Comment by A7U** [comment]
Ok I did fix, but still having the error

**Comment by A7U** [comment]
Galnir I did install every single dependency

**Comment by galnir** [comment]
That error only happens when discord.js master is not installed. Are you installing the dependencies in the right folder? All you need to do if you cloned this repo is run `npm install` in the root folder

**Comment by galnir** [comment]
@A7U Will reopen this issue if the solutions above dont work for you.
