### ISSUE TITLE
Error when doing !music-trivia 0

### ISSUE THREAD

**Issue by ModoSN** [galnir/Master-Bot#260]
**Describe the bug**
When you tell music-trivia to play 0 songs, it gets confused and errors.

**To Reproduce**
![image](https://user-images.githubusercontent.com/13785654/97784764-c17b6300-1b98-11eb-95e5-9a0ac899dc69.png)

**Expected behavior**

- do not allow the value of 0

**Desktop (please complete the following information):**
 - OS: Windows Server
 - Node Version(Should be v12 atleast): 12.0.0
 - Are python 2.7 and Ffmpeg installed?: Yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): VPS

**Comment by galnir** [comment]
Fixed in b7e273e
