### ISSUE TITLE
How to stop this unwanted msg?

### ISSUE THREAD

**Issue by mkgaming54** [galnir/Master-Bot#262]
**Explain your suggestion**
How can i stop this msg? 
![391F5D76-E41E-48A3-B241-6910367511C0_4_5005_c](https://user-images.githubusercontent.com/68937935/97792217-66ca2180-1c01-11eb-9476-35d47ebcfdf7.jpeg)

**Comment by Bacon-Fixation** [comment]
for me i use `!` as a prefix to prevent Triggers during conversation

using `'` would mean words like "that's", "don't" will trigger this error 
because there isn't a `'s` or `'t` commands 

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
I don't understand what you mean, is this triggering during conversation?

You can try changing the prefix to a different symbol than ``` to like `!` and see if it still happens.

if you can give me some more info like what the situation that made the message appear.

Much Love
-Bacon

**Comment by mkgaming54** [comment]
@Bacon-Fixation the problem is whenever i use a wrong command it shows this msg. My prefix is ` .
When I type "`<examplewrongcmd>" It shows this msg. I don't want this :(

**Comment by ModoSN** [comment]
Can you show the message from above? 

So we know what is triggering the message.

**Comment by mkgaming54** [comment]
> Can you show the message from above?
> 
> So we know what is triggering the message.

@ModoSN yea sure
![54052286-B95B-457C-BADD-38B253909D38](https://user-images.githubusercontent.com/68937935/97804228-7c2c6380-1c74-11eb-89de-40429103ddf9.jpeg)

**Comment by galnir** [comment]
Read #81 , you need to disable the help command

**Comment by mkgaming54** [comment]
@galnir ty :)

**Comment by PRINCE-HERE** [comment]
Uh hi 👋🏻 First of all thanks for this repostiry so much! U rly appreciate your hard work! I wanted to ask that how to remove that unknown command thingy. I already removed the help command. But idk how to remove that unknown command thingy. I've Read #81 carefully but idk about the unknown command thingy

**Comment by galnir** [comment]
> Uh hi 👋🏻 First of all thanks for this repostiry so much! U rly appreciate your hard work! I wanted to ask that how to remove that unknown command thingy. I already removed the help command. But idk how to remove that unknown command thingy. I've Read #81 carefully but idk about the unknown command thingy

Yeah as I wrote there you need to add 'unknownCommand' property and set it to false:
```.registerDefaultCommands({ eval: false, prefix: false, commandState: false, help: false, unknownCommand: false })```

You're also welcome to take a look at the new version of the bot I released yesterday, it uses new features like slash commands and select menus

**Comment by PRINCE-HERE** [comment]
Oh Thanks for your help! Well I'm facing a new problem. I can't hear Music in the music-trivia and when I jist play a song the bot can't join the vc (it have administrator) but still says I don't have perms to join ur vc.

**Comment by galnir** [comment]
> Oh Thanks for your help! Well I'm facing a new problem. I can't hear Music in the music-trivia and when I jist play a song the bot can't join the vc (it have administrator) but still says I don't have perms to join ur vc.

Did you install everything I listed in the requirements?

**Comment by PRINCE-HERE** [comment]
I added all the api keys. I use repl So I don't need to download those node.js and raspberry?
