### ISSUE TITLE
Fix this

### ISSUE THREAD

**Issue by 3raden** [galnir/Master-Bot#263]
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\npm-packlist-27721e70\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\npm-bundled-b13a45d4\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\npm-bundled-b13a45d4\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\npm-normalize-package-bin-667908e8\.npmignore'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\normalize-path-61f820aa\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\npm-packlist-27721e70\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\npm-bundled-b13a45d4\package.json'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\npm-normalize-package-bin-667908e8\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\normalize-path-61f820aa\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\npm-bundled-b13a45d4\README.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\normalize-path-61f820aa\LICENSE'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\normalize-path-61f820aa\README.md'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\resolve-url-ae4c8bb6\test\resolve-url.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\ret-514f09ea\lib\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\common-tags-0ccf831f\lib\oneLine\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\ret-514f09ea\lib\positions.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\common-tags-0ccf831f\lib\oneLine\oneLine.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\ret-514f09ea\lib\sets.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\ret-514f09ea\lib\types.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\ret-514f09ea\lib\util.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\parse5-17233182\lib\extensions\location_info\open_element_stack_mixin.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\parse5-17233182\lib\extensions\location_info\parser_mixin.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\lib\validators\react\isCompatTag.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\parse5-17233182\lib\extensions\location_info\tokenizer_mixin.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\lib\validators\react\isReactComponent.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@discordjs\opus-2321ec33\deps\opus\silk\fixed\find_LPC_FIX.c'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\lib\definitions\jsx.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\scripts\utils\lowerFirst.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@discordjs\opus-2321ec33\deps\opus\silk\fixed\find_LTP_FIX.c'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@discordjs\opus-2321ec33\deps\opus\silk\fixed\find_pitch_lags_FIX.c'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\lib\definitions\misc.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\lib\definitions\placeholders.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\lib\modifications\prependToMemberExpression.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@discordjs\opus-2321ec33\deps\opus\silk\fixed\find_pred_coefs_FIX.c'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\lib\comments\removeComments.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\lib\modifications\removeProperties.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\lib\modifications\removePropertiesDeep.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@discordjs\opus-2321ec33\deps\opus\silk\fixed\k2a_FIX.c'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@discordjs\opus-2321ec33\deps\opus\silk\fixed\k2a_Q16_FIX.c'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\lib\utils\shallowEqual.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\scripts\utils\stringifyValidator.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\lib\converters\toBindingIdentifierName.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\lib\converters\toBlock.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\lib\converters\toComputedKey.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\lib\converters\toExpression.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\scripts\utils\toFunctionName.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\lib\converters\toIdentifier.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\lib\converters\toKeyAlias.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\lib\converters\toSequenceExpression.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\lib\converters\toStatement.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@discordjs\opus-2321ec33\deps\opus\silk\arm\LPC_inv_pred_gain_neon_intr.c'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\lib\definitions\typescript.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\scripts\generators\typescript.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@discordjs\opus-2321ec33\deps\opus\silk\fixed\LTP_analysis_filter_FIX.c'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\lib\definitions\utils.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@discordjs\opus-2321ec33\deps\opus\silk\fixed\LTP_scale_ctrl_FIX.c'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@babel\types-fdd214c6\lib\converters\valueToNode.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@discordjs\opus-2321ec33\deps\opus\src\mapping_matrix.c'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\@discordjs\opus-2321ec33\deps\opus\src\mlp_data.c'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\rxjs-8c637dbe\src\internal\AsyncSubject.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\rxjs-8c637dbe\src\internal\BehaviorSubject.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\rxjs-8c637dbe\src\internal\config.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\rxjs-8c637dbe\src\internal\InnerSubscriber.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\rxjs-8c637dbe\src\internal\Notification.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\rxjs-8c637dbe\src\internal\Observable.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\rxjs-8c637dbe\src\internal\scheduled\scheduleArray.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\rxjs-8c637dbe\src\internal\scheduled\scheduled.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\rxjs-8c637dbe\src\internal\scheduled\scheduleIterable.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\rxjs-8c637dbe\src\internal\scheduled\scheduleObservable.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\brade\Downloads\Master-Bot-master\Master-Bot-master\node_modules\.staging\rxjs-8c637dbe\src\internal\scheduled\schedulePromise.ts'
npm WARN master-bot@1.0.0 No repository field.

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/discordjs/Commando.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by 3raden** [comment]
How do i fix

**Comment by galnir** [comment]
You didn't install Git

**Comment by ModoSN** [comment]
You haven't followed the template, but yeah you need to install Git.

**Comment by galnir** [comment]
If after installing Git through the [git website](https://git-scm.com/) you still run into problems, you're welcome to open a new issue
