### ISSUE TITLE
how

### ISSUE THREAD

**Issue by alonalibarmn** [galnir/Master-Bot#265]
when i do !help i get
To run a command in גברים מהדסים, use %command or @DJ coshi#4346 command. For example, %prefix or @DJ coshi#4346 prefix.
To run a command in this DM, simply use command with no prefix.

Use help <command> to view detailed information about a specific command.
Use help all to view a list of all commands, not just available ones.
whare i edit it?

**Comment by ModoSN** [comment]
Please follow the bug template: https://github.com/galnir/Master-Bot/issues/new?assignees=&labels=bug&template=bug_report.md&title=

Also, please provide screenshots so we can help better.

**Comment by alonalibarmn** [comment]
its nut a bug i mean i want to edit the !help

**Comment by ModoSN** [comment]
Edit the `config.json` or `commands/other/help.js`

**Comment by alonalibarmn** [comment]
thare is no commands/other/help.js or something in config.json

**Comment by galnir** [comment]
You cant edit the help command, because it comes with the Commando framework. Read #81 on how to disable it. After you disable it you can write a new one

**Comment by alonalibarmn** [comment]
![image](https://user-images.githubusercontent.com/71559074/97804539-4e85f100-1c59-11eb-9961-ca1062b4cbbb.png)
still

**Comment by galnir** [comment]
You need to add a line:
help: false

**Comment by alonalibarmn** [comment]
![image](https://user-images.githubusercontent.com/71559074/97806280-93af2080-1c63-11eb-95ec-a80dc43dfbf5.png)

**Comment by galnir** [comment]
you need to add a , after the false

**Comment by alonalibarmn** [comment]
![image](https://user-images.githubusercontent.com/71559074/97806345-e4bf1480-1c63-11eb-8c1e-5ad53cbbc7a0.png)
still

**Comment by galnir** [comment]
did you put a , after the line before?

**Comment by alonalibarmn** [comment]
![image](https://user-images.githubusercontent.com/71559074/97806381-ff918900-1c63-11eb-9ba6-c15296f7ca9d.png)

**Comment by galnir** [comment]
Put a , after the commandState: false

**Comment by alonalibarmn** [comment]
ok ty and how do i edit this
![image](https://user-images.githubusercontent.com/71559074/97806558-d0c7e280-1c64-11eb-95f0-a4c08fed73b5.png)

**Comment by alonalibarmn** [comment]
how can i edit this

**Comment by alonalibarmn** [comment]
?

**Comment by galnir** [comment]
You also need to disable the unknown command and create a new command for this
To disable do the same you did with help just with unknownCommand: false
