### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by RikuDola-ctrl** [galnir/Master-Bot#266]
I'm not 100% if you could label this as a bug, but when I search a song that has a `"` in the title, it will instead show `quot;` in the title when it is being searched.
Is there a way to replace the `quot;` with `"`?
Thanks a lot

**Comment by Bacon-Fixation** [comment]
I'm having the same thing as well any title with punctuation is doing that same thing .

![search weirdness](https://user-images.githubusercontent.com/12632936/97809738-6ac36700-1c34-11eb-8a2a-52f515388146.PNG)

but only during search
 
doesn't seem to appear in other embed messages

**Comment by galnir** [comment]
For some reason when searching for a video the youtube api does that. When fetching the chosen video it doesn't do that.
I'll try to write something that replaces ```quot;``` with ```""``` when I'll have time for that. Thanks for opening this issue and making me aware of this

**Comment by RikuDola-ctrl** [comment]
tyvm

**Comment by Bacon-Fixation** [comment]
@RikuDola-ctrl do you happen to have a search term that will give me a search result with "" quotes

**Comment by Natemo6348** [comment]
@Bacon-Fixation here's one

“Hello, world” from scratch on a 6502 — Part 1

It's a video, but it has quotes lol

**Comment by Natemo6348** [comment]
ah ok
