### ISSUE TITLE
Hi how can i change the messages

### ISSUE THREAD

**Issue by saltukozelgul** [galnir/Master-Bot#27]
Hi greetings. i'm using your bot at my discord server but i have to translate to Turkish
I translated commands but i can't edit help command. For example when i write //help bot says "Sent you a DM with information." but i want to change it. I can not find it at files can you help me? (:

**Comment by galnir** [comment]
Help command comes with Commando. You can disable it and make own of your own. Look at the docs to find out how I don't remember :/

**Comment by galnir** [comment]
It's here https://discord.js.org/#/docs/commando/master/class/CommandoRegistry?scrollTo=registerDefaultCommands
You need to set help command to false(the method is called in index.js). Then just make one of your own and place it under the 'guild' folder or the 'other' folder

**Comment by saltukozelgul** [comment]
Hi again. I deleted   ".registerDefaultCommands()" in index.js and yes it worked //help command isn't working anymore thanks a lott, but i have another question. When i use play command bot says "Respond with "cancel" to cancel command..." i guess it comes with Commando as well but how can i delete it? I want to translated it Turkish at all so i want to delete it.

**Comment by galnir** [comment]
You need to change that manually in Commando's code. Btw you can also change help command manually there if you want it back. 
Open your node modules, go to discord.js-commando/src/commands/argument.js 
Translate lines 184, 273 and 281. That's for the "respond with..." message. 

If you want to translate the help command, open up discord.js-commando//src/commands/util/help.js and translate lines 57 and 98

**Comment by galnir** [comment]
@saltukozelgul Did it work?

**Comment by galnir** [comment]
The solutions above should work, if not, I'll reopen the issue.
