### ISSUE TITLE
Another problem-

### ISSUE THREAD

**Issue by RikuDola-ctrl** [galnir/Master-Bot#272]
anyways, on search it shows` &amp;` instead of `&`, just wanted y'all to know, i got it fixed

**Comment by Bacon-Fixation** [comment]
Here you go @RikuDola-ctrl 

If you find more let me know

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
@RikuDola-ctrl  Did it solve your issue ?

**Comment by RikuDola-ctrl** [comment]
yes, but it seems there is an error with #, but i cant find what to replace it with

**Comment by Bacon-Fixation** [comment]
> yes, but it seems there is an error with #, but i cant find what to replace it with
> @Bacon-Fixation

@RikuDola-ctrl 
I've updated again to catch all of them

**Comment by Bacon-Fixation** [comment]
@RikuDola-ctrl was your issue fixed?

Much Love
-Bacon
