### ISSUE TITLE
How do I change this so I can add the bot online status ie. (Idle. Online, DND, Invs)

### ISSUE THREAD

**Issue by Pierzety** [galnir/Master-Bot#274]
console.log('Ready!');
  client.user.setActivity(`${prefix}help | 2 Servers `, {
    type: 'WATCHING',
    url: "blank"
    
  });
});

**Comment by galnir** [comment]
Add another property 'status' and set its value to 'idle' or whatever youd like

**Comment by Natemo6348** [comment]
i'm surprised i didn't realize this, i was about to try and do it with client.user.setStatus()

**Comment by Natemo6348** [comment]
i tried adding a 'status' property, and it didn't work, so I guess I'll do client.user.setStatus('value')

**Comment by galnir** [comment]
@Natemo6348 @Pierzety Oh I thought OP meant something else. 
What OP wants can be done by doing
```client.user.presence.equals(value)```
value can be 'online', 'idle', 'offline', 'dnd'
