### ISSUE TITLE
Can you please keep stop commad to stop the music playing not only for music trivia

### ISSUE THREAD

**Issue by koushikpuppala5** [galnir/Master-Bot#275]
**Explain your suggestion**

**Comment by galnir** [comment]
!stop is equal to !pause
I don't understand what do you mean

**Comment by koushikpuppala5** [comment]
> !stop is equal to !pause
> I don't understand what do you mean

Means pause means it will not end the song 
Stop means it will end the whole query of the paylist

**Comment by galnir** [comment]
> > !stop is equal to !pause
> > I don't understand what do you mean
> 
> Means pause means it will not end the song
> Stop means it will end the whole query of the paylist

!skipall (or !skip-all) ends the whole query and leaves the voice channel after 1.5 mins of inactivity
!leave ends the whole query and leaves the voice channel immediately

**Comment by koushikpuppala5** [comment]
I don't want bot to leave the channel

**Comment by galnir** [comment]
> I don't want bot to leave the channel

Then you have !skipall
You can change the number in line 319 to a bigger one if you want the bot to leave after a long time of inactivity

**Comment by koushikpuppala5** [comment]
In which

**Comment by galnir** [comment]
> In which

play.js

**Comment by koushikpuppala5** [comment]
If I remove the whole it will never leave the server

**Comment by galnir** [comment]
If you want it to **never** leave the channel, remove lines 309 and 319

**Comment by koushikpuppala5** [comment]
Where is help command

**Comment by galnir** [comment]
It comes with the discord.js-commando package. If you want to write a new one you need to disable it, read #81

**Comment by koushikpuppala5** [comment]
But I need some stop commad not skip 
It is better to use

**Comment by galnir** [comment]
!skipall basically does what you ask for, you want it to be named stop? Just remove the 'stop' alias from line 7 in pause.js and add a 'stop' alias in skipall.js line 7

**Comment by koushikpuppala5** [comment]
Ok

**Comment by galnir** [comment]
If you have issues with the bot you're always welcome to open a new one, enjoy :)

**Comment by koushikpuppala5** [comment]
Do you know how remove automatically command typed by us

**Comment by galnir** [comment]
You can disable the help, ping, unknownCommand the same way #81 describes how to disable help

**Comment by koushikpuppala5** [comment]
Not that if we type '+help' can we delete this with the help of bot

**Comment by galnir** [comment]
I honestly don't get what you mean, if you could write that with correct english chances are I would understand

**Comment by koushikpuppala5** [comment]
See I have typed '+help' to get commands
Now I will get msg for bot 
At the same time can bot delete this '+help' statement

**Comment by koushikpuppala5** [comment]
I saw it in botgoast

**Comment by koushikpuppala5** [comment]
![Screenshot_2020-11-07-16-24-32-31.jpg](https://user-images.githubusercontent.com/70138027/98439137-c189de80-2115-11eb-8a4e-bf51f486fb6a.jpg)

**Comment by galnir** [comment]
I'll keep this request of yours in mind, in the future I will add this

**Comment by koushikpuppala5** [comment]
Ok please do it fast
