### ISSUE TITLE
how to fix

### ISSUE THREAD

**Issue by alonalibarmn** [galnir/Master-Bot#276]
why do i get this and the bot have perm
![image](https://user-images.githubusercontent.com/71559074/98543776-a21cbe00-229b-11eb-8ad8-2e6a7add6e91.png)

**Comment by Bacon-Fixation** [comment]
Hello @alonalibarmn,
you can try this 

As an Admin of your discord server double check that the bot has permission to join the channel 
right-click on your server and click 'server settings' you are looking for 'Roles' should be second from the top
now find your bot check your permissions 

if its set correctly look into the channel setting and add your bot if it is a private channel
right-click channel and invite your bot

if the other solutions don't work for you can try the solutions in #256 

Much Love
-Bacon

**Comment by galnir** [comment]
This error might show up if you didn't install ffmpeg/ytdl-core correctly.
What OS are you running the bot on?

**Comment by galnir** [comment]
Closing because of no response
