### ISSUE TITLE
Change the text while using help command

### ISSUE THREAD

**Issue by icsmac** [galnir/Master-Bot#28]
How to change the Text list of Help command?

**Comment by galnir** [comment]
Look at #27

**Comment by icsmac** [comment]
How do i change the status of of bot?
Like instead of Playing, its Listening
I change it to listening nothing happens

**Comment by galnir** [comment]
@icsmac Pull the new changes I just made to the bot and update line 47 in index.js :)

**Comment by icsmac** [comment]
Thank you 😇
