### ISSUE TITLE
need custum prefix command

### ISSUE THREAD

**Issue by koushikpuppala5** [galnir/Master-Bot#280]
**Explain your suggestion**
We need to change prefix from one channel to another channel

**Comment by galnir** [comment]
You can change line 47 in index.js to
```prefix: true,```

**Comment by koushikpuppala5** [comment]
Thanks 👍👍👍👍👍

**Comment by Natemo6348** [comment]
is there a way to use the existing code of the premade prefix command and edit it to store prefixes from each server in a JSON?

**Comment by koushikpuppala5** [comment]
> is there a way to use the existing code of the premade prefix command and edit it to store prefixes from each server in a JSON?

We have to do some changes
