### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by RikuDola-ctrl** [galnir/Master-Bot#284]
Well, this is a bug report and a feature request, but mainly a bug report. So, when I move the bot to a different voice-channel than it was already in, it would leave after starting a new song and join the voice-channel it was originally in when I started playing music. Also, please make a `!summon` command that summons the bot to the voice-channel you are currently in.

Thanks a lot! 😁
~ Riku

**Comment by RikuDola-ctrl** [comment]
[[A]]+[[Shift]]

**Comment by galnir** [comment]
I fixed the issue in commit 135756b
I told someone before that I don't intend on writing a !summon command because it's pretty useless to have the bot idle in a voice channel
