### ISSUE TITLE
Play commad is not working

### ISSUE THREAD

**Issue by koushikpuppala5** [galnir/Master-Bot#290]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**

**To Reproduce**
1. Use 'x' command
2. provide 'y' argument

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...]
 - Node Version(Should be v12 atleast): 
 - Are python 2.7 and Ffmpeg installed?:
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...):

**Additional context**

**Comment by koushikpuppala5** [comment]
![IMG20201113185807.jpg](https://user-images.githubusercontent.com/70138027/99077061-2fd11400-25e2-11eb-8028-1a2d5f6738d7.jpg)![IMG20201113185752.jpg](https://user-images.githubusercontent.com/70138027/99077070-32cc0480-25e2-11eb-8621-efafd2d2c4d0.jpg)


I am getting like this pic
First one is in logs of bot hosting
Second one is in server

**Comment by galnir** [comment]
Try updating your ytdl-core version:
npm i ytdl-core@4.0.3

**Comment by koushikpuppala5** [comment]
I am hosting it in disclould in that no need to download

**Comment by galnir** [comment]
You need to update your ytdl-core version in order to fix this issue. I don't know what discloud is but you need to find a way to update it there

**Comment by koushikpuppala5** [comment]
Mine is latest

**Comment by Natemo6348** [comment]
This may be an error with the YouTube API. I had this issue before, and all I had to do to fix it was to generate a new API key and change it in config.json

**Comment by galnir** [comment]
> Mine is latest

Does it do that for every video? If yes there's a problem with your API key. If not, can you run ```npm list ytdl-core``` and take a screenshot?

**Comment by koushikpuppala5** [comment]
I will try tomorrow morning and I will send

**Comment by koushikpuppala5** [comment]
No it is not working again error
![16053504858401737777308121533506](https://user-images.githubusercontent.com/70138027/99145360-1ee0db00-2694-11eb-87c6-a0edd327a6e6.jpg)
![16053505211021983332634099295582](https://user-images.githubusercontent.com/70138027/99145363-26a07f80-2694-11eb-9c17-d80572d0feea.jpg)
![16053505375178659676866178651389](https://user-images.githubusercontent.com/70138027/99145365-30c27e00-2694-11eb-84c5-a5e7e0c25ea3.jpg)

**Comment by galnir** [comment]
Can you take the picture I requested?

**Comment by koushikpuppala5** [comment]
Which

**Comment by galnir** [comment]
Look at my comment above

**Comment by Natemo6348** [comment]
@koushikpuppala5 run `npm list ytdl-core` and screenshot the output

**Comment by Natemo6348** [comment]
Oh I see you got a different error this time, last time had a status code 429, this one has status code 416

**Comment by galnir** [comment]
ytdl-core@4.0.4 probably fixes this but you're not providing the screenshot

**Comment by koushikpuppala5** [comment]
I am getting error in upload of screen shot I will try tomorrow morning again

**Comment by koushikpuppala5** [comment]
![Uploading Screenshot_2020-11-15-23-33-24-30.jpg…]()

**Comment by galnir** [comment]
@koushikpuppala5 okay so what is displayed when you '''npm i ytdl-core'''?

**Comment by koushikpuppala5** [comment]
^4.0.3

**Comment by koushikpuppala5** [comment]
![2020-11-16](https://user-images.githubusercontent.com/70138027/99210749-a4779e80-27ec-11eb-9dd6-7758d64e9cbe.png)
   
i am geting now like this

**Comment by koushikpuppala5** [comment]
Typeerror: this.fetchUser is not a function

**Comment by galnir** [comment]
First of all, update your ytdl-core version to the latest version(4.0.5):
```npm i ytdl-core@4.0.5```

About the this.fetchUser error, you need to provide info. What command are you trying to use?

**Comment by koushikpuppala5** [comment]
Yes did it is working but getting error like this some time


In log

🎶Musics is Ready to Play🎶
[
  'IRON MAN™',
  '✨𝐼𝑁𝐷𝐼𝐴𝑁 𝐶𝑂𝑀𝑀𝐴𝑁𝐷𝑂𝑆™✨',
  'TEST SERVER',
  'AVENGERS ASSEMBLY'
] Connected!
Fontconfig warning: \"/etc/fonts/fonts.conf\", line 100: unknown element \"blank\"
MinigetError: input stream: Status code: 416
    at ClientRequest.\u003canonymous\u003e (/home/node/node_modules/miniget/dist/index.js:197:27)
    at ClientRequest.args.\u003ccomputed\u003e (/etc/node_modules/appmetrics/lib/aspect.js:30:20)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at HTTPParser.execute (\u003canonymous\u003e)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:315:20) {
  statusCode: 416
}

**Comment by koushikpuppala5** [comment]
![Screenshot_2020-11-17-10-16-43-75](https://user-images.githubusercontent.com/70138027/99347930-4e732b80-28be-11eb-9e78-1f1d63e7ff56.jpg)

**Comment by galnir** [comment]
Again can you provide more information? What do you do that triggers this error

**Comment by koushikpuppala5** [comment]
I have type +play music's and it gave me 5 option and I selected 2nd option then it is stopped by saying that  can't play music

![2020-11-17_LI](https://user-images.githubusercontent.com/70138027/99355254-f2180800-28cd-11eb-9bcd-27f4d1b7471c.jpg)

**Comment by galnir** [comment]
I've never seen this error, did you change anything in play.js?

**Comment by koushikpuppala5** [comment]
![2020-11-17 (3)_LI](https://user-images.githubusercontent.com/70138027/99355742-da8d4f00-28ce-11eb-9683-4ee46563cb96.jpg)
![2020-11-17 (1)](https://user-images.githubusercontent.com/70138027/99355752-dd883f80-28ce-11eb-8a13-2b72610fde67.png)

no i have not change any but i have extended life time of bot in voice channel

**Comment by Bacon-Fixation** [comment]
I've gotten this error 416 today on current commit when a song tries to start but gets a 416 Requested Range Not Satisfiable From youtube

**Comment by koushikpuppala5** [comment]
what to do

**Comment by Bacon-Fixation** [comment]
try npm i miniget@3.1.0

**Comment by Bacon-Fixation** [comment]
This 416 error is very random I can play the same URL 200 and 10 failed to 416 Error with an unaltered Clone of the bot
I really don't know why

**Comment by koushikpuppala5** [comment]
Ok

**Comment by Bacon-Fixation** [comment]
@koushikpuppala5 try this #298

**Comment by Natemo6348** [comment]
I think it's weird that I've never gotten status 416

**Comment by Bacon-Fixation** [comment]
i had to go looking for link that would fail and worked backwards

**Comment by galnir** [comment]
#298 fixes this for me aswell. 
@koushikpuppala5 Pull all the new changes, update your dependencies and make sure you did it correct. If you still get errors after doing these steps, open a new issue
