### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by razvandamian** [galnir/Master-Bot#293]
saved playlists delete after restart on heroku

**Comment by Natemo6348** [comment]
This is caused by something unknown to us because I have the same issue

**Comment by galnir** [comment]
@Natemo6348 On heroku?

**Comment by razvandamian** [comment]
idk, it happens for me on heroku, i didnt try on another hosting things but yes...

**Comment by galnir** [comment]
This is out of my reach, I have no idea why heroku recreates/deletes json.sqlite every time you restart the bot. You can Google similar issues or copy the file before every restart :/

**Comment by razvandamian** [comment]
we can't copy the json file couse we dont have access to heroku ftp or console

**Comment by Bacon-Fixation** [comment]
Maybe this helps ya https://www.reddit.com/r/webdev/comments/aq495t/prevent_heroku_from_deleting_my_sqlite_database/

**Comment by galnir** [comment]
> there may not be an easy way to fix this tbh @galnir
> Maybe this helps ya https://www.reddit.com/r/webdev/comments/aq495t/prevent_heroku_from_deleting_my_sqlite_database/
> other people were having this issue with heroku and SQLite
> 
> heroku
> https://devcenter.heroku.com/articles/active-storage-on-heroku
> 
> i dont have a heroku test bed set up ...... yet
> to do testing on that platform

Yeah as I suspected it's heroku deleting the json.sqlite file
@razvandamian I can't prevent heroku from deleting the database file sadly, if you insist on using heroku you gotta find a workaround. Maybe heroku deletes files only if you're on the free tier?

**Comment by Natemo6348** [comment]
What I know so far is that when a Dyno is running, file changes made while it's running remain, but at least once a day they restart and use a clean copy of every file, so only what you have on, let's say Github, will be there after the restart

**Comment by Natemo6348** [comment]
> @Natemo6348 On heroku?

Also @galnir yes my issue is on Heroku too

**Comment by razvandamian** [comment]
i will probabily buy a host from digital ocean, couse its preety fast and they have that 100$ free for students, i don't know how to make that with heroku

**Comment by Natemo6348** [comment]
you could also host on glitch for free but your bot won't stay on 24/7, that's the main reason why I switched to heroku

**Comment by galnir** [comment]
I recommend the 5$ droplet on digital ocean
