### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined 

### ISSUE THREAD

**Issue by BlueMoon73** [galnir/Master-Bot#296]
Hi!, I've been trying to get this to work where the name of the channel the message is sent in is stored in "channel". That way I can use it for later references, also I am very new to Discord.js and JS in general so explanations of solutions would be appreciated.
This is my entire code, the switch statment at the bottom is minimized as I don't think it matters and it's very big but if you need it, let me know!

`var Discord = require('discord.io');
var logger = require('winston');
var auth = require('./auth.json');
// Configure logger settings
logger.remove(logger.transports.Console);
logger.add(new logger.transports.Console, {
    colorize: true
});

logger.level = 'debug';
// Initialize Discord Bot
var bot = new Discord.Client({
   token: auth.token,
   autorun: true
});
bot.on('ready', function (evt) {
    logger.info('Connected');
    logger.info('Logged in as: ');
    logger.info(bot.username + ' - (' + bot.id + ')');
});
bot.on('message', function (user, userID, channelID, message, evt) {
    // Our bot needs to know if it will execute a command
    // It will listen for messages that will start with `;`
    if (message.substring(0, 1) == ';') {
        var args = message.substring(1).split(' ');
        var cmd = args[0];
        args = args.splice(1);
		 let guildMember = message.member
		 let guild = message.guild
		let channel = message.member.channel
		 let member = message.member
		 bot.guildMember !== undefined
		let senderID = message.user.id
	switch(cmd) {
	}`

The error is:
let channel = message.member.channel
                                             ^

TypeError: Cannot read property 'channel' of undefined
    at DiscordClient.<anonymous> (C:\discordbots\testbot2\bot.js:32:32)
    at DiscordClient.emit (events.js:315:20)
    at DiscordClient.handleWSMessage (C:\discordbots\testbot2\node_modules\discord.io\lib\index.js:1854:11)
    at WebSocket.emit (events.js:315:20)
    at Receiver.ontext (C:\discordbots\testbot2\node_modules\ws\lib\WebSocket.js:841:10)
    at C:\discordbots\testbot2\node_modules\ws\lib\Receiver.js:536:18
    at Receiver.applyExtensions (C:\discordbots\testbot2\node_modules\ws\lib\Receiver.js:371:5)
    at C:\discordbots\testbot2\node_modules\ws\lib\Receiver.js:508:14
    at Receiver.flush (C:\discordbots\testbot2\node_modules\ws\lib\Receiver.js:347:3)
    at Receiver.finish (C:\discordbots\testbot2\node_modules\ws\lib\Receiver.js:541:12)

Also a similar error occurs with the let senderID = message.user.id if I comment out the let channel = message.member.channel.

The rest of the code (the switch statement) works as it's inteded if the 	 
                  let guildMember = message.member
		 let guild = message.guild
		let channel = message.member.channel
		 let member = message.member
		 bot.guildMember !== undefined
		let senderID = message.user.id is commented out. Thank you in advance!!

**Comment by galnir** [comment]
Hey, issues are for addressing bugs/problems with the bot. The code you provided here isn't from the repository and uses libraries I'm not familiar with. Nevertheless you're welcome to open issues related to the repository :)
