### ISSUE TITLE
cannot read property 

### ISSUE THREAD

**Issue by pranav2206** [galnir/Master-Bot#30]
PS C:\Users\Avyaan\Desktop\Discord Bot> node .
C:\Users\Avyaan\Desktop\Discord Bot\index.js:6
Structures.extend('Guild', Guild => {
           ^

TypeError: Cannot read property 'extend' of undefined
    at Object.<anonymous> (C:\Users\Avyaan\Desktop\Discord Bot\index.js:6:12)
?[90m    at Module._compile (internal/modules/cjs/loader.js:959:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:815:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:727:14)?[39m
?[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)?[39m
?[90m    at internal/main/run_main_module.js:17:11?[39m
PS C:\Users\Avyaan\Desktop\Discord Bot> npm view discord.js version
11.5.1
PS C:\Users\Avyaan\Desktop\Discord Bot> npm view discord.js-commando version
0.10.0
PS C:\Users\Avyaan\Desktop\Discord Bot>

**Comment by galnir** [comment]
2 options:
1. You didn't install discord.js master
2. You didn't import Structures

**Comment by pranav2206** [comment]
Structures.extend('Guild', Guild => {
           ^

TypeError: Cannot read property 'extend' of undefined
    at Object.<anonymous> (C:\Users\Avyaan\Desktop\PerL Bot\index.js:6:12)
?[90m    at Module._compile (internal/modules/cjs/loader.js:959:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:815:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:727:14)?[39m
?[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)?[39m
?[90m    at internal/main/run_main_module.js:17:11?[39m
PS C:\Users\Avyaan\Desktop\PerL Bot>

**Comment by pranav2206** [comment]
i install all pkg 
can make video on it on youtube

**Comment by pranav2206** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/60147938/72998834-7a4f8d00-3e24-11ea-9501-23a9b3af5b92.png)
![Screenshot (6)](https://user-images.githubusercontent.com/60147938/72998835-7ae82380-3e24-11ea-9529-1c27a52f4077.png)

**Comment by pranav2206** [comment]
![Capture](https://user-images.githubusercontent.com/60147938/73014693-a2e58000-3e40-11ea-84e8-790852d8d6e0.JPG)

**Comment by galnir** [comment]
This only happens when you are not on master.
If your package.json is the same as the repo's, just do ```npm i``` (check if you have Git before, you need).
If not just install discord.js *master* : ```npm install discordjs/discord.js```

**Comment by galnir** [comment]
@pranav2206 Closing the issue, will reopen if the solutions above dont work for you
