### ISSUE TITLE
Process exited with code 1 Uncaught Error: Cannot find module 'discord.js' Require stack

### ISSUE THREAD

**Issue by HyperSpySG** [galnir/Master-Bot#300]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
when i try to run the code it says Process exited with code 1
Uncaught Error: Cannot find module 'discord.js'
Require stack:
- c:\Users\Admin\node_modules\discord.js-commando\src\index.js
- c:\Users\Admin\Downloads\Master-Bot-master (1)\Master-Bot-master\index.js

**To Reproduce**
1. Use 'x' command
2. provide 'y' argument

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...]
 - Node Version(Should be v12 atleast): 
 - Are python 2.7 and Ffmpeg installed?:
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...):

**Additional context**

**Comment by Natemo6348** [comment]
run `npm i` in the console

**Comment by galnir** [comment]
Open an issue after following the instructions. One of the first things in to run ```npm i``` ...

**Comment by HyperSpySG** [comment]
i did do npm i but the same error keeps happening

**Comment by Natemo6348** [comment]
do `npm i` again and screenshot what shows up in the console

**Comment by HyperSpySG** [comment]
![Screenshot 2020-11-18 140745](https://user-images.githubusercontent.com/74608654/99576208-ae91cc80-29a7-11eb-831b-17743ffbeba1.png)

**Comment by Natemo6348** [comment]
is discord.js listed in dependencies in package.json?

**Comment by HyperSpySG** [comment]
it says 
![Screenshot 2020-11-18 143539](https://user-images.githubusercontent.com/74608654/99578810-5bba1400-29ab-11eb-842d-38bb6bbae064.png)

**Comment by Natemo6348** [comment]
ok could you copy and paste the output from `npm i`

**Comment by HyperSpySG** [comment]
i copied and pasted the output but when i run the code it only runs for one second and then stops

**Comment by Natemo6348** [comment]
i meant copy and paste it here

**Comment by Natemo6348** [comment]
so i can see the entire error

**Comment by HyperSpySG** [comment]
oh ok here: 

PS C:\Users\Admin\Downloads\Master-Bot-master (1)> npm i
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Admin\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Admin\package.json'
npm WARN discord.js-commando@0.10.0 requires a peer of discord.js@^11.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js-commando@0.10.0 requires a peer of sqlite@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN Admin No description
npm WARN Admin No repository field.
npm WARN Admin No README data
npm WARN Admin No license field.

audited 6 packages in 0.331s
found 0 vulnerabilities

**Comment by Natemo6348** [comment]
@galnir i'm at a loss here, think you can help figure it out? they did do `npm i` but it looks like it's looking for package.json in the wrong place

**Comment by galnir** [comment]
I think you have a duplicate there because of the (1). Maybe you're installing the dependencies in the wrong place? Try deleting the folders and cloning the repo again without duplicates

**Comment by Bacon-Fixation** [comment]
yeah im with GalNir i ran into issues with appended folders with Vscode and the old Powershell  i remove the Spaces and use `_` underscore or update Powershell for Vscode

**Comment by HyperSpySG** [comment]
ok so i deleted all the folders a had and then cloned the repo again but i still have the same issue

**Comment by galnir** [comment]
> ok so i deleted all the folders a had and then cloned the repo again but i still have the same issue

You're doing something wrong. All you need to do is clone and run ```npm i``` (assuming you also installed python 2.7 and ffmpeg)

**Comment by HyperSpySG** [comment]
yeah i have ffmpeg and python 2.7 but when i run npm i it does:
PS C:\Users\Admin\Downloads\Master-Bot-master> node i
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Users\Admin\Downloads\Master-Bot-master\i'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
PS C:\Users\Admin\Downloads\Master-Bot-master>

**Comment by Bacon-Fixation** [comment]
Use `npm i` instead of `node i` to install

**Comment by Natemo6348** [comment]
yes use `npm i` instead of `node i`

**Comment by HyperSpySG** [comment]
oh sorry ok i did npm i:
PS C:\Users\Admin\Downloads\Master-Bot-master> npm i
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Admin\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Admin\package.json'
npm WARN discord.js-commando@0.10.0 requires a peer of discord.js@^11.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js-commando@0.10.0 requires a peer of sqlite@^2.0.0 but none is installed. You must install 
peer dependencies yourself.
npm WARN Admin No description
npm WARN Admin No repository field.
npm WARN Admin No README data
npm WARN Admin No license field.

audited 6 packages in 0.664s
found 0 vulnerabilities

PS C:\Users\Admin\Downloads\Master-Bot-master>

**Comment by Natemo6348** [comment]
check for a package.json at C:\Users\Admin and if there is one there, delete it and run `npm i` again

**Comment by Bacon-Fixation** [comment]
you can also try to not have the bot in the downloads folder try cloning to C:/Bot/ something that is not in users folder

i have run into issues with Vscode and the users folder

**Comment by Natemo6348** [comment]
yeah, i always ended up putting it on my desktop

**Comment by Bacon-Fixation** [comment]
Yo heads up if you copy and paste the failed clone to a different folder and try to rerun `npm i` it will install to the old directory 
found this just now during testing 

Clone it fresh and open that fresh clone and run your `npm i` and the `node .` after

**Comment by HyperSpySG** [comment]
ok so i checked for a package.json at C:\Users\Admin and deleted it then a copy and pasted the master bot in desktop and ran npm i but i still has the same issue: PS C:\Users\Admin\Desktop\Master-Bot-master> npm i
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Admin\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Admin\package.json'
npm WARN discord.js-commando@0.10.0 requires a peer of discord.js@^11.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js-commando@0.10.0 requires a peer of sqlite@^2.0.0 but none is installed. You must install 
peer dependencies yourself.
npm WARN Admin No description
npm WARN Admin No repository field.
npm WARN Admin No README data
npm WARN Admin No license field.

audited 6 packages in 0.425s
found 0 vulnerabilities

**Comment by Natemo6348** [comment]
> Yo heads up if you copy and paste the failed clone to a different folder and try to rerun `npm i` it will install to the old directory and fail to find Dir.
> found this just now during testing
> the install and check path of the npm command transferred over on VScode
> 
> Clone it fresh to a different folder (preferably not in the Downloads folder) and open that fresh clone and run your `npm i`
> its ok to copy your config.json over

**Comment by galnir** [comment]
Clone the repository to desktoo
