### ISSUE TITLE
Welcome message

### ISSUE THREAD

**Issue by koushikpuppala5** [galnir/Master-Bot#301]
How can I stop welcome message and sending errors to dm of a member

**Comment by Bacon-Fixation** [comment]
is the Error to the user on in default channel  or console ?

**Comment by koushikpuppala5** [comment]
Channel

**Comment by koushikpuppala5** [comment]
Means sending need permission for kick in dms

**Comment by koushikpuppala5** [comment]
And want to stop welcome message

**Comment by Bacon-Fixation** [comment]
I on it now My friend

**Comment by koushikpuppala5** [comment]
What

**Comment by koushikpuppala5** [comment]
Lyrics commad is also not working

**Comment by Natemo6348** [comment]
what error do you get when using the lyrics command?

**Comment by Bacon-Fixation** [comment]
im really confused is this an Error or a request ?

**Comment by koushikpuppala5** [comment]
![Screenshot_2020-11-19-01-02-11-14](https://user-images.githubusercontent.com/70138027/99578547-fdb91b00-2a02-11eb-939e-21ea6fe400f3.jpg)

**Comment by Natemo6348** [comment]
ok @koushikpuppala5 open new issue for lyrics command to keep from causing more confusion

**Comment by koushikpuppala5** [comment]
> How can I stop welcome message and sending errors to dm of a member

Answer to this please

**Comment by Natemo6348** [comment]
is welcome message sending an error? if so, what is it?

**Comment by koushikpuppala5** [comment]
Not error I don't want to send that msg

**Comment by koushikpuppala5** [comment]
Only. Music is main

**Comment by Natemo6348** [comment]
@Bacon-Fixation 

> Not error I don't want to send that msg

they don't want it to send a welcome message

**Comment by koushikpuppala5** [comment]
Yes they have kicked bot for that reason

**Comment by Bacon-Fixation** [comment]
kk

**Comment by Natemo6348** [comment]
i have recently changed the welcome message code to send in a channel named `welcome`, so would that be a good solution for you @koushikpuppala5 ?

**Comment by Bacon-Fixation** [comment]
Heyo back here with a Pull Request #303 So the server admin has a choice of having the message

**Comment by galnir** [comment]
Addressed in #303
