### ISSUE TITLE
Lyrics commad

### ISSUE THREAD

**Issue by koushikpuppala5** [galnir/Master-Bot#302]
![Screenshot_2020-11-19-01-02-11-14](https://user-images.githubusercontent.com/70138027/99578966-93ed4100-2a03-11eb-9125-4510976b7c9f.jpg)

**Comment by Natemo6348** [comment]
ok so this looks like an error originating from the welcome message code in index.js, so I would think that if that was fixed then you should be able to run the lyrics command, bur don't hold me to it lol

**Comment by Bacon-Fixation** [comment]
i can't Replicate this error with the Lyrics command may i ask if there was a discord message with it

i've seen this error when canvas is missing

**Comment by Bacon-Fixation** [comment]
Just wondering if this error is still occurring or if there was any additional info of the conditions that triggered this error?

Mush Love
-Bacon

**Comment by koushikpuppala5** [comment]
There is still error

**Comment by Bacon-Fixation** [comment]
Is this a Windows or a Linux system that you are running?
Can you trigger this error with the `!lyrics` command?

**Comment by koushikpuppala5** [comment]
Windows 10

**Comment by Natemo6348** [comment]
> Can you trigger this error with the `!lyrics` command?

> Does this Error happen when a new member joins a server?

**Comment by koushikpuppala5** [comment]
It is not welcome error

**Comment by Natemo6348** [comment]
> Can you trigger this error with the `!lyrics` command?

**Comment by galnir** [comment]
@koushikpuppala5  The lyrics command doesn't use Canvas. What steps can I take to replicate this? Without info there's not much I can do to debug...

**Comment by galnir** [comment]
If you're still getting this open a new issue and fill the template
