### ISSUE TITLE
Embed Help Command

### ISSUE THREAD

**Issue by icsmac** [galnir/Master-Bot#31]
Hi, can you help me to make help command that send embed in channel and not dm the user. 

Thats it only...

**Comment by galnir** [comment]
All you need to do is disable the help command and then write a new help command, it's not complicated...
Read discord.js docs

**Comment by icsmac** [comment]
How do i disable it?

**Comment by icsmac** [comment]
When i use help commands this is what shows..

@SoapFromYT, An error occurred while running the command: TypeError: RichEmbed is not a constructor
You shouldn't ever receive an error like this.
Please contact hyperzone#1185.

**Comment by galnir** [comment]
@icsmac I'm not getting this error on my side, have you installed discordjs master and commando correctly?

**Comment by icsmac** [comment]
Yes

**Comment by icsmac** [comment]
And bot disconnected after playing the song
how to fix it?

**Comment by galnir** [comment]
The bot intentionally disconnects after a song is played(assumed there are no songs left in the queue)
