### ISSUE TITLE
Lyrics command not working

### ISSUE THREAD

**Issue by mkgaming54** [galnir/Master-Bot#310]
Why the lyrics command is not working? It is showing this for every song. PLS HELP
![72780C24-5766-4E0E-817E-CD3E4A9D452E_4_5005_c](https://user-images.githubusercontent.com/68937935/99669844-ae6ffa80-2a95-11eb-8e64-ea4040531952.jpeg)

**Comment by Bacon-Fixation** [comment]
Make sure your Genius Lyrics API key is entered correctly. Double-check you have the Key entered correctly inside your config.json
file

Genius Lyrics Key https://genius.com/api-clients/ selected your App and grab the key
if there isn't one create one here https://genius.com/api-clients/new

Much Love
-Bacon

**Comment by galnir** [comment]
Basically what @Bacon-Fixation suggested, make sure you entered a correct API key

**Comment by Bacon-Fixation** [comment]
@mkgaming54 Just wanted to know if your issue was resolved or if you still had issues

Much Love
-Bacon

**Comment by mkgaming54** [comment]
I still have the issue and my genius lyrics api is entered correctly in config.json.

**Comment by Bacon-Fixation** [comment]
I can't replicate these symptoms with a Valid Key 

Make sure you are clicking on the Generate Access Token and using the  key that pops up and not the Client Secret 
![image](https://user-images.githubusercontent.com/12632936/99865115-42f95c00-2b6d-11eb-9cbb-592896eb40fb.png)

**Comment by mkgaming54** [comment]
Oh ok

**Comment by mkgaming54** [comment]
Btw I use heroku

**Comment by mkgaming54** [comment]
@Bacon-Fixation @galnir Thanks, I made a mistake I copied the Client Secret instead of clicking Client access token. Sorry my bad lol. Lyrics command is now working :D

**Comment by Bacon-Fixation** [comment]
I know this issue is close but I noticed songs like Eminem's - Stan was hitting a limit i to really enjoy Eminem, Bust Rhymes, and Lil Dicky. So I went working to remove this restriction in this PR #315

**Comment by mkgaming54** [comment]
@Bacon-Fixation yeah <3 Eminem

**Comment by mkgaming54** [comment]
> I know this issue is close but I noticed songs like Eminem's - Stan was hitting a limit. I to really enjoy Eminem, Bust Rhymes, and Lil Dicky. So I went working to remove this restriction in this PR #315

so how do I get the new lyrics.js?

**Comment by Bacon-Fixation** [comment]
https://github.com/Bacon-Fixation/Beta-test-file

**Comment by Bacon-Fixation** [comment]
@mkgaming54 Heads up the Lyrics Update was Added to this Repo so you can just clone Normally from galner/Master-Bot
