### ISSUE TITLE
quick.db cannot find bindings file

### ISSUE THREAD

**Issue by Natemo6348** [galnir/Master-Bot#314]
/home/runner/Botemo/node_modules/quick.db/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/build/better_sqlite3.node
 → /home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/build/Debug/better_sqlite3.node
 → /home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/build/Release/better_sqlite3.node
 → /home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/out/Debug/better_sqlite3.node
 → /home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/Debug/better_sqlite3.node
 → /home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/out/Release/better_sqlite3.node
 → /home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/Release/better_sqlite3.node
 → /home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/build/default/better_sqlite3.node
 → /home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/compiled/12.18.3/linux/x64/better_sqlite3.node
 → /home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node
 → /home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node
 → /home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node
 → /home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/lib/binding/node-v72-linux-x64/better_sqlite3.node
    at bindings (/home/runner/Botemo/node_modules/quick.db/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/lib/database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/lib/index.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:1137:30) {
  tries: [
    '/home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/build/better_sqlite3.node',
    '/home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/build/Debug/better_sqlite3.node',
    '/home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/build/Release/better_sqlite3.node',
    '/home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/out/Debug/better_sqlite3.node',
    '/home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/Debug/better_sqlite3.node',
    '/home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/out/Release/better_sqlite3.node',
    '/home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/Release/better_sqlite3.node',
    '/home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/build/default/better_sqlite3.node',
    '/home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/compiled/12.18.3/linux/x64/better_sqlite3.node',
    '/home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/addon-build/release/install-root/better_sqlite3.node',
    '/home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/addon-build/debug/install-root/better_sqlite3.node',
    '/home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/addon-build/default/install-root/better_sqlite3.node',
    '/home/runner/Botemo/node_modules/quick.db/node_modules/better-sqlite3/lib/binding/node-v72-linux-x64/better_sqlite3.node'
  ]
}
exit status 1

I have no idea what's causing this or how to fix it, as I haven't really worked with things like quick.db
Trying to host on repl.it so I can save to json.sqlite
This is preventing me from running my bot on repl.it

**Comment by Bacon-Fixation** [comment]
Setting up a repl.it Test bed now will give you a heads up after testing 

Much Love
-Bacon

**Comment by Natemo6348** [comment]
ok, i will wait for a testing response

**Comment by Bacon-Fixation** [comment]
`yarn global add windows-build-tools` then retry `npm i`

**Comment by Bacon-Fixation** [comment]
just noticed that its not creating the node_modules folder when i come back to the website

**Comment by Natemo6348** [comment]
ran `yarn global add windows-build-tools` and here's the output: 
error windows-build-tools@5.2.2: The platform "linux" is incompatible with this module.
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

**Comment by Natemo6348** [comment]
not entire output but probably the main part that matters

**Comment by Bacon-Fixation** [comment]
yeah my error was different 

Error: The module '/home/runner/Master-Bot/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1187:18)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/home/runner/Master-Bot/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/home/runner/Master-Bot/node_modules/better-sqlite3/lib/database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)

**Comment by Natemo6348** [comment]
oh yours has better-sqlite3 installed? mine keeps trying to install it and failing

**Comment by Bacon-Fixation** [comment]
yeah
it was able to install only after the  `yarn global add windows-build-tools`

**Comment by Natemo6348** [comment]
guess i cant install it since windows build tools is "incompatible"
also I'm trying to run npm rebuild to maybe see if it fixes it

**Comment by Bacon-Fixation** [comment]
run `npm i quick-db`

**Comment by Bacon-Fixation** [comment]
im trying `npm i build-tools` since a few of my errors are compiler missing errors

**Comment by Bacon-Fixation** [comment]
Is your nod_modules folder Visible on the left side with your folders and file list?
Mine isn't there even after a npm i and it has me concerned

**Comment by Natemo6348** [comment]
my node_modules folder isn't visible

**Comment by Natemo6348** [comment]
i think the node modules are just listed in packages on the left side, just click the packages button

**Comment by Bacon-Fixation** [comment]
hmmmmmmm i wonder if its not allowing it because its not in the Github Repo. i noticed it redownloads mine every time I load my project in rapl.it and have to reinstall

**Comment by Bacon-Fixation** [comment]
You're right they are in the packages tab TY i was freaking out man

**Comment by Bacon-Fixation** [comment]
no luck here my friend i can replicate this error on my Raspberry PI but i have access to the sudo and apt-get command to install what i need like `sudo apt-get install build-essentials` and i dont have that permission with repl.it

this error is with repl.it current versions of things, like I can find a lot of repos with quick.db and better-sqlite3 on repl.it
that worked previous but the better-sqlite3 can't install with repl.it's current setup

**Comment by Natemo6348** [comment]
oh ok, i guess i'll have to find another hosting option, thanks anyway

**Comment by Natemo6348** [comment]
@Bacon-Fixation do you happen to know any hosting sites I can use, at least until I have a local hosting option

**Comment by Natemo6348** [comment]
tried to go back to glitch, exact same error, guess I can't use databases until I can host locally.

**Comment by Bacon-Fixation** [comment]
@Natemo6348  i had this error testing on glitch BUT I was successful in a workaround I'm will try it on repl.it as well after the is 
i added 
```
  "engines": {
    "node": "15.x",
    "python": "2.7",
    "node-gyp": "6.x"
  },
```

to my package.json file 

like so
![image](https://user-images.githubusercontent.com/12632936/99895564-84ae0380-2c4e-11eb-9039-5b36b2e8269f.png)

![image](https://user-images.githubusercontent.com/12632936/99895555-56c8bf00-2c4e-11eb-8376-adde2aa4d53a.png)

Let me know if this helped you 

Much Love
-Bacon

**Comment by Natemo6348** [comment]
Ok i just added it and will seeif it works

**Comment by Bacon-Fixation** [comment]
LOL it auto starts on Glitch Log in the logs i ran the `node .` and was really confused when i had 2 responses

**Comment by Natemo6348** [comment]
didn't work sadly, also lol i've had that happen before

**Comment by Bacon-Fixation** [comment]
is this a fresh clone or a copy over ?

**Comment by Natemo6348** [comment]
it was once a fresh clone, but I have added my own code, never changed the existing code

**Comment by Bacon-Fixation** [comment]
kk i will retrace my steps and see if i missed a step

**Comment by Bacon-Fixation** [comment]
yoooooooooooooo 

i started a new project  cloned the galnir/Master-Bot repo and opened tools / logs and waited to see the missing config.json file and draged my Setup config and it just started no npm or anything
![image](https://user-images.githubusercontent.com/12632936/99896172-9cd45180-2c53-11eb-9a02-0052aaa989a0.png)

**Comment by Natemo6348** [comment]
lol nice, also i'm trying with a fresh clone in repl.it to see if your fix works without my extra code additions

**Comment by Bacon-Fixation** [comment]
nah repl.it didnt work for me

**Comment by Natemo6348** [comment]
ah ok, guess i'll use glitch then

**Comment by Bacon-Fixation** [comment]
im still looking into it now that i have new data to work with

**Comment by Natemo6348** [comment]
i just made a fresh clone on glitch and i didn't get the error so idk what the issue is with mine, because I got the error with mine

**Comment by Natemo6348** [comment]
@Bacon-Fixation fixed the error with mine on glitch after running `npm rebuild better-sqlite3`

**Comment by Bacon-Fixation** [comment]
Thank you again for the Data <3
I will add that to my notes for Glitch fixes for this issue
I'm still occasionally poking at repl.it.
The one thing that keeps me from repl.it is free version is Public Only and I only put a throwaway token/key config in there during testing then remove it when I'm done

**Comment by Natemo6348** [comment]
Ah, I should probably remove my token then since I'm just leaving it set there for people to steal

**Comment by galnir** [comment]
@Natemo6348 Did @Bacon-Fixation solve your problem? 
Hosting on sites such as Glitch can be a pain as I see from this and previous issues

**Comment by Natemo6348** [comment]
@galnir my issue still persists, but I will close this since it seems the only way to fix this is to contact repl.it support

**Comment by Natemo6348** [comment]
@galnir @Bacon-Fixation just as I went to contact support the dependency installed so my issue has been fixed lol

**Comment by Bacon-Fixation** [comment]
Nice
