### ISSUE TITLE
 I have no permission to join your channel!

### ISSUE THREAD

**Issue by Trentyn** [galnir/Master-Bot#317]
I have no permission to join your channel!

**Comment by Bacon-Fixation** [comment]
make sure you setup your permissions correct when creating your Discord App 
- **Demonstration Only** (just a visual aid) 
![permissions](https://user-images.githubusercontent.com/12632936/97736210-5737c500-1aa9-11eb-8036-6032de4d6798.PNG)

Screenshot is from https://discordpy.readthedocs.io/en/latest/discord.html

try with 
- Send Message
- Embed Links 
- View Channels
- Connect
- Speak
- Manage Messages

 ***Optional**

- Kick Members
- Ban Members

you can always kick your bot and re-invite him with new permissions 

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
If it is a private channel
Add your bot to a role that can see it like Role Admin

**Comment by Natemo6348** [comment]
@FreshSoul if this doesn't help you, check in the console for any specific errors and send them here

**Comment by ELECTROISLIVE** [comment]
same issue with me also

**Comment by ELECTROISLIVE** [comment]
bot had admin perm when i invited it

**Comment by ELECTROISLIVE** [comment]
@Bacon-Fixation please tell how to fix it

**Comment by Natemo6348** [comment]
@ELECTROISLIVE read this and #276

**Comment by galnir** [comment]
This error can show up if you didn't install ffmpeg and python 2.7

**Comment by Bacon-Fixation** [comment]
Just wanted to Touch Back to see if this Issue was resolved

Much Love
-Bacon

**Comment by Natemo6348** [comment]
Weird, I suddenly started getting this issue too with no error log, but it's repl.it so I can't say I'm surprised

**Comment by Natemo6348** [comment]
Ok if anyone is using repl.it you cannot install ffmpeg because they removed it completely

**Comment by galnir** [comment]
@Trentyn If this bug persists open a new issue and fill the template

**Comment by Natemo6348** [comment]
I would like to add that if you do `npm i ffmpeg-static`, even on repl.it, it will work
