### ISSUE TITLE
Join command issue

### ISSUE THREAD

**Issue by Natemo6348** [galnir/Master-Bot#319]
@Bacon-Fixation when I ran the join command to test the welcome message I got this error: Fontconfig error: Cannot load default config file
And this happens:
![Screenshot_20201123-013300_Discord](https://user-images.githubusercontent.com/64607128/99937680-e7c19800-2d2b-11eb-8e71-b7de5210717b.jpg)

**Comment by Bacon-Fixation** [comment]
the font file is missing .... is this Glitch?

**Comment by Natemo6348** [comment]
Repl.it

**Comment by Bacon-Fixation** [comment]
LOL of course

**Comment by Bacon-Fixation** [comment]
it use the default font that should have been cross-platform sans-serif

**Comment by Bacon-Fixation** [comment]
in the index.js search for 
```
ctx.font = `${(fontSize -= 10)}px sans-serif`;
```
 and try 
```
ctx.font = `${(fontSize -= 10)}px Arial`;
```

**Comment by Natemo6348** [comment]
I changed it and I messed up somewhere and it tried to reinstall dependencies, now I have to deal with better-sqlite3 again

**Comment by Natemo6348** [comment]
Now it's canvas failing to install, repl.it really doesn't like npm

**Comment by Natemo6348** [comment]
And now back to better-sqlite3

**Comment by Bacon-Fixation** [comment]
did `npm rebuild better-sqlite3` work again for you ?

**Comment by Natemo6348** [comment]
@Bacon-Fixation rebuild worked again, but I'm still getting the same error for font

**Comment by Bacon-Fixation** [comment]
I will have more time tomorrow to look into this I will keep you posted I have some ideas i want to try like doing a font and altering the canvas section to reference that file rather than the systems library

**Comment by Natemo6348** [comment]
Ok I will be waiting for your results, it's 3am here

**Comment by galnir** [comment]
If you're getting errors when installing the dependencies try adding these flags:
```npm i --unsafe-perm=true --allow-root```

**Comment by Bacon-Fixation** [comment]
@Natemo6348 try Draft #323 and let me know it worked ok for me but i want to see if it worked for you as well
added 2 Open fonts that have a License to USE but not to Sell 
just for Repl.it

**Comment by Natemo6348** [comment]
@Bacon-Fixation it works, thanks

**Comment by Bacon-Fixation** [comment]
I apologize that I never thought of checking if VPS's have access to a System Library's like Fonts moving Forward I will Also Test at Least on Glitch and repl.it if the Feature uses something like that again 

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
@Natemo6348 If you want to add your own Font I made a quick How To on Adding Custom Fonts to Canvas [Here](https://github.com/Bacon-Fixation/Master-Bot/wiki/Customizing-The-Welcome-Image#addingchanging-fonts)

Much Love
-Bacon
