### ISSUE TITLE
How do I translate everything?

### ISSUE THREAD

**Issue by chimaerra** [galnir/Master-Bot#32]
Hello there. I don't really like opening "issues" for just questions but since it's almost the only way to discuss, here I am. 
First of all, your bot is awesome with all these features and stuff(translate option and news especially), so thank you very much for that. Would be happy to donate you some amount of money but I don't have much.
So basically how do I translate the bot completely? As I understand, I need to translate ./commands and discord.js-commando. Is there anything more I need to know? Thanks.

**Comment by chimaerra** [comment]
Oh, and I forgot. 
Would be good to add a feature to store volume amount based on the... guild id? I guess?
Thing is, every time the music skips/changes to other track, volume resets. Not good.

**Comment by galnir** [comment]
About translating commands, just translate each one in the commands folder and take a look at #28, I explained how to translate the built-in Commando commands there.
About the volume, I'll fix it in the weekend.
I don't intend to open up a donation page, just drop a star if you like the bot :)

**Comment by galnir** [comment]
Fixed volume issue in commit 5b178d44ecfd77456fd9027a747d0dccd2378e43
