### ISSUE TITLE
playlist

### ISSUE THREAD

**Issue by zero59344** [galnir/Master-Bot#322]
How can I play a song from a playlist that I created in my name?

**Comment by galnir** [comment]
A playlist you created using the !create-playlist command? If yes you can only play the entire playlist right now

**Comment by zero59344** [comment]
> A playlist you created using the !create-playlist command? If yes you can only play the entire playlist right now

Yes, I created a playlist with the command I mentioned and added a song, and the bot did not work.

**Comment by zero59344** [comment]
> A playlist you created using the !create-playlist command? If yes you can only play the entire playlist right now

I want to play the song that I added in my playlist.

**Comment by galnir** [comment]
!play playlistname
doesnt work?

**Comment by zero59344** [comment]
> !play playlistname
> doesnt work? A menu should pop up and ask you if you want to play the playlist or query the name on youtube

Thank you .. I suggest you have a command to allow a person or rank to use the bot .

**Comment by galnir** [comment]
not really on my feature list but noted
