### ISSUE TITLE
Problem playing playlists

### ISSUE THREAD

**Issue by wukongg** [galnir/Master-Bot#33]
It does not play any playlist. Only 1 first song.

**Comment by galnir** [comment]
You need to elaborate... Do you get any errors? Did you install everything listed?

**Comment by wukongg** [comment]
Hi, thanks for the reply.
Here the print: https://prnt.sc/r2z1on
I don't get any errors.
I play a playlist, but it identifies only 1 song, plays it and leaves.

**Comment by galnir** [comment]
Can you share the playlist link?

**Comment by wukongg** [comment]
https://www.youtube.com/watch?v=dlO8aANekSM&list=PL7zsB-C3aNu03RwSy2Bn3Ov3oaEReOlT5&index=29

**Comment by galnir** [comment]
It's because it's not a playlist link

**Comment by wukongg** [comment]
Wow, I got it. Excuse me and thank you. It's working perfectly.
