### ISSUE TITLE
please change the system to Lavalink 

### ISSUE THREAD

**Issue by mina9999** [galnir/Master-Bot#333]
hi good job and your bot is great but the problem is youtube api only have 10.000 quatos per day and it finish really soon when people play so many songs per day and also when your bot is in so many servers u will get youtube rate limit too . you cant get banned with Lavalink  bc it have ip rotation and it dont use youtube api and its so amazing.

**Comment by Bacon-Fixation** [comment]
I would suggest if you were exceeding the 10,000 daily API limits, try separating your Guilds onto different keys(spread the load)
Personally I don't think purposely evading a Ban is a good reason to switch to Lavalink
that's just me

Much Love
-Bacon

**Comment by galnir** [comment]
I will look into implementing Lavalink, but until then you can apply for a bigger quota via your YouTube dev console

**Comment by Bacon-Fixation** [comment]
^^^^^ Much simpler solution, Deleted my comment (was only really suitable for torture testing commands)

I apologize for any confusion
Much love 
-Bacon

**Comment by mina9999** [comment]
Lavalink server is so good my bot is in 2000 servers and im using Lavalink server for bot music bot.

**Comment by galnir** [comment]
I've looked into it. Lavalink is indeed better but isn't better at all for a self-host bot. It took me time to get my Java version right, and it may take even more time for users who have no background in using Java.
The setup will get harder as a result of that, so if you have an idea on how to make integrating Lavalink easier I'd love to hear

**Comment by NikosProGamer** [comment]
check out lavacord

**Comment by galnir** [comment]
I'm closing this issue since Lavalink got off my todo list for now
