### ISSUE TITLE
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch

### ISSUE THREAD

**Issue by Princevikas** [galnir/Master-Bot#337]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**getting error r10 on heroku**
Web process failed to bind to $PORT within 60 seconds of launch 

**To reproduce the bug host the bot on heroku **
1. use any command
2. the bot goes offline after some time

**Expected behavior**
expected to be running normally , after starting the bot

**Screenshots**
screenshot added below

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...](dynos linux)
 - Node Version(Should be v12 atleast): ( connected and deployed the bot through github heroku)
 - Are python 2.7 and Ffmpeg installed?:( tried to install python build pack manuallly but , build is failing)
 - How are you hosting the bot( heroku, ):

**Additional context**

getting this error on heroku hosting after few minutes everytime how to fix
![image](https://user-images.githubusercontent.com/58914249/100742558-f9c4ca00-3400-11eb-871a-8aba57186be0.png)

**Comment by galnir** [comment]
Can you fill the issue template? You deleted it when posting this issue

**Comment by Princevikas** [comment]
ok sorry

**Comment by Princevikas** [comment]
> 
> 
> Can you fill the issue template? You deleted it when posting this issue

i did brother please check it out also sorry for previous inconvenience

**Comment by galnir** [comment]
A quick Google search yielded [this](https://stackoverflow.com/questions/15693192/heroku-node-js-error-web-process-failed-to-bind-to-port-within-60-seconds-of). Btw the music commands will not work without having Python 2.7 installed

**Comment by Princevikas** [comment]
> A quick Google search yielded [this](https://stackoverflow.com/questions/15693192/heroku-node-js-error-web-process-failed-to-bind-to-port-within-60-seconds-of). Btw the music commands will not work without having Python 2.7 installed

already saw that but couldn't understood , nvm will try something on my own

**Comment by Natemo6348** [comment]
@Princevikas you have to change the Dyno it runs on

**Comment by Princevikas** [comment]
> @Princevikas you have to change the Dyno it runs on

can you elaborate a little brother

**Comment by Natemo6348** [comment]
First, make a file called `Procfile`, and in that file type `worker: node index.js`. Then you go into the Resources tab on Heroku and turn off the web Dyno and turn on the worker Dyno

**Comment by Princevikas** [comment]
> First, make a file called `Procfile`, and in that file type `worker: node index.js`. Then you go into the Resources tab on Heroku and turn off the web Dyno and turn on the worker Dyno

oh i already did that ,

**Comment by Princevikas** [comment]
i wanted to know that how should i add python in heroku , cause when i tried buildpack it doesn't worked

**Comment by Natemo6348** [comment]
Try adding
  "engines": {
    "python": ">=3"
  }
to the end of the package.json just before the last `}`

**Comment by Princevikas** [comment]
> 
> 
> Try adding
> "engines": {
> "python": ">=3"
> }
> to the end of the package.json just before the last `}`

 App not compatible with buildpack: https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/python.tgz

       More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure

 !     Push failed 


getting this error

**Comment by Natemo6348** [comment]
did you disable the python buildpack?

**Comment by Princevikas** [comment]
> 
> 
> did you disable the python buildpack?

yes i can post errror logs too
[error logs.txt](https://github.com/galnir/Master-Bot/files/5633883/error.logs.txt)

**Comment by Natemo6348** [comment]
All I can find for your issue is [this](https://help.heroku.com/7CW5LBC5/why-am-i-getting-error-waiting-for-network-resource-temporarily-unavailable-errors), and after looking at your error logs, it looks like the web Dyno is still trying to run, which could be causing this

**Comment by Bacon-Fixation** [comment]
@Princevikas Try running `$ heroku scale web=0 worker=1` in the Heroku Terminal then try to run the bot

**Comment by Princevikas** [comment]
> 
> 
> Edit: I misspelled the command
> 
> @Princevikas Try running `$ heroku ps:scale web=0` or `heroku ps:scale web=0` in the Heroku Terminal then try to run the bot
> 
> I don't think there should be a web scaler in your logs
> 
> if there is no response from the web scaler then the bot will shut down after 1 minute
> 
> in your log `heroku/web.1: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch `
> it should say Worker and not web, there isn't a port defined inside Master-Bot for a [Web scaler](https://devcenter.heroku.com/articles/scaling#manual-scaling) to bind to and will cause this error
> 
> I apologize for the delay took me a little while to recreate this error
> 
> Much Love
> -Bacon



in response your  [https://github.com/galnir/Master-Bot/pull/342#issuecomment-738190633](question here) 

the bot is a download of master bot , i downloaded and created a repository in github 

then deployed using connecting heroku with github  
[build log.txt](https://github.com/galnir/Master-Bot/files/5641038/build.log.txt) here are the build logs , it is a new bot for me, it even worked for a minute then it crashed 

sorry idk much about java 
 maybe python dependency not  installed or something , i even added the line in package.json file but its just says package-lock.json out of sync 

any help is appreciated 
- vikas

**Comment by Princevikas** [comment]
can you create a separate branch  to connect into heroku it will be a great help @Bacon-Fixation

**Comment by Princevikas** [comment]
@Bacon-Fixation i deleted the old repo cloned new one and scaled the web to 0 now working file thanks for the support

**Comment by Bacon-Fixation** [comment]
Np @Princevikas, happy to help if I can. enjoy my friend 

Much Love 
-Bacon

**Comment by Princevikas** [comment]
> Np @Princevikas, happy to help if I can. enjoy my friend 
> 
> Much Love 
> -Bacon

sure I'll let you know if anything comes up

**Comment by Princevikas** [comment]
@Bacon-Fixation uh something came up again when i cloned your code to to host another bot on heroku , i didnt modified anything 
just added config json file and tokens and procfile too , and its giving me these errors
[buglog.txt](https://github.com/galnir/Master-Bot/files/5899938/buglog.txt)

and this is my build log
[buildlog.txt](https://github.com/galnir/Master-Bot/files/5899942/buildlog.txt)

**Comment by Bacon-Fixation** [comment]
run `npm install` looks like you are missing a module called `is-promised` which is part of `discordjs-Commando `

**Comment by Princevikas** [comment]
> 
> 
> run `npm install` looks like you are missing a module called `is-promised` which is part of `discordjs-Commando `

[again error.txt](https://github.com/galnir/Master-Bot/files/5900006/again.error.txt)

did this again having error

**Comment by Bacon-Fixation** [comment]
Make sure you are running the `npm install` inside the Master-Bot folder `cd Master-Bot`

**Comment by Princevikas** [comment]
![image](https://user-images.githubusercontent.com/58914249/106389886-d079e780-640b-11eb-9b7b-e933f7a941a5.png)

it showing this

**Comment by Bacon-Fixation** [comment]
try `npm install github:discordjs/Commando` to see if the error changes if it does recreate your deployment in Heroku something went wrong with the package.json file

**Comment by Princevikas** [comment]
`
[command log.txt](https://github.com/galnir/Master-Bot/files/5900136/command.log.txt)
[npm audit fix.txt](https://github.com/galnir/Master-Bot/files/5900137/npm.audit.fix.txt)

the problem still there , i also tried using the old code which used to work in December , it showing same error

**Comment by galnir** [comment]
> `
> [command log.txt](https://github.com/galnir/Master-Bot/files/5900136/command.log.txt)
> [npm audit fix.txt](https://github.com/galnir/Master-Bot/files/5900137/npm.audit.fix.txt)
> 
> the problem still there , i also tried using the old code which used to work in December , it showing same error

Those logs show nothing out of the ordinary. What error are you getting when you enter: 
```node index.js```

**Comment by Princevikas** [comment]
> > 
> > 
> > run `npm install` looks like you are missing a module called `is-promised` which is part of `discordjs-Commando `
> 
> [again error.txt](https://github.com/galnir/Master-Bot/files/5900006/again.error.txt)
> 
> did this again having error
> 

@galnir this one

**Comment by galnir** [comment]
> > > run `npm install` looks like you are missing a module called `is-promised` which is part of `discordjs-Commando `
> > 
> > 
> > [again error.txt](https://github.com/galnir/Master-Bot/files/5900006/again.error.txt)
> > did this again having error
> 
> @galnir this one

try to ```npm i is-promise```

**Comment by Bacon-Fixation** [comment]
Alter your Procfile to `worker = node index.js` and redeploy and have it selected in the Heroku resources tab
![image](https://user-images.githubusercontent.com/12632936/106394281-6f2d2680-63c1-11eb-9437-82535a57dee4.png)

**Comment by Princevikas** [comment]
> > > > run `npm install` looks like you are missing a module called `is-promised` which is part of `discordjs-Commando `
> > > 
> > > 
> > > [again error.txt](https://github.com/galnir/Master-Bot/files/5900006/again.error.txt)
> > > did this again having error
> > 
> > 
> > @galnir this one
> 
> try to `npm i is-promise`

[dj1.txt](https://github.com/galnir/Master-Bot/files/5900435/dj1.txt)
[is promise.txt](https://github.com/galnir/Master-Bot/files/5900436/is.promise.txt)
after trying npm i is-promise

**Comment by Princevikas** [comment]
> Alter your Procfile to `worker: node index.js` and redeploy and have it selected in the Heroku resources tab 
> 'worker' may not show up until you turn on or off 'web' after deploy
> ![image](https://user-images.githubusercontent.com/12632936/106394281-6f2d2680-63c1-11eb-9437-82535a57dee4.png)
> 
> App log make sure to select the Worker in Application Log
> ![image](https://user-images.githubusercontent.com/12632936/106394383-f67a9a00-63c1-11eb-98e0-a903372c71bd.png)
> 

but it was the first thing I did,

**Comment by Princevikas** [comment]
> Alter your Procfile to `worker: node index.js` and redeploy and have it selected in the Heroku resources tab 
> 'worker' may not show up until you turn on or off 'web' after deploy
> ![image](https://user-images.githubusercontent.com/12632936/106394281-6f2d2680-63c1-11eb-9437-82535a57dee4.png)
> 
> App log make sure to select the Worker in Application Log
> ![image](https://user-images.githubusercontent.com/12632936/106394383-f67a9a00-63c1-11eb-98e0-a903372c71bd.png)
> 

![Screenshot_20210201-025800929.jpg](https://user-images.githubusercontent.com/58914249/106398537-582a1b00-6439-11eb-844d-fa7a08e0b7d2.jpg)
maybe some sort of stack incompatibility?

**Comment by Bacon-Fixation** [comment]
the example was on heroku-20 but that doesn't make sense if your old build no longer works

try creating a new app in Heroku with your old build and see if it works then try with the build you are trying to use

**Comment by Princevikas** [comment]
oh working now idk how 😶😶 maybe i was doing something wrong but i used the same process as earlier , nvm it is working now , thanks for the help again ,( i still wonder how it is working again)
