### ISSUE TITLE
avatar.js should be created

### ISSUE THREAD

**Issue by kizule** [galnir/Master-Bot#341]
I think that command !avatar which shows own avatar or someone else's avatar.

On example:
1. If i type !avatar, it should show my own avatar.
2. If i type !avatar @Someone it should show avatar of user @Someone

**Comment by Natemo6348** [comment]
@kizule just as a heads up, maybe next time put a space between @ and Someone so you don't mention other github users accidentally

**Comment by Bacon-Fixation** [comment]
I like the idea

and @Natemo6348 Notemo6348 you probably could (don't sell yourself short my friend)

I can play around too and see what can be done

**Comment by Natemo6348** [comment]
this isnt related to this issue at all, but if I pull changes, will it remove my config.json or not

**Comment by Bacon-Fixation** [comment]
the .gitignore file has the config.json listed, so if you clone the PR the config.json is not changed

**Comment by Natemo6348** [comment]
oh ok, thanks

**Comment by Bacon-Fixation** [comment]
np <3

**Comment by galnir** [comment]
Added in 42849e7 by @Natemo6348
