### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Jriskamm** [galnir/Master-Bot#343]
After using /play command to play music, that error appears

**Comment by Bacon-Fixation** [comment]
Make sure you have ffmpeg and Python2.7 installed

**Comment by Jriskamm** [comment]
> Make sure you have [ffmpeg](https://www.ffmpeg.org/download.html) and [python 2.7](https://www.python.org/downloads/) are installed correctly.
> 
> Much Love
> -Bacon

they are being installed, but still dosent work

**Comment by Bacon-Fixation** [comment]
I have a few extra questions
Did you clone Master-Bot or is it altered?

How are you hosting Master-Bot? 
(Heroku, Windows 10, Linux, etc)

What version of Node are you using?
(requires node 12 or higher)

Are there any errors when you run `npm i` ?

Much Love
-Bacon

**Comment by Jriskamm** [comment]
> I have a few extra questions
> Did you clone Master-Bot or is it altered?
> 
> How are you hosting Master-Bot?
> (Heroku, Windows 10, Linux, etc)
> 
> What version of Node are you using?
> (requires node 12 or higher)
> 
> Are there any errors when you run `npm i` ?
> 
> Much Love
> -Bacon

its okay i have fixed it everything working fine just that youtube api rate limited. thankuu tho!
