### ISSUE TITLE
TypeError: Cannot read property 'end' of null  and /music-trivia stops working off a sudden

### ISSUE THREAD

**Issue by Jriskamm** [galnir/Master-Bot#344]
Music Trivia ongoing but it stopped working out of a sudden, have to restart the bot everytime and also it crashes sometimes.
with the typeerror below, maybe is the cause of missing permissions? im not sure, can u update me with what permission it requires?
<img width="392" alt="Screenshot (204)" src="https://user-images.githubusercontent.com/69320092/101271187-939ec500-37bb-11eb-9495-642459e1bd4f.png">

**Comment by galnir** [comment]
1. fill the issue template
2. did you clone this repo or copy code?

**Comment by Jriskamm** [comment]
clone to test

> 1. fill the issue template
> 2. did you clone this repo or copy code?

clone to test on heroku

**Comment by Jriskamm** [comment]
> 1. fill the issue template
> 2. did you clone this repo or copy code?

i will open another issue and close this\
