### ISSUE TITLE
I have no permission to join your channel

### ISSUE THREAD

**Issue by RihardKeegi** [galnir/Master-Bot#348]
Error: :no_entry: I have no permission to join your channel! I have ffmpeg and python 2.7 installed

**Comment by Bacon-Fixation** [comment]
Look at #276 also

If it is a private channel (assuming it works on others but not in one discord server)
Add your bot to a role that can see it like Role Admin inside discord server




if that doesn't help make sure you set up your permissions correctly when creating your Discord App for your Bot Token/Key
inside the [Discord Dev portal](https://discord.com/developers/applications/) 
- **Demonstration Only** (just a visual aid) 
![permissions](https://user-images.githubusercontent.com/12632936/97736210-5737c500-1aa9-11eb-8036-6032de4d6798.PNG)

Screenshot is from https://discordpy.readthedocs.io/en/latest/discord.html

try with 
- Send Message
- Embed Links 
- View Channels
- Connect
- Speak
- Manage Messages
- Kick Members
- Ban Members
- Manage Roles
- Attach Files

you can always kick your bot and re-invite him with new permissions 

I hope this helps you 

Much Love
-Bacon

**Comment by RihardKeegi** [comment]
it dont help

**Comment by Bacon-Fixation** [comment]
try `npm i ytdl-core`

**Comment by RihardKeegi** [comment]
i have ytdl core installed

**Comment by Bacon-Fixation** [comment]
is this a clone or a code copy?

What version of node are you running?

Was it working previously?

How are you hosting the bot?

**Comment by RihardKeegi** [comment]
> is this a clone or a code copy? I installed it from github and followed guides 
> 
> What version of node are you running? I dont know, I asked it from PebbleHost staff
> 
> Was it working previously? no
> 
> How are you hosting the bot? By PebbleHost bot hosting: https://billing.pebblehost.com/cart.php?a=confproduct&i=1

**Comment by RihardKeegi** [comment]
How are you hosting the bot?
(Heroku, Windows, Ubuntu, etc...) Ubunutu

**Comment by RihardKeegi** [comment]
Nodejs version is "12.16.3"

**Comment by Bacon-Fixation** [comment]
what there any errors during the `npm install` inside the bot folder

**Comment by RihardKeegi** [comment]
no

**Comment by Bacon-Fixation** [comment]
what is your bots Role set to in discord ?
set it to admin

**Comment by RihardKeegi** [comment]
I edited my comment

**Comment by RihardKeegi** [comment]
> what is your bots Role set to in discord ?
> try admin

Bot have owner

**Comment by Bacon-Fixation** [comment]
is this on there minecraft hosting or there discord bot hosting?

Minecraft Hosting(is the link you sent)

but the Discord bot Hosting
should already have Nodejs 14.15.0 installed
but Python2.7 is not installed they have 3.x (wich should of failed to compile the node_modules)

**Comment by RihardKeegi** [comment]
wait... i cant run js and py at same time

**Comment by Bacon-Fixation** [comment]
you have another bot running that uses node ?

**Comment by RihardKeegi** [comment]
i dont run my bot at dedicated hosting

**Comment by RihardKeegi** [comment]
https://prnt.sc/vx28hs

**Comment by Bacon-Fixation** [comment]
How was ffmpeg installed ?

**Comment by RihardKeegi** [comment]
https://prnt.sc/vx29bw

**Comment by RihardKeegi** [comment]
https://prnt.sc/vx29wz

**Comment by RihardKeegi** [comment]
{
  "name": "master-bot",
  "version": "1.0.0",
  "description": "a discord music bot with guild , gifs and misc commands",
  "main": "index.js",
  "scripts": {
    "start": "node .",
    "pretest": "eslint --ignore-path .gitignore .",
    "test": "echo "Error: no test specified" && exit 1"
  },
  "author": "Nir Gal",
  "license": "ISC",
  "dependencies": {
    "@discordjs/opus": "^0.3.3",
    "canvas": "^2.6.1",
    "cheerio": "^1.0.0-rc.3",
    "discord-paginationembed": "^2.1.0",
    "discord.js": "github:discordjs/discord.js",
    "discord.js-commando": "github:discordjs/Commando",
    "ffmpeg-static": "^2.7.0",
    "iso-639-1": "^2.1.4",
    "quick.db": "^7.1.3",
    "simple-youtube-api": "^5.2.1",
    "ytdl-core": "^4.1.3"
  },
  "devDependencies": {
    "@getify/eslint-plugin-proper-arrows": "^8.0.1",
    "@getify/eslint-plugin-proper-ternary": "^3.0.1",
    "babel-eslint": "^10.1.0",
    "eslint": "^5.16.0",
    "nodemon": "^1.19.4",
    "prettier": "^1.19.1"
  }
}

**Comment by RihardKeegi** [comment]
package.json

**Comment by Bacon-Fixation** [comment]
7:4.3.1-5ubuntu1 for ffmpeg i don't know why its at 0.0.4

**Comment by RihardKeegi** [comment]
???

**Comment by Bacon-Fixation** [comment]
https://www.ffmpeg.org/download.html#build-linux

**Comment by Bacon-Fixation** [comment]
the one you have in your picture is the Node Version of ffmpeg https://www.npmjs.com/package/ffmpeg

**Comment by RihardKeegi** [comment]
How i can install this one: https://www.ffmpeg.org/download.html#build-linux

**Comment by Bacon-Fixation** [comment]
`apt-get install ffmpeg`  or `sudo apt-get install ffmpeg`

**Comment by RihardKeegi** [comment]
ok

**Comment by RihardKeegi** [comment]
Python is not a node module, it is simply installed by default into the container: https://i.jaywilliams.me/4dWdfhg5K.png

**Comment by galnir** [comment]
@RihardKeegi Is it working now?

**Comment by galnir** [comment]
If it still doesn't work, open a new issue and make sure to fill the entire issue template
