### ISSUE TITLE
/music-trivia command 

### ISSUE THREAD

**Issue by Jriskamm** [galnir/Master-Bot#349]
**Describe the bug**
/music-trivia stop working halfway, but other commands work perfectly fine, it just stop carryin on the quiz half way. if i try to end it or start a new quiz "TypeError: Cannot read property 'end' of null" appears
<img width="392" alt="Screenshot (204)" src="https://user-images.githubusercontent.com/69320092/101296991-863c1600-3861-11eb-8462-3965354229f8.png">

**Expected behavior**
Expecting the /music-trivia to carry on with this quiz, even if i choose 5 quiz /15quiz, sometimes it may just stop halfway

**Desktop (please complete the following information):**
 - Windows
 - 14.15.1
 - Are python 2.7 and Ffmpeg installed?: Yes
 - Heroku

![Screenshot (216)](https://user-images.githubusercontent.com/69320092/101307148-c7442280-3881-11eb-900f-52ac948b9110.png)
![Screenshot (215)](https://user-images.githubusercontent.com/69320092/101307153-c9a67c80-3881-11eb-827b-db9bd87c7043.png)

**Comment by Bacon-Fixation** [comment]
i was able to replicate this submitted a fix here #350

Much Love
-Bacon

**Comment by Jriskamm** [comment]
> @Jriskamm I was able to replicate this issue and submitted a fix here #350
> can also happen if the Daily YouTube limit was reached
> 
> Much Love
> -Bacon

thank u much sir
