### ISSUE TITLE
MinigetError: input stream: Status code: 429

### ISSUE THREAD

**Issue by Jriskamm** [galnir/Master-Bot#353]
**Describe the bug**
MinigetError: input stream: Status code: 429

**Expected behavior**
To play a song, but it provides an error, leaves the voice channel afterwards

**Screenshots**
<img width="524" alt="Screenshot (223)" src="https://user-images.githubusercontent.com/69320092/101568142-110d4400-3a0d-11eb-9c88-c6da469338d7.png">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...] Windows
 - Node Version(Should be v12 atleast): Yes
 - Are python 2.7 and Ffmpeg installed?: Yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): VPS

**Additional context**
ytdl-core: 4.1.4
i have also changed my youtube api key

**Comment by Bacon-Fixation** [comment]
Code 429 is a Limit Error from youtube

**Comment by zero59344** [comment]
> Code 429 is a Limit Error, as in you hit the Daily limit for youtube API you can apply for a larger limit in Dev Portal for the Youtube API v3

In this problem, you should wait for tomorrow until the bot gets back to work?

**Comment by galnir** [comment]
It does seem like a rate limit issue, Try tommorow with the same key and report your results.
If it will stay the same you likely have done something wrong because the music functions are not broken. Make sure you've placed the right API key in config.json, installed python 2.7 and ffmpeg, and if you copied code over to another bot or from another bot the music functions will not work as expected

**Comment by Jriskamm** [comment]
> It does seem like a rate limit issue, Try tommorow with the same key and report your results.
> If it will stay the same you likely have done something wrong because the music functions are not broken. Make sure you've placed the right API key in config.json, installed python 2.7 and ffmpeg, and if you copied code over to another bot or from another bot the music functions will not work as expected

how do u get unlimited use of api key
