### ISSUE TITLE
my list command

### ISSUE THREAD

**Issue by razvandamian** [galnir/Master-Bot#354]
at my list, you should put after the playlist name how long playlist the is in the songs

**Comment by galnir** [comment]
I don't understand the sentence "how long playlist the is in the songs"

**Comment by razvandamian** [comment]
like the number of songs that playlist have

**Comment by razvandamian** [comment]
and at volume command, it would be nice to show the current volume

**Comment by galnir** [comment]
1. I still don't understand what you mean, why would you add how many songs the playlist has as an argument? The command lists your song and it has a paged embed.
2. Volume command is meant to be used as a setter. It shows you the new volume after you set it

**Comment by razvandamian** [comment]
forget it, but when i want to remove a song from a playlist, how can i see the songs number that i want to delete it?

**Comment by galnir** [comment]
> forget it, but when i want to remove a song from a playlist, how can i see the songs number that i want to delete it?

!my-playlist playlistName
Gives you a list of songs, each one has a number according to its place
!delete-song playlistName songNumber

**Comment by razvandamian** [comment]
yes, thanks!
