### ISSUE TITLE
I can't play the song!

### ISSUE THREAD

**Issue by zero59344** [galnir/Master-Bot#355]
I changed the API key and the bot still says: I can't play the song!

**Comment by galnir** [comment]
Fill the issue template

**Comment by zero59344** [comment]
> Fill the issue template

This is the error the server showed me

![Capture](https://user-images.githubusercontent.com/69620603/101846180-18416880-3b59-11eb-9b7a-78afec3a4730.PNG)

**Comment by galnir** [comment]
429 means you got rate limited. Make sure ytdl-core is at its latest version(4.1.4) by entering: 
```npm list ytdl-core```
if it's not 4.1.4 enter:
```npm i ytdl-core@4.1.4```

Check your Google developer console to see if you got rate limited

**Comment by zero59344** [comment]
> 429 means you got rate limited. Make sure ytdl-core is at its latest version(4.1.4) by entering:
> `npm list ytdl-core`
> if it's not 4.1.4 enter:
> `npm i ytdl-core@4.1.4`
> 
> Check your Google developer console to see if you got rate limited

Yes, I checked everything .. But the problem is still there and the bot does not play music

**Comment by galnir** [comment]
@zero59344 429 is rate limit, only options are:
1. ytdl-core isn't 4.1.4
2. You used the entire daily unit quota, change key or wait

**Comment by zero59344** [comment]
> @zero59344 429 is rate limit, only options are:
> 
> 1. ytdl-core isn't 4.1.4
> 2. You used the entire daily unit quota, change key or wait

Did you mean to change the key: youtube api v3 ?

**Comment by galnir** [comment]
> > @zero59344 429 is rate limit, only options are:
> > 
> > 1. ytdl-core isn't 4.1.4
> > 2. You used the entire daily unit quota, change key or wait
> 
> Did you mean to change the key: youtube api v3 ?

YouTube Data API v3

**Comment by galnir** [comment]
If the problem still exists open a new issue and fill the template this time
