### ISSUE TITLE
Show how many users and servers in Activity

### ISSUE THREAD

**Issue by icsmac** [galnir/Master-Bot#36]
I cant use this..

console.log(`Bots is ready and working in ${bot.guilds.size} servers with ${bot.users.size} users!`);

help me

**Comment by chimaerra** [comment]
You shouldn't use `bot`
instead, you should use `client`
for example: ${client.guilds.size} & ${client.users.size}

DM your bot with this and you'll see.
eval message.say(`GUILDS: ` + `${client.guilds.size}` + ` ` + `USERS: `  + `${client.users.size}`)

**Comment by chimaerra** [comment]
You shouldn't use `bot`
instead, you should use `client`
for example: ${client.guilds.size} & ${client.users.size} 

DM your bot with this and you'll see.

` 
eval message.say("GUILDS: " + `${client.guilds.size}` + " " + "USERS: " + `${client.users.size}`)
`

**Comment by galnir** [comment]
@chimaerra You don't need to put $ and curly braces around a variable if it's not inside a [template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals). 
So @icsmac to answer your question, you need to log this:
console.log(`Bot is ready and working in ${client.guilds.cache.size} servers with ${client.users.cache.size} users!`);

For some reason GitHub removes the template literals from the beginning and the end of the text inside the log statement so add them in code.
And btw, in discord.js master it's **client.guilds.cache.size** and **client.users.cache.size**.

**Comment by chimaerra** [comment]
> @chimaerra You don't need to put $ and curly braces around a variable if it's not inside a [template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).
> So @icsmac to answer your question, you need to log this:
> console.log(`Bot is ready and working in ${client.guilds.cache.size} servers with ${client.users.cache.size} users!`);
> 
> For some reason GitHub removes the template literals from the beginning and the end of the text inside the log statement so add them in code, look [here](https://gist.github.com/galnir/7cc111b6721652b855518ebfe8ca5650).
> And btw, in discord.js master it's **client.guilds.cache.size** and **client.users.cache.size**.

Yea I kinda understand what you said but I'm a newbie in javascript for real :)
Thanks for explanation though

**Comment by icsmac** [comment]
Thanks!! A lot
