### ISSUE TITLE
Add setting that bot can send messages for welcoming and on server

### ISSUE THREAD

**Issue by kizule** [galnir/Master-Bot#361]
Feature for sending messages for welcoming is great. But, maybe we should make way and to bot send message on server if someone wants, no just in user's DM.

**Comment by galnir** [comment]
It used to be a server greeting but we changed it to dm(@Bacon-Fixation's feature). If you'd like you can implement it yourself, take a look at [this example](https://discord.js.org/#/docs/main/master/examples/greeting)

**Comment by Bacon-Fixation** [comment]
yeah i can fix that make it a options or something

**Comment by Bacon-Fixation** [comment]
So something like this #361 kizule?

**Comment by kizule** [comment]
Maybe it should ping user also? But idea looks good.

**Comment by Bacon-Fixation** [comment]
:D i apologize

**Comment by Bacon-Fixation** [comment]
@kizule how about now? #362

**Comment by kizule** [comment]
Yup, this looks good. Thank you! @Bacon-Fixation

**Comment by Bacon-Fixation** [comment]
Np my friend

**Comment by kizule** [comment]
Maybe and feature for sending message when user leaves server should be added also.

**Comment by Bacon-Fixation** [comment]
I like that too :D I will see what I can come up with, probably not in PR #362 (I want to do a lot more testing for something like that)

**Comment by galnir** [comment]
Adressed in #386
