### ISSUE TITLE
Hey try to make 247 command

### ISSUE THREAD

**Issue by koushikpuppala5** [galnir/Master-Bot#363]
**Hey try to make 247 command which makes the bot stay in a voice channel with some role need in main server**

**Comment by galnir** [comment]
Not on my todo list atm, but if you'd like you can write one yourself and open a pull request :)

**Comment by koushikpuppala5** [comment]
I can't because you kept leave command in play.js it should also should change

**Comment by galnir** [comment]
Well if you have experience with coding you can change that

**Comment by koushikpuppala5** [comment]
**Can you tell me your ToDo's**

**Comment by galnir** [comment]
Spotify and code improvements for now, don't have much time to focus on major stuff

**Comment by koushikpuppala5** [comment]
Ok
