### ISSUE TITLE
Can’t change package.json

### ISSUE THREAD

**Issue by biswajitguha01** [galnir/Master-Bot#368]
I can’t change package json because there ytdl version is 4.1.4 but new version is available now 4.1.6 but when I put 4.1.6 then it does not run.

**Comment by Bacon-Fixation** [comment]
`npm i ytdl-core@latest -s` it will save it to the package.json

**Comment by biswajitguha01** [comment]
Thanks for your reply, but I am using heroku for hosting so there is no option for npm install in console

**Comment by Bacon-Fixation** [comment]
i don't understand what you mean ????  [Nodejs deploy](https://devcenter.heroku.com/articles/deploying-nodejs)
![image](https://user-images.githubusercontent.com/12632936/102416781-18f65680-3fc0-11eb-98d0-b7d29e42b0ed.png)

**Comment by biswajitguha01** [comment]
I am not using heroku cli I am using github clone in heroku that mean I am connected my GitHub repository with heroku account then I am deployed & then it show `app[api]: Build failed -- check your build output: https://dashboard.heroku.com/apps/565d1a85-55b7-4730-ac6e-d44d29b19b88/activity/builds/b8b16d50-504b-4090-b3c0-91e1b4911cb3` that so I am asking you.

**Comment by Bacon-Fixation** [comment]
all good i have put in a PR for the update to ytdl-core for you it may be updated soon for ya

**Comment by Bacon-Fixation** [comment]
oh BTW  that link dosent work
Access denied.

This Heroku account does not have the required permissions to access this page.

**Comment by biswajitguha01** [comment]
Thank for update its working now... ❤️. Can you please add `dblapi.js` in `package.json` & `package.lock.json` Thanks again

**Comment by Bacon-Fixation** [comment]
np <3 what do you have in mind with it ?

**Comment by biswajitguha01** [comment]
Ok thanks. By the way this project is great & music quality awesome.

**Comment by Bacon-Fixation** [comment]
You can make a fork of Master-Bot and use that to alter and then link it to your Heroku for a non-CLI way of changing the package.json

**Comment by biswajitguha01** [comment]
Ok

**Comment by Bacon-Fixation** [comment]
i love this project so much (TY galnir <3) that  i picked up learning JS to make a few features there is a ton of [Documentation](https://discordjs.guide/)

**Comment by galnir** [comment]
Glad @Bacon-Fixation was able to help you!
