### ISSUE TITLE
Ticket

### ISSUE THREAD

**Issue by PRITu-v2** [galnir/Master-Bot#370]
**Please Add Ticket System Also because There Are Soo Many Members Are Needed Ticket System Soo Please Make It**

**Comment by Bacon-Fixation** [comment]
What is a Ticket System?
May I ask for some additional info on what you mean. I'm keen to try when I have some extra time (be warned I am slow :D)

**Comment by galnir** [comment]
> What is a Ticket System?
> May I ask for some additional info on what you mean. I'm keen to try when I have some extra time (be warned I am slow still new to JS :D)
> 
> Much Love
> -Bacon

Probably a system that allows users to send tickets to moderators/admins. 
I've decided that until I consider the music functions done in terms of features I will shift the focus to guild commands, because guild commands can be complex and require time. I'll remember your request
