### ISSUE TITLE
discord player control by reactions

### ISSUE THREAD

**Issue by Princevikas** [galnir/Master-Bot#371]
i was thinking if it is possible to add filters and control music with reactions like we can do in [https://github.com/ZerioDev/Music-bot](url)

**Comment by razvandamian** [comment]
+1

**Comment by Bacon-Fixation** [comment]
I can poke around with this idea (be warned I'm slow :P)

Much Love
-Bacon

**Comment by razvandamian** [comment]
if you make the filter thing your awsome

**Comment by Princevikas** [comment]
> 
> 
> I can poke around with this idea (be warned I'm slow :P I have a few commands already in the works)
> 
> Much Love
> -Bacon

you're the best 🙏

**Comment by Princevikas** [comment]
you are the best
