### ISSUE TITLE
error while installing some dependencies on Win8@32bit

### ISSUE THREAD

**Issue by muhitrhn** [galnir/Master-Bot#372]
I am having errors while trying to install the `npm install discord.js @discordjs/opus` and `npm install canvas` dependencies on my win8 32 bit pc.

Here is the log file - 
[2020-12-17T12_42_31_330Z-debug.log](https://github.com/galnir/Master-Bot/files/5709659/2020-12-17T12_42_31_330Z-debug.log)

Can you help with that, please?

**Comment by Bacon-Fixation** [comment]
Make sure you have a compiler for Canvas Windows 8 32Bit `npm install--global windows-build-tools` then rerun `npm i canvas`

Much Love
-Bacon

**Comment by muhitrhn** [comment]
I have tried installing the compiler using `npm install --global windows-build-tools` (Successful) but still seeing this error when I run `npm install` 
[2020-12-17T17_49_30_192Z-debug.log](https://github.com/galnir/Master-Bot/files/5711242/2020-12-17T17_49_30_192Z-debug.log)

**Comment by Bacon-Fixation** [comment]
Error suggests that [Git](https://git-scm.com/) is not installs to grab the Repo 
```
701 error code ENOENT
702 error syscall spawn git
703 error path git
704 error errno -4058
705 error enoent Error while executing:
705 error enoent undefined ls-remote -h -t ssh://git@github.com/discordjs/discord.js.git
705 error enoent
705 error enoent
705 error enoent spawn git ENOENT
706 error enoent This is related to npm not being able to find a file.
707 verbose exit [ -4058, true ]
```

**Comment by muhitrhn** [comment]
I installed Git CLI and also have re-run `npm install` but the same error shows up.

> I have also tried downloading the GTK 2@x32 and extracting the files on C:\GTK but doesn't seem to work.

**Comment by Bacon-Fixation** [comment]
if you run `git --version` what comes up

```
PS C:\Users\zirre> git --version
git version 2.27.0.windows.1
```

**Comment by muhitrhn** [comment]
Okay, seems Windows really can't find git. Is there a solution for that?

**Comment by Bacon-Fixation** [comment]
https://git-scm.com/download/win

**Comment by muhitrhn** [comment]
Now it's also super confusing for me ;-(
Thank you for standing to help!

Okay, after a reboot, seems windows now can detect the Git CLI but now there is a new error.
[2020-12-17T18_48_10_979Z-debug.log](https://github.com/galnir/Master-Bot/files/5711557/2020-12-17T18_48_10_979Z-debug.log)

**Comment by Bacon-Fixation** [comment]
try a `npm clean-install`

**Comment by muhitrhn** [comment]
Okay, can you please tell me how to clone? Is it just extracting the downloaded files in the destination folder?

**Comment by muhitrhn** [comment]
Tried that too.
better-SQL easily gets installed but the main problem is with Opus and Canvas. Both of them show a bunch of errors while installing.

**Comment by Bacon-Fixation** [comment]
forgive me i forgot something #187 when i comes to 32 bit.
i will make you an alteration you can use on win 32 bit systems
or a guide because Opus and Canvas have a special step for there installation give me a moment to prepare that for you

**Comment by muhitrhn** [comment]
> forgive me i forgot something #187 when i comes to 32 bit.
> i will make you an alteration you can use on win 32 bit systems
> or a guide because Opus and Canvas have a special step for there installation give me a moment to prepare that for you

Sure. Don't be sorry, thank you so much for your time instead!

**Comment by Bacon-Fixation** [comment]
just curious have you looked into services like Glitch, Heroku, repl.it for hosting ?
These are all web base hosts that you can use for hosting the bot .... just in case I can't remember how I did this on my laptop

they have free options  with their own pros and cons 
its taking for ever to charge this battery LOL

**Comment by Bacon-Fixation** [comment]
i regret to inform you the version i have on my laptop is before the addition of Canvas i dont have a solution for canvas and 32bit node version

**Comment by muhitrhn** [comment]
> just curious have you looked into services like Glitch, Heroku, repl.it for hosting ?
> These are all web base hosts that you can use for hosting the bot .... just in case I can't remember how I did this on my laptop
> 
> they have free options with their own pros and cons
> its taking for ever to charge this battery LOL

LOL!
I didn't try them out, I was trying to setup the bot on my pc so that it's active when I am.

> i regret to inform you the version i have on my laptop is before the addition of Canvas i dont have a solution for canvas and win 32bit node

No worries, then I think I should try out one of the we based hosting providers

**Comment by Bacon-Fixation** [comment]
yeah opus has instructions to install for other platforms on the website. It's what I used originally but Canvas is proving an issue,
 i did try the GTK they have on their optional install instructions to no avail.
Just thought I would still try it :D

**Comment by muhitrhn** [comment]
Thank you!
Actually for everything. 

Take love <3!

**Comment by galnir** [comment]
Running on a 32bit os can be tricky. If you don't have the option to host it on a local 64bit os you can go for the options Bacon suggested :)
