### ISSUE TITLE
/play does not support video link

### ISSUE THREAD

**Issue by Jriskamm** [galnir/Master-Bot#373]
The "play" command does not support video links.

**Expected behavior**
The command to play the music when i paste a link

**Screenshots**
<img width="432" alt="Screenshot (20)" src="https://user-images.githubusercontent.com/69320092/102524619-39173a00-40d4-11eb-9e59-df9774e0ee2a.png">

**Desktop (please complete the following information):**
Windows
 - Node Version(Should be v12 atleast): Yes
 - Are python 2.7 and Ffmpeg installed?: Yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): VPS

**Comment by Bacon-Fixation** [comment]
I'm having trouble replicating this error 
is it possible to provide an offending link i can use to look into this further?

Much Love
-Bacon

**Comment by galnir** [comment]
Do you get this error for **every** link? If yes, you might have reached the daily limit for your API key.
If no, what links are failing?

**Comment by KosmitoX** [comment]
i have the same issue and i add on my case dont work the search 
capture
[https://puu.sh/GYyNy/43296fb4c2.png](url)

regards

**Comment by Jriskamm** [comment]
> Do you get this error for **every** link? If yes, you might have reached the daily limit for your API key.
> If no, what links are failing?

i just pasted like a random ncs music link

**Comment by Jriskamm** [comment]
> I'm having trouble replicating this error
> is it possible to provide an offending link i can use to look into this further?
> 
> Much Love
> -Bacon

**Comment by Bacon-Fixation** [comment]
what is nsc music ?

**Comment by Jriskamm** [comment]
> what is ncs music ?

no copy right song music

**Comment by Bacon-Fixation** [comment]
kk i will look furrther

**Comment by Jriskamm** [comment]
> kk i will look furrther

https://m.youtube.com/watch?v=EP625xQIGzs <---- this video link

**Comment by KosmitoX** [comment]
i can invite you to my discord server to test the error if you like but i reinstall the bot and still i have the same error maybe is the OS?

**Comment by Bacon-Fixation** [comment]
i still can't replicate the issue make sure you are up to date there was an update a couple of hours ago for the ytdl-core
![image](https://user-images.githubusercontent.com/12632936/102553660-d3ea2700-4088-11eb-9134-7a0ccaf0e441.png)

**Comment by KosmitoX** [comment]
i reinstall ytdl-core and nothing 
There was a problem searching the video you requested!
@Kosmito, An error occurred while running the command: TypeError: Cannot read property 'length' of undefined
You shouldn't ever receive an error like this.

this is on Debian 10 
nodejs 14

**Comment by Bacon-Fixation** [comment]
KosmitoX your issue is more related to #14 which is most likely missing ffmpeg

**Comment by KosmitoX** [comment]
are installed 
ffmpeg -v
ffmpeg version 4.1.6-1~deb10u1 Copyright (c) 2000-2020 the FFmpeg developers
Python 2.7.16
i always check all is installed before to install the bot so is strange why i have that error

**Comment by Jriskamm** [comment]
> @KosmitoX your issue is more related to #14 which is most likely missing ffmpeg or python2.7 or one of the other need installs
> 
> Much Love
> -Bacon

<img width="541" alt="Screenshot (21)" src="https://user-images.githubusercontent.com/69320092/102554667-329eb780-4100-11eb-80af-29e3bfb27b79.png">
now, it coes up with the search result after i updated ytdl-core

**Comment by Bacon-Fixation** [comment]
Hmmmmmm interesting i will try to look further into that

give me a sec i have a Debian 10 system i can try to replicate it @KosmitoX 

which VPS are you using @Jriskamm so i can better replicate your issue i have Heroku , Glitch, and repl.it on hand

**Comment by Jriskamm** [comment]
> Hmmmmmm interesting i will try to look further into that i ran my test on a Windows 10 build
> 
> give me a sec i have a Debian 10 system i can try to replicate it @KosmitoX
> 
> which VPS are you using @Jriskamm so i can better replicate your issue

microsoft azure

**Comment by Bacon-Fixation** [comment]
windows or linux deply ?

**Comment by Jriskamm** [comment]
> windows or linux deploy ?

windows

**Comment by Bacon-Fixation** [comment]
kk i will try my best to come back with a solution

**Comment by Bacon-Fixation** [comment]
@Jriskamm the Desktop Link https://www.youtube.com/watch?app=desktop&v=EP625xQIGzs works without any issues

 but the Mobile Link https://m.youtube.com/watch?v=EP625xQIGzs Does Not (it asks for a decision) it's not a 'fix" (still working on it now i found a cause for the popup)
 
 @KosmitoX I apologize if i sound like a broken record<3, but i just want to verify that you have all the installed the prerequisites  (i really can't replicate your situation on my Debian 10 system I'm sorry I have failed)

Much Love
-Bacon

**Comment by KosmitoX** [comment]
i send you a email with the information but i try on fedora 32 too on my pc and dont works yet @Bacon-Fixation if you're interested about the bug

**Comment by Bacon-Fixation** [comment]
KosmitoX that's an altered build of Master-Bot isn't it ?
(i joined your Discord Server)

**Comment by Jriskamm** [comment]
> @Jriskamm check out #375 should resolve your issue
> 
> @KosmitoX that's an altered build of Master-Bot isn't it ?
> (i joined your Discord Server)
> 
> Much Love
> -Bacon
play.js is not updated, when can i copy the

**Comment by Bacon-Fixation** [comment]
> > @Jriskamm check out #375 should resolve your issue
> > @KosmitoX that's an altered build of Master-Bot isn't it ?
> > (i joined your Discord Server)
> > Much Love
> > -Bacon
> > play.js is not updated, when can i copy the

https://github.com/Bacon-Fixation/Beta-test-file

**Comment by Jriskamm** [comment]
> > > @Jriskamm check out #375 should resolve your issue
> > > @KosmitoX that's an altered build of Master-Bot isn't it ?
> > > (i joined your Discord Server)
> > > Much Love
> > > -Bacon
> > > play.js is not updated, when can i copy the
> 
> https://github.com/Bacon-Fixation/Beta-test-file

got it! thanku so much bacon <3

**Comment by Bacon-Fixation** [comment]
Posting addition info for anyone else out there that may find this useful for solving KosmitoX's issue
Youtube v3 Api Log Showed that it had a 100% error rate and any `!play search term`(link or searching) will show a Type error of either Duration or Length

Much Love
-Bacon

**Comment by razvandamian** [comment]
Hello, i got same issue with Kalwi & Remi - Explosion
![image](https://user-images.githubusercontent.com/67657296/102644044-d623b280-4168-11eb-85f3-6cda96e5cad1.png)

**Comment by galnir** [comment]
addressed in #375

**Comment by Sehyn** [comment]
Excuse me @Bacon-Fixation 

But, yeah regarding that error: 
![image](https://user-images.githubusercontent.com/48888351/103134341-cba97180-46b0-11eb-8f45-b27778298659.png)

What's the proper fix ? 

Also, Cloning using Git Bash your repo gives different versions of Discord.JS and such.

![image](https://user-images.githubusercontent.com/48888351/103134348-e2e85f00-46b0-11eb-9061-11d5d2e546a7.png)


Perhaps, I'am doing something wrong but I have no clue.

**Comment by Bacon-Fixation** [comment]
was addressed and merged #375
