### ISSUE TITLE
Deleting more than 100 messages should be available

### ISSUE THREAD

**Issue by kizule** [galnir/Master-Bot#379]
With command prune, currently 99 messages can be deleted. I think that deleting more messages should be available.

**Comment by galnir** [comment]
It's limited at 99 so no one will try deleting a thousand messages at once, which isn't a good idea. If that bothers you just remove the limit in your end

**Comment by kizule** [comment]
It no works, it is reason why I've created this issue.

**Comment by Bacon-Fixation** [comment]
im with Galnir
![image](https://user-images.githubusercontent.com/12632936/102698596-3d427500-4204-11eb-99cd-61ad0230edba.png)
when doing 1000 or even doing just over 100 it can Lag out any of the Music that is playing in all servers not just the one the !prune was commanded in

**Comment by galnir** [comment]
@kizule prune command works for me on 2 instances. Your bot needs admin perms in order for it to work

**Comment by kizule** [comment]
It works for me too, but not with more than 99 messages even if I bump it in the file.

**Comment by galnir** [comment]
> It works for me too, but not with more than 99 messages even if I bump it in the file.

https://discord.com/developers/docs/resources/channel#bulk-delete-messages
It has a limit of 100 messages

**Comment by Bacon-Fixation** [comment]
in test i had 10bulk deletes and anything over 100 was sent to the next bulckdelete and so, on in my test it's not ideal 
it takes to long to run, and it causes issues with other running commands but that was how i went over and again its not recommended 

Much Love
-Bacon
