### ISSUE TITLE
Ability to disable categories

### ISSUE THREAD

**Issue by kaaax0815** [galnir/Master-Bot#383]
**Explain your suggestion**
Not a command, but maybe in the config you can specify what categories you want (e.g. only music) and the rest doesnt get loaded

**Comment by Bacon-Fixation** [comment]
If you only want the Music features you can delete the other commands from the Master-Bot/commands/ folder

or you can try `commandState: true` 'index.js' for the option to disable them with `!disable` command as a DM to bot for All Servers (Owner Permission required)

or in a Discord server text channel to only disable it only on that server (Admin permission required) 

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
If you only want the Music features you can delete the other commands from the Master-Bot/commands/<category-name> folders

or you can try `commandState: true` 'index.js' for the option to disable them with `!disable` command as a DM to bot for All Servers (Owner Permission required)

or in a Discord server text channel to only disable it only on that server (Admin permission required) 

Much Love
-Bacon

**Comment by galnir** [comment]
@kaaax0815 #384 does the trick, although it isn't exactly what you asked for. I'll look into it in the future again
