### ISSUE TITLE
how to add channel greeting

### ISSUE THREAD

**Issue by royalus** [galnir/Master-Bot#39]
i tried it but nothing happen 
![Untitled](https://user-images.githubusercontent.com/59321692/75575187-5ce79180-5a68-11ea-99f6-58faa819b989.png)
![Untitled](https://user-images.githubusercontent.com/59321692/75575277-8d2f3000-5a68-11ea-93a1-bebe6620ff59.png)

**Comment by galnir** [comment]
Did you install discord.js **master**?
The only reason it wouldn't work is if you haven't installed master or the channel isn't a text channel

**Comment by royalus** [comment]
> Did you install discord.js **master**?
> The only reason it wouldn't work is if you haven't installed master or the channel isn't a text channel

bot work fine but each time this appear and say channel didnt found

**Comment by galnir** [comment]
I think you're not saving index.js after modifying it, because the error shows 'general' and not 'lounge'...

**Comment by royalus** [comment]
oky where to put the channel to receive greeting welcome

**Comment by galnir** [comment]
Exactly like you did in the second image, but it seems like you're not saving the file because the error message shows a different channel name

**Comment by royalus** [comment]
nothing bro same

**Comment by galnir** [comment]
This is taken from the docs...
https://discord.js.org/#/docs/main/stable/examples/greeting
