### ISSUE TITLE
[FEAT] Command !leave should send message when bot leaves channel

### ISSUE THREAD

**Issue by kizule** [galnir/Master-Bot#394]
**Steps to reproduce**
1. Join in the voice channel
2. Play some sound
3. Use command !leave

**Expected behaviour**
Bot should send a message that he leaved channel.

**Actual behaviour**
Bot just leaves channel without sending message.

----
Just to note. This isn't bug, this is a feature request. 😄

**Comment by galnir** [comment]
addressed in #395
