### ISSUE TITLE
To allow bot to play your saved playlist

### ISSUE THREAD

**Issue by Jriskamm** [galnir/Master-Bot#396]
**Explain your suggestion**
So my suggestion is to make ur bot play your saved playlist.

**Comment by galnir** [comment]
It can do that, that's the point of the feature
!play playlistname

**Comment by Jriskamm** [comment]
> It can do that, that's the point of the feature
> !play playlistname

it dosent work on mines, when i type out my playlist name, it sends the youtube search for the name instead

**Comment by galnir** [comment]
Did you change anything in play.js? It should work perfectly I just tested it on my end. The logic behind it is in lines 55-64

**Comment by Jriskamm** [comment]
> Did you change anything in play.js? It should work perfectly I just tested it on my end. The logic behind it is in lines 55-64

ohh i found it. thankyou so much, i think i accidentally changed it while editing
