### ISSUE TITLE
Help with the Music

### ISSUE THREAD

**Issue by Soperlol** [galnir/Master-Bot#398]
I tried to put myself on a music command. But I fail miserably. could you maybe help me? My Discord User Name is Flooky#2778

LG Flooky

**Comment by galnir** [comment]
Fill the issue template, I can help you here

**Comment by Soperlol** [comment]
I've tried a lot of music codes, but it never worked. I don't quite understand how that works either

**Comment by kizule** [comment]
@Soperlol Could you provide more details what's happening?

**Comment by galnir** [comment]
> I've tried a lot of music codes, but it never worked. I don't quite understand how that works either

Tbh if you don't understand how it works and how to set up a music bot(requires basic knowledge in using cmd/bash and nodejs), you shouldn't run a bot yourself.
If you still wanna set it up yourself, follow the readme carefully. If you stumble into errors, open a new issue and fill the template
