### ISSUE TITLE
/lyrics dosen't seem to work for me

### ISSUE THREAD

**Issue by Jriskamm** [galnir/Master-Bot#400]
**Describe the bug**
Did the command /lyrics (song mame) but unable to find. provided the valid token from genius api website

**Screenshots**
![Screenshot (36)](https://user-images.githubusercontent.com/69320092/103372143-3244ea00-4b0c-11eb-80b9-bfbcbfedb735.png)

**Comment by Bacon-Fixation** [comment]
make sure you got the right Key from Genius lyrics 

https://github.com/galnir/Master-Bot/issues/310#issuecomment-731491900

**Comment by Jriskamm** [comment]
> @Jriskamm
> Make sure you are clicking on the **Generate Access Token** Link and using the key that pops up and **not** the Client Secret
> ![image](https://user-images.githubusercontent.com/12632936/99865115-42f95c00-2b6d-11eb-9cbb-592896eb40fb.png)
> 
> I personally think there Webpage is a bit confusing to me
> 
> what `!lyrics maria hwasa` grabs when Key is Valid
> ![image](https://user-images.githubusercontent.com/12632936/103375769-95009c00-4aa0-11eb-9ff1-eefe90ab7cc5.png)
> 
> Much Love
> -Bacon

i did that but it dosent seem to work for me, not sure why too? do i have to install anything?

**Comment by galnir** [comment]
> > @Jriskamm
> > Make sure you are clicking on the **Generate Access Token** Link and using the key that pops up and **not** the Client Secret
> > ![image](https://user-images.githubusercontent.com/12632936/99865115-42f95c00-2b6d-11eb-9cbb-592896eb40fb.png)
> > I personally think there Webpage is a bit confusing to me
> > what `!lyrics maria hwasa` grabs when Key is Valid
> > ![image](https://user-images.githubusercontent.com/12632936/103375769-95009c00-4aa0-11eb-9ff1-eefe90ab7cc5.png)
> > Much Love
> > -Bacon
> 
> i did that but it dosent seem to work for me, not sure why too? do i have to install anything?

Did you change anything in the code? It should work fine, tested on 2 operating systems and I believe bacon has tested it on even more

**Comment by Jriskamm** [comment]
> > > @Jriskamm
> > > Make sure you are clicking on the **Generate Access Token** Link and using the key that pops up and **not** the Client Secret
> > > ![image](https://user-images.githubusercontent.com/12632936/99865115-42f95c00-2b6d-11eb-9cbb-592896eb40fb.png)
> > > I personally think there Webpage is a bit confusing to me
> > > what `!lyrics maria hwasa` grabs when Key is Valid
> > > ![image](https://user-images.githubusercontent.com/12632936/103375769-95009c00-4aa0-11eb-9ff1-eefe90ab7cc5.png)
> > > Much Love
> > > -Bacon
> > 
> > 
> > i did that but it dosent seem to work for me, not sure why too? do i have to install anything?
> 
> Did you change anything in the code? It should work fine, tested on 2 operating systems and I believe bacon has tested it on even more

only genius api is needed for this right?

**Comment by Bacon-Fixation** [comment]
Correct only genius access token is needed to run and lyrics command on Master-Bot
all installs were handled during the `npm install`

double-check the config.json that casing is correct should look like `"geniusLyricsAPI": ` 


Much Love
-Bacon

**Comment by galnir** [comment]
As bacon suggested, make sure you placed the access token in config.json.
If you still encounter this, open a new issue and fill the template
