### ISSUE TITLE
Play.js

### ISSUE THREAD

**Issue by Necroz6** [galnir/Master-Bot#403]
Uncaught c:\Users\denis\OneDrive\Bureau\New project\database\commands\Musique\play.js:226
  static playSong(queue, message) {
         ^^^^^^^^

SyntaxError: Unexpected identifier
at  " static playSong(queue, message) {" ligne: 255

**Comment by galnir** [comment]
1. Fill the issue template
2. Did you clone this repo or copy the code from play.js? This error shouldn't be thrown if you cloned the repo

**Comment by galnir** [comment]
Closing until you respond
