### ISSUE TITLE
play.js

### ISSUE THREAD

**Issue by x7s** [galnir/Master-Bot#405]
When trying to play a playlist like this: `/playlist?list=YouTubeOfPlayListIDHere`  I found an error 

```
Error: resource youtube#videoListResponse not found
    at /home/myuser/mynodejsapp/node_modules/simple-youtube-api/src/Request.js:35:68
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async PlayCommand.run (/home/myuser/mynodejsapp/commands/music/play.js:161:27)
    at async CommandoMessage.run (/home/myuser/mynodejsapp/node_modules/discord.js-commando/src/extensions/message.js:235:20)
    at async CommandDispatcher.handleMessage (/home/myuser/mynodejsapp/node_modules/discord.js-commando/src/dispatcher.js:143:19)
```

Can you check if you want a playlist or another input method is requested to check all possible ones and if there is a private video clip it should not be played but skipped

Here is a little info about mine machine
 - OS: [CentOS 7]
 - Node Version(14.15.0): 
 - Are python 2.7 and Ffmpeg installed?: Yes Ffmpeg installed and Python version is 2.7.5
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): It's mine machine like a VPS with WHM & cPanel at the same machine but bot is running with another user

when i trying to play a playlist like this `/watch?v=SomeIDhere&list=YouTubeOfPlayListIDHere` everythink work perfect without conflict with any library

**Comment by Bacon-Fixation** [comment]
I don't quite understand your issue
![image](https://user-images.githubusercontent.com/12632936/103666569-69ffc780-4f3a-11eb-9081-876dcdf69d33.png)

play list links like `/watch?v=SomeIDhere&list=YouTubeOfPlayListIDHere` don't exactly have an end as they were created by youtube to run nearly for ever and not a person created play list that has a defined start and end  

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
I went and made a Docker Image using CentOS 7(smallest (~1.04G) but the longest, build in 239.2s), and it still works a treat maybe update your node modules with `npm update`

you should not be getting an error with the current build of Master-Bot

Much Love
-Bacon

**Comment by x7s** [comment]
at this moment i trying update modules and another error

```
-bash-4.2$ npm update
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/myuser/.npm/_logs/2021-01-05T18_08_40_259Z-debug.log
```
when i trying to update it fsevents i see another err

```
-bash-4.2$ npm install fsevents
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/myuser/.npm/_logs/2021-01-05T18_15_55_233Z-debug.log
```
how to install that module without conflict bcos i use it at another command

**Comment by Bacon-Fixation** [comment]
I apologize, but I have no clue how to help you if Master-Bot is conflicting with other bots or if master-bot was modified
no way for me to replicate conditions 

the Dockerfile I made is [here](https://github.com/Bacon-Fixation/Beta-test-file/blob/master/CentOS%207/Dockerfile) if it helps you any

Much Love
-Bacon

**Comment by x7s** [comment]
Master-Bot is not in conflict with other bots, I just added a module fsevents to work with another new command in it but thats not good idea i guess i can't add another command to work at the Master-Bot
any help how can i remove that module so as not to create conflicts at the future

**Comment by Bacon-Fixation** [comment]
`npm uninstall <node_module-name>`

[npm uninstall docs](https://docs.npmjs.com/cli/v6/commands/npm-uninstall)

Much Love
-Bacon

**Comment by x7s** [comment]
Thank you very much for the help this again did not help
I will try with a clean installation without any added modules on my part to prevent block the operation of the music function in Master-Bot

**Comment by Bacon-Fixation** [comment]
can try to add your version of fsevents to the package.json file

**Comment by x7s** [comment]
At this moment the bug is still here clean installation without any changes at Master-Bot
```
-bash-4.2$ node index.js
Master-Bot#3069 is Ready!
[ 'Test-Server' ] Connected!
```
and when i try to play this link https://www.youtube.com/playlist?list=PL75Y3okhrTLxS9FAcq4MFGu3H8nxUBVZ9 at the server same error
```
Error: resource youtube#videoListResponse not found
    at /home/myuser/mycleannodejsapp/node_modules/simple-youtube-api/src/Request.js:35:68
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async PlayCommand.run (/home/myuser/mycleannodejsapp/commands/music/play.js:162:27)
    at async CommandoMessage.run (/home/myuser/mycleannodejsapp/node_modules/discord.js-commando/src/extensions/message.js:235:20)
    at async CommandDispatcher.handleMessage (/home/myuser/mycleannodejsapp/node_modules/discord.js-commando/src/dispatcher.js:143:19)
```

**Comment by Bacon-Fixation** [comment]
I get the same error with that playlist on all systems, because of the deleted video
```
[ "Bacon's Bot Testing Grounds" ] Connected!
Error: resource youtube#videoListResponse not found
at /Master-Bot/node_modules/simple-youtube-api/src/Request.js:35:68
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async PlayCommand.run (/Master-Bot/commands/music/play.js:162:27)
at async CommandoMessage.run (/Master-Bot/node_modules/discord.js-commando/src/extensions/message.js:235:20)
at async CommandDispatcher.handleMessage (/Master-Bot/node_modules/discord.js-commando/src/dispatcher.js:143:19)
```

i will look into a possible solution but i think galnir mentioned somewhere that they may be working on the play commands and i don't want to make it difficult for galnir

Much Love
-Bacon

**Comment by x7s** [comment]
OMG i cant beleve it this playlist is mine and when i delete the song whitch missing from that playlist everythink work normal now

**Comment by galnir** [comment]
Yeah, I need to fix it. I'll keep this issue open until then

**Comment by galnir** [comment]
@x7s do you happen to have the url of the deleted video? I'll need a deleted video url for testing

**Comment by Bacon-Fixation** [comment]
https://www.youtube.com/watch?v=epM3eXqgoFk&list=PL75Y3okhrTLxS9FAcq4MFGu3H8nxUBVZ9&index=56

**Comment by x7s** [comment]
nope i remove the song from that playlist and work perfect now
but i found another playlist with missing song and you can tryit on it https://www.youtube.com/playlist?list=PL75Y3okhrTLw1DD8Xj4jaRV0fX-s825ee @galnir when you're done with the tests just type here at this topic to remove the deleted video from the playlist

**Comment by galnir** [comment]
c303594 should solve it, let me know if it doesn't

**Comment by x7s** [comment]
At this point it works perfectly, if I encounter problems again I will write
Off topic: If it's not impudent of me, will you accept the invitation I sent you to take a quick look?

**Comment by galnir** [comment]
> At this point it works perfectly, if I encounter problems again I will write
> Off topic: If it's not impudent of me, will you accept the invitation I sent you to take a quick look @galnir ?

I barely have time to review this repo, so maybe another time :/
