### ISSUE TITLE
Ban.js

### ISSUE THREAD

**Issue by PRITu-v2** [galnir/Master-Bot#410]
**Hey Bro Please Fix ``Ban`` Command. It's Not Working Properly**

**Comment by Bacon-Fixation** [comment]
I need more info for bugs, please fill out the template

Ban Works
![image](https://user-images.githubusercontent.com/12632936/104324941-ad63b400-54ad-11eb-97ce-d21ea3fcacc1.png)

Much Love
-Bacon

**Comment by galnir** [comment]
It's working properly. If you still encounter it open a new issue and **fill the template**
