### ISSUE TITLE
Music Trivia only plays one song

### ISSUE THREAD

**Issue by danflix** [galnir/Master-Bot#42]
When starting a music trivia the bot only plays one song, after it either hitting the 30 second timeout or the correct answer is given the bot doesn't play a second song.

I've tried running !end-trivia but this also does nothing. Running !music-trivia again just says one is already running.

**Comment by galnir** [comment]
Latest discordjs update broke the command, I'm working on a fix rn

**Comment by galnir** [comment]
Fixed in 8d41ccf0d696ce1aef4e8568650fb07c0ea220d8
Pull the new changes
