### ISSUE TITLE
Cannot read property '0' of undefined (music-trivia.js)

### ISSUE THREAD

**Issue by Jriskamm** [galnir/Master-Bot#422]
<img width="775" alt="Screenshot (1)" src="https://user-images.githubusercontent.com/69320092/105625449-6dfd7600-5e64-11eb-8b2d-881261d2680b.png">

It shows the error in the terminal when /music-trivia is ongoing halfway.

Hosted in on VPS, windows

**Comment by galnir** [comment]
@Bacon-Fixation Does it happen to you? IIRC you test the bot on multiple instances

**Comment by Bacon-Fixation** [comment]
I didn't come across this error when I was testing

Much Love
-Bacon

**Comment by Jriskamm** [comment]
> I didn't come across this error when I was testing
> 
> Much Love
> -Bacon

not sure too, i was using it halfway til the error pops out, this error doesnt show up commonly

**Comment by galnir** [comment]
bb4f2d1 should fix this, let me know if it doesn't
