### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by danflix** [galnir/Master-Bot#43]
Hey,

It'd be great to have the following features added to the music-trivia if at all possible:

- [x] When a song isn't guessed correctly it says the artist and song name in chat.
- [x] Show a leader-board of the top 5 people from the quiz instead of just the winner.
- [ ] After starting a trivia I'd like it to play a preset sound file to give a countdown (i can get the file)

Many thanks

**Comment by galnir** [comment]
I pushed features 1 and 2. 3 will be worked on in the future

**Comment by Burday** [comment]
I would suggest a command with which you can add songs to the trivia list without hardcoding it in the json.

**Comment by FirezzzZ** [comment]
then whats the use of trivia?

**Comment by Burday** [comment]
yeah, I guess so. Anyways, I have another suggestion. How about every time you play a song, the amount of times you've played it gets stored?

**Comment by galnir** [comment]
@Burday  Storing data requires a database. One of the goals is to have an easy setup process for users, and involving a database will make it harder. I'm getting messages about errors and whatnot everyday :/

**Comment by Burday** [comment]
Considering that this is a beginner project, I imagine using JSON won't be that bad. Yeah it's not the best thing to use, but for beginners its nice.

**Comment by galnir** [comment]
I'm closing this issue since I can't find a proper royalty-free audio file for request number 3. If someone has one, please send it to me :)
