### ISSUE TITLE
The bot should play only the first song it gets

### ISSUE THREAD

**Issue by AayanAsim746** [galnir/Master-Bot#432]
sorry for disturbing but can it play the first song it gets

**Comment by Bacon-Fixation** [comment]
YouTubes search isn't great and often times gathers the wrong song and is advised to have 5 results 

if you want to skip the selection use a URL instead it will play it without the need to answer the Search Message
`Iplay <youtube URL>`

Much Love
-Bacon

**Comment by AayanAsim746** [comment]
but pls change if possible

**Comment by Bacon-Fixation** [comment]
@AayanAsim746 I still don't advise it (it can get frustrating)
I still quickly made an alteration that fits your requirements [Here](https://github.com/Bacon-Fixation/Beta-Commands/)

https://github.com/Bacon-Fixation/Beta-Commands/

Much Love
-Bacon

**Comment by AayanAsim746** [comment]
tysm

**Comment by Jriskamm** [comment]
> @AayanAsim746 I still don't advise it (it can get frustrating)
> I made a quick and dirty alteration to `play.js` that fits your requirements [Here](https://github.com/Bacon-Fixation/Beta-Commands/)
> 
> https://github.com/Bacon-Fixation/Beta-Commands/
> 
> this alters lines 372 through 499 in `play.js`
> 
> Much Love
> -Bacon

does it affects usage of youtube api ket whether it's 5 search result or just 1
