### ISSUE TITLE
Twitch Announcement doesnt get called

### ISSUE THREAD

**Issue by TrueMB** [galnir/Master-Bot#437]
Hey!

I am not quite sure if it is a Bug or not even a full implemented feature. But I got the Problem at the moment, that the **Twitch Announcements doesnt get called out** in the setted up Channel. I did change some stuff, but not in the Twitch-API or Command Area.

The Channel Name is "🎥twitch" and on Discord set up as an Announcement Channel.

I found out, after I tried looking in the sqllite Database, that the channel ID **is not** the ID of the channel that I want. After trying to change that manually to the channel, the bot couldnt find the entry anymore and I needed to set it up with the commands again.
It then created a second entry in the Database. The ID kinda looks simliar to the one of the channel. Thatswhy I think it is another channel and it just couldnt find the right one.

There are no errors in the console.

Also I am not quite sure, where the scheduler checks for streams. Is that also getting called in the "twitch-announcement" command?

If you need any pictures or maybe code, please let me know!

 - OS: Bot running on Debian 10 64Bit
 - Node Version(Should be v12 atleast):  1py2.20.1
 - Are python 2.7 and Ffmpeg installed?: Python 2.7.16 and  3.7.3; ffmpeg 4.1.6-1~deb10u1
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): Root Server Provider

**Comment by Bacon-Fixation** [comment]
Make sure that you start the timer `!ta enable` I have been using this with no issue since December
`!ta enable`
![image](https://user-images.githubusercontent.com/12632936/106755051-49876380-65f3-11eb-8ade-3456c5912e8d.png)

Much Love
-Bacon

**Comment by TrueMB** [comment]
Thanks for you reply @Bacon-Fixation!

Sadly I multiple times tried checking the status and reset the Settings.
It somehow doesnt work.

![image](https://user-images.githubusercontent.com/25579052/106757803-16fc5b80-6631-11eb-99a1-4ffa7573f250.png)

I think I need to look into it myself then, if it normally works....
Do you use a normal Text Channel on Discord or an Announcement Channel for your Streams?

![image](https://user-images.githubusercontent.com/25579052/106758158-7a868900-6631-11eb-8232-b78ef4f7ef86.png)

**Comment by Bacon-Fixation** [comment]
In the Mochtroids server it's in an Announcement Channel where on my personal server it's a normal Text Channel

**Comment by TrueMB** [comment]
Okay thanks for your replys. I will try some Stuff out and would comment, if I got any news.

**Comment by Bacon-Fixation** [comment]
Double-check the roles to the Channel see if the bot can send a message to that channel if the bot dosen't have permission to send messages in that channel it will also not pop up

**Comment by TrueMB** [comment]
The Bot is an Administrator.

Tried refreshing the ClientID and Secret and now getting at least an error:

`(node:29113) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'say' of undefined
    at Timeout._onTimeout (Master-Bot/commands/guild/twitch-announcer.js:301:44)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

(node:29113) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

(node:29113) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:29113) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'game_name' of undefined
    at Timeout._onTimeout (Master-Bot/commands/guild/twitch-announcer.js:232:44)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

(node:29113) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

(node:29113) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'game_name' of undefined
    at Timeout._onTimeout (Master-Bot/commands/guild/twitch-announcer.js:232:44)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

(node:29113) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

(node:29113) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'game_name' of undefined
    at Timeout._onTimeout (Master-Bot/commands/guild/twitch-announcer.js:232:44)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

(node:29113) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
`

Line 301: await announcedChannel.message.say(DBInfo.botSay),
Line 232: currentGame = streamInfo.data[0].game_name;

there is one Line difference because of a comment that I added. Everything else is the same as here in GitHub

**Comment by TrueMB** [comment]
Ohhhhhh :D

Thanks for your help. I will try that out!

**Comment by Bacon-Fixation** [comment]
Thank you for bring this up. 

I apologize for line 300, I missed that when I was testing

but given the Error it triggered but because of my goof it errored and without a catch, again I apologize
that was on me

I did go back to fix it both the typo and the UnhandledPromiseRejectionWarnings 
![image](https://user-images.githubusercontent.com/12632936/106769868-0c2ad200-6603-11eb-9632-1e505bd15697.png)

Much Love
-Bacon

**Comment by TrueMB** [comment]
Well, the error is gone. Thanks for that!
But sadly I still dont get the notification. I will do some farther testing..

**Comment by Bacon-Fixation** [comment]
How did you get the :movie_camera: emoji in the Channel name ?
is that your addition?

Try removing the emoji from the channel name

Much Love
-Bacon

**Comment by TrueMB** [comment]
You can add UniCodes to your Channel. (f.e. https://unicode.org/emoji/charts/full-emoji-list.html)

In the Database is the correct Channel ID and name. But I could try that.

**Comment by TrueMB** [comment]
It does seem to work!
But could you also implement the unicode?

Thank you really much for your help!

**Comment by Bacon-Fixation** [comment]
i did try with a unicode in the channel name

![image](https://user-images.githubusercontent.com/12632936/106774057-59a93e00-6607-11eb-9c41-b34eb2b5498b.png)

**Comment by TrueMB** [comment]
At this point I dont know anymore xD

I removed the emoji from the channel and did the setup command once more.
Going to try that again, with the emoji

**Comment by TrueMB** [comment]
Changed it back and it worked. Maybe something was wrong with the Database after the tests that I did. D:
I will keep an eye on that.

But thank you once more for your help!

**Comment by Bacon-Fixation** [comment]
NP enjoy my friend <3

Much Love
-Bacon

**Comment by TrueMB** [comment]
Tested the Stream Announcement yesterday without problems. But today I reveived in the settings channel a message, that the announcer stopped working.

After looking the error, I got following error:

TypeError: Cannot read property '0' of undefined
    at fetchUserInfo (../Master-Bot/resources/twitch/twitch-api.js:69:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    
    
![image](https://user-images.githubusercontent.com/25579052/106870721-b7a25800-66d1-11eb-9139-cce469b2bb5c.png)

**Comment by Bacon-Fixation** [comment]
Thank you for the Heads up, I'm looking into this now

I got the same message this morning too, but in the logs mine was a HTTP code 500 which was an internal server error on twitch side
but when I went to look at the [Twitch Server Status](https://devstatus.twitch.tv/) never showed any downtime in the last 90 days

this one may take me a while to figure out(not 100% on where to look on this one)

I apologize for the inconvenience 

Much Love
-Bacon

**Comment by TrueMB** [comment]
I expected something like a downtime too. 
Gonna reenable the announcement feature and will try it out tomorrow.

Maybe the announcer didnt really care much about that error, because it seems to be still enabled.

**Comment by Bacon-Fixation** [comment]
I would run `!ta enable` to restart the check timer

I didn't want to start uncontrollably looping so all the Error messages in the Twitch Announcer Command stop the timer to prevent this near endless loop situation
