### ISSUE TITLE
Says left due to inactivity even after leave command was used

### ISSUE THREAD

**Issue by Natemo6348** [galnir/Master-Bot#438]
Not much more I can say, besides leaving a screenshot
![Screenshot_20210203-023503_Discord](https://user-images.githubusercontent.com/64607128/106720362-02847880-65c9-11eb-8304-7f3130d2c497.jpg)

**Comment by galnir** [comment]
Does it happen regularly?

**Comment by TrueMB** [comment]
I think I had this issue after doing the leave command. Fixed it like this:

![Unbenannt](https://user-images.githubusercontent.com/25579052/107147279-68685b80-694d-11eb-91e8-20792f5bdaa5.png)

**Comment by Bacon-Fixation** [comment]
this happens when the bot is in a voice channel with an empty queue and a user does a `!leave`, the inactivity timer is never stopped when a !leave` is used on an empty queue

**Comment by Natemo6348** [comment]
Ah ok that makes sense

**Comment by galnir** [comment]
> this happens when the bot is in a voice channel with an empty queue (also not playing) and a user does a `!leave`, the inactivity timer is never stopped when a `!leave` is used on an empty queue the timer will still tick down then show the message
> 
> i can replicate this by waiting till the song ends with an empty queue then run `!leave`
> after 90000 ms '💤 Left channel due to inactivity.' will appear

Weird, that shouldn't happen because of line 326 in play.js. The callback function of setTimeout won't send the 'left channel due ...' message and call the .leave() method unless the bot is present in a voice channel

**Comment by galnir** [comment]
@Bacon-Fixation I'm not able to replicate it like you did

**Comment by Bacon-Fixation** [comment]
@galnir i Apologize i forgot to mention to pause it before leave
![image](https://user-images.githubusercontent.com/12632936/107393527-860a0200-6ac0-11eb-8e3e-6588d66ba93d.png)

**Comment by Bacon-Fixation** [comment]
the bot doesn't leave the channel when `?leave` happens on a paused song

**Comment by galnir** [comment]
424bc91 should solve it (tested on 2 operating systems)
Let me know here if it doesn't solve it for you
