### ISSUE TITLE
secondary lyrics api

### ISSUE THREAD

**Issue by Princevikas** [galnir/Master-Bot#443]
**Explain your suggestion**
basically sometimes genius lyrics api couldn't able to find the song lyrics or throw random gibberish i suggest there should be a secondary musix match api too🤔

**Comment by galnir** [comment]
All other lyrics APIs cost money. Unless you want to pay, Genius is the best free option

**Comment by Princevikas** [comment]
but musixmatch gives free api for 2k calls per month 🤔🤔🤔🤔

**Comment by galnir** [comment]
> but musixmatch gives free api for 2k calls per month 🤔🤔🤔🤔

https://developer.musixmatch.com/plans 
They give you access to 30% of the song's lyrics in the free tier

**Comment by Princevikas** [comment]
oh then i guess 😅 can't do anything i suppose 😅
