### ISSUE TITLE
TypeError: Cannot read property 'end' of null

### ISSUE THREAD

**Issue by Natemo6348** [galnir/Master-Bot#447]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
Every time I try to play music I get `TypeError: Cannot read property 'end' of null` for line 76 in index.js: `newState.guild.musicData.songDispatcher.end();`

**To Reproduce**
1. Use 'play' command
2. provide any music or playlist
3. Error

**Expected behavior**
Should've played music like it used to
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...] Linux x64
 - Node Version(Should be v12 atleast): 12.18.3
 - Are python 2.7 and Ffmpeg installed?: Yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): Hosting on repl.it

**Additional context**
Didn't used to happen before, not sure why it is now

**Comment by galnir** [comment]
Does it happen all the time? That 'if' statement is entered only if a user disconnects your bot using the 'Disconnect' option

**Comment by Natemo6348** [comment]
This happens every time I try to play music now

**Comment by galnir** [comment]
> This happens every time I try to play music now

Did you change anything in play.js or index.js? That line shouldn't be executed unless you disconnect the bot manually

**Comment by Natemo6348** [comment]
I have not changed play.js and the only changes I made in index.js were add server invite, changes bot status, and adding 2 listeners for guildCreate and guildDelete on the end

**Comment by galnir** [comment]
> I have not changed play.js and the only changed I made in index.js were add server invite, changed bot status, and adding 2 listeners for guildCreate and guildDelete on the end

So did it happen out of the blue or after changing something in index.js?

**Comment by galnir** [comment]
Also mind sharing your index.js file? Drop it on gist or something. Just make sure to remove any sensitive information before(API keys etc)

**Comment by Natemo6348** [comment]
It happened out of the blue some time after I changed index.js

**Comment by galnir** [comment]
> It happened out of the blue some time after I changed index.js
> 
> https://gist.github.com/Natemo6348/1c1f16de14d9d9450d5519cb9f968588

Very odd. Can you try matching your dependencies' versions to the ones in package.json?

**Comment by Natemo6348** [comment]
Yeah, right after I get a new non rate limited youtube api key lol

**Comment by galnir** [comment]
> Yeah, right after I get a new non rate limited youtube api key lol. Just happened now btw

Integrating Lavalink will eliminate the need of a youtube api key. But it won't allow you to run the bot via repl.it
You can ask Youtube for an increased quota

**Comment by Natemo6348** [comment]
Oh, why won't I be able to run it on repl.it?

**Comment by galnir** [comment]
> Oh, why won't I be able to run it on repl.it?

You'll need to run the bot via docker, unless you can somehow run java programs there (Lavalink is jar file)

**Comment by Natemo6348** [comment]
Oh I see, well I guess I'll have to figure it out then, the quota limit is kinda annoying lol

**Comment by Natemo6348** [comment]
Idk if I should close this issue or not, because it suddenly stopped giving me error and idk if it'll happen again

**Comment by galnir** [comment]
> Idk if I should close this issue or not, because it suddenly stopped giving me error and idk if it'll happen again

It's really odd that it does throw an error, mainly because it shouldn't enter that if statement unless you disconnect the bot manually. If it happens again I'll reopen this and we'll try to figure it out

**Comment by Natemo6348** [comment]
Ok, also I looked it up, and apparently many people have been using lavalink on repl.it

**Comment by galnir** [comment]
> Ok, also I looked it up, and apparently many people have been using lavalink on repl.it

I'll look into how they do it
