### ISSUE TITLE
role information?

### ISSUE THREAD

**Issue by Natemo6348** [galnir/Master-Bot#449]
**Explain your suggestion**
Ok so I don't know if it's possible, but can you make a role info command that gets the permissions of the role and who has that role?

**Comment by Bacon-Fixation** [comment]
:D Heck Yeah, it's possible I can work on that.
I really love the idea

Much Love
-Bacon

**Comment by Natemo6348** [comment]
Ok thank you @Bacon-Fixation, main reason I thought of this is because I was given owner of a server and was trying to see who had what roles so I could adjust as needed, but every time it took forever to figure out who had what role, and then I had to figure out what every roles permissions were so that nobody could be given access to a channel when they're not supposed to have access, which also took forever XD

**Comment by Bacon-Fixation** [comment]
@Natemo6348 Let me know if #452 fits your needs 

Much Love
-Bacon

**Comment by galnir** [comment]
Merged
