### ISSUE TITLE
Playing music no works

### ISSUE THREAD

**Issue by zoranzoki21** [galnir/Master-Bot#45]
Hello,
when I use !play (youtube link), bot joins to voice channel but there isn't sound.

Bot have correct permissions on Discord server, so it shouldn't be problem. API keys are also correct.

**Comment by galnir** [comment]
Make sure you installed all requirements listed in the README(ffmpeg, python 2.7)

**Comment by zoranzoki21** [comment]
Yes, it is.

**Comment by zoranzoki21** [comment]
Hmm, I updated bot now, and when I use !play I get this error:
```
An error occurred while running the command: TypeError: Cannot read property 'isTriviaRunning' of undefined
```

**Comment by zoranzoki21** [comment]
```zoranzoki21@discord:~/KizuleBot$ node --version
v12.16.1
zoranzoki21@discord:~/KizuleBot$ npm --version
6.13.4
zoranzoki21@discord:~/KizuleBot$
```

**Comment by galnir** [comment]
Did you clone this repo or only copy the play command? If you copied only the command it will not work as intended

**Comment by zoranzoki21** [comment]
I cloned full repo, translated it into the Serbian. Other (non-music) commands works.

Information about discord-js and discord.js-commando per #14:
```
zoranzoki21@discord:~/KizuleBot$ npm view discord.js version
12.0.2
zoranzoki21@discord:~/KizuleBot$ npm view discord.js-commando version
0.10.0
zoranzoki21@discord:~/KizuleBot$
```

**Comment by galnir** [comment]
What error are you getting in the console? If you didn't touch index.js or atleast didn't change any variable names, there is no reason you would get that error as far as I know

**Comment by zoranzoki21** [comment]
In console I get nothing. There is just:
```
zoranzoki21@discord:~/KizuleBot$ node .
Ready!
```

Uh, I removed:
```
Structures.extend('Guild', Guild => {
  class MusicGuild extends Guild {
    constructor(client, data) {
      super(client, data);
      this.musicData = {
        queue: [],
        isPlaying: false,
        nowPlaying: null,
        songDispatcher: null,
        volume: 1
      };
      this.triviaData = {
        isTriviaRunning: false,
        wasTriviaEndCalled: false,
        triviaQueue: [],
        triviaScore: new Map()
      };
    }
  }
  return MusicGuild;
});
```
from index.js, and I added it back now, sorry.

But I still have problem with playing sound (what I reported :) ).

**Comment by galnir** [comment]
Glad we resolved that. About the sound, if you are getting an error, paste it here. Make sure again that python and ffmpeg are correctly installed, and run `npm i node-opus`, make sure the build doesn't fail

**Comment by zoranzoki21** [comment]
Python 2.7 and ffmpeg are correctly, installed, `npm i node-opus` done.

**Comment by galnir** [comment]
when installing node-opus, did it run a build?

**Comment by zoranzoki21** [comment]
Yes

**Comment by galnir** [comment]
If you have a bad network(or slow speed) that may also cause it. I run the bot on 2 machines with different operating systems and it works flawlessly(good network on both).
Are you running it on your pc?

**Comment by zoranzoki21** [comment]
No, I run bot on VPS.

**Comment by galnir** [comment]
How did you install ffmpeg?

**Comment by zoranzoki21** [comment]
Debian 10, via apt.

**Comment by galnir** [comment]
We went through everything that could be done.. 
1. make sure python 2.7 and ffmpeg are installed
2. make sure node-opus build doesn't fail
3. check network connection(you said you run the bot on a VPS so its got to have a good connection)

If you're not getting any console error I can't go beyond these 3 solutions :/ 
The problem is on your end somewhere

**Comment by zoranzoki21** [comment]
Ok, thanks!
