### ISSUE TITLE
Could not locate the binding files

### ISSUE THREAD

**Issue by Jaccosf** [galnir/Master-Bot#451]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
When I try to start the bot, I will get the error: Could not locate the binding files

**To Reproduce**
1. node index.js
2. error: Could not locare the binding files

**Desktop (please complete the following information):**
 - OS: Windows
 - Latest Python version
 - Latest git version

Full error:
C:\Users\Ad\Documents\Music\node_modules\bindings\bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → C:\Users\Ad\Documents\Music\node_modules\better-sqlite3\build\better_sqlite3.node
 → C:\Users\Ad\Documents\Music\node_modules\better-sqlite3\build\Debug\better_sqlite3.node
 → C:\Users\Ad\Documents\Music\node_modules\better-sqlite3\build\Release\better_sqlite3.node
 → C:\Users\Ad\Documents\Music\node_modules\better-sqlite3\out\Debug\better_sqlite3.node
 → C:\Users\Ad\Documents\Music\node_modules\better-sqlite3\Debug\better_sqlite3.node
 → C:\Users\Ad\Documents\Music\node_modules\better-sqlite3\out\Release\better_sqlite3.node
 → C:\Users\Ad\Documents\Music\node_modules\better-sqlite3\Release\better_sqlite3.node
 → C:\Users\Ad\Documents\Music\node_modules\better-sqlite3\build\default\better_sqlite3.node
 → C:\Users\Ad\Documents\Music\node_modules\better-sqlite3\compiled\12.18.3\win32\x64\better_sqlite3.node
 → C:\Users\Ad\Documents\Music\node_modules\better-sqlite3\addon-build\release\install-root\better_sqlite3.node
 → C:\Users\Ad\Documents\Music\node_modules\better-sqlite3\addon-build\debug\install-root\better_sqlite3.node
 → C:\Users\Ad\Documents\Music\node_modules\better-sqlite3\addon-build\default\install-root\better_sqlite3.node
 → C:\Users\Ad\Documents\Music\node_modules\better-sqlite3\lib\binding\node-v72-win32-x64\better_sqlite3.node
    at bindings (C:\Users\Ad\Documents\Music\node_modules\←[4mbindings←[24m\bindings.js:126:9)
    at Object.<anonymous> (C:\Users\Ad\Documents\Music\node_modules\←[4mbetter-sqlite3←[24m\lib\database.js:9:24)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1137:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:985:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:878:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1025:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
    at Object.<anonymous> (C:\Users\Ad\Documents\Music\node_modules\←[4mbetter-sqlite3←[24m\lib\index.js:2:18)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1137:30)←[39m {
  tries: [
    ←[32m'C:\\Users\\Ad\\Documents\\Music\\node_modules\\better-sqlite3\\build\\better_sqlite3.node'←[39m,
    ←[32m'C:\\Users\\Ad\\Documents\\Music\\node_modules\\better-sqlite3\\build\\Debug\\better_sqlite3.node'←[39m,
    ←[32m'C:\\Users\\Ad\\Documents\\Music\\node_modules\\better-sqlite3\\build\\Release\\better_sqlite3.node'←[39m,
    ←[32m'C:\\Users\\Ad\\Documents\\Music\\node_modules\\better-sqlite3\\out\\Debug\\better_sqlite3.node'←[39m,
    ←[32m'C:\\Users\\Ad\\Documents\\Music\\node_modules\\better-sqlite3\\Debug\\better_sqlite3.node'←[39m,
    ←[32m'C:\\Users\\Ad\\Documents\\Music\\node_modules\\better-sqlite3\\out\\Release\\better_sqlite3.node'←[39m,
    ←[32m'C:\\Users\\Ad\\Documents\\Music\\node_modules\\better-sqlite3\\Release\\better_sqlite3.node'←[39m,
    ←[32m'C:\\Users\\Ad\\Documents\\Music\\node_modules\\better-sqlite3\\build\\default\\better_sqlite3.node'←[39m,
    ←[32m'C:\\Users\\Ad\\Documents\\Music\\node_modules\\better-sqlite3\\compiled\\12.18.3\\win32\\x64\\better_sqlite3.node'←[39m,
    ←[32m'C:\\Users\\Ad\\Documents\\Music\\node_modules\\better-sqlite3\\addon-build\\release\\install-root\\better_sqlite3.node'←[39m,
    ←[32m'C:\\Users\\Ad\\Documents\\Music\\node_modules\\better-sqlite3\\addon-build\\debug\\install-root\\better_sqlite3.node'←[39m,
    ←[32m'C:\\Users\\Ad\\Documents\\Music\\node_modules\\better-sqlite3\\addon-build\\default\\install-root\\better_sqlite3.node'←[39m,
    ←[32m'C:\\Users\\Ad\\Documents\\Music\\node_modules\\better-sqlite3\\lib\\binding\\node-v72-win32-x64\\better_sqlite3.node'←[39m
  ]
}

**Comment by Natemo6348** [comment]
try running `npm rebuild better-sqlite3` as I originally said in #442

**Comment by Bacon-Fixation** [comment]
have you run the `npm install` first?
 And did it have any errors during install?

"* Latest Python version" and "* Latest git version"isn't much help
Python should be 2.7.x as the [README.md](https://github.com/galnir/Master-Bot#setup) states 

Much Love
-Bacon

**Comment by Jaccosf** [comment]
> npm rebuild better-sqlite3

This worked, tysm!
