### ISSUE TITLE
facing problem in advice.js

### ISSUE THREAD

**Issue by AayanAsim746** [galnir/Master-Bot#453]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**

**To Reproduce**
1. Use 'x' command
2. provide 'y' argument

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...]
 - Node Version(Should be v12 atleast): 
 - Are python 2.7 and Ffmpeg installed?:
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...):

**Additional context**

**Comment by AayanAsim746** [comment]
Fontconfig error: Cannot load default config file
(node:805) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
embed.author.url: Scheme "adviceslip.com" is not supported. Scheme must be one of ('http', 'https').
    at RequestHandler.execute (/home/runner/Alisha/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/home/runner/Alisha/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
(node:805) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:805) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 the error

**Comment by AayanAsim746** [comment]
nvm i got the error

**Comment by galnir** [comment]
Thanks for letting me know about the error, fixed in 06895ed
