### ISSUE TITLE
Welcome message not showing

### ISSUE THREAD

**Issue by Jaccosf** [galnir/Master-Bot#455]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
When someone joins the server, no welcome message will be shown.

**To Reproduce**
1. I have already done !welcome enable and !welcome yes
2. I tested it with !show-welcome-message (that worked)
3. I have set the welcome message to a channel, it says it is saved.
4. But then when someone joins nothing will happen.

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version(Should be v12 atleast): 
 - Are python 2.7 and Ffmpeg installed?:
 - How are you hosting the bot: Locally

**Comment by galnir** [comment]
@Bacon-Fixation Do you have any idea?

**Comment by Bacon-Fixation** [comment]
i can test for it once i have stable power here, we have been in a black-out for the last few days with no water, i apologize for the inconvenience Texas was not ready for snow

**Comment by Jaccosf** [comment]
> i can test for it once i have stable power here, we have been in a black-out for the last few days with no water, i apologize for the inconvenience Texas was not ready for snow

No problem man, I can imagine that!

**Comment by Bacon-Fixation** [comment]
Found this searching around from https://stackoverflow.com/questions/64618047/guild-member-add-does-not-work-discordjs
"
Discord made some changes a few days ago. The bot is not sending the welcome message because it never gets the guildMemberAdd event. From now on to get these types of events you will have to turn the intents on in the dev portal. After doing this your code will start working again."
![image](https://user-images.githubusercontent.com/12632936/108262688-dde0e280-712a-11eb-8113-512db7526bf9.png)

**Comment by Jaccosf** [comment]
Hi, I have tried that and copied the typos. Unfortunately this is not a solution already.

**Comment by Bacon-Fixation** [comment]
Have you enabled the above settings in your discord [Developer console](https://discordapp.com/developers/applications/)?

i mentioned in the pr it wasn't a fix for this :D

**Comment by Jaccosf** [comment]
Yes yes I know, I was talking about the screen you sent. I'm reinstalling the bot completely to check now.

**Comment by Jaccosf** [comment]
Didn't work either.

**Comment by Bacon-Fixation** [comment]
I mean no disrespect,
I can't seem to replicate this I've tried on my Raspi pi and my Windows system

I had a friend join a few times (message sent to a text channel called  `#bot-errors`, we also tried direct-message)
![image](https://user-images.githubusercontent.com/12632936/108275379-dece4000-713b-11eb-9011-e67ca8aedf59.png)

the `!show-welcome-message` command emits the `guildMemberAdd` event (the same event when a new user joins a guild) if that is displaying a message 

I would double-check your Dev console for the Intent settings and make sure to save the settings and restart your bot 

Much Love
-Bacon

**Comment by Jaccosf** [comment]
After trying a couple of time and trying to look closer in the code, I have found out that the issue originates when I change the message destination with the !welcome-settings command.

**Comment by Jaccosf** [comment]
I found it out! I forgot that every time you change the destination/url/text you need to enable the welcome message again.
Thank you very much Bacon!

**Comment by Jaccosf** [comment]
Apparently there is a problem with my hosting and this combination. When I host it from the console from my PC, there won't occur any error, but I wat to host it through Heroku. I don't know if you do know where this problem comes from?

**Comment by Bacon-Fixation** [comment]
Heroku restarts and wipes the DB every 24 hours and, not really a good choice for this feature 
I would recommend a local host if possible.

Systems used to test Welcome Messages
- Local
Windows 10 (recommended)
Debian 10 (recommended)
raspberry OS 10 (arm7 and arm64  'My Main Host')
 
- Web
Heroku(Cons - 24 hour DB wipe and restart)
Glitch.com(Cons - Have to wake it up before use)
repl.it(Cons- Keys are open to public unless you pay)

Much Love 
- Bacon

**Comment by Jaccosf** [comment]
Mmhm, I will try to host it on my Raspberry Pi (Debian) tomorrow!

**Comment by Bacon-Fixation** [comment]
im not sure if you saw this in the Wiki section for Running on a Pi here is the link just in case
https://github.com/galnir/Master-Bot/wiki/Running-the-bot-on-a-Raspberry-Pi

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Just wanted to get back with you and see if you were still having issues with the Welcome message ?

Much Love
-Bacon

**Comment by Jaccosf** [comment]
Thanks for asking! Unfortunately I was not able to work with my Raspberry Pi this week, I'll close this issue and if it doesn't work, I'll reopen it. For now I know enough! 👍
