### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LilDerp-IsBetter** [galnir/Master-Bot#458]
So I noticed you integrated playlists into the bot and was wondering how users could play the lists they have made. Is this possible with where the bot is or would you be able to point me in the right direction

Thanks in advance

**Comment by galnir** [comment]
!play playlistname
It will ask you if you want to search 'playlistname' on youtube or play your saved playlist(named 'playlistname')

**Comment by LilDerp-IsBetter** [comment]
Thank you.
