### ISSUE TITLE
hello, not sure if it's consider a bug but i wanted to add reactions for a command

### ISSUE THREAD

**Issue by Jriskamm** [galnir/Master-Bot#459]
so i add
return message.react('👋') for leave command and an error pops out, but the command is working
<img width="106" alt="Screenshot (28)" src="https://user-images.githubusercontent.com/69320092/108744506-f7dc5400-7574-11eb-8d79-071bc95ffa90.png">
<img width="470" alt="Screenshot (29)" src="https://user-images.githubusercontent.com/69320092/108744514-f9a61780-7574-11eb-8df3-d8ddd81e6d0d.png">

**Comment by galnir** [comment]
message.react [returns a promise](https://discord.js.org/#/docs/main/master/class/Message?scrollTo=react).
Remove the 'return' keyword

**Comment by Jriskamm** [comment]
> message.react [returns a promise](https://discord.js.org/#/docs/main/master/class/Message?scrollTo=react).
> Remove the 'return' keyword

oh i got it. thankya so much
