### ISSUE TITLE
Playlist

### ISSUE THREAD

**Issue by LilDerp-IsBetter** [galnir/Master-Bot#461]
The ability to change the name of playlists.

**Comment by Natemo6348** [comment]
This is also something I want, I can try to do it although I don't know if I can lol.

**Comment by Bacon-Fixation** [comment]
i believe in you Natemo :D

Much Love
-Bacon

**Comment by Natemo6348** [comment]
well, i tried to do it and couldn't figure it out, not very good with databases lol
