### ISSUE TITLE
Music Quiz Vote Skip

### ISSUE THREAD

**Issue by TrueMB** [galnir/Master-Bot#466]
Hello!

I would appriciate, if you guys could add an Song Skip Vote in the Music Quiz.
Atm you cant skip the Songs and get the message, to stop the Quiz.

It would be awesome that instead there is a message "Do you wanna Skip?" ✔️ ❎ 
and all the Music Quiz participents can vote. Since I think the Emote will be more difficult to handle, the command would be enough.
2x People wanna skip -> both do the skip command.

In the config f.e. is then a needed Percentage. 
3x Player Playing -> Config needed Vote Percentage 60% -> After the second Player also votes for skip, the Song gets skipped and the next one starts.
If 2x dont wanna skip or the song rans out, it starts again for the next song with nobody voted.

**Comment by galnir** [comment]
Implemented in 1e41e4a 
Lemme know if you encounter bugs
