### ISSUE TITLE
Include attachments in “Say.js” command

### ISSUE THREAD

**Issue by muhitrhn** [galnir/Master-Bot#468]
I was hoping if you guys could add the image including functionality to the “Say.js” command. 

It would be great if the replies with the say text and attached image!
Thank you.

**Comment by muhitrhn** [comment]
Anyone?
@Bacon-Fixation ?

**Comment by galnir** [comment]
Meaning the ability to pass an image and have the bot send it? Or do you mean the bot will send the text in a canvas?

**Comment by muhitrhn** [comment]
Yes, the first one

> the ability to pass an image and have the bot send it

**Comment by muhitrhn** [comment]
Can you help with that?

**Comment by ThatGuyJacobee** [comment]
var embed = new MessageEmbed()
      .setTitle(`Just wanted to say...`)
      .setColor('#888888')
      .setDescription(text)
      .setTimestamp()
      .setFooter(
        `${message.member.displayName}, made me say it!`,
        message.author.displayAvatarURL()
      );

Add `.setImage('URL LINK')` to anywhere within the message embed.

**Comment by muhitrhn** [comment]
> var embed = new MessageEmbed()
> .setTitle(`Just wanted to say...`)
> .setColor('#888888')
> .setDescription(text)
> .setTimestamp()
> .setFooter(
> `${message.member.displayName}, made me say it!`,
> message.author.displayAvatarURL()
> );
> 
> Add `.setImage('URL LINK')` to anywhere within the message embed.

Not this, i wanted to send an image and the bot will instantly send it back. No local image. Just like @galnir said.

**Comment by muhitrhn** [comment]
Something like this (doesn’t work)! 
`run(message, { text }) {
    let image = message.attachments.array().length == 0 ? null:message.attachments.first().url;
    var embed = new MessageEmbed()
      .setColor('#888888')
      .setDescription(text)
      .setImage(image)
      .setTimestamp();
    message.channel.send(embed);
  } `

**Comment by galnir** [comment]
> Something like this (doesn’t work)! @galnir
> 
> > run(message, { text }) {
> > let image = message.attachments.array().length == 0 ? null:message.attachments.first().url;
> > var embed = new MessageEmbed()
> > .setColor('#888888')
> > .setDescription(text)
> > .setImage(image)
> > .setTimestamp();
> > message.channel.send(embed);
> > }

I get the point, but isn't that a redundant feature? The image you attach will appear in chat and then the bot will send it, making it appear twice in total

**Comment by muhitrhn** [comment]
> > Something like this (doesn’t work)! @galnir
> > > run(message, { text }) {
> > > let image = message.attachments.array().length == 0 ? null:message.attachments.first().url;
> > > var embed = new MessageEmbed()
> > > .setColor('#888888')
> > > .setDescription(text)
> > > .setImage(image)
> > > .setTimestamp();
> > > message.channel.send(embed);
> > > }
> 
> I get the point, but isn't that a redundant feature? The image you attach will appear in chat and then the bot will send it, making it appear twice in total

Yes it is, but i want the image published as the bot, i will delete my message including the image afterwards.

**Comment by muhitrhn** [comment]
It will be better if the bot deletes my response messages automatically after triggering “say” command.

**Comment by muhitrhn** [comment]
Please let me know if you could help.

**Comment by muhitrhn** [comment]
This code worked for once when i pushed the changes of the codes. But after that, it is showing error in the console log `(node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8) `

> run(message, { text, attachments }) {
    var lattachment = message.attachments.first();
    if (
    var embed = new MessageEmbed()
      .setColor('#888888')
      .setDescription(text)
      .attachFiles(lattachment)
      .setTimestamp();
    message.channel.send(embed, lattachment);
  }

**Comment by muhitrhn** [comment]
Okay i have achieved the functionality! The only thing i need help with is, i want the bot to automatically delete the commands i sent. Please see the screenshot attached. Can you help me with auto deleting these messages by the bot after completion of the command?
![76060A05-EAF3-4B6C-947E-061547589663](https://user-images.githubusercontent.com/36473811/111794587-964ba300-88f0-11eb-8daa-62ff6420f91e.jpeg)

**Comment by galnir** [comment]
> Okay i have achieved the functionality! The only thing i need help with is, i want the bot to automatically delete the commands i sent. Please see the screenshot attached. Can you help me with auto deleting these messages by the bot after completion of the command? @galnir
> ![76060A05-EAF3-4B6C-947E-061547589663](https://user-images.githubusercontent.com/36473811/111794587-964ba300-88f0-11eb-8daa-62ff6420f91e.jpeg)

Take a look at say.js as it is now. I pushed a commit today that deletes the user's message after the execution of the command

**Comment by muhitrhn** [comment]
> > Okay i have achieved the functionality! The only thing i need help with is, i want the bot to automatically delete the commands i sent. Please see the screenshot attached. Can you help me with auto deleting these messages by the bot after completion of the command? @galnir
> > ![76060A05-EAF3-4B6C-947E-061547589663](https://user-images.githubusercontent.com/36473811/111794587-964ba300-88f0-11eb-8daa-62ff6420f91e.jpeg)
> 
> Take a look at say.js as it is now. I pushed a commit today that deletes the user's message after the execution of the command

Thank you. It worked!

**Comment by muhitrhn** [comment]
I had to reopen this issue, can you please tell me a way to include the attachment in the embed?

**Comment by Bacon-Fixation** [comment]
.attachFiles(lattachment) in your message embed

**Comment by muhitrhn** [comment]
I tried that, but seems it didn’t work. Besides, seems the text is going under the image now (please check attached image). Here is my code -
`run(message, { text }) {
      if ( message.attachments.size > 0 ) {
        var lattachment = message.attachments.first(); 
      }
    var embed = new MessageEmbed()
      .setColor('#888888')
      .setDescription(text)
      .attachFiles(lattachment)
      .setTimestamp();
    message.channel.send(embed).then(
        () => message.delete().catch(e => console.error(e)) // nested promise
      )
      .catch(e => console.error(e));
    return;
  } `
![C177152C-9308-4DF4-BA9B-D48D0A3AFBCA](https://user-images.githubusercontent.com/36473811/111832814-71b8f080-891b-11eb-9a31-ab4b56bc7d83.jpeg)

**Comment by Natemo6348** [comment]
If you really want the text to be above the image, you could do setTitle instead of setDescription

**Comment by muhitrhn** [comment]
> If you really want the text to be above the image, you could do setTitle instead of setDescription

I tried that, doesn’t change anything.

**Comment by Bacon-Fixation** [comment]
sorry i was away,  but I'm back 
here you go

![image](https://user-images.githubusercontent.com/12632936/111838934-072a9500-88c8-11eb-9c48-9086f2584fb8.png)


```
  run(message, { text }) {
    const embed = new MessageEmbed()
      .setColor('#888888')
      .setDescription(text)
      .setTimestamp();

    if (message.attachments.size > 0) {
      //const attachmentString =
      const attachment = message.attachments.first().attachment;
      embed.setImage(attachment);
    }

    message.channel
      .send(embed)
      .then(
        () => message.delete().catch(e => console.error(e)) // nested promise
      )
      .catch(e => console.error(e));
    return;
  }
```

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
heads up 

no need for the var it doesn't change you can add the image after
`lattachment` was pointed to a map and not to a URL path
but you had it close my friend

**Comment by muhitrhn** [comment]
> heads up
> 
> no need for the `var` it doesn't change, you can add the image after with `embed.setImage()`
> `attachment` was pointed to a map and not to a URL path
> but you had it close my friend
> 
> Much Love
> -Bacon

Aah, missed it for for a bit, was so close. Thank you @Bacon-Fixation for helping getting it done. And once again, it’s really good to see you again!

**Comment by muhitrhn** [comment]
See you on that issue!
