### ISSUE TITLE
ECONNRESET error when trying to play certain youtube videos

### ISSUE THREAD

**Issue by aflamant** [galnir/Master-Bot#47]
I'm getting this error when trying to play some songs :

    Error: read ECONNRESET
        at TLSWrap.onStreamRead (internal/stream_base_commons.js:201:27) {
      errno: 'ECONNRESET',
      code: 'ECONNRESET',
      syscall: 'read'
    }

## How to reproduce

I'm getting the error when trying this command:

    !play https://www.youtube.com/watch?v=Y5tjtUFL0j4

## Environment informations

    $ node -v
    v12.14.0
    $ npm -v
    6.14.4
    $ python2.7 --version
    Python 2.7.16
    $ ffmpeg -version                                                                                                                                                                               
    ffmpeg version 4.1.4-1~deb10u1 Copyright (c) 2000-2019 the FFmpeg developers

**Comment by galnir** [comment]
Have you tried updating all the dependencies in package.json? I run the bot both on debian 9 and windows and it works with that song

**Comment by gusdiva** [comment]
hey @galnir  why when i request play the music, the bot still exit the voice channel after not play any song?

**Comment by galnir** [comment]
@gusdiva Make sure you installed **all** the dependencies and other requirements(python 2.7, ffmpeg) correctly. If you did, there is no reason it wouldn't work

**Comment by gusdiva** [comment]
i already installed python 2.7 and ffmpeg, but still didn't work

**Comment by galnir** [comment]
```npm install node-opus ytdl-core``` again and check if the node-opus build fails

**Comment by gusdiva** [comment]
Failed at the node-opus@0.3.3 install script >> i got this when i install the node-opus

**Comment by galnir** [comment]
@gusdiva That's the issue, because the node-opus package build fails, you can't hear any sound from the bot. I recommend you do search the error on Google with your operating system and try the suggested solutions. After you fix that issue and install node-opus(and make sure the build doesn't fail), you'll hear the bot

**Comment by aflamant** [comment]
Yes I have cloned the master branch and ran `npm install`. I'm running it on both debian 10 and raspbian and getting this error. Maybe it comes from my network, I will try to investigate that.

What seems weird to me is that it works perfectly fine for some youtube videos but not for others.

**Comment by aflamant** [comment]
Ok, so I just checked by using another network to connect the bot and it works, so the error must be coming from my network, sorry for bothering you, I'm closing the issue.
