### ISSUE TITLE
:mag: :notes: Searching for lyrics! @ΜΔĐ乛TeamIG, :x: No song has been found for this query

### ISSUE THREAD

**Issue by swayam-crypto** [galnir/Master-Bot#476]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**

**To Reproduce**
1. Use 'x' command
2. provide 'y' argument

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...]
 - Node Version(Should be v12 atleast): 
 - Is python 2.7 installed?:
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...):

**Additional context**

**Comment by swayam-crypto** [comment]
![image](https://user-images.githubusercontent.com/80890491/111868546-960ae080-89a0-11eb-867f-14bd7b2d3d01.png)

**Comment by Bacon-Fixation** [comment]
Make sure you are clicking on the Generate Access Token Link and using the key that pops up and not the Client Secret
![image](https://user-images.githubusercontent.com/12632936/111872024-2e7e7200-895b-11eb-9c7b-497e6a771aeb.png)


I personally think there Webpage is a bit confusing to me

Much Love
-Bacon

**Comment by galnir** [comment]
Make sure you generate the correct token from the Genius API

**Comment by galnir** [comment]
@swayam-crypto Again, the issue is most likely that you didn't generate a correct token. If the issue persists after generating the correct token, comment here and I'll reopen this issue
