### ISSUE TITLE
trouble when installing dependencies

### ISSUE THREAD

**Issue by amirshah2935** [galnir/Master-Bot#483]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
Following your readme files, when installing the depencencies, with "npm i" or "npm install" will return error 

**To Reproduce**
1. from index.js screen, open console and type "npm i" or "npm install"
2. console will return a long error and warning with prior form looking at it i think is somehting with discord.js-commando issue

**Expected behavior**
if not mistaken from your readme and forum, it should be just straight away works after clone your code.

**Screenshots**
![image](https://user-images.githubusercontent.com/38003845/112719815-d2f14d00-8f35-11eb-993b-b72a270ab38e.png)
![image](https://user-images.githubusercontent.com/38003845/112719834-f1574880-8f35-11eb-972d-b69cf57c8f3e.png)
![image](https://user-images.githubusercontent.com/38003845/112719843-016f2800-8f36-11eb-8f80-6e269ccf8b8d.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Node Version(Should be v12 atleast): v14.16.0
 - Is python 2.7 installed?: Yes latest vers3.9.2
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): i believe is just locally.

**Additional context**

**Comment by galnir** [comment]
You didn't install Git

**Comment by amirshah2935** [comment]
owh thanks it seems my visual studio code is not integrate with git, where i have install the git, but i need to use git cmd only can run the npm install, but after run npm install i t seems others error pops out.

1. TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.
2. UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body

**Comment by galnir** [comment]
I think you checked the 'PRESENCE INTENT' section under 'Privileged Gateway Intents' in the 'Bot' page in your Discord Developer Portal. You don't need intents unless your bot is active on more than 100 servers

**Comment by amirshah2935** [comment]
yup i notice that..so the bots is working, but im not ablet o deploy under heroku..not sure why..but whenever i online the bot, i got this error, but it still online and works..im not sure why it says my user_id xxxx is not snowflake, cannot find any snowflake command in your code also..if you can help when not busy..if not its okay..as long as its wokring for my small server..really appreciate your code..
![image](https://user-images.githubusercontent.com/38003845/112935554-93ee1200-9156-11eb-9b8f-5c56ca80e9e9.png)

**Comment by galnir** [comment]
Did you change anything in the code? I'm not getting these errors on my instances

**Comment by amirshah2935** [comment]
in my current code yes..i did change the msg replies to my language to make it fun..

but this error i receive is from your fresh download zip from your github here...

my step as below:
1. Download
2. unzip download file
3. add config.json
4. run npm install
5. then run node .

attached also whats in 
![image](https://user-images.githubusercontent.com/38003845/112966099-7cc21b00-917c-11eb-88d7-60280bc562b6.png)
my config .json file 
![image](https://user-images.githubusercontent.com/38003845/112965760-23f28280-917c-11eb-99cb-5f7e8d416cc1.png)

**Comment by galnir** [comment]
The error says you changed something to 'YoshiyukiAdly' instead of putting your user ID

**Comment by amirshah2935** [comment]
dang...ahhhh...im so really much sorry...my bad..i tot that was my discord id, usually the the id means username. seriously my bad. anyway no error now once i change that..ill close this will be looking to deploy this code with heroku.. thanks so much for your wondewrfull codes and help..

add me in discord if you want, YoshiyukiAdly#9405. cheers.
