### ISSUE TITLE
Remove dm

### ISSUE THREAD

**Issue by AlexCiurar** [galnir/Master-Bot#484]
Hi ! I try to remove bot send dm , not work ! what to do ?

**Comment by AlexCiurar** [comment]
> What DM? The 'help' command?

Hi ! Yes

**Comment by Bacon-Fixation** [comment]
Check out #120 & #478 

Much Love
-Bacon

**Comment by AlexCiurar** [comment]
> Check out #120 & #478
> 
> Much Love
> -Bacon

I read but again not working :(

**Comment by galnir** [comment]
> > Check out #120 & #478
> > Much Love
> > -Bacon
> 
> I read but again not working :(

#120 is how to edit or disable 'help'
#478 is how to edit it so the bot sends it in the channel

**Comment by AlexCiurar** [comment]
> > > Check out #120 & #478
> > > Much Love
> > > -Bacon
> > 
> > 
> > I read but again not working :(
> 
> #120 is how to edit or disable 'help'
> #478 is how to edit it so the bot sends it in the channel

Hi , i disable 'help' , in guild i  create other help.js.. i try to edit but not working :(  BTW : i'm new in programming .. can you give me your discord ? i want to share my code and i need more explanations.

**Comment by galnir** [comment]
> > > > Check out #120 & #478
> > > > Much Love
> > > > -Bacon
> > > 
> > > 
> > > I read but again not working :(
> > 
> > 
> > #120 is how to edit or disable 'help'
> > #478 is how to edit it so the bot sends it in the channel
> 
> Hi , i disable 'help' , in guild i create other help.js.. i try to edit but not working :( BTW : i'm new in programming .. can you give me your discord ? i want to share my code and i need more explanations.

Hey, issues are meant for addressing bugs. The issues we linked(120 and 478) are the solutions to what you're trying to do. If you're new to JavaScript and everything related to hosting a bot, I recommend you to read or watch guides and then try again when you have more knowledge
