### ISSUE TITLE
MasterBot music not working

### ISSUE THREAD

**Issue by MrShehabTito** [galnir/Master-Bot#489]
hey, when I try to play any music the bot give me a error "I have no permission to join your channel!" [https://ibb.co/ScxxQ3N](url) and I'm giving the bot full permissions, everything is working in the bot but only this thing is not working I tried everything and still the bot not working

**Comment by Bacon-Fixation** [comment]
check out #317,#407 

Much Love
-Bacon

**Comment by Jaccosf** [comment]
Hey, I am experiencing the same issue. Tried the fixes for #317 and #407 and many more, but no luck. I am hosting my bot on Windows VPS btw. Hope you guys can help me out.

**Comment by galnir** [comment]
Did everything get installed correctly? Try removing your node_modules directory and entering 'npm i' again, make sure there are no critical errors regarding the database or ytdl-core

**Comment by Jaccosf** [comment]
Only getting this warning:
npm WARN deprecated node-opus@0.3.3: This project is unmaintained. See @discordjs/opus for an alternative.

After that also did npm i node-opus, but that doesn't make any difference.

**Comment by galnir** [comment]
> Only getting this warning:
> npm WARN deprecated node-opus@0.3.3: This project is unmaintained. See @discordjs/opus for an alternative.
> 
> After that also did npm i node-opus, but that doesn't make any difference.

Please open a new issue so I can help you with your specific problem

**Comment by galnir** [comment]
I'm closing this until @MrShehabTito responds
