### ISSUE TITLE
Heroku Deployment Steps

### ISSUE THREAD

**Issue by Bacon-Fixation** [galnir/Master-Bot#490]
Heroku has a 24hour redeployment which means the saved database is removed and All Twitch Timers will be stopped

First on github create a private Fork of Master-Bot and add a completed config.json file to your fork
Create a File called `Procfile` and add `worker: node index.js` and add it to your fork (`Master-Bot/` with the config.json file)

Go to Heroku.com and Create a New App
![image](https://user-images.githubusercontent.com/12632936/112651369-5289f980-8e1a-11eb-9186-119675b147db.png)

Name your app and click on Create App
![image](https://user-images.githubusercontent.com/12632936/112651626-95e46800-8e1a-11eb-9b8a-7f832fe578b3.png)

Go to Deployment Method and click connect to Github, log in and find the repo you created click on connect
![image](https://user-images.githubusercontent.com/12632936/112651962-e8258900-8e1a-11eb-83e5-be7bb730d0ed.png)

scroll down to Manual Deploy section and click deploy branch
![image](https://user-images.githubusercontent.com/12632936/112652221-291d9d80-8e1b-11eb-955d-4fabeee6427b.png)

this will start the Install for the Dependencies (wait for it to complete...)
once the install is complete, go to the Resources Tab and click the pencils
![image](https://user-images.githubusercontent.com/12632936/112653813-caf1ba00-8e1c-11eb-92e0-7af3db8e44ee.png)

Disable `Web` then Enable `Worker` click confirm on both
![image](https://user-images.githubusercontent.com/12632936/112654008-f5437780-8e1c-11eb-8c25-e222d234c16e.png)

now lets see if it is running, in the top right click on more > view log
![image](https://user-images.githubusercontent.com/12632936/112654726-b104a700-8e1d-11eb-9317-a5098f753774.png)

if it is working, it should look like this
![image](https://user-images.githubusercontent.com/12632936/112654910-e3160900-8e1d-11eb-8fb2-247d299aa136.png)

Much Love
-Bacon

**Comment by galnir** [comment]
Are they doing the redeployment thing only to free users?

**Comment by Bacon-Fixation** [comment]
for Heroku a dyno can run for a max of 24 hours at a time then its restarted and anything that wasn't in the github repo at the time of Heroku deployment is deleted.

**Comment by RxNationGaming** [comment]
It dint worked because I get errors in heroku
