### ISSUE TITLE
Make say command an embed and add an argument for channel.

### ISSUE THREAD

**Issue by thetechguy-cpu** [galnir/Master-Bot#492]
**Explain your suggestion**
The bot only sends the message from say command in a regular message. It would be cool if it became an embed. It will also be cool if you could add in an argument for channel where the bot will send the message.

**Comment by Natemo6348** [comment]
The say command is an embed, make sure your code matches the code in this repo

**Comment by thetechguy-cpu** [comment]
> The say command is an embed, make sure your code matches the code in this repo

Ah. I see it now. It would still be nice to add a channel argument. though

**Comment by muhitrhn** [comment]
@thetechguy-cpu you can check #504 , it contains exactly what you asked for. Made that for my server but never thought anyone will need that.

Enjoy!

**Comment by galnir** [comment]
Merged in #504 
Thanks @muhitrhn for opening that PR!
@thetechguy-cpu thanks for suggesting this. You're welcome to suggest more features or/and contribute code to this repo :)
