### ISSUE TITLE
A branch of Master-Bot for .env usability?

### ISSUE THREAD

**Issue by Natemo6348** [galnir/Master-Bot#493]
**Explain your suggestion**
I was thinking that maybe you could make a branch with a .env file for those hosting on something like replit that needs API keys and tokens hidden without having to upgrade their account

**Comment by Bacon-Fixation** [comment]
here ya go a dotenv version @Natemo6348 

https://github.com/Bacon-Fixation/Master-Bot/tree/dotenv

create a `.env` file and follow the format below
```
{
  prefix= !
  discord_owner_id= dicord id no quotes
  token= token no quotes
  tenorAPI= 
  newsAPI=
  geniusLyricsAPI=
  youtubeAPI=
  twitchClientID=
  twitchClientSecret=
  invite= false
}
```

**Comment by galnir** [comment]
If you need a .env file you can use bacon's suggestion :)
