### ISSUE TITLE
Twitch Announcer Not Working

### ISSUE THREAD

**Issue by PhantomNimbi** [galnir/Master-Bot#494]
**Describe the bug**
Twitch Announcer keeps disabling itself and leaving the following error in console:
```js
TypeError: Cannot read property '0' of undefined
    at fetchUserInfo (/home/container/resources/twitch/twitch-api.js:65:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**To Reproduce**
1. Use 'twitch-announcer-settings' command
2. provide 'twitch user and discord channel name' arguments

**Expected behavior**
Expected to announce when the user goes live on Twitch.

**Desktop:**
 - OS: Linux [PloxHost Docker Image]
 - Node Version: 14
 - Is python 2.7 installed?: No, PloxHost auto installs the selected bot language only. Since this is a Node.js bot then python doesn't get installed and there's no command line access to install it through. The console it provides only displays the logs and doesn't allow for running commands through.
 - How are you hosting the bot: PloxHost

**Comment by Bacon-Fixation** [comment]
What version of python shows up when you do a `python --version`?
it is required to have 2.7 installed before installing the dependencies with `npm install` 

Much Love
-Bacon

**Comment by PhantomNimbi** [comment]
No idea, my bot host doesn't let me do that. it uses a Docker image to run the setup and install everything from a package.json file first then has me swap from the setup.js to the index.js file. I'm not able to run command line arguments through it.

**Comment by galnir** [comment]
> No idea, my bot host doesn't let me do that. it uses a Docker image to run the setup and install everything from a package.json file first then has me swap from the setup.js to the index.js file. I'm not able to run command line arguments through it.
> 
> If it doesn't auto install, I'm going to need a js file that will install it otherwise there's no other way to get python on a node.js bot with PloxHost.
> 
> -- Edit --
> 
> I sent a support Tiecket to PloxHost support asking them to see if they can install Python2.7 onto our server. Hopefully this will work. I'll need to look for ways to do this via a shell file or something in the future though.

I'm closing this issue since it's related to your hosting solution

**Comment by PhantomNimbi** [comment]
Can't be fixed. Our host is refusing to install they're basically being idiots. So we need a way to install it via a js file.
