### ISSUE TITLE
Twitch Announcer couldn’t send message to this channel.

### ISSUE THREAD

**Issue by muhitrhn** [galnir/Master-Bot#496]
Hello,
Why the bot says this when i enable twitch announcer?

![3AEEDC2F-2FBB-4E8D-8538-2CFFFF798BB5](https://user-images.githubusercontent.com/36473811/114242359-95b4a280-99ac-11eb-982f-0c3d50c53af6.jpeg)

and this error shows up in console -
![8AB55F14-4462-4293-AE33-C558FBDBF876](https://user-images.githubusercontent.com/36473811/114242431-aebd5380-99ac-11eb-8492-c39c3f9bc37a.jpeg)

I have also checked the code and seems `DBInfo` can’t be located as a variable in some lines. In the attached image, all DBInfo are marked as yellow. Which means it can’t be located as a variable.
![873BEF9E-48AB-4133-9882-A09628ECE3D7](https://user-images.githubusercontent.com/36473811/114242791-4ae75a80-99ad-11eb-9a42-bdbcfa70c6e0.jpeg)

Please check this issue.

**Comment by Bacon-Fixation** [comment]
in the repo line 48 
` const DBInfo = Twitch_DB.get(`${message.guild.id}.twitchAnnouncer`);`

in your picture
the `row[0]` is not from the original
not much i can do if it was changed

Much Love
-Bacon

**Comment by muhitrhn** [comment]
> ```
>  const DBInfo = Twitch_DB.get(`${message.guild.id}.twitchAnnouncer`);
> ```

Could you please tell me what this line does? Does it look for guild.id.twitchAnnouncer row from the database table?

**Comment by Bacon-Fixation** [comment]
I believe so

**Comment by muhitrhn** [comment]
The line 306 of my image `DBInfo.rows[0].botsay` also does the same thing, it fetches value of `botSay` input. Then why doesn’t it work? And as you see in this image - 
![DE0555E2-A82C-4685-AC14-AB4A4CA9BD63](https://user-images.githubusercontent.com/36473811/114251567-4d54af00-99c3-11eb-8266-e51b0e2455e9.jpeg)

All other values get’s printed by the bot, they also have the same type of fetch code. Suppose `DBInfo.rows[0].name` = `Streamer Name` which clearly gets fetched by the bot.

**Comment by muhitrhn** [comment]
Seems this repo also can’t find the `DBInfo` variable, i guess the yellow color means that?
![C1116B65-8810-4186-A829-76AC075724CD](https://user-images.githubusercontent.com/36473811/114251830-56924b80-99c4-11eb-91e9-05e9576d47e1.jpeg)

**Comment by muhitrhn** [comment]
Never mind, i fixed that.
