### ISSUE TITLE
Command issues

### ISSUE THREAD

**Issue by Jglenn12** [galnir/Master-Bot#5]
The bot won't play songs that have been added to the queue, instead, it plays the first song and stops. And if you use the %play again it just adds it to the queue unless you restart the bot.

**Comment by galnir** [comment]
@Jglenn12 What OS are you running the bot on? sorry for the late reply

**Comment by Jglenn12** [comment]
Windows.

**Comment by galnir** [comment]
@Jglenn12 Yeah this bug occures only on Windows. This might be an OS problem rather than code, because I run my bot on Debian 9(also on Ubuntu 16) and it runs perfect.
I'll try to figure it out.

**Comment by galnir** [comment]
@Jglenn12 Can you update your dependencies(most important is that ytdl-core is up to date), pull new changes and give it a try?
Also make sure ffmpeg and python 2.7 are installed

**Comment by galnir** [comment]
@Jglenn12 Have you managed to solve it?

**Comment by galnir** [comment]
Will open again if anyone else has this issue.
