### ISSUE TITLE
A nowplaying command like rythmbot

### ISSUE THREAD

**Issue by FirezzzZ** [galnir/Master-Bot#50]
- [x] A nowplaying command like rythmbot

**Comment by galnir** [comment]
@FirezzzZ If you encounter bugs let me know

**Comment by FirezzzZ** [comment]
![image](https://user-images.githubusercontent.com/55920870/80223500-fea0ee80-8665-11ea-9e03-b1f9a0b96896.png)

i meant something like this..

**Comment by galnir** [comment]
![longvideo](https://user-images.githubusercontent.com/36937694/80275877-f6d85d00-86ec-11ea-9593-196b57145634.jpg)
![shortvideo](https://user-images.githubusercontent.com/36937694/80275881-022b8880-86ed-11ea-827a-cc37f2068a69.jpg)

@FirezzzZ Let me know if there's a bug or if it acts weird :)

**Comment by FirezzzZ** [comment]
![image](https://user-images.githubusercontent.com/55920870/80309795-ca0f6d00-87f4-11ea-98fe-05b485e80d1b.png)
 i am not using commando so i have edited your code a little bit, everythin seems to work fine except the formatDuration function
i have tried console logging them and it seems that this line
`                playBack = `${passedTimeFormatted}  ${playBack}  ${totalDurationFormatted}`;
`
comes as 
`Promise {
  '[object Promise]  :musical_note:▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬  [object Promise]'
}` when i console.log(playbackBar(video))
Here's my current code, please help when you are free
[](https://hastebin.com/okituzahac.js)

**Comment by galnir** [comment]
@FirezzzZ This probably happens because you declared formatDuration and playbackBar as async functions, and async functions return Promises. Try to remove the async keyword, it's not needed, these functions are meant to be synchronous.

**Comment by FirezzzZ** [comment]
Thank You So Much Galnir, it is working. thanks for the hardwork you have put in this code @galnir

**Comment by galnir** [comment]
I fixed it then forgot to push it to GitHub, I'll push it tommorow

**Comment by FirezzzZ** [comment]
ok

**Comment by FirezzzZ** [comment]
ok

**Comment by FirezzzZ** [comment]
Hello @galnir ?

**Comment by galnir** [comment]
> Hello @galnir ?

9103818093ec4b17824b24704c8c1d6f44d4cf35
