### ISSUE TITLE
Twitch Announcer issue.

### ISSUE THREAD

**Issue by muhitrhn** [galnir/Master-Bot#502]
Hello @Bacon-Fixation ,
Hope you are well, i have to say you did a great job with the twitch announcer.

I have a question regarding it. Is the twitch announcer supposed to announce the streamers presence every 2 minutes(default)?

I’m trying to announce a streamers stream on my server and it is only being announced once after 2 minutes of enabling using `*ta enable`. Not sure if it’s supposed to work like that.

Hope you will be able to help, thanks in advance.
Much appreciated!

**Comment by Bacon-Fixation** [comment]
by default it checks the status of the twitch channel every 2 minute (default is 2min and lowest is 1 min) and will post only 1 discord message when the streamer goes live, and once the streamer goes offline it will edit the old message 

it does not continuously send an online message every 2 mins

There isn't much of a reason to check faster than every min, it takes about 1 to 3 min for twitch to send a notice when a streamer has come online. 


Much Love
-Bacon

**Comment by muhitrhn** [comment]
Okay thank you!
