### ISSUE TITLE
add-role.js and rmv-role.js change suggestions

### ISSUE THREAD

**Issue by Natemo6348** [galnir/Master-Bot#503]
**Explain your suggestion**
Currently they don't work with user/role id or name, so maybe make it where you don't have to mention the user or role? If you think it's a good idea I can do it, but since I don't have the time right now, I thought I'd get some opinions.

**Comment by galnir** [comment]
I'll look into it. My intention was that it would work with user/role id and names

**Comment by Bacon-Fixation** [comment]
check out #520 

I had some spare time, I hope you don't mind Galnir.
I leveraged discordjs-commando's "member" and "role" flags for the arguments.

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
@Natemo6348 thank you for the suggestion
checkout the latest commit (ea644d5)

allows for the use of the (Name, Mention, or ID) to add or remove a role

```
Examples
!ar bacon muted
!rr Bacon#**** <role-id>
!ar <user-id> <mention-role>
etc...
```

if you have any other suggestions don't hesitate to open another enhancement page with suggestions <3

Much Love
-Bacon
