### ISSUE TITLE
error while installing modules on windows and heroku too

### ISSUE THREAD

**Issue by Trentyn** [galnir/Master-Bot#506]
![Desktop Screenshot 2021 04 15 - 10 54 16 09](https://user-images.githubusercontent.com/63451568/114834230-073f8700-9dd9-11eb-9b2e-b3f005defffe.png)
![Desktop Screenshot 2021 04 15 - 10 54 08 75](https://user-images.githubusercontent.com/63451568/114834232-0870b400-9dd9-11eb-9519-e21e5a0604e5.png)
![Desktop Screenshot 2021 04 15 - 10 54 23 16](https://user-images.githubusercontent.com/63451568/114834237-09a1e100-9dd9-11eb-8bb6-ad6b2b2f3d79.png)

**Comment by galnir** [comment]
You need to install Git

**Comment by Trentyn** [comment]
And on Heroku, git installed

Installing dependencies
       Installing node modules
       npm ERR! Error while executing:
       npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/discordjs/Commando.git
       npm ERR! 
       npm ERR! Host key verification failed.
       npm ERR! fatal: Could not read from remote repository.
       npm ERR! 
       npm ERR! Please make sure you have the correct access rights
       npm ERR! and the repository exists.
       npm ERR! 
       npm ERR! exited with error code: 128
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.YYcdY/_logs/2021-04-15T08_33_43_296Z-debug.log
-----> Build failed

**Comment by Trentyn** [comment]
but if I use files from the previous version of the bot (package.json and package-lock.json), then everything works

**Comment by galnir** [comment]
Pull the new changes I just committed and try again. It might be that the commando version needs to be explicit

**Comment by Trentyn** [comment]
> Pull the new changes I just committed and try again. It might be that the commando version needs to be explicit

success, but is this all normal?

make: Entering directory '/tmp/build_bd07081d/node_modules/better-sqlite3/build'
         TOUCH b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
         ACTION deps_sqlite3_gyp_locate_sqlite3_target_extract_sqlite3 b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
         TOUCH Release/obj.target/deps/locate_sqlite3.stamp
         CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
         AR(target) Release/obj.target/deps/sqlite3.a
         COPY Release/sqlite3.a
         CXX(target) Release/obj.target/better_sqlite3/src/better_sqlite3.o
       In file included from ./src/better_sqlite3.lzz:10,
                        from ../src/better_sqlite3.cpp:4:
       /app/.cache/node-gyp/14.16.1/include/node/node.h:778:51: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Context>)’ to ‘node::addon_context_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Context>, void*)’} [-Wcast-function-type]
         778 |       (node::addon_context_register_func) (regfunc),                  \
             |                                                   ^
       /app/.cache/node-gyp/14.16.1/include/node/node.h:796:3: note: in expansion of macro ‘NODE_MODULE_CONTEXT_AWARE_X’
         796 |   NODE_MODULE_CONTEXT_AWARE_X(modname, regfunc, NULL, 0)
             |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
       /app/.cache/node-gyp/14.16.1/include/node/node.h:827:3: note: in expansion of macro ‘NODE_MODULE_CONTEXT_AWARE’
         827 |   NODE_MODULE_CONTEXT_AWARE(NODE_GYP_MODULE_NAME,                     \
             |   ^~~~~~~~~~~~~~~~~~~~~~~~~
       ./src/better_sqlite3.lzz:67:1: note: in expansion of macro ‘NODE_MODULE_INIT’
       ./src/objects/database.lzz: In static member function ‘static void Database::JS_new(const v8::FunctionCallbackInfo<v8::Value>&)’:
       ./src/objects/database.lzz:172:21: warning: variable ‘status’ set but not used [-Wunused-but-set-variable]
       ./src/util/data.lzz: In function ‘v8::Local<v8::Value> Data::GetValueJS(v8::Isolate*, sqlite3_stmt*, int, bool)’:
       ./src/util/data.lzz:75:92: warning: this statement may fall through [-Wimplicit-fallthrough=]
       ./src/util/data.lzz:75:197: note: here
       ./src/util/data.lzz: In function ‘v8::Local<v8::Value> Data::GetValueJS(v8::Isolate*, sqlite3_value*, bool)’:
       ./src/util/data.lzz:79:81: warning: this statement may fall through [-Wimplicit-fallthrough=]
       ./src/util/data.lzz:79:175: note: here
         SOLINK_MODULE(target) Release/obj.target/better_sqlite3.node
         COPY Release/better_sqlite3.node
         CC(target) Release/obj.target/test_extension/deps/test_extension.o
         SOLINK_MODULE(target) Release/obj.target/test_extension.node
         COPY Release/test_extension.node
       rm b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
       make: Leaving directory '/tmp/build_bd07081d/node_modules/better-sqlite3/build'

**Comment by galnir** [comment]
> > Pull the new changes I just committed and try again. It might be that the commando version needs to be explicit
> 
> success, but is this all normal?
> 
> make: Entering directory '/tmp/build_bd07081d/node_modules/better-sqlite3/build'
> TOUCH b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
> ACTION deps_sqlite3_gyp_locate_sqlite3_target_extract_sqlite3 b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
> TOUCH Release/obj.target/deps/locate_sqlite3.stamp
> CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
> AR(target) Release/obj.target/deps/sqlite3.a
> COPY Release/sqlite3.a
> CXX(target) Release/obj.target/better_sqlite3/src/better_sqlite3.o
> In file included from ./src/better_sqlite3.lzz:10,
> from ../src/better_sqlite3.cpp:4:
> /app/.cache/node-gyp/14.16.1/include/node/node.h:778:51: warning: cast between incompatible function types from ‘void (_)(v8::Localv8::Object, v8::Localv8::Value, v8::Localv8::Context)’ to ‘node::addon_context_register_func’ {aka ‘void (_)(v8::Localv8::Object, v8::Localv8::Value, v8::Localv8::Context, void*)’} [-Wcast-function-type]
> 778 | (node::addon_context_register_func) (regfunc),
> | ^
> /app/.cache/node-gyp/14.16.1/include/node/node.h:796:3: note: in expansion of macro ‘NODE_MODULE_CONTEXT_AWARE_X’
> 796 | NODE_MODULE_CONTEXT_AWARE_X(modname, regfunc, NULL, 0)
> | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> /app/.cache/node-gyp/14.16.1/include/node/node.h:827:3: note: in expansion of macro ‘NODE_MODULE_CONTEXT_AWARE’
> 827 | NODE_MODULE_CONTEXT_AWARE(NODE_GYP_MODULE_NAME,
> | ^~~~~~~~~~~~~~~~~~~~~~~~~
> ./src/better_sqlite3.lzz:67:1: note: in expansion of macro ‘NODE_MODULE_INIT’
> ./src/objects/database.lzz: In static member function ‘static void Database::JS_new(const v8::FunctionCallbackInfov8::Value&)’:
> ./src/objects/database.lzz:172:21: warning: variable ‘status’ set but not used [-Wunused-but-set-variable]
> ./src/util/data.lzz: In function ‘v8::Localv8::Value Data::GetValueJS(v8::Isolate*, sqlite3_stmt*, int, bool)’:
> ./src/util/data.lzz:75:92: warning: this statement may fall through [-Wimplicit-fallthrough=]
> ./src/util/data.lzz:75:197: note: here
> ./src/util/data.lzz: In function ‘v8::Localv8::Value Data::GetValueJS(v8::Isolate*, sqlite3_value*, bool)’:
> ./src/util/data.lzz:79:81: warning: this statement may fall through [-Wimplicit-fallthrough=]
> ./src/util/data.lzz:79:175: note: here
> SOLINK_MODULE(target) Release/obj.target/better_sqlite3.node
> COPY Release/better_sqlite3.node
> CC(target) Release/obj.target/test_extension/deps/test_extension.o
> SOLINK_MODULE(target) Release/obj.target/test_extension.node
> COPY Release/test_extension.node
> rm b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
> make: Leaving directory '/tmp/build_bd07081d/node_modules/better-sqlite3/build'

Should be ok

**Comment by Trentyn** [comment]
Ok

**Comment by galnir** [comment]
Are you experiencing any more issues? If no I'll close this issue
