### ISSUE TITLE
While playing saved playlists auto shuffle 

### ISSUE THREAD

**Issue by Stalker-hash** [galnir/Master-Bot#510]
It would be cool if you can add auto shuffle to the saved playlists too

**Comment by Bacon-Fixation** [comment]
Look at the options.json file in the Master-Bot/ folder then look for  "AutomaticallyShuffleYouTubePlaylists" and change it to true save it then restart the bot, then Enjoy 

should look like 

  "AutomaticallyShuffleYouTubePlaylists": true

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Check out #519 

I added a shuffle option to the saved playlists, I hope this is what you had in mind

Much Love
-Bacon

**Comment by Stalker-hash** [comment]
yeah thanks!
