### ISSUE TITLE
[REQUEST] Option to specify role mention on twitch announcer

### ISSUE THREAD

**Issue by PhantomNimbi** [galnir/Master-Bot#511]
**Explain your suggestion**

I would like to see the option to specify which role the twitch announcer mentions. Also maybe give the user the option to disable role mention all together if they don't want to have it mention any role at all.

**Comment by Bacon-Fixation** [comment]
You can currently with `!tasettings  "s" "s" "s" "@stream-gang"` if you just wanted to change the mentions part of the announcer

I hope this helps, stream-gang can be what ever role you would like to mention

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
@PhantomNimbi  wanted to get back with you and see if you needed addition help or information

Much Love
-Bacon

**Comment by galnir** [comment]
seeing that Bacon helped you, I'm closing this issue.
As Bacon wrote if you need additional help you're always welcome to comment here or open a new issue
