### ISSUE TITLE
I need help but this is not a bug.

### ISSUE THREAD

**Issue by MeetThumar** [galnir/Master-Bot#516]
New version is out thats 7.9.0 how can i update the bot

**Comment by galnir** [comment]
Version of what?

**Comment by Bacon-Fixation** [comment]
My only assumption is that you are referring to the npm version, it was recently updated to 7.10.0

`npm -g install npm` or you can `npm -g install npm@7.10.0` to install a specified version

Much Love
-Bacon

**Comment by galnir** [comment]
Did you refer the the npm version? If yes that's not an issue you're not obligated to update npm often. If you meant something else please comment here or open a new issue and make sure to fill the issue template
