### ISSUE TITLE
Timer Freezes

### ISSUE THREAD

**Issue by meiaihara06** [galnir/Master-Bot#517]
**Describe the bug**
timer/seek freezes and stuck on 00:00 to the end of song

**To Reproduce**
`git clone https://github.com/galnir/Master-Bot`
`cd Master-Bot`
(configuring)
`npm start`
then go play a song with "?play SongNAME" (? is the prefix for me) 
**Expected behavior**
timer/seek should update every 10/20 seconds
**Screenshots**
![image](https://user-images.githubusercontent.com/46371349/115833643-895b2b80-a429-11eb-8f1d-250006988f62.png)

**Desktop (please complete the following information):**
 - OS: Windows Server 2019 (tested with ubuntu20 and the problem was same)
 - Node Version(Should be v12 atleast): v14.15.1
 - Is python 2.7 installed?: Python 3.9.4
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): on a windows VPS

**Additional context**
config : 
```
{
  "prefix": "?",
  "discord_owner_id": "***********",
  "token": "************************************************************",
  "youtubeAPI": "**************************************************"
}
```

**Comment by Bacon-Fixation** [comment]
its not a bug, 
that is how it is supposed work
 
the timer only updates when buttons are pressed
it does not auto update when music is playing 

i apologize for any confusion 

it was not possible to reliably have the embed message updated every second without errors or endless loops 

Much Love
-Bacon

**Comment by Natemo6348** [comment]
plus with enough instances running, it could be considered API spam

**Comment by galnir** [comment]
Yeah it doesn't auto-update every x seconds mainly because of the reason Natemo mentioned. If Discord was to increase the rate limit I would implement many commands I have in mind or some I already wrote

@meiaihara06 If you have any more questions you're welcome to tag me here :) You're also welcome to open issues if you're facing bugs
