### ISSUE TITLE
"Playing" Message should not send every time on loop

### ISSUE THREAD

**Issue by meiaihara06** [galnir/Master-Bot#518]
**Explain your suggestion**

when you loop a music , it should not send a message every time it loops ,or at least an option to disable it

**Comment by Bacon-Fixation** [comment]
it was implemented that way in case the playing message was in a busy channel, when the song ends it  brings the controls back into view

Much Love
-Bacon

**Comment by Natemo6348** [comment]
maybe when the song is over and it's on loop, delete the previous embed before sending again?

**Comment by Bacon-Fixation** [comment]
i just added the option to have the old Play Message deleted when the song ends 

check out #519

Much Love
-Bacon

**Comment by meiaihara06** [comment]
Thank you!
solved!

**Comment by Bacon-Fixation** [comment]
No Problem, Enjoy :D 
I apologize for delays, I had to stress to test it

Much Love
-Bacon
