### ISSUE TITLE
Add play command flags

### ISSUE THREAD

**Issue by rafaeldamasceno** [galnir/Master-Bot#528]
**Explain your suggestion**
As suggested by #513, instead of setting the playlist shuffle settings statically, it would be nice to let the users indicate whether or not they want to shuffle the playlist with a flag, like this:
`!play https://www.youtube.com/playlist?list=PLDZnY98LGxBcS7hgBmmZK2dNDFj9SSWhT -shuffle`

As such, I propose the following flags for the play command for playlist order manipulation

- [x] 1. `-shuffle` or `-s` for shuffling the playlist before queueing it. #540 

- [x]  `-reverse` or `-r` for reversing the playlist before queueing it.

Aditionally, these following flags would be useful for any query:

- [x]  `-next` or `-n` for queueing the query right after the current song.

- [x]  `-jump` or `-j` for queueing the query right after the current song and instantly skip to it.

**Comment by galnir** [comment]
Merged #540 and #543 both by @kfirmeg :)
