### ISSUE TITLE
Add seeking commands

### ISSUE THREAD

**Issue by rafaeldamasceno** [galnir/Master-Bot#529]
**Explain your suggestion**
Seeking commands are useful for big songs and videos. The following commands would be nice:

- `!seek` would jump to the indicated time. For example, `!seek 1:30` would go to the 1:30 timestamp of the song.
- `!fastforward` would jump ahead the indicated time. For example, if the current song was at 0:30 and we used `!fastforward 1:30`, the song would be at 2:00.
- `!rewind` would jump back the indicated time. For example, if the current song was at 0:30 and we used `!rewind 0:10`, the song would be at 0:20.

Having this command accept input both in seconds or mm:ss format would be ideal.

**Comment by galnir** [comment]
I addressed this in #134 
I tried before to write a seek command it had a 30% success rate and would sometimes crash the bot. Ytdl-core and ffmpeg are not optimal for it unfortunately
