### ISSUE TITLE
Define disconnection timeout on config

### ISSUE THREAD

**Issue by rafaeldamasceno** [galnir/Master-Bot#530]
**Explain your suggestion**
Currently the disconnection timeout is quite short when compared to other bots defaults. However, the only way to change it is to manually change the timeout value in the code itself. Adding this value to the config file and setting it in seconds would let admins configure it more easily.

**Comment by meiaihara06** [comment]
hey , yes that's nice
check out #525 !

**Comment by Bacon-Fixation** [comment]
#525 was merged

Thank you again, meiaihara06

closing this issue,  if you have any other suggestions or find bug feel free to open a new issue

Much Love
-Bacon
