### ISSUE TITLE
Keep all songs in queue and add previous command

### ISSUE THREAD

**Issue by rafaeldamasceno** [galnir/Master-Bot#531]
**Explain your suggestion**
It would be interesting to keep all queued songs in the queue until the bot timeouts. This way, if someone accidentally skips a song, it would be possible to go back to previous song. A command to clear the queue would also be nice in this situation.

**Comment by galnir** [comment]
Great suggestion, I'll work on it.
What do you mean by 'a command to clear the queue'?

**Comment by Natemo6348** [comment]
Technically `skipall` clears the queue

**Comment by galnir** [comment]
Merged in b785bef

Thanks for the great suggestion @rafaeldamasceno
