### ISSUE TITLE
TypeError: Cannot invoke Embeds class without a valid array to paginate.

### ISSUE THREAD

**Issue by RxNationGaming** [galnir/Master-Bot#535]
When I'm on the dm's of the bot while I'm trying the command speedrun it sending me TypeErrors

**Comment by RxNationGaming** [comment]
& I'm getting this!!
![Screenshot_2021-04-27-09-11-30-38_5a415ff834f6bc153619606941c55eb5](https://user-images.githubusercontent.com/81674505/116170485-8158ff80-a739-11eb-85a2-e329f2a53af3.png)

**Comment by Bacon-Fixation** [comment]
Thank you for the Heads up 
i was able to replicate this issue as well, i am looking into that now 

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
@RxNationGaming just pushed (44d849b) that fixes the issue

Thank you for bring this to my attention, if you have any other issue feel free to open another issue 

Much Love
-Bacon
