### ISSUE TITLE
TypeError: Cannot read property 'run' of undefined

### ISSUE THREAD

**Issue by RxNationGaming** [galnir/Master-Bot#537]
I just see it on the logs

**Comment by Bacon-Fixation** [comment]
happy to help ya
Could you do me a favor and fill out the Bug report template
so we have the info needed to better help with your issue 
[Bug Report Template](https://github.com/galnir/Master-Bot/issues/new?assignees=&labels=bug&template=bug_report.md&title=)

Much Love
-Bacon

**Comment by RxNationGaming** [comment]
Ok

**Comment by RxNationGaming** [comment]
Closing this issue & making a new issue :)
