### ISSUE TITLE
Twitch Announcer Auto Disabling

### ISSUE THREAD

**Issue by PhantomNimbi** [galnir/Master-Bot#544]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
The Twitch Announcer command itself sets up the stream announcement. However after a set amount of time when I return I see a message in the channel I ran the command in stating Twitch Announcer has been disabled. 

**To Reproduce**:
1. Use 'tasettings' command
2. provide '"Discord" "stream-alerts" "1" "Stream Starting!"' arguments

**Expected behavior**:
It should send a notification to the stream-alerts channel whenever Discord goes live on Twitch.

**Screenshots**:

**Desktop:**
 - OS: Ubuntu 20.04
 - Node Version: 14
 - Is python 2.7 installed?: Yes
 - How are you hosting the bot:  VPS

**Additional context**:
We originally thought this was our host, but weve since regained our own VPS amd have all the access we need to properly install all of the dependencies. This time we made sure everything was installed properly. Yet the bug still persists. It's not throwing any errors or giving any stream failed message. It's just auto disabling the Twitch Announcer and we are flat out baffled as to why this is happening.

**Comment by Bacon-Fixation** [comment]
I have a few extra questions, I hope you don't mind <3

can you confirm the bot/host is not restarting or rebooting after the Twitch announcer is enabled? 
(timer does not persist after restart)

In the text channel that you enabled the announcer in, is there a message ? 

which VPS are you using? 
(some services like Heroku will reboot every 24 hours)


Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Howdy @PhantomNimbi, 

just wanted to get back with you to see if you were still having issues with the twitch announcer?

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
i finally had this error (took 7 days for me to get it), if any issue with gathering data it will stop the timer (intention was to prevent rapid cycling)
i am working on a more robust twitch announcer set up right now, it may take a bit for me to redo 

- current plan
 i would like the Timers to persist even if the bot restarts/reboot(if possible)
use less token calls, removing the constant refresh of the access token and have it refresh every 24 hours instead
Fix the disable bug (somehow now the timer can't be stopped with `!ta disable` command)
would like to regather data from twitch if the status is not 429 (rate limit) instead of disabling the announcer

Much Love
-Bacon

**Comment by PhantomNimbi** [comment]
> Howdy @PhantomNimbi,
> 
> just wanted to get back with you to see if you were still having issues with the twitch announcer?
> 
> Much Love
> -Bacon

Yo, soz for the late reply, yes this is still happening. I'll be keeping an eye on the revamp though. Hopefully it fixes the problem.

**Comment by Bacon-Fixation** [comment]
I have concluded my endurance test and feel confident that I resolved this issue with #551

Thank You for posting this issue.
I hope to further expand the twitch commands in the future to allow it to have more than 1 streamer
and to re-enable the timers after a reboot 

Much Love
-Bacon

**Comment by galnir** [comment]
Merged #551
