### ISSUE TITLE
An error for one user (so far)

### ISSUE THREAD

**Issue by Natemo6348** [galnir/Master-Bot#549]
So far when this user uses `create-playlist` or `play` they get an error, but I do not, as well as other that tried it.
![20210507_215446](https://user-images.githubusercontent.com/64607128/117523642-1c927600-af7f-11eb-87aa-14019799aab1.jpg)
![20210507_215406](https://user-images.githubusercontent.com/64607128/117523643-1ef4d000-af7f-11eb-81c6-028029d9d333.jpg)

**Comment by Natemo6348** [comment]
Not sure what could be causing this

**Comment by galnir** [comment]
Was this the first time the user used the create-playlist command?

**Comment by Natemo6348** [comment]
Yes, and I actually fixed it by deleting their id from the database

**Comment by galnir** [comment]
@Natemo6348 A very odd error, not sure how it happened

**Comment by galnir** [comment]
If this error will pop up again please open a new issue and I'll look into it more seriously. I've read the code again and I'm not sure how the savedPlaylists property got deleted
