### ISSUE TITLE
tic tac toe?

### ISSUE THREAD

**Issue by Natemo6348** [galnir/Master-Bot#552]
**Explain your suggestion**
I know that connect 4 was just made, but could there also be something like tic tac toe for a shorter game?

**Comment by Bacon-Fixation** [comment]
:D i was thinking about other games as well, but one thing I encountered right away was how to have the player select a place on the board, if i did the same as connect4 I would need a button for each possible place (9) and would be hard to convey what button went where 

could do a `x,y' maybe (i need to see how to do the prompts with the paginations module for the embed)

just brainstorming <3

Much Love
-Bacon

**Comment by Natemo6348** [comment]
oh alright, also just an idea, but maybe you could do it like a, b, c, 1, 2, 3 similar to battleship

**Comment by Bacon-Fixation** [comment]
@Natemo6348 Check out #555

I would love some feedback  <3

Much Love
-Bacon
