### ISSUE TITLE
Bot not reconnecting to the voice channel after manually disconnecting

### ISSUE THREAD

**Issue by Aayushpatil77** [galnir/Master-Bot#553]
**Describe the bug**
Whenever I disconnected bot manually and then run the play command it should join the voice channel and play that particular song however, It doesn't. The bot only send the embed message.

**To Reproduce**
1. Use 'play' command
2. Disconnect the bot from the voice channel.
3. Run the play command again

**Expected behavior**
Should Play the song

**Desktop (please complete the following information):**
 - OS:Windows
 - Node Version  v12.13.0
 - Is python 2.7 installed?: yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...):Locally

**Comment by Aayushpatil77** [comment]
Use the disconnect option by right click on the bot not the commands

**Comment by Bacon-Fixation** [comment]
:( I still can't replicate this, (right-clicking -> disconnect on the bot it still returns with `!play <song-link>`)

update your Node to 14+ and see if that helps

Much Love
-Bacon

**Comment by galnir** [comment]
I wasn't able to replicate this. Please follow Bacon's suggestion and report back
