### ISSUE TITLE
a Remind feature (for admins / everyone)

### ISSUE THREAD

**Issue by meiaihara06** [galnir/Master-Bot#556]
**Explain your suggestion**
a command to set reminder on custom tasks
for example owner send:
`!remind Cookies 2h`
and bot will remind 2 hours later like this:

`@owner_user! you wanted me to remind you : "Cookies"`

thanks!

**Comment by Bacon-Fixation** [comment]
Just wanted to let you know I have started work on this

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Check out #563
would love some feedback <3

Thank you for posting this idea!
i hope i met your expectations 
if you have any other idea don't hesitate to post them :D

Much Love
-Bacon

**Comment by meiaihara06** [comment]
Thank you!!!
sure I'll test it as soon as possible!

**Comment by meiaihara06** [comment]
following up in #563
thanks again to @Bacon-Fixation 
closing issue to keep things clean
