### ISSUE TITLE
When I try to play a song I get this error: 

### ISSUE THREAD

**Issue by thiagogebrim13** [galnir/Master-Bot#558]
![image](https://user-images.githubusercontent.com/75040244/118501859-86d5b400-b6ff-11eb-84e5-1fd97ce5338e.png)

**Comment by Bacon-Fixation** [comment]
Can you do me a fave and fill out the Issues Template?

It gives us some additional information needed to better help resolve issues 

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Howdy @thiagogebrim13,

Wanted to get back with you, and see if you were still having issues 

Much Love
-Bacon

**Comment by galnir** [comment]
Most likely that you didn't generate a YouTube Data API key or that you didn't use the correct API key

**Comment by thiagogebrim13** [comment]
I already managed to solve it, you can remove it. It was an error in the API
