### ISSUE TITLE
Cloud setting

### ISSUE THREAD

**Issue by Meszi84** [galnir/Master-Bot#566]
**Explain your suggestion**
Hi. Where can I edit a cloud setting?
error message: "could not be found"

**Comment by galnir** [comment]
There are no cloud settings
Can you take a screenshot of the error?

**Comment by Meszi84** [comment]
![Uploading Screenshot_20210523-100104_Discord.jpg…]()

**Comment by Meszi84** [comment]
Twitch setting

**Comment by Bacon-Fixation** [comment]
Howdy @Meszi84,
 I noticed you were using `#` in the channel name
try again without it 

Example `!taconfig bturbo bot-chat-room 1 none`
![image](https://user-images.githubusercontent.com/12632936/119263280-09e58700-bba4-11eb-95f8-6988d3621d72.png)


Much Love
-Bacon

**Comment by Meszi84** [comment]
Thank, it work!

**Comment by Bacon-Fixation** [comment]
no problem my friend enjoy <3

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
if you have any other issues don't hesitate to post them :D

closing as issue is resolved

Much Love
-Bacon
