### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Natemo6348** [galnir/Master-Bot#567]
I'm not sure if I did something wrong or if it's just a bug or what, but I can't seem to find lyrics for any song. Didn't change the code or change my API key since the last time I used it. (worked then) Can someone help me figure this out?

**Comment by Bacon-Fixation** [comment]
@Natemo6348  Check out #568

They changed the web page slightly, and couldn't find the text should be good to go now :D

Much Love
-Bacon

**Comment by galnir** [comment]
Merged #568, thanks Bacon for taking care of this 🥇
