### ISSUE TITLE
Update Issue Play.js

### ISSUE THREAD

**Issue by TrueMB** [galnir/Master-Bot#569]
After Updating (manually, possible that I misscopied) the play command doesnt work anymore. Tried to update the [Pull Request](https://github.com/galnir/Master-Bot/pull/564) and play command in general.

Errors that I get:
https://pastebin.com/QgznJWtF

Play Class:
https://pastebin.com/mxrmBdPT

Trying to use **play** with a playlist and songs. But throws the errors everytime.

**Comment by Bacon-Fixation** [comment]
sounds like you are missing the Class `GuildData` from `index.js` 

Much Love
-Bacon

**Comment by TrueMB** [comment]
Hello Bacon-Fixation,

well solved the issue pretty much. Songs are now playing again. Thanks for the hint. Seems like I missed that entry....
But I still got a error with playing playlists.

After I enter **?play %playlist%** and select **playlist**, it throws an deprecated error.
The playlist starts tho. Its only the message and error that i get.

Error: https://pastebin.com/hM5UCE4b
Play.js: https://pastebin.com/mxrmBdPT
![image](https://user-images.githubusercontent.com/25579052/120073192-a5409580-c097-11eb-8368-af2caa97d510.png)

It calls the catch block at Line 763.

**Comment by Bacon-Fixation** [comment]
i ran your version of play.js and i dont get any warnings, make sure you dependencies are up-to-date

![image](https://user-images.githubusercontent.com/12632936/120075429-d654a200-c066-11eb-848c-02e708daecbf.png)


Much Love
-Bacon

**Comment by TrueMB** [comment]
The problem was not updated Dependencies like you said. Thanks again!

**Comment by Bacon-Fixation** [comment]
Np my friend enjoy

Much Love
-Bacon
