### ISSUE TITLE
error play music

### ISSUE THREAD

**Issue by galenco** [galnir/Master-Bot#57]
![Screenshot_17](https://user-images.githubusercontent.com/22531651/80403409-26ba6880-8885-11ea-8ca7-5da48974d61b.png)

**Comment by zoranzoki21** [comment]
Hello @galenco, please check #14

**Comment by galnir** [comment]
What operating system are you hosting the bot on?
What is your nodejs version? 
Have you installed all the requirements(python 2.7, ffmpeg etc..)?
Did you copy code or clone this repo?

**Comment by galenco** [comment]
Centos 7, node 12.16.2, python2.7 ffmpeg. Clone repo.

**Comment by galnir** [comment]
@galenco  Can you paste the error log as shown in console? Also what video did you try to play?

**Comment by galenco** [comment]
the error was due to the youtube API and I already solved it, but now this error appears
![Screenshot_21](https://user-images.githubusercontent.com/22531651/80587422-22ed2a00-89dc-11ea-8702-6ad5b30e13a2.png)

**Comment by galnir** [comment]
@galenco I've never seen this error before, this is most likely a network error on your end. Google it up I guess

**Comment by galenco** [comment]
@galnir Fixed this was a CSF firewall error
