### ISSUE TITLE
Say Command

### ISSUE THREAD

**Issue by AayanAsim746** [galnir/Master-Bot#574]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
Anyone can use the say Command and write in channels where they don't have the perms

**Expected behavior**
Only admins can use it

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...]
 - Node Version(Should be v14 atleast): yes
 - Is python 2.7 installed?:yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...):Replit

**Additional context**

**Comment by Bacon-Fixation** [comment]
Howdy, @AayanAsim746 

you can add `userPermissions: ['ADMINISTRATOR'],`

- Edited Say command for Admins only below (you can copy and paste this into say.js)
```
const { Command } = require('discord.js-commando');
const { MessageEmbed } = require('discord.js');

module.exports = class SayCommand extends Command {
  constructor(client) {
    super(client, {
      name: 'say',
      aliases: ['make-me-say', 'print'],
      memberName: 'say',
      group: 'other',
      guildOnly: true,
      clientPermissions: ['SEND_MESSAGES', 'MANAGE_MESSAGES'],
      userPermissions: ['ADMINISTRATOR'],
      description: 'Make the bot say anything!',
      args: [
        {
          key: 'channel_name',
          prompt: 'In which channel do you want the announcement to be sent?',
          type: 'channel'
        },
        {
          key: 'text',
          prompt: ':microphone2: What do you want the bot to say?',
          type: 'string'
        }
      ]
    });
  }

  run(message, { channel_name, text }) {
    const embed = new MessageEmbed()
      .setTitle(`Just wanted to say...`)
      .setColor('#888888')
      .setDescription(text)
      .setTimestamp()
      .setFooter(
        `${message.member.displayName}, made me say it!`,
        message.author.displayAvatarURL()
      );

    channel_name.send(embed).catch(e => console.error(e));
    return;
  }
};
```
Much Love
-Bacon

**Comment by AayanAsim746** [comment]
Thx

**Comment by Bacon-Fixation** [comment]
No problem my friend, enjoy <3

Much Love
-Bacon
