### ISSUE TITLE
Play Command on specific time

### ISSUE THREAD

**Issue by TrueMB** [galnir/Master-Bot#575]
Using the Play Command with a youtube timestart in it. (f.e.: https://www.youtube.com/watch?v=_K6KA-MvXfU&t=2092s)
Its sometimes really helpful, if you got a long video and want to show only a part of it.

Getting the time seconds from the url and start the music/video on that time.
Pretty much like the music-travia Command, just not a random time.

Would be awesome if you could add that <3

**Comment by rafaeldamasceno** [comment]
Maybe related to #134

**Comment by TrueMB** [comment]
Start like the following #445
The time should be possible to get from the String with a splitter.

**Comment by galnir** [comment]
Added in 37799f9
