### ISSUE TITLE
Spotify support

### ISSUE THREAD

**Issue by ChillNotTaken** [galnir/Master-Bot#576]
**Hey i was wondering if yall could add Spotify support like SudhanPlayz/DiscordMusic-Bot where you can do like !play (Spotify playlist link> and bot adds all the song in playlist to queue and maybe add discord-buttons support using the discord-buttons   npm**

**Comment by Bacon-Fixation** [comment]
check out #444

Much Love
-Bacon

**Comment by galnir** [comment]
The bot now supports Spotify URLs (By converting them to YouTube URLs) :tada:
