### ISSUE TITLE
When I play a song it ask me the desired option to play and then shows an error that "i do not have perms not connect to your channel" even if i have given  all the suitable perms to the bot

### ISSUE THREAD

**Issue by cybermagma-dev** [galnir/Master-Bot#577]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**

**To Reproduce**
1. Use 'x' command
2. provide 'y' argument

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...]
 - Node Version(Should be v14 atleast): 
 - Is python 2.7 installed?:
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...):

**Additional context**

**Comment by cybermagma-dev** [comment]
![image](https://user-images.githubusercontent.com/77920021/121325471-413b8e00-c92f-11eb-9247-f5ead54d913c.png)

**Comment by cybermagma-dev** [comment]
![image](https://user-images.githubusercontent.com/77920021/121326086-d9d20e00-c92f-11eb-947d-236ec08381d6.png)

**Comment by cybermagma-dev** [comment]
I read the previous issues its fixed now! Thanks

**Comment by williameom5678** [comment]
how did you fix it?

**Comment by williameom5678** [comment]
> 
> 
> how did you fix it?

pls give me a hint for it...

**Comment by cybermagma-dev** [comment]
Hey you just gotta delte the node modules and install it by npm i..... that's it👍🏿

**Comment by williameom5678** [comment]
> 
> 
> Hey you just gotta delte the node modules and install it by npm i..... that's it👍🏿

oh.
