### ISSUE TITLE
music-trivia songs

### ISSUE THREAD

**Issue by cybermagma-dev** [galnir/Master-Bot#578]
**Explain your suggestion**
Hey !can you tell that the how can we update the songs of the music trivia as i find out that they repeat after sometime and are not random .....pls tell .... Thanks!

**Comment by Bacon-Fixation** [comment]
look in `/Master-Bot/resources/music/musictrivia.json`

Much Love
-Bacon

**Comment by cybermagma-dev** [comment]
So I have to add it manually know?

**Comment by galnir** [comment]
> So I have to add it manually know?

Yes

**Comment by cybermagma-dev** [comment]
Ok thanks
