### ISSUE TITLE
Error 404 on playing music 

### ISSUE THREAD

**Issue by cybermagma-dev** [galnir/Master-Bot#580]
On playing music from the bot there is an error coming 
![image](https://user-images.githubusercontent.com/77920021/123377374-9f13db00-d5a9-11eb-95f8-b28571c2e609.png)

Pls tell how i can solve it/

**Comment by galnir** [comment]
YouTube changed their API and it broke [ytdl-core](https://github.com/fent/node-ytdl-core/issues/945).
I'll update ytdl-core's version once they update it (supposed to be soon)

**Comment by galnir** [comment]
Pull the new commit and hit ```npm i``` :)
