### ISSUE TITLE
Cannot join channel when use play command

### ISSUE THREAD

**Issue by Sinomaru** [galnir/Master-Bot#582]
I already enable all permission but still error

Here is the error
![Screenshot_2021-07-01-11-38-31-1-1](https://user-images.githubusercontent.com/65635989/124065730-8b60ec80-da61-11eb-8c25-9bf2bdcc5912.png)

**Comment by ProtectorYT364** [comment]
Yep same bug

**Comment by galnir** [comment]
@Sinomaru Did you generate a valid YouTube API key?

**Comment by Sinomaru** [comment]
> @Sinomaru Did you generate a valid YouTube API key?

Yea i already put valid youtube API Key

**Comment by ProtectorYT364** [comment]
> @Sinomaru Did you generate a valid YouTube API key?

I Putted a Valid Key

**Comment by Alan-Wen-3344** [comment]
Having the same issue, the YT API is valid and python 2.7 & node v14.16 are installed.

**Comment by xFaithNation** [comment]
I am having the same issue, anyone know a fix?

**Comment by rafaeldamasceno** [comment]
@galnir Because I hadn't seen anyone else complain, I thought this was only a problem on my end. However, since 4afc402b27b1947d31ed496e4612488a23b47ee8, I haven't been able to run the bot with Node.js LTS. I suspect it has something to do with the `@discordjs/opus` module upgrade. Using Node.js Current works.

**Comment by galnir** [comment]
@xFaithNation @Sinomaru @Alan-Wen-3344 @ProtectorYT364 

Please pull the new changes (the console.error commit) and take a screenshot of the error that pops up in the console

**Comment by rafaeldamasceno** [comment]
I also have the same bug, but the reason might be totally different:
![image](https://user-images.githubusercontent.com/6492427/124674409-94631b00-deb2-11eb-90eb-3e4dd4012485.png)

For me, this is the stack trace:
```
Error: Error: Cannot find module '/Master-Bot/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-arm-musl-1.1.24/opus.node'
Require stack:
- /Master-Bot/node_modules/@discordjs/opus/lib/index.js
- /Master-Bot/node_modules/prism-media/src/util/loader.js
- /Master-Bot/node_modules/prism-media/src/opus/Opus.js
- /Master-Bot/node_modules/prism-media/src/opus/index.js
- /Master-Bot/node_modules/prism-media/src/index.js
- /Master-Bot/node_modules/discord.js/src/client/voice/player/BasePlayer.js
- /Master-Bot/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
- /Master-Bot/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
- /Master-Bot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
- /Master-Bot/node_modules/discord.js/src/client/Client.js
- /Master-Bot/node_modules/discord.js/src/index.js
- /Master-Bot/node_modules/discord.js-commando/src/client.js
- /Master-Bot/node_modules/discord.js-commando/src/index.js
- /Master-Bot/index.js
Error: Cannot find module 'node-opus'
Require stack:
- /Master-Bot/node_modules/prism-media/src/util/loader.js
- /Master-Bot/node_modules/prism-media/src/opus/Opus.js
- /Master-Bot/node_modules/prism-media/src/opus/index.js
- /Master-Bot/node_modules/prism-media/src/index.js
- /Master-Bot/node_modules/discord.js/src/client/voice/player/BasePlayer.js
- /Master-Bot/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
- /Master-Bot/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
- /Master-Bot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
- /Master-Bot/node_modules/discord.js/src/client/Client.js
- /Master-Bot/node_modules/discord.js/src/index.js
- /Master-Bot/node_modules/discord.js-commando/src/client.js
- /Master-Bot/node_modules/discord.js-commando/src/index.js
- /Master-Bot/index.js
Error: Cannot find module 'opusscript'
Require stack:
- /Master-Bot/node_modules/prism-media/src/util/loader.js
- /Master-Bot/node_modules/prism-media/src/opus/Opus.js
- /Master-Bot/node_modules/prism-media/src/opus/index.js
- /Master-Bot/node_modules/prism-media/src/index.js
- /Master-Bot/node_modules/discord.js/src/client/voice/player/BasePlayer.js
- /Master-Bot/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
- /Master-Bot/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
- /Master-Bot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
- /Master-Bot/node_modules/discord.js/src/client/Client.js
- /Master-Bot/node_modules/discord.js/src/index.js
- /Master-Bot/node_modules/discord.js-commando/src/client.js
- /Master-Bot/node_modules/discord.js-commando/src/index.js
- /Master-Bot/index.js
    at Object.loader [as require] (/Master-Bot/node_modules/prism-media/src/util/loader.js:12:9)
    at loadOpus (/Master-Bot/node_modules/prism-media/src/opus/Opus.js:17:17)
    at new OpusStream (/Master-Bot/node_modules/prism-media/src/opus/Opus.js:46:10)
    at new Encoder (/Master-Bot/node_modules/prism-media/src/opus/Opus.js:149:5)
    at AudioPlayer.playPCMStream (/Master-Bot/node_modules/discord.js/src/client/voice/player/BasePlayer.js:58:34)
    at AudioPlayer.playUnknown (/Master-Bot/node_modules/discord.js/src/client/voice/player/BasePlayer.js:53:17)
    at VoiceConnection.play (/Master-Bot/node_modules/discord.js/src/client/voice/util/PlayInterface.js:71:28)
    at /Master-Bot/commands/music/play.js:537:10
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

This is very interesting... It confirms my suspicion that somehow the opus module is not building correctly, but this is also because I'm running this with the Dockerfile on my Raspberry Pi which is armv7 based. Are there prebuilt binaries for Linux/Windows amd64/x86? Maybe the issue always occurs on armv7? However, npm doesn't really report any error and the module builds with no issue. If I use Node.js v16, then it does it all the same but no issue happens.

In any case, I have found a way to get it to work even on LTS, which is to run `npm ci` instead of `npm i` and force it to install the module versions on the lockfile.

**Comment by galnir** [comment]
> I also have the same bug, but the reason might be totally different:
> ![image](https://user-images.githubusercontent.com/6492427/124674409-94631b00-deb2-11eb-90eb-3e4dd4012485.png)
> 
> For me, this is the stack trace:
> 
> ```
> Error: Error: Cannot find module '/Master-Bot/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-arm-musl-1.1.24/opus.node'
> Require stack:
> - /Master-Bot/node_modules/@discordjs/opus/lib/index.js
> - /Master-Bot/node_modules/prism-media/src/util/loader.js
> - /Master-Bot/node_modules/prism-media/src/opus/Opus.js
> - /Master-Bot/node_modules/prism-media/src/opus/index.js
> - /Master-Bot/node_modules/prism-media/src/index.js
> - /Master-Bot/node_modules/discord.js/src/client/voice/player/BasePlayer.js
> - /Master-Bot/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
> - /Master-Bot/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
> - /Master-Bot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
> - /Master-Bot/node_modules/discord.js/src/client/Client.js
> - /Master-Bot/node_modules/discord.js/src/index.js
> - /Master-Bot/node_modules/discord.js-commando/src/client.js
> - /Master-Bot/node_modules/discord.js-commando/src/index.js
> - /Master-Bot/index.js
> Error: Cannot find module 'node-opus'
> Require stack:
> - /Master-Bot/node_modules/prism-media/src/util/loader.js
> - /Master-Bot/node_modules/prism-media/src/opus/Opus.js
> - /Master-Bot/node_modules/prism-media/src/opus/index.js
> - /Master-Bot/node_modules/prism-media/src/index.js
> - /Master-Bot/node_modules/discord.js/src/client/voice/player/BasePlayer.js
> - /Master-Bot/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
> - /Master-Bot/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
> - /Master-Bot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
> - /Master-Bot/node_modules/discord.js/src/client/Client.js
> - /Master-Bot/node_modules/discord.js/src/index.js
> - /Master-Bot/node_modules/discord.js-commando/src/client.js
> - /Master-Bot/node_modules/discord.js-commando/src/index.js
> - /Master-Bot/index.js
> Error: Cannot find module 'opusscript'
> Require stack:
> - /Master-Bot/node_modules/prism-media/src/util/loader.js
> - /Master-Bot/node_modules/prism-media/src/opus/Opus.js
> - /Master-Bot/node_modules/prism-media/src/opus/index.js
> - /Master-Bot/node_modules/prism-media/src/index.js
> - /Master-Bot/node_modules/discord.js/src/client/voice/player/BasePlayer.js
> - /Master-Bot/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
> - /Master-Bot/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
> - /Master-Bot/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
> - /Master-Bot/node_modules/discord.js/src/client/Client.js
> - /Master-Bot/node_modules/discord.js/src/index.js
> - /Master-Bot/node_modules/discord.js-commando/src/client.js
> - /Master-Bot/node_modules/discord.js-commando/src/index.js
> - /Master-Bot/index.js
>     at Object.loader [as require] (/Master-Bot/node_modules/prism-media/src/util/loader.js:12:9)
>     at loadOpus (/Master-Bot/node_modules/prism-media/src/opus/Opus.js:17:17)
>     at new OpusStream (/Master-Bot/node_modules/prism-media/src/opus/Opus.js:46:10)
>     at new Encoder (/Master-Bot/node_modules/prism-media/src/opus/Opus.js:149:5)
>     at AudioPlayer.playPCMStream (/Master-Bot/node_modules/discord.js/src/client/voice/player/BasePlayer.js:58:34)
>     at AudioPlayer.playUnknown (/Master-Bot/node_modules/discord.js/src/client/voice/player/BasePlayer.js:53:17)
>     at VoiceConnection.play (/Master-Bot/node_modules/discord.js/src/client/voice/util/PlayInterface.js:71:28)
>     at /Master-Bot/commands/music/play.js:537:10
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> ```
> 
> This is very interesting... It confirms my suspicion that somehow the opus module is not building correctly, but this is also because I'm running this with the Dockerfile on my Raspberry Pi which is armv7 based. Are there prebuilt binaries for Linux/Windows amd64/x86? Maybe the issue always occurs on armv7? However, npm doesn't really report any error and the module builds with no issue. If I use Node.js v16, then it does it all the same but no issue happens.
> 
> In any case, I have found a way to get it to work even on LTS, which is to run `npm ci` instead of `npm i` and force it to do a clean install of the module versions on the lockfile.

In your case the error was thrown because of a failed opus build
I'm waiting for the other users to post screenshots of the error they're getting in console to determine what's causing this for them

**Comment by Alan-Wen-3344** [comment]
It's working with node v16.4.2 for me, but not resume the music after pause. (it still says "Song resumed!" without any errors)
Even I play another song it won't play either. (it did show "Now Playing" embed)

**Comment by galnir** [comment]
> It's working with node v16.4.2 for me, but not resume the music after pause. (it still says "Song resumed!" without any errors)
> Even I play another song it won't play either. (it did show "Now Playing" embed)

read my last comment on #579
