### ISSUE TITLE
lyrics messed up after hosting it into heroku

### ISSUE THREAD

**Issue by starklite1** [galnir/Master-Bot#588]
the codes running fine on visual code but sometimes need twice or more caused fetching lyrics problem when finding any lyrics. while after hosting it into heroku without changing anything of the codes it wont working so correctly anymore and always got notif fetching problem from bot message.

**Comment by galnir** [comment]
@starklite1 
It sounds like the key you're using in heroku is wrong, because there is nothing that prevents the lyrics command from working in heroku

**Comment by Bacon-Fixation** [comment]
@galnir just a heads-up that the lyrics command no longer works.
Genius lyrics changed stuff again, and I can't seem to find it

Much Love
-Bacon

**Comment by galnir** [comment]
@Bacon-Fixation I'll look into it

**Comment by galnir** [comment]
fixed in 621a6f6
