### ISSUE TITLE
Someone copied your script

### ISSUE THREAD

**Issue by Whirl21** [galnir/Master-Bot#589]
Hello there this is not a bug report but a report ..
someone copied your script 
they also copied a lot of scripts so yeah 
you can sue them
here is the link
https://github.com/TeamRainbowDevs/advanced-music-bot/

**Comment by galnir** [comment]
If that user claims the entire codebase as his work he probably can't code a bot :(
Thanks for letting me know tho @Whirl21 👍

**Comment by Whirl21** [comment]
yes he is a skid 
and not a problem
