### ISSUE TITLE
Message for unknown command

### ISSUE THREAD

**Issue by zoranzoki21** [galnir/Master-Bot#59]
Hello,
I can't find where is defined message "Unknown command. Use !help.....". How I can change it, I want to use another text.

**Comment by galenco** [comment]
@zoranzoki21 node_modules/discord.js-commando/src/commands/util/help.js

**Comment by galnir** [comment]
@zoranzoki21 It's part of Commando's util commands, you can either disable it(read commando's docs) or change the message in **node_modules/discord.js-commando/src/commands/util/unknown-command.js**

**Comment by zoranzoki21** [comment]
> @zoranzoki21 It's part of Commando's util commands, you can either disable it(read commando's docs) or change the message in **node_modules/discord.js-commando/src/commands/util/unknown-command.js**

Thanks!
