### ISSUE TITLE
crowdin

### ISSUE THREAD

**Issue by huangdangwibu** [galnir/Master-Bot#598]
i would like to translate the bot

**Comment by galnir** [comment]
To what language?

**Comment by huangdangwibu** [comment]
vietnamese

**Comment by galnir** [comment]
Added to feature list #667

**Comment by comradekingu** [comment]
@huangdangwibu @galnir Crowdin is an anti-feature in all respects.
No community, far less userbase, inefficient and lackluster functionality, awful terms, and closed source software.

**Comment by galnir** [comment]
> @huangdangwibu @galnir Crowdin is an anti-feature in all respects.
> No community, far less userbase, inefficient and lackluster functionality, awful terms, and closed source software.

Do you know any good alternatives?

**Comment by comradekingu** [comment]
@galnir 
There is sadly only one good alternative called Weblate,
and all of the other Discord projects are on https://hosted.weblate.org/hosting/
Translatewiki is in the running, but it has Google Analytics.
