### ISSUE TITLE
Feature: Playlist :D

### ISSUE THREAD

**Issue by lactran1702** [galnir/Master-Bot#6]
Hi, Your code helps me out a lot.

I would love to see the playlist feature write by you.

I did the url.match for the playlist but it didn't work. If you have free time please help me out, if not it's totally fine :)

Many thanks,

**Comment by galnir** [comment]
Hey @lactran1702 , thanks for your interest in my bot!
I started writing the command a few days ago, the problem with the url.match is that it also matches the playlist url but it applies a single song url logic on it. 
We can solve it by making the regex more specific or by writing another match that will come before the first match and that match will check for playlist urls.

**Comment by lactran1702** [comment]
Hi @galnir ,
Thank you for noticing my opinion.
I'm trying to write another match that contains both url.match song and url.match playlist :D
Not sure it will work out tho haha

**Comment by galnir** [comment]
@lactran1702 The feature is currently in the dev branch, needs some testing so im not pushing to master yet :)

**Comment by lactran1702** [comment]
@galnir thank you very much, I'll test it out :D. Sorry for the late respond

**Comment by lactran1702** [comment]
@galnir ayeee Working like a champ!!!

Thank you very much :D

**Comment by galnir** [comment]
@lactran1702 Btw what OS are you running the bot on? Related to another issue

**Comment by lactran1702** [comment]
@galnir I'm using Window 10 and I don't have that issue though. I tried to queue many songs and skip to the ordered number. Nothing goes wrong

**Comment by galnir** [comment]
Feature added in #7
