### ISSUE TITLE
Where's prefix?

### ISSUE THREAD

**Issue by PRINCE-HERE** [galnir/Master-Bot#602]
Where do I set prefix? In config.json or in env? Or what should be the name? "PREFIX"? "prefix"? "Prefix"? What should it be

**Comment by galnir** [comment]
If you're on the master branch there is no need to set a prefix, Discord has a new feature called 'slash commands'.
You simply type / in chat and a menu opens with the available commands you can use

**Comment by PRINCE-HERE** [comment]
Oh okay thanks!
