### ISSUE TITLE
Bot does not start

### ISSUE THREAD

**Issue by ChickenIQ** [galnir/Master-Bot#603]
**To Reproduce**
1. Follow the steps provided on the Github page.
2. node index.js

**Expected behavior**
You get the following error:
Started refreshing application (/) commands.
Successfully reloaded application (/) commands.
/home/chickeniq/Desktop/Master-Bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:244
        throw new Error(WSCodes[error.code]);
              ^

Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/home/chickeniq/Desktop/Master-Bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:244:15)
    at async Client.login (/home/chickeniq/Desktop/Master-Bot/node_modules/discord.js/src/client/Client.js:245:7) {
  [Symbol(code)]: 'DISALLOWED_INTENTS'

**Screenshots**

![unknown](https://user-images.githubusercontent.com/36515619/131568209-fac5e706-8f88-4903-9881-c7c69659e663.png)

 - OS: Arch Linux
 - Node Version: V16
 - Python version: 3.9.6
 - Locally hosted.

**Comment by galnir** [comment]
You need to enable intents in the "Bot" page in the Discord developer portal
