### ISSUE TITLE
Passive bot

### ISSUE THREAD

**Issue by MrUnstable** [galnir/Master-Bot#605]
**Describe the bug**
I really don't know if this is supposed to happen but after following every single step (even multiple times with reinstalling different versions of Node.js) bot is just T-posing ( *being passive* ) lets put it like that >.>
whats confusing me is the fact that bot is online but i cant call it with / nor ! ... spent almost an hour tryin out different API keys , versions of node. also tried out communicating with mongo db ant it works just fine , permissions on discord server also looks good and after runnin around in circle i tried out other disc bot (java based) from gh and yup it worked 

**To Reproduce**
1. node index.js
2. x

**Expected behavior**
Bot should be online and working

**Screenshots**
![Screenshot_17](https://user-images.githubusercontent.com/37300966/131603478-38caceae-3d79-4ef2-b21d-1d4c2a499e6c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version(Should be v14 atleast):  V16.6 right now *tried with almost every version*
 - Is python 2.7 installed?: 3.9.7
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): Locally

**Additional context**
I tried to run it in cmd and ps as admin but it returned the same result Ready! message without any errors or pointers where did it gone wrong

**Comment by cybermagma-dev** [comment]
for what purpose are you using mongo db

**Comment by MrUnstable** [comment]
> for what purpose are you using mongo db

well, honestly i don't know xd i just saw that mongodb is needed and i wanted a lil challenge that sums it up

**Comment by galnir** [comment]
> for what purpose are you using mongo db

MongoDB is needed for the saved playlists feature and more features that will be added in the future

**Comment by galnir** [comment]
@MrUnstable When you type / in the chat do you see the menu pop up?

**Comment by MrUnstable** [comment]
> @MrUnstable When you type / in the chat do you see the menu pop up?

Nope theres no options from bot just vanilla discord built ins i invited other bots just to see if my disc is bugged or something but they showed up in /

![Screenshot_18](https://user-images.githubusercontent.com/37300966/131720661-599c2b0e-8941-42b8-8496-5d8771c5db94.png)

**Comment by galnir** [comment]
> > @MrUnstable When you type / in the chat do you see the menu pop up?
> 
> Nope theres no options from bot just vanilla discord built ins i invited other bots just to see if my disc is bugged or something but they showed up in /
> 
> ![Screenshot_18](https://user-images.githubusercontent.com/37300966/131720661-599c2b0e-8941-42b8-8496-5d8771c5db94.png)

And the bot is online in that exact same server you opened the menu in?

**Comment by galnir** [comment]
@MrUnstable 
Kick your bot from the server and follow this [guide step by step](https://discordjs.guide/preparations/adding-your-bot-to-servers.html#creating-and-using-your-invite-link). You may have enabled or disabled something when you created your bot in the developer portal. Lemme know if it helps you
