### ISSUE TITLE
LeaveTimeOut not working.

### ISSUE THREAD

**Issue by ChickenIQ** [galnir/Master-Bot#608]
The bot does not leave after the set time.

The current config:
{
  "playLiveStreams": true,
  "playVideosLongerThan1Hour": true,
  "maxQueueLength": 1000,
  "AutomaticallyShuffleYouTubePlaylists": true,
  "LeaveTimeOut": 300,
  "MaxResponseTime": 30,
  "deleteOldPlayMessage": true
}

**Comment by ChickenIQ** [comment]
This does not always happen but I got reports of the bot staying in a channel hours at a time.

**Comment by navidmafi** [comment]
Please follow the issue reporting template and describe version of your bot, nodejs python and your environment.
also please test with a clean installation and see if it happens there too
Thanks

**Comment by galnir** [comment]
#667
