### ISSUE TITLE
I get an error like Syntax error: Unexpected token '?'

### ISSUE THREAD

**Issue by PRINCE-HERE** [galnir/Master-Bot#612]
![Screenshot_2021_0902_022243](https://user-images.githubusercontent.com/86729260/132106361-30fb32b3-5c4c-46da-b89e-6e3e96e5d7c8.png)
Was it because of the v3 update? I tried to update to v3 but it didn't worked still

**Comment by galnir** [comment]
Update your Node.js version to v16 (latest is 16.8.0)

**Comment by PRINCE-HERE** [comment]
I use replit how do I do it?

**Comment by galnir** [comment]
@PRINCE-HERE I don't use replit so look it up on Google or on their forums

**Comment by imanimtiyaz** [comment]
> I use replit how do I do it?

![Screenshot 2021-09-08 104257](https://user-images.githubusercontent.com/90232327/132437972-2962da80-e290-49b6-82ad-5363ad0451b6.png


follow this link to install node.js v16:https://github.com/FlameQuard/DiscordJSv13-Tutorial
