### ISSUE TITLE
DeleteOldPlayMessage does not delete play message

### ISSUE THREAD

**Issue by JackW25** [galnir/Master-Bot#613]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
DeleteOldPlayMessage in options.json does not delete the previous play message (although it is set to true)

**To Reproduce**
1. Set DeleteOldPlayMessage to true
2. Play a song, when another song comes on/no song playing anymore, the bot wont delete message

**Expected behavior**
I expected the old play message to delete itself

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version(Should be v14 atleast): V14.17
 - Is python 2.7 installed?: Yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): Heroku

**Additional context**
The bot has Delete Message Permissions, the bot has deleted the old message before, but this has only happened once or twice (Sorry to bother you again with another question)

**Comment by galnir** [comment]
> Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.
> 
> **Describe the bug**
> DeleteOldPlayMessage in options.json does not delete the previous play message (although it is set to true)
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Set DeleteOldPlayMessage to true
> 2. Play a song, when another song comes on/no song playing anymore, the bot wont delete message
> 
> **Expected behavior**
> I expected the old play message to delete itself
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows
> * Node Version(Should be v14 atleast): V14.17
> * Is python 2.7 installed?: Yes
> * How are you hosting the bot(Locally, on a vps, heroku, glitch...): Heroku
> 
> **Additional context**
> The bot has Delete Message Permissions, the bot has deleted the old message before, but this has only happened once or twice (Sorry to bother you again with another question)

Are you on the old v12 branch or the new v13 branch?

**Comment by JackW25** [comment]
v12 Branch

**Comment by galnir** [comment]
@JackW25 I'm not maintaining the old v12 branch because I focus on the new v13 branch. The old v12 branch is there for people who don't want to use the new version yet (for whatever reason). It's on my todo list to implement DeleteOldPlayMessage to the new version

**Comment by JackW25** [comment]
I see, thanks man for the reply, and awesome job with the bot!
