### ISSUE TITLE
Playing a spotify link results in infinite "thinking..." but does work

### ISSUE THREAD

**Issue by ElectrodeYT** [galnir/Master-Bot#616]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**

Giving a spotify link to the /play command works but the bot is "thinking" forever

**To Reproduce**
1. /play spotify-link (I used https://open.spotify.com/track/684FIG25iUTSub2yFk22Ab?si=21a40c13ab3c4bf7)
2. /queue to see that the song is in the queue after waiting a short while
3. The bot should still be "thinking...."

**Expected behavior**

A "Enqueued" response similar to the youtube response

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...] Ubuntu server
 - Node Version(Should be v14 atleast): v16
 - Is python 2.7 installed?: yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): local server

**Additional context**

**Comment by galnir** [comment]
Fixed in e23e9e1
@ElectrodeYT Thanks for alerting me on this 👍
