### ISSUE TITLE
Adding a spotify song doesnt make bot join channel and causes the play command to lock up

### ISSUE THREAD

**Issue by ElectrodeYT** [galnir/Master-Bot#617]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**

When using /play <spotify link> without the bot already being in the channel, the bot does not join the voice channel and will not accept further play calls ("Please wait until the last play call is processed")

Also the reply differs ("Added x to the queue" with spotify, vs. "Enqueued x" with youtube)

**To Reproduce**
1. /play <spotify link> without bot in channel
2. The bot will reply, but it will not join the channel
3. A further (youtube) /play command gets the respone "Please wait until the last play call is processed"

**Expected behavior**

The bot joining the channel and accepting further calls to /play properly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...] Ubuntu server
 - Node Version(Should be v14 atleast): v16
 - Is python 2.7 installed?: yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): local server

**Additional context**

**Comment by galnir** [comment]
@ElectrodeYT nvm I was able to reproduce the second bug. Fixed in f83080f

**Comment by ElectrodeYT** [comment]
Yeah thats what i mean lol
sorry for not being clear enough
