### ISSUE TITLE
Music bot with no previous experience. Not sure what's wrong.

### ISSUE THREAD

**Issue by shepherdwolf** [galnir/Master-Bot#619]
**Describe the bug**
After following all steps to best of abilities, encountered multiple issues. After bug-fixing most issues, which mostly stemmed from misunderstanding of instructions, am now presented with unresponsive bot showing signs that code _mostly_ worked. CMD prompt lists multiple errors (Check screenshots) and bot does not respond to commands. Bot is listed as "Watching/" instead of previously listed as something along the lines of  "Autocode"

Did not Alter code except where instructed.

**To Reproduce**
1. Install all dependencies. (Fresh install)
2. Follow instructions as close as possible.
3. Run cmd "node index.js"

**Expected behavior**
Bot should respond to commands to stream youtube videos through voice channel.

**Screenshots**
![image](https://user-images.githubusercontent.com/90588479/133018275-90edceea-624a-4e0e-907e-af3377177028.png)
![image](https://user-images.githubusercontent.com/90588479/133018337-bea8660c-cc33-4943-bc27-8446367c64d2.png)
![image](https://user-images.githubusercontent.com/90588479/133018429-1c67c724-3ea9-4366-92d0-d36732295b64.png)
![image](https://user-images.githubusercontent.com/90588479/133018813-3f1bc028-49b8-4bdb-a7fa-0713cf8db51f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version(Should be v14 atleast): V16.9.1
 - Is python 2.7 installed?: Yes (Started with latest version, 3.x, uninstalled and reinstalled 2.7)
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): Locally, I think? Instruction started with making bot, which redirected to Autocode.com and Master-Bot folder is on my desktop.

**Additional context**
I have little to no coding experience. As such, I have made no alterations to code except where specified.

This is actually my second attempt. Encountered numerous bug on my first attempt, and once I was more confident in what I was doing, I deleted the original code and redownloaded.

Had to reinstall dependencies after encountering bugs, notably version issues. Current installs are all proper versions, I think.

Instructions stated to change line 7 on index.js. Line 7 on index.js is blank on my code? As I was unable to figure out what to do, I skipped step.

I restarted my computer, incase the issue was solved that way. Also kicked bot from server and rejoined, with correct permissions. Previously, bot would respond to simple call and response (Autocode "bot mention") but now the bot is completely unresponsive.

**Comment by shepherdwolf** [comment]
After looking at the code, I think I know roughly where the problem is.... but my skill level is too low to fix this on my own. it has something to do with "mongo" or "Mongoose" but I cant really tell more than that. It looks like it started to run this protocol, (See attached screenshot) then got lost? Or maybe I'm just muddling things up.

![image](https://user-images.githubusercontent.com/90588479/133033976-7036486e-7ebe-4d8b-901b-75d96bef8ce1.png)

Because this particular set of code sets status to "Watching" at the beginning, and outputs in cmd "mongo is ready" at the end. The "Watching" part is working but it's not making it to "Mongo is ready", if that helps?

**Comment by galnir** [comment]
You need to add another field in config.json:
"client_id": "your-bot-id"
make sure to add a comma where needed.
Also it looks like you didn't place a valid Mongo connection string. Did you follow the instructions on how to get one from Mongo Atlas?

**Comment by shepherdwolf** [comment]
I will do that as soon as I can. And the instructions didn't mention anything about a Mongo connection string or mongo atlas, though, so i did no such thing.

**Comment by galnir** [comment]
> I will do that as soon as I can. And the instructions didn't mention anything about a Mongo connection string or mongo atlas, though, so i did no such thing.
> 
> Is there a chance the instructions at https://dev.to/galnir/how-to-make-a-discord-music-bot-3c0p are not up to date? if so, where can i find full, updated instructions?

The instructions on dev.to are definitely not up to date. The updated instructions are in the [README](https://github.com/galnir/Master-Bot/blob/main/README.md)
