### ISSUE TITLE
Command Request

### ISSUE THREAD

**Issue by Natemo6348** [galnir/Master-Bot#62]
Could you maybe add a mute and unmute command? Would be very useful.

**Comment by galnir** [comment]
What kind of a mute command? If it's a "mute someone" command I already replied to #48 that I'll work on moderation commands in the future since the bot is mainly a music bot right now

**Comment by Natemo6348** [comment]
Oh ok, I meant a "mute someone" command

On 5/2/20, Nir <notifications@github.com> wrote:
> What kind of a mute command? If it's a "mute someone" command I already
> replied to #48 that I'll work on moderation commands in the future since the
> bot is mainly a music bot right now
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/galnir/Master-Bot/issues/62#issuecomment-623052799


-- 
~Nathaniel Sartin~
