### ISSUE TITLE
Spotify playlist causes infinite thinking

### ISSUE THREAD

**Issue by ElectrodeYT** [galnir/Master-Bot#623]
Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**

Putting a spotify playlist in the /play command causes the bot to process/hang forever

**To Reproduce**
1. /play {spotify playlist} (https://open.spotify.com/album/04h0D2eFUY2hIAIt3BqsPf?si=wWxmKUeXTV67Tkt5izAr7w&dl_branch=1) for example
2. See that it processes forever
3. The bot also hangs and does not accept further /play commands

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...] Ubuntu server
 - Node Version(Should be v14 atleast): v16
 - Is python 2.7 installed?: yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): local server

**Additional context**

**Comment by galnir** [comment]
Fixed in 28b29205efcbed9aa234b7e3778c39e588f63595
Issue was that the request returns different data for albums and playlists so that needed adjustment
