### ISSUE TITLE
Bot does not respond to any commands when online 

### ISSUE THREAD

**Issue by danielkemp017** [galnir/Master-Bot#626]
**Describe the bug**
Bot does not respond to any commands when online and added to a fresh sever with full admin permissions 

**Screenshots**
![image](https://user-images.githubusercontent.com/50493375/133527753-dcfc13ed-a68e-4597-b1ab-6671704866f0.png)

**Desktop (please complete the following information):**
 - OS: [ Windows 10]
 - Node Version(Should be v16 atleast): 16.9.1
 - Is python 2.7 installed?: python 3.7
 - How are you hosting the bot(Locally):

**Additional context**

**Comment by Bacon-Fixation** [comment]
Howdy,
try with `/play`

with the update to discord.js v13, commands are built from discord's slash command and don't use the "!" prefix

I hope this helps

Much Love
-Bacon

**Comment by danielkemp017** [comment]
Ah that seems to work for DM ing the bot but can seem to do it in a server

**Comment by Bacon-Fixation** [comment]
check out #605

" Kick your bot from the server and follow this guide [step by step](https://discordjs.guide/preparations/adding-your-bot-to-servers.html#creating-and-using-your-invite-link). You may have enabled or disabled something when you created your bot in the developer portal. "

Much Love
-Bacon

**Comment by danielkemp017** [comment]
nice one thanks for the help all good and working now
