### ISSUE TITLE
It runs successfully, but nothing happens

### ISSUE THREAD

**Issue by kurumicute** [galnir/Master-Bot#628]
**Expected behavior**
It runs successfully, but nothing happens

**Screenshots**
![image](https://user-images.githubusercontent.com/90886946/133933618-4dc1005e-5264-48ac-b07d-8a68dccf0524.png)
![image](https://user-images.githubusercontent.com/90886946/133933696-429c8b8c-dfee-4adc-8988-04d0cc1423b3.png)
![image](https://user-images.githubusercontent.com/90886946/133933716-d9e13608-24f8-4220-8e7e-449bdd1ed344.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...] W10
 - Node Version(Should be v14 atleast): 16.9.1
 - Is python 2.7 installed?: yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): my computer

**Comment by galnir** [comment]
There is a new feature called slash commands. You use commands by typing / and choosing which one you want to use from the menu

**Comment by kurumicute** [comment]
> There is a new feature called slash commands. You use commands by typing / and choosing which one you want to use from the menu

how can i use it?

**Comment by kurumicute** [comment]
> There is a new feature called slash commands. You use commands by typing / and choosing which one you want to use from the menu
![image](https://user-images.githubusercontent.com/90886946/133936428-c765eae5-4e3f-4a3b-8f24-a4ecb1ba3fb6.png)
When I play a youtube video, he appears this
Am I using it wrong?...

**Comment by Natemo6348** [comment]
will prefix based commands come back as well, or will it just be slash commands?

**Comment by Natemo6348** [comment]
will prefix based commands come back as well, or will it just be slash commands?

**Comment by kurumicute** [comment]
> will prefix based commands come back as well, or will it just be slash commands?

just slash commands

**Comment by galnir** [comment]
> will prefix based commands come back as well, or will it just be slash commands?

Slash commands are imo much better because the user can see what inputs the command expects and also it doesn't allow no inputs at all. I know some frameworks are expected to come out in the near future so I'll look into them and if it's possible to have slash commands together with prefix based commands

**Comment by kurumicute** [comment]
> > will prefix based commands come back as well, or will it just be slash commands?
> 
> Slash commands are imo much better because the user can see what inputs the command expects and also it doesn't allow no inputs at all. I know some frameworks are expected to come out in the near future so I'll look into them and if it's possible to have slash commands together with prefix based commands

How can I deal with this error?
I tried for a whole day and couldn't handle it...

**Comment by galnir** [comment]
> > > will prefix based commands come back as well, or will it just be slash commands?
> > 
> > 
> > Slash commands are imo much better because the user can see what inputs the command expects and also it doesn't allow no inputs at all. I know some frameworks are expected to come out in the near future so I'll look into them and if it's possible to have slash commands together with prefix based commands
> 
> How can I deal with this error?
> I tried for a whole day and couldn't handle it...

Did you generate a valid mongoDB URI?

**Comment by kurumicute** [comment]
> > > > will prefix based commands come back as well, or will it just be slash commands?
> > > 
> > > 
> > > Slash commands are imo much better because the user can see what inputs the command expects and also it doesn't allow no inputs at all. I know some frameworks are expected to come out in the near future so I'll look into them and if it's possible to have slash commands together with prefix based commands
> > 
> > 
> > How can I deal with this error?
> > I tried for a whole day and couldn't handle it...
> 
> Did you generate a valid mongoDB URI?

![image](https://user-images.githubusercontent.com/90886946/134045263-6fa16414-053f-4f70-80cb-6502795aa6f1.png)
yeah i guess

**Comment by kurumicute** [comment]
> > > > will prefix based commands come back as well, or will it just be slash commands?
> > > 
> > > 
> > > Slash commands are imo much better because the user can see what inputs the command expects and also it doesn't allow no inputs at all. I know some frameworks are expected to come out in the near future so I'll look into them and if it's possible to have slash commands together with prefix based commands
> > 
> > 
> > How can I deal with this error?
> > I tried for a whole day and couldn't handle it...
> 
> Did you generate a valid mongoDB URI?
![unknown](https://user-images.githubusercontent.com/90886946/134048265-bd944699-17f5-4d2c-aa78-aca51325480f.png)
yeah i guess...

**Comment by ysalomon409** [comment]
Also having this issue, I had commands working for a few minutes, but then all of a sudden the / commands didn't appear when I tried using them again.

**Comment by galnir** [comment]
@kurumicute Can you walk me through the steps you do to get this error?
Does it happen immediately after you /play 'songname' or does it show you the select menu and after you select it happens?

**Comment by galnir** [comment]
@kurumicute If the issue still persists please comment here
