### ISSUE TITLE
fields.flat is not a function

### ISSUE THREAD

**Issue by ISAGORIVAN** [galnir/Master-Bot#63]
I don't know why I get this error, I cloned it using glitch and when I do !play, it says "fields.flat is not a function." If you could help me, thank you.

**Comment by galnir** [comment]
Update your Node.js version to v12 atleast

**Comment by ISAGORIVAN** [comment]
i already did that, no idea why it still doesn't work.

**Comment by galnir** [comment]
No way, this is the fix for this particular error. How do you update nodejs version on glitch?

**Comment by ISAGORIVAN** [comment]
by adding the package "node": "^14.0.0"

**Comment by galnir** [comment]
Nodejs is not a package you can install via npm.. It is a runtime
Google how to update nodejs version on Glitch
