### ISSUE TITLE
DiscordAPIError[50035]: Invalid Form Body

### ISSUE THREAD

**Issue by Dufhamx** [galnir/Master-Bot#634]
j

**Comment by navidmafi** [comment]
PLEASE follow the issue template and provide environment info, or reproduce steps.
How can we help you if we don't know what is causing the problem at your side?

**Comment by Dufhamx** [comment]
i solved this problem. The bot works fine though. not responding to any commands 

Doesn't show up in slash commands would you help me with this topic

**Comment by navidmafi** [comment]
You can close the issue instead of editing your whole message with a "j".
Anyway, I hope your issue is solved.
