### ISSUE TITLE
Bot started, but nothing happens

### ISSUE THREAD

**Issue by Lilakoa** [galnir/Master-Bot#637]
**Describe the bug**
Hi! When bot started, i write slash (/) and i don`t see the commands of bot. When i for example write /play lol or !play lol. In console and in discord nothing happen

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Node Version(Should be v14 atleast): 16.10.0
 - Is python 2.7 installed?:yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...):locally

**Comment by navidmafi** [comment]
Hi!
Did you give bot the correct permissions? Try in a new server with admin perms.
Also, try to invite the bot with "application.commands" scope enabled

![image](https://user-images.githubusercontent.com/46371349/134766564-36bf5286-34bd-47e1-84aa-5740d244c82a.png)

**Comment by windows10win7posreadywoeskio** [comment]
> Hi! Did you give bot the correct permissions? Try in a new server with admin perms. Also, try to invite the bot with "application.commands" scope enabled
> 
> ![image](https://user-images.githubusercontent.com/46371349/134766564-36bf5286-34bd-47e1-84aa-5740d244c82a.png)

This happens to me too. I enabled "applications.commands".

**Comment by navidmafi** [comment]
Glad to see that resolved
