### ISSUE TITLE
Bot runs and responds to commands but all commands fail

### ISSUE THREAD

**Issue by LivingLastWeek** [galnir/Master-Bot#638]
I have the scopes and everything setup properly I believe but it's saying the interaction failed, its doing this with all commands
![Capture](https://user-images.githubusercontent.com/91373950/134784727-e01db867-aa2e-490a-8d25-477ba48eb962.PNG)

**Comment by NotKyoyo** [comment]
Please do update your issue using the issue template so we could reproduce the error from our ends aswell. 

> A fix that that you could probably try
- Removing your bot from the server then readding it with the proper perms.

**Comment by galnir** [comment]
@LivingLastWeek Are you getting any error in console?

**Comment by galnir** [comment]
> @galnir it shows that the bot booted up correctly, I have the scopes set to bot and app commands

Can you open a new issue and fill the template this time? The info you provide is crucial in order to help you
