### ISSUE TITLE
Play command with queue being undefined

### ISSUE THREAD

**Issue by Burday** [galnir/Master-Bot#64]
Hey,
I have a few issues with the play command. 
I have added the Structures in index.js but play will keep saying that "queue" is undefined. I have installed everything listed and code is identical. Any ideas?

**Comment by galnir** [comment]
I can't figure out where it comes from if you didn't clone this repo.. Copying commands to an existing bot is not recommended

**Comment by Burday** [comment]
I figured it out, it was related to the fact I changed "queue" to a different name while testing and I forgot to change it on the command file, resulting in 2 different names.

Sorry for the trouble
