### ISSUE TITLE
[Feature request/Suggestion] Soundcloud support?

### ISSUE THREAD

**Issue by chimaerra** [galnir/Master-Bot#649]
Youtube becomes a more difficult platform to use in terms of listening to music.

1. Age-restricted videos are no longer playable and that's an issue with ytdl-core and discordjs in general, I don't think anything can be done to prevent this (i.e no workarounds). Their system also flags any videos with specific tags, as an example "gachi". 
2. They constantly ban videos and channels for unusual reasons
3. More platforms to use - higher amount of possible content

[Also, a plenty of bots already support Soundcloud](https://top.gg/tag/soundcloud?page=2), Fredboat, MEE6 and Tony Bamanaboni support Soundcloud too.

I'll include Soundcloud docs just in case:
https://developers.soundcloud.com/docs/api/guide
https://developers.soundcloud.com/docs/api/sdks

**Comment by chimaerra** [comment]
To give a hint as to how it's used, this repo might help: https://github.com/eritislami/evobot

play.js / config.json.example
dependencies: soundcloud-downloader + soundcloud-key-fetch

**Comment by galnir** [comment]
@chimaerra You can now play tracks from SoundCloud #666 :)
