### ISSUE TITLE
Spotify Playlist causes infinite "Processing Playlist..."

### ISSUE THREAD

**Issue by ElectrodeYT** [galnir/Master-Bot#653]
### IMPORTANT : *DO NOT SKIP THIS STEPS AND DO NOT DELETE THEM. WE CAN NOT HELP YOU IF YOU DO NOT PROVIDE INFORMATION AND STEPS TO REPRODUCE*

Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
using a spotify playlist (https://open.spotify.com/playlist/5GYFxYE4fWXEZ17wwei4BD?si=19475f12cd634f8d) causes the bot to hang on "Processing Playlist..."

**To Reproduce**
1. /play https://open.spotify.com/playlist/5GYFxYE4fWXEZ17wwei4BD?si=19475f12cd634f8d
2. Infinite "Processing Playlist..."

Sometimes this seems to crash the entire bot (cant reproduce, have been told by my friends that this happens sometimes)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...]: Ubuntu server
 - Node.js Version(Should be v16 at least): v16
 - Is python 2.7 installed?: yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): local server

**Additional context**

**Comment by galnir** [comment]
I've looked into it and there is no way at the moment to reduce the time it takes to convert a Spotify playlist into a Youtube playlist. I will be looking into it again in the future :)
