### ISSUE TITLE
Command ! not working 

### ISSUE THREAD

**Issue by Bancukx** [galnir/Master-Bot#655]
### IMPORTANT : *DO NOT SKIP THIS STEPS AND DO NOT DELETE THEM. WE CAN NOT HELP YOU IF YOU DO NOT PROVIDE INFORMATION AND STEPS TO REPRODUCE*

Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**

**To Reproduce**
1. Use 'x' command
2. provide 'y' argument

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...]:
 - Node.js Version(Should be v16 at least): 
 - Is python 2.7 installed?:
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...):

**Additional context**

**Comment by slambot5** [comment]
The commands fail if you didn't set up the permissions correctly on discord. I had problems like that for a while before I got them right

**Comment by slambot5** [comment]
Or if you are running it off of a 32-bit OS, I also had problems with it

**Comment by JibuxH4l0** [comment]
i running 64 bit os

**Comment by JibuxH4l0** [comment]
> 
> 
> The commands fail if you didn't set up the permissions correctly on discord. I had problems like that for a while before I got them right

where is permission?, in discord developers?

**Comment by JibuxH4l0** [comment]
Please help me :(

**Comment by galnir** [comment]
Can you please fill the issue template? You left it blank. To be able to help you it would be helpful to know the OS you're running and your Node.js version

**Comment by JibuxH4l0** [comment]
Windows 10 64 bit os
Node js v16.6.0
Npm 7.19.1

**Comment by galnir** [comment]
> Windows 10 64 bit os Node js v16.6.0 Npm 7.19.1

Run a fresh clone of this repository and make sure to give the bot all the permissions it needs. Also **make sure to enable intents in the discord developer portal**

**Comment by JibuxH4l0** [comment]
Already fresh clone and enable intents, still dont working :(

**Comment by JibuxH4l0** [comment]
i had error from this
# npm audit report

ansi-regex  >2.1.1 <5.0.1
Severity: moderate
 Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix`
node_modules/strip-ansi/node_modules/ansi-regex
  strip-ansi  4.0.0 - 5.2.0
  Depends on vulnerable versions of ansi-regex
  node_modules/strip-ansi
    string-width  2.1.0 - 4.1.0
    Depends on vulnerable versions of strip-ansi
    node_modules/string-width

3 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

**Comment by galnir** [comment]
Check out the solution to [this issue](https://github.com/galnir/Master-Bot/issues/637). Maybe it also solves your problem?

**Comment by Bancukx** [comment]
YESS ITS WORKING THANKS FOR HELP
