### ISSUE TITLE
what is this 

### ISSUE THREAD

**Issue by Suktod** [galnir/Master-Bot#658]
/home/runner/Music-Bot/node_modules/@discordjs/rest/dist/lib/RequestManager.js:66
        const hash = this.hashes.get(`${request.method}:${routeID.bucketRoute}`) ?? `Global(${request.method}:${routeID.bucketRoute})`;
                                                                                  ^

SyntaxError: Unexpected token '?'

**Comment by slambot5** [comment]
I had an error like that last week after updates. I ended up saving the config and options file, and wiped the folder out and re-cloned it. Worked fine after

**Comment by galnir** [comment]
Are you running Node.js v16+ ?
