### ISSUE TITLE
Using slash commands in private channels results in a crash

### ISSUE THREAD

**Issue by navidmafi** [galnir/Master-Bot#662]
### IMPORTANT : *DO NOT SKIP THIS STEPS AND DO NOT DELETE THEM. WE CAN NOT HELP YOU IF YOU DO NOT PROVIDE INFORMATION AND STEPS TO REPRODUCE*

Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
Using play command in a channel that the bot does not access to send messages in , results in a crash

**To Reproduce**
1. Use play command in a channel that bot does not access to send messages in

**Expected behavior**
Anything other than a crash

**Screenshots**
![image](https://user-images.githubusercontent.com/46371349/144300028-69c0c203-8153-4f59-a2bc-9653bf6e834a.png)
![image](https://user-images.githubusercontent.com/46371349/144300260-f3e68a29-5d05-4faf-9c67-d9e3f7031643.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...]: Windows 10 LTSC 2021
 - Node.js Version(Should be v16 at least): 16.11
 - Is python 2.7 installed?: no
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): locally

**Additional context**
maybe use try catch?

**Comment by galnir** [comment]
Happened to me aswell
Kick the bot and invite it again with 'application.commands' and 'bot' scopes and also with 'Administrator' checked under 'Bot Permissions'
