### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mkidcqpw** [galnir/Master-Bot#664]
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/Master-Bot-1/index.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! master-bot@1.0.0 start: `node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the master-bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-12-17T08_08_49_840Z-debug.log
exit status 1

**Comment by galnir** [comment]
You need to run ```npm install```
