### ISSUE TITLE
Continued Question of Documented Code

### ISSUE THREAD

**Issue by BradChism** [galnir/Master-Bot#67]
Hi @galnir ,

What I am asking is for a documented command list. 

I have the bot working 100% on my local Linux box tied into my Discord Server. I added security checks for skipping files so only the person that originally played the song can skip it. Also added another option to confirm skipping so if someone wanted to skipall they can confirm it if someone else chose to skip it.  Also added more Admin rights so my user ID and my kids can pass security checks.  Also added a few mathematical tests as well as a calculator. 

Mainly this is for my kids and their friends to use and me to expand on. 

My thing is, I am looking for the lay of the land. What commands are setup, what do I need to add, am I being redundant if I want to add something. Etc. 

Do you have anything like this or did you build this on top of someone else's code and if so, who? 

Thanks for your time, 
B

**Comment by galnir** [comment]
@BradChism Yeah, sure, if you scroll down the repository [page](https://github.com/galnir/Master-Bot), you'll see the commands list, each command has a description and a usage example. Ofc you can add additional commands if you wish, just follow the [command framework](https://discord.js.org/#/docs/commando/master/general/welcome) I used.

**Comment by galnir** [comment]
Did that answer your question?

**Comment by Natemo6348** [comment]
@BradChism I would think @galnir coded this himself lol

**Comment by galnir** [comment]
Closing since this is a general question and not an issue
