### ISSUE TITLE
Another way to host lavalink for hosting bot on Heroku

### ISSUE THREAD

**Issue by KiyoshiKunCool** [galnir/Master-Bot#671]
Hi everyone, I've found another way to host the lavalink by using [repl.it](https://replit.com/)
>**_Install automatically_**
[![Host lavalink on Repl.it](https://repl.it/badge/github/DarrenOfficial/lavalink-replit)](https://repl.it/github/DarrenOfficial/lavalink-replit)

# Instruction for **lavalink**
- Clicking the button above, signing up or logging in and waiting for repl.it creates your lavalink project
- Once everything is done, click the "Run" button and keep waiting for it until you see the link on the right corner like mine

![Screenshot](https://user-images.githubusercontent.com/69381154/147846295-0b77285f-882c-4801-b903-0d261f4525c4.jpg)
✍**Notes:** _Your lavalink repl.it's link will like this:_ `https://lavalink-replit."yourusername".repl.co`

# Setting bot
- The default port to connect is `443` and the default password is `maybeiwasboring`
- Open your bot project folder, click on `config.json`:
> At "lava_host", copy your link on repl.it and you need to remove `https://` for bot working
> At "lava_pass", copy the default password `maybeiwasboring`

➤ It should be like this:
![Screenshot](https://user-images.githubusercontent.com/69381154/147846574-53ea525c-76a6-46fa-9927-f25d2d7ecf86.jpg)
- Next, click on `ExtendedClient.js` in `utils` folder.  Looking at line number 22 and adjusting like me:
![Screenshot](https://user-images.githubusercontent.com/69381154/147846739-85e0c079-3ddf-4cdf-80df-bb2d196a6e5b.png)

# Notes
- You can’t change the lavalink port! It will default to 443 due to how replit work.
- Replit is using **_https_** so we need to add `secure: true` to make the bot work.

## Youtube tutorial
↪ Link: [https://www.youtube.com/watch?v=bznq-P0Ovzk](https://www.youtube.com/watch?v=bznq-P0Ovzk)
Say thanks to [kakarot](https://github.com/Kakarot-0690) for making it! 😍

## How to keep the replit on with **_freshping_**
Go to [freshping](https://www.freshworks.com/website-monitoring/), and set HTTP request to your discord bot I.e. `https://lavalink-replit."yourusername".repl.co/metrics` and it should show that it's online. 
![freshpingisbetterthanuptimerobot](https://darrennathanael.com/cdn/873E3AB4-8862-49A2-B5F6-5A0B97E3BCF1.jpeg)
- - -
It's all done. Thanks for reading my instruction ☺☺
Instruct by [KiyoshiKunCool](https://github.com/KiyoshiKunCool)⭐ from **_Vietnam_** with love❤
#KiyoshiKunCool

**Comment by KiyoshiKunCool** [comment]
@JackW25 This is for you, my friend :3

**Comment by JackW25** [comment]
> @JackW25 This is for you, my friend :3

Thank you so much! I got everything working okay except I get this error with lavalink:

ERROR 328 --- [  XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /172.18.0.1:57894

Was wondering if you know anything about that,
aside from that issue though, everything is working as it should, thank you again!

**Comment by KiyoshiKunCool** [comment]
@JackW25 You need to run the bot and it'll connect to lavalink on replit. If you connect successful, the replit console should show the handle of your discord bot (I use `/play` to play my favourite song :3)

![Screenshot](https://user-images.githubusercontent.com/69381154/147860939-9572f679-2c21-441a-9533-6b169437ba2a.png)

✍**Note:** It'll show `Authentication failed from...` per an hour because of the _freshping_ **mechanism**. So, feel free to use it, my friend ^^
#KiyoshiKunCool

**Comment by JackW25** [comment]
I still seem to get the error

Error: Error: connect ETIMEDOUT 35.186.245.55:433
    at Connection._onerror (C:\Users\user\Documents\GitHub\Rainure\node_modules\lavaclient\dist\lib\node\Connection.js:127:33)
    at WebSocket.onError (C:\Users\user\Documents\GitHub\Rainure\node_modules\ws\lib\event-target.js:220:18)

Aside from that everything seems to be as it should in replit console, I'm not sure if its possible i have something wrong in the application.yml

Thanks again for your help mate, I really do appreciate it

**Comment by galnir** [comment]
> I still seem to get the error
> 
> Error: Error: connect ETIMEDOUT 35.186.245.55:433 at Connection._onerror (C:\Users\user\Documents\GitHub\Rainure\node_modules\lavaclient\dist\lib\node\Connection.js:127:33) at WebSocket.onError (C:\Users\user\Documents\GitHub\Rainure\node_modules\ws\lib\event-target.js:220:18)
> 
> Aside from that everything seems to be as it should in replit console, I'm not sure if its possible i have something wrong in the application.yml
> 
> Thanks again for your help mate, I really do appreciate it

Make sure you run the Lavalink server before running the bot

**Comment by JackW25** [comment]
> > I still seem to get the error
> > Error: Error: connect ETIMEDOUT 35.186.245.55:433 at Connection._onerror (C:\Users\user\Documents\GitHub\Rainure\node_modules\lavaclient\dist\lib\node\Connection.js:127:33) at WebSocket.onError (C:\Users\user\Documents\GitHub\Rainure\node_modules\ws\lib\event-target.js:220:18)
> > Aside from that everything seems to be as it should in replit console, I'm not sure if its possible i have something wrong in the application.yml
> > Thanks again for your help mate, I really do appreciate it
> 
> Make sure you run the Lavalink server before running the bot

Hey there, seems to work all good, if it's possible to run this by you quickly, I seem to get this error whenever I try and start the bot,

/app/node_modules/lavaclient/dist/lib/cluster/Cluster.js:23
this.userId ??= user && (0, Utils_1.getId)(user);
                  ^^^
SyntaxError: Unexpected token '??='
at wrapSafe (internal/modules/cjs/loader.js:1001:16)
at Module._compile (internal/modules/cjs/loader.js:1049:27)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
at Module.load (internal/modules/cjs/loader.js:950:32)
at Function.Module._load (internal/modules/cjs/loader.js:790:12)
at Module.require (internal/modules/cjs/loader.js:974:19)
at require (internal/modules/cjs/helpers.js:93:18)
at Object.<anonymous> (/app/node_modules/lavaclient/dist/index.js:15:14)
at Module._compile (internal/modules/cjs/loader.js:1085:14)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

Thanks again, and sorry for the bother

**Comment by galnir** [comment]
> > > I still seem to get the error
> > > Error: Error: connect ETIMEDOUT 35.186.245.55:433 at Connection._onerror (C:\Users\user\Documents\GitHub\Rainure\node_modules\lavaclient\dist\lib\node\Connection.js:127:33) at WebSocket.onError (C:\Users\user\Documents\GitHub\Rainure\node_modules\ws\lib\event-target.js:220:18)
> > > Aside from that everything seems to be as it should in replit console, I'm not sure if its possible i have something wrong in the application.yml
> > > Thanks again for your help mate, I really do appreciate it
> > 
> > 
> > Make sure you run the Lavalink server before running the bot
> 
> Hey there, seems to work all good, if it's possible to run this by you quickly, I seem to get this error whenever I try and start the bot,
> 
> /app/node_modules/lavaclient/dist/lib/cluster/Cluster.js:23 this.userId ??= user && (0, Utils_1.getId)(user); ^^^ SyntaxError: Unexpected token '??=' at wrapSafe (internal/modules/cjs/loader.js:1001:16) at Module._compile (internal/modules/cjs/loader.js:1049:27) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) at Module.load (internal/modules/cjs/loader.js:950:32) at Function.Module._load (internal/modules/cjs/loader.js:790:12) at Module.require (internal/modules/cjs/loader.js:974:19) at require (internal/modules/cjs/helpers.js:93:18) at Object. (/app/node_modules/lavaclient/dist/index.js:15:14) at Module._compile (internal/modules/cjs/loader.js:1085:14) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
> 
> Thanks again, and sorry for the bother

What Node version are you running?
```node -v```

**Comment by JackW25** [comment]
> > > > I still seem to get the error
> > > > Error: Error: connect ETIMEDOUT 35.186.245.55:433 at Connection._onerror (C:\Users\user\Documents\GitHub\Rainure\node_modules\lavaclient\dist\lib\node\Connection.js:127:33) at WebSocket.onError (C:\Users\user\Documents\GitHub\Rainure\node_modules\ws\lib\event-target.js:220:18)
> > > > Aside from that everything seems to be as it should in replit console, I'm not sure if its possible i have something wrong in the application.yml
> > > > Thanks again for your help mate, I really do appreciate it
> > > 
> > > 
> > > Make sure you run the Lavalink server before running the bot
> > 
> > 
> > Hey there, seems to work all good, if it's possible to run this by you quickly, I seem to get this error whenever I try and start the bot,
> > /app/node_modules/lavaclient/dist/lib/cluster/Cluster.js:23 this.userId ??= user && (0, Utils_1.getId)(user); ^^^ SyntaxError: Unexpected token '??=' at wrapSafe (internal/modules/cjs/loader.js:1001:16) at Module._compile (internal/modules/cjs/loader.js:1049:27) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) at Module.load (internal/modules/cjs/loader.js:950:32) at Function.Module._load (internal/modules/cjs/loader.js:790:12) at Module.require (internal/modules/cjs/loader.js:974:19) at require (internal/modules/cjs/helpers.js:93:18) at Object. (/app/node_modules/lavaclient/dist/index.js:15:14) at Module._compile (internal/modules/cjs/loader.js:1085:14) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
> > Thanks again, and sorry for the bother
> 
> What Node version are you running? `node -v`

v16.13.0

**Comment by KiyoshiKunCool** [comment]
@JackW25 Did you add `node` into `package.json` (if you're host the bot on heroku) like this?
![Screenshot](https://user-images.githubusercontent.com/69381154/147899198-2b6281a4-0efb-4730-b8c8-53c5ce026187.png)

**Comment by JackW25** [comment]
> @JackW25 Did you add `node` into `package.json` (if you're host the bot on heroku) like this? ![Screenshot](https://user-images.githubusercontent.com/69381154/147899250-479e12b7-aab0-4971-aa1e-fd3eaa285042.png)

That managed to fix the issue, thank you!

Thank you @galnir and @KiyoshiKunCool for your help, I know you guys are probably tired of all the issues I've been having lol, but thank you all for the help,  the new Lavalink update is awesome and I am excited to see what more this project will have.

I now feel happy that my issue is solved, you may reclose the issue if you wish.

Thanks again,
Jack

**Comment by KiyoshiKunCool** [comment]
Glad to help you :3 ☺ 
#KiyoshiKunCool

**Comment by galnir** [comment]
@KiyoshiKunCool Thanks for taking the time to write this helpful guide!
I'm pinning this issue so more people can benefit from it :)

**Comment by liloko** [comment]
when i start the bot, i see this error: Error: Error: connect ECONNREFUSED 35.186.245.55:2333
![Снимок экрана от 2022-02-05 04-36-52](https://user-images.githubusercontent.com/78354559/152643157-8657d6fc-04e9-48bf-a636-3648d8b664ec.png)

**Comment by galnir** [comment]
@liloko Make sure the Lavalink server runs before you attempt to run the bot
