### ISSUE TITLE
Crashing when playing a spotify song.

### ISSUE THREAD

**Issue by AyeYerMa** [galnir/Master-Bot#673]
### IMPORTANT : *DO NOT SKIP THIS STEPS AND DO NOT DELETE THEM. WE CAN NOT HELP YOU IF YOU DO NOT PROVIDE INFORMATION AND STEPS TO REPRODUCE*

Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
The bot (latest version) works fine except for when I try to play a track from Spotify it just closes. Lavalink does not crash, instead it says 'Connection closed from /127.0.0.1:33028 -- CloseStatus[code=1006, reason=]'

**To Reproduce**
1. Run a play command with a spotify link.
2. watch it crash within a second.

**Expected behavior**
It should of course play the requests track from Spotify instead of crashing. 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Node.js Version(Should be v16 at least): v16.10.0 
 - Is python 2.7 installed?: Yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): Locally

**Additional context**

https://user-images.githubusercontent.com/87860151/147929320-b8975991-30e6-47ef-a751-ff0673d0cbc5.mp4

**Comment by galnir** [comment]
@AyeYerMa 
When you invited the bot, did you make sure to check 'application.commands' under OAuth2 > URL generator?

**Comment by AyeYerMa** [comment]
Yeah I have, it can play YouTube links just fine it just crashes immediately upon trying to play a Spotify link. 
The previous version of the bot that doesn't use lavalink can still play Spotify tracks fine but I'd rather the bot be up to date, luckily I still kept the old bot because in case something like this happened.

**Comment by galnir** [comment]
@AyeYerMa Can you share the error you're getting in Node? I can't see it fully on the video

**Comment by AyeYerMa** [comment]
Yep, here ya go, I'm currently in the process of just cloning the bot again in case I missed any steps which I undoubtedly have lol


D:\Hooty Latest>node index.js
Started refreshing application (/) commands.
w[50035]: Invalid Form Body
guild_id[NUMBER_TYPE_COERCE]: Value "undefined" is not snowflake.
    at Z.runRequest (D:\Hooty Latest\node_modules\@discordjs\rest\dist\index.js:7:581)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Z.queueRequest (D:\Hooty Latest\node_modules\@discordjs\rest\dist\index.js:5:2989)
    at async D:\Hooty Latest\index.js:101:5 {
  rawError: {
    code: 50035,
    errors: { guild_id: [Object] },
    message: 'Invalid Form Body'
  },
  code: 50035,
  status: 400,
  method: 'put',
  url: 'https://discord.com/api/v9/applications/887308597871132713/guilds/undefined/commands',
  requestBody: {
    attachments: undefined,
    json: [
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      [Object]
    ]
  }
}

**Comment by galnir** [comment]
You have to wait like 5 minutes for the commands to register

**Comment by galnir** [comment]
Actually no, I've made a mistake in index.js. I forgot to register the commands globally and not in a specific guild(I use it for testing)
Make sure the guild id you've placed in your config json is the same guild id you use the bot in

**Comment by AyeYerMa** [comment]
I haven't got a guild ID in my config.json, only my client ID, how would I go about adding a guild ID to it?
Would it just be "guild_id": "####",  ?

**Comment by galnir** [comment]
@AyeYerMa Yeah and don't add a , if it's the last property in your config.json

**Comment by AyeYerMa** [comment]
Ok so that fixed the error on node but it still crashes when trying to play a link to a spotify song, gonna kick and reinvite the bot see if that changes anything

**Comment by AyeYerMa** [comment]
OMG I forgot there's two readme's, I was following the one on here instead of the one in the actual bot -_-
Excuse my idiocy please lol

**Comment by galnir** [comment]
@AyeYerMa Add both keys and you're good to go :)

**Comment by AyeYerMa** [comment]
Yes it's working great now, thank you and keep up the good work, I noticed this version of the bot has higher audio quality and can handle higher volumes without distortion too which is very welcome lol

**Comment by galnir** [comment]
> Yes it's working great now, thank you and keep up the good work, I noticed this version of the bot has higher audio quality and can handle higher volumes without distortion too which is very welcome lol

Yeah that's why I rewrote the music system using lavalink
