### ISSUE TITLE
Errors when i run npm run dev

### ISSUE THREAD

**Issue by QuantaNeon** [galnir/Master-Bot#677]
**Describe the bug**
I followed the wiki..did everything...now when i run npm run dev it says found 178 errors..

**To reprodice**
1 git clone the repo
2 run lavalink
3 do the config
4 npm run dev

**Screenshots**
![image](https://user-images.githubusercontent.com/84242952/152641970-2f1c1b73-0997-4c74-a474-ab98ea4e036e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Node.js Version: 16.13.2
 - Is python 2.7 installed?: yes
 - How are you hosting the bot: vps

**Comment by galnir** [comment]
@QuantaNeon I accidentally changed sapphire's framework version to one that doesn't support application commands

Pull the new changes or clone the repo again and it should work

**Comment by galnir** [comment]
If the issue still persist comment here and ill reopen the issue
