### ISSUE TITLE
Index.js file missing?

### ISSUE THREAD

**Issue by AyeYerMa** [galnir/Master-Bot#678]
So I cloned the new bot because there'd been quite a few updates since I last did and a lot of stuff seems to be in SRC now except I don't have an index.js file and the old one won't work with the new one. I have an index.ts file should I rename it or is the readme outdated?

**Comment by PhantomNimbi** [comment]
You need to run `npm run dev` after placing your `LavaLink.jar`, `config.json` and `application.json` into the `src` folder. 
That seems to be how it runs now.

**Comment by galnir** [comment]
@AyeYerMa I have rewritten the bot in TypeScript which is a superset of JavaScript. TypeScript files end with .ts and need to be compiled to JavaScript.

What PhantomNimbi wrote above is correct, you need to get a Lavalink.jar and application.yml in the project's root directory and move the config.json file into the src folder. I suggest you follow the README for the instructions. If you have any questions or issues let me know
