### ISSUE TITLE
The url argument must be a type string

### ISSUE THREAD

**Issue by Burday** [galnir/Master-Bot#68]
I was wondering if this was a global issue, since it doesn't appear to be from any of the code which seems to be relevant. Error occurs randomly while playing songs or music trivia. 

Error code:
`TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined

    at validateString (internal/validators.js:120:11)

    at Url.parse (url.js:159:3)

    at Object.urlParse [as parse] (url.js:154:13)

    at doDownload (D:\CommandoBot\node_modules\miniget\dist\index.js:90:28)

    at processTicksAndRejections (internal/process/task_queues.js:79:11) {

  code: 'ERR_INVALID_ARG_TYPE'`

**Comment by galnir** [comment]
@Burday Did you edit any code yourself? I've never seen this error before. Can that be reproduced?

**Comment by Burday** [comment]
I'm running the exact same code as the one from the repo. I will try to reproduce it again. It's hosted on a Windows machine

**Comment by Linguine92** [comment]
I have the same problem

**Comment by galnir** [comment]
@Burday @Linguine92 Can you paste here the full error message?

**Comment by galnir** [comment]
Seems like this is a ytdl-core error which has been fixed in the package's new update. I'm pushing an update to package.json.
Pull the new changes and hit 'npm i'
