### ISSUE TITLE
Can't Play Music - PostgreSQL Permissions Error

### ISSUE THREAD

**Issue by PhantomNimbi** [galnir/Master-Bot#693]
## Describe the bug
Can't play music due to `PostgreSQL` error. It keeps throwing this error:
```js
PrismaClientInitializationError:
  Invalid `prisma.user.upsert()` invocation:
     User `SocketBot` was denied access on the database `master-bot.public`
```

## To Reproduce
**1**. Use the `/play` command
**2**. provide a song

## Expected behavior
It should play the song

## Screenshots
Ignore the timestamp on this response. I had the date on my PC set wrong lol.
![](https://user-images.githubusercontent.com/17615050/162343293-8f9ad3e3-ef07-44b5-b863-7ba1c63c10a7.png)

## Desktop
 * **OS**: `AlmaLinux 8`
 * **Node.js Version**: `16.3.1`
 * **Is python 2.7 installed?**: `Yes`
 * **How are you hosting the bot**: `VPS`

## Additional context
**Console Log**:

```js
> master-bot@1.0.0 dev
> npm run build && npm run start


> master-bot@1.0.0 build
> tsc


> master-bot@1.0.0 start
> node dist/index.js

[INFO] ApplicationCommandRegistries: Initializing...
[INFO] ApplicationCommandRegistries: Took 731ms to initialize.
PrismaClientInitializationError: 
Invalid `prisma.user.upsert()` invocation:


  User `SocketBot` was denied access on the database `master-bot.public`
    at Object.request (/home/almalinux/SocketBot/Master-Bot/node_modules/@prisma/client/runtime/index.js:39824:15)
    at async PrismaClient._request (/home/almalinux/SocketBot/Master-Bot/node_modules/@prisma/client/runtime/index.js:40649:18)
    at async UserInDB.chatInputRun (/home/almalinux/SocketBot/Master-Bot/dist/preconditions/UserInDB.js:12:13)
    at async Object.chatInputSequential (/home/almalinux/SocketBot/Master-Bot/node_modules/@sapphire/framework/dist/lib/utils/preconditions/conditions/PreconditionConditionAnd.js:26:28)
    at async CoreListener.run (/home/almalinux/SocketBot/Master-Bot/node_modules/@sapphire/framework/dist/listeners/application-commands/chat-input/CorePreChatInputCommandRun.js:19:29)
    at async fromAsync (/home/almalinux/SocketBot/Master-Bot/node_modules/@sapphire/framework/dist/lib/parsers/Result.js:52:19)
    at async CoreListener._run (/home/almalinux/SocketBot/Master-Bot/node_modules/@sapphire/framework/dist/lib/structures/Listener.js:93:24) {
  clientVersion: '3.11.1',
  errorCode: undefined
}
```
**.env**:
I replaced the password with `12345` to keep my db password secure.
```.env
# Environment variables declared in this file are automatically made available to Prisma.
# See the documentation for more detail: https://pris.ly/d/prisma-schema#accessing-environment-variables-from-the-schema

# Prisma supports the native connection string format for PostgreSQL, MySQL, SQLite, SQL Server, MongoDB (Preview) and CockroachDB (Preview).
# See the documentation for all the connection string options: https://pris.ly/d/connection-strings

DATABASE_URL="postgresql://SocketBot:12345@localhost:5432/master-bot?schema=public"
```

**Comment by galnir** [comment]
Try
```npx prisma db pull```

**Comment by PhantomNimbi** [comment]
> Try `npx prisma db pull`

Didn't work...

```js
[almalinux@NimbiDiscord Master-Bot]$ npx prisma db pull
Prisma schema loaded from prisma/schema.prisma
Environment variables loaded from .env
Datasource "db": PostgreSQL database "master-bot", schema "public" at "localhost:5432"

Introspecting based on datasource defined in prisma/schema.prisma …

Error: P1010

User `SocketBot` was denied access on the database `master-bot.public`
```

**Comment by PhantomNimbi** [comment]
hmmm looks like it never created the database in my postgesql setup....

```node
postgres=# \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges
-----------+----------+----------+-------------+-------------+-----------------------
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/postgres         +
           |          |          |             |             | postgres=CTc/postgres
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
(3 rows)

postgres=#
```

**Comment by galnir** [comment]
@PhantomNimbi My bad, I forgot to add this step in the README
```
npx prisma migrate dev
```

**Comment by PhantomNimbi** [comment]
> @PhantomNimbi My bad, I forgot to add this step in the README
> 
> ```
> npx prisma migrate dev
> ```

Not working. Still claiming that the user is denied access to the database.

**Comment by galnir** [comment]
> > @PhantomNimbi My bad, I forgot to add this step in the README
> > ```
> > npx prisma migrate dev
> > ```
> 
> Ok that went through without triggering an error. However it's still denying access to the database.
> 
> **Log File**: [debug-2022.04.15-03.49.55.log](https://github.com/galnir/Master-Bot/files/8493728/debug-2022.04.15-03.49.55.log)

The DATABASE_URL env variable's name needs to be your OS's username
```
DATABASE_URL="postgresql://yourOSname:doe@localhost:5432/master-bot?schema=public"
```

If that doesn't work, set the password to the os's name as well

```
DATABASE_URL="postgresql://yourOSname:yourOSname@localhost:5432/master-bot?schema=public"
```

**Comment by PhantomNimbi** [comment]
> > > @PhantomNimbi My bad, I forgot to add this step in the README
> > > ```
> > > npx prisma migrate dev
> > > ```
> > 
> > 
> > Ok that went through without triggering an error. However it's still denying access to the database.
> > **Log File**: [debug-2022.04.15-03.49.55.log](https://github.com/galnir/Master-Bot/files/8493728/debug-2022.04.15-03.49.55.log)
> 
> The DATABASE_URL env variable's name needs to be your OS's username
> 
> ```
> DATABASE_URL="postgresql://yourOSname:doe@localhost:5432/master-bot?schema=public"
> ```
> 
> If that doesn't work, set the password to the os's name as well
> 
> ```
> DATABASE_URL="postgresql://yourOSname:yourOSname@localhost:5432/master-bot?schema=public"
> ```

I tried that as well. No change. Still claims `user 'socket' was denied access on the database 'master-bot.public'` and I'm running it from the `socket` user.

**Comment by galnir** [comment]
> > > > @PhantomNimbi My bad, I forgot to add this step in the README
> > > > ```
> > > > npx prisma migrate dev
> > > > ```
> > > 
> > > 
> > > Ok that went through without triggering an error. However it's still denying access to the database.
> > > **Log File**: [debug-2022.04.15-03.49.55.log](https://github.com/galnir/Master-Bot/files/8493728/debug-2022.04.15-03.49.55.log)
> > 
> > 
> > The DATABASE_URL env variable's name needs to be your OS's username
> > ```
> > DATABASE_URL="postgresql://yourOSname:doe@localhost:5432/master-bot?schema=public"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If that doesn't work, set the password to the os's name as well
> > ```
> > DATABASE_URL="postgresql://yourOSname:yourOSname@localhost:5432/master-bot?schema=public"
> > ```
> 
> I tried that as well. No change. Still claims `user 'socket' was denied access on the database 'master-bot.public'` and I'm running it from the `socket` user.
> 
> I even tried setting it to ` DATABASE_URL="postgresql://root:root@localhost:5432/master-bot?schema=public"` to try and force the access but it still gives the same error.
> 
> At this point I'm starting to think this is an old Prisma issue that never got fixed because I've seen people having this issue on another post in Prisma's official github.
> 
> * Prisma Github: [Issue#4520](https://github.com/prisma/prisma1/issues/4520?msclkid=7c74a550bea811ecb76f8698a8ad9699)

I looked at the screenshot you posted above and from there it seems your OS username is NimbiDiscord

**Comment by PhantomNimbi** [comment]
> > > > > @PhantomNimbi My bad, I forgot to add this step in the README
> > > > > ```
> > > > > npx prisma migrate dev
> > > > > ```
> > > > 
> > > > 
> > > > Ok that went through without triggering an error. However it's still denying access to the database.
> > > > **Log File**: [debug-2022.04.15-03.49.55.log](https://github.com/galnir/Master-Bot/files/8493728/debug-2022.04.15-03.49.55.log)
> > > 
> > > 
> > > The DATABASE_URL env variable's name needs to be your OS's username
> > > ```
> > > DATABASE_URL="postgresql://yourOSname:doe@localhost:5432/master-bot?schema=public"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > If that doesn't work, set the password to the os's name as well
> > > ```
> > > DATABASE_URL="postgresql://yourOSname:yourOSname@localhost:5432/master-bot?schema=public"
> > > ```
> > 
> > 
> > I tried that as well. No change. Still claims `user 'socket' was denied access on the database 'master-bot.public'` and I'm running it from the `socket` user.
> > I even tried setting it to ` DATABASE_URL="postgresql://root:root@localhost:5432/master-bot?schema=public"` to try and force the access but it still gives the same error.
> > At this point I'm starting to think this is an old Prisma issue that never got fixed because I've seen people having this issue on another post in Prisma's official github.
> > 
> > * Prisma Github: [Issue#4520](https://github.com/prisma/prisma1/issues/4520?msclkid=7c74a550bea811ecb76f8698a8ad9699)
> 
> I looked at the screenshot you posted above and from there it seems your OS username is NimbiDiscord I had the same issue on my Mac and changing the connection string user to my Mac user solved it

Will test and see if that works. Not sure why it has that as the OS user when the login user wasn't that lol.

**Comment by galnir** [comment]
> > > > > > @PhantomNimbi My bad, I forgot to add this step in the README
> > > > > > ```
> > > > > > npx prisma migrate dev
> > > > > > ```
> > > > > 
> > > > > 
> > > > > Ok that went through without triggering an error. However it's still denying access to the database.
> > > > > **Log File**: [debug-2022.04.15-03.49.55.log](https://github.com/galnir/Master-Bot/files/8493728/debug-2022.04.15-03.49.55.log)
> > > > 
> > > > 
> > > > The DATABASE_URL env variable's name needs to be your OS's username
> > > > ```
> > > > DATABASE_URL="postgresql://yourOSname:doe@localhost:5432/master-bot?schema=public"
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > If that doesn't work, set the password to the os's name as well
> > > > ```
> > > > DATABASE_URL="postgresql://yourOSname:yourOSname@localhost:5432/master-bot?schema=public"
> > > > ```
> > > 
> > > 
> > > I tried that as well. No change. Still claims `user 'socket' was denied access on the database 'master-bot.public'` and I'm running it from the `socket` user.
> > > I even tried setting it to ` DATABASE_URL="postgresql://root:root@localhost:5432/master-bot?schema=public"` to try and force the access but it still gives the same error.
> > > At this point I'm starting to think this is an old Prisma issue that never got fixed because I've seen people having this issue on another post in Prisma's official github.
> > > 
> > > * Prisma Github: [Issue#4520](https://github.com/prisma/prisma1/issues/4520?msclkid=7c74a550bea811ecb76f8698a8ad9699)
> > 
> > 
> > I looked at the screenshot you posted above and from there it seems your OS username is NimbiDiscord I had the same issue on my Mac and changing the connection string user to my Mac user solved it
> 
> Will test and see if that works. Not sure why it has that as the OS user when the login user wasn't that lol.
> 
> --- edit ---
> 
> Nope still doesn't work...
> 
> ```shell
> DATABASE_URL="postgresql://NimbiDiscord:doe@localhost:5432/master-bot?schema=public"
> ```
> 
>  ```js
> Error: P1010: User `NimbiDiscord` was denied access on the database `master-bot.public`
> ```
> 
>  ```shell
> DATABASE_URL="postgresql://NimbiDiscord:NimbiDiscord@localhost:5432/master-bot?schema=public"
> ```
> 
>  ```js
> Error: P1010: User `NimbiDiscord` was denied access on the database `master-bot.public`
> ```
> 
> Perhaps it might be better to specify the login info via the `.env` file as well as the connection string to avoid issues like this one if possible? It might be a better method since it can be used for both creating the database and logging into it.
> 
> **Example**:
> 
> ```shell
> DATABASE_USER="john"
> DATABASE_PASSWORD="doe"
> DATABASE_NAME="master-bot"
> DATABASE_ADDRESS="127.0.0.1"
> DATABASE_PORT="5432"
> DATABASE_URL="postgresql://john:doe@127.0.0.1:5432/master-bot?schema=public"
> ```
> 
> Not to mention it's also more secure than defaulting to the OS name since the username and password can be manually set this way.
> 
> Another thing I'm beginning to wonder is if this actually creates the database or if I need to manually download a Prisma server docker image to use with this.

I'll check this out on my Windows machine and get back to you with a solution

**Comment by galnir** [comment]
@PhantomNimbi Okay so getting Prisma to connect to a local Postgres db on Windows is a major pain. I will update the README with instructions on how to host Postgres on Heroku, it takes like 5 min to setup and runs really well and you can also use the same credentials on different machines so you have the same db no matter where you run the bot

**Comment by galnir** [comment]
@PhantomNimbi Try following the new instructions and lemme know if it works :)

**Comment by galnir** [comment]
@PhantomNimbi Lemme know if you experienced issues getting Postgres to work on the cloud or with bacon's solution

**Comment by PhantomNimbi** [comment]
Sorry for the late response. Just saw the updates. My PC was down.
