### ISSUE TITLE
Loop-command does not loop

### ISSUE THREAD

**Issue by KungfuPancake** [galnir/Master-Bot#70]
If I use the loop command on the currently playing song, said song will be added to the queue one more time - but it does not loop. The bot leaves after playing the song a second time.

Is this the intended behavior?

**Comment by galnir** [comment]
Yeah this is intended

**Comment by KungfuPancake** [comment]
Thank you for the quick feedback!

**Comment by Natemo6348** [comment]
@galnir if I wanted it to loop continuously, how could I change it to do so?

**Comment by galnir** [comment]
@KungfuPancake @Natemo6348 Pull the new changes, you can now specify how many times you want the song to loop(!loop x). If no argument is provided the song will loop once
