### ISSUE TITLE
Help Command Hanging - The application did not respond

### ISSUE THREAD

**Issue by PhantomNimbi** [galnir/Master-Bot#729]
**Describe the bug**

**To Reproduce**
1. Use `/help` command
2. provide any argument

**Expected behavior**
Should display the help command response.

**Screenshots**

![](https://who.is-yiffing.me/FS6d2V-bxx.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...]: AlmaLinux
 - Node.js Version(Should be v16 at least): 16.13.11
 - Is python 2.7 installed?: Yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): VPS

**Additional context**

I've tried both with and without the command arguments but it has the same response every time. 
`The application did not respond`

**Comment by PhantomNimbi** [comment]
> Howdy friend, I am having some troubles replicating the issue in main or dashboard branches and have a few additional questions.
> 
> Is there an error in console? If not, Is `/src/commands/other/help.ts` present on the host?
> 
> Confusingly, previously registered slash commands will still show up as if they are available even when the bot was compiled/launched without the commands file(`help.ts`), this situation is known to exhibit this behavior (no console error, and `The application did not respond` discord message)
> 
> Much Love -Bacon

Will have to look and see. was assuming it was there since the recent push supposedly added it but maybe not. I'll check right now.

**Comment by Bacon-Fixation** [comment]
Nice! Glad to hear everything is working

If you have any other issues, feel to make a post, and we will try and sort them out  <3

Much Love
-Bacon
