### ISSUE TITLE
Cmd gives me an error

### ISSUE THREAD

**Issue by KastroMugnaio** [galnir/Master-Bot#74]
Hi, when I try to start the bot I get an error message: Unexpected token / in JSON at 21 position at parse, but going to check on that line there is no command string ... How do I solve?
![Desktop Screenshot 2020 05 14 - 09 34 33 100](https://user-images.githubusercontent.com/65294975/81906294-4b714880-95c6-11ea-9ad8-858e886aa9d4.png)

**Comment by galnir** [comment]
You didn't place the api keys correctly, make sure it's between " "
Look at the example in the readme

**Comment by KastroMugnaio** [comment]
Yes, I have already checked and everything is fine

**Comment by galnir** [comment]
Take a pic of your config.json and blur or cut the api keys

**Comment by KastroMugnaio** [comment]
![Desktop Screenshot 2020 05 14 - 10 58 54 02](https://user-images.githubusercontent.com/65294975/81914824-18cd4d00-95d2-11ea-8562-1599db4c5f07.png)

**Comment by galnir** [comment]
Remove the ; from the end of the last api key

**Comment by KastroMugnaio** [comment]
Thanks
