### ISSUE TITLE
Dashboard Login issue

### ISSUE THREAD

**Issue by Bacon-Fixation** [galnir/Master-Bot#741]
Found this during Docker PR testing, so I reran the current main branch. It doesn't seem to matter how I host, the issue is the same.
I'm not sure how to fix, so I'm posting an issue <3

#### Issue
* It stopped asking to log in (even when clearing browser data)
* It doesn't matter who (not bot owner) goes to `http://www.dashboard.com:3000/` (example) it shows the guilds of the bot owner only, and others can adjust the bot owner's guild bot settings.

 
#### Steps To Replicate
  * access dashboard on 2 or more different machines (can be local network)

#### Setup
 * Node: 16.16
 * Host: Windows 10/11, Debian Arm64, Docker
 * Build: [99fb3ba](https://github.com/galnir/Master-Bot/commit/99fb3bad60e5cef973bd061aa7e832ad1f4d86bc)
   

Much Love
-Bacon

**Comment by galnir** [comment]
Can you try to reproduce it on the latest commit?

**Comment by galnir** [comment]
Let me know if it works after the latest commit

**Comment by Bacon-Fixation** [comment]
@galnir Nice, it is fixed, Thank you 


Much Love
-Bacon
