### ISSUE TITLE
Error after Installation and the first boot

### ISSUE THREAD

**Issue by TrueMB** [galnir/Master-Bot#748]
Getting following error after installing the Bot on a Linux server.
NEXT_PUBLIC_INVITE_URL is set, and the client ID was changed.
Not quite sure where to look for the mistake of mine.

Dependencies should all be installed.

Errors: https://pastebin.com/0b2jyMSu

**Comment by Bacon-Fixation** [comment]
Howdy, was able to replicate this error message

Make sure the `.env` is in the root folder, and run `npm run dev` in root folder. 

I get this error when i try to start the dashboard and bot separately with `.env` in the wrong folder

i hope this helps

Much Love
-Bacon

**Comment by TrueMB** [comment]
![image](https://user-images.githubusercontent.com/25579052/189728210-9ede05ac-eeda-470c-9324-e5759affa841.png)
![image](https://user-images.githubusercontent.com/25579052/189728573-175a6061-99ae-43e5-9954-ba38991e921c.png)

This should be correct :?

**Comment by Bacon-Fixation** [comment]
Yep yep, that is the correct place for the `.env`, 
I'm not sure why the `src` folder is there tho. Maybe try cloning the repo to a new folder, and copy over your `.env`, and run the `npm i`, then `npm run dev`, and see if you get this error again.

 I am curious if this is from a `git pull` that possibly failed

Much Love
-Bacon

**Comment by TrueMB** [comment]
I think there was a problem after I cloned the repo in the past. Yesterday I wanted to update and run the new bot. That seemed to run with no problems.

I deleted the directory and cloned the repo again. Now the source folder is gone, but the problem still exists.

![grafik](https://user-images.githubusercontent.com/25579052/189869998-fcbd306a-8f3d-405f-b579-61be226c1f64.png)

![grafik](https://user-images.githubusercontent.com/25579052/189869952-d31a2199-aedd-4c2d-b7ee-f50b2c25f6f6.png)

**Comment by galnir** [comment]
@TrueMB Does your .env look like [.env.example](https://github.com/galnir/Master-Bot/blob/main/.env.example)?
You have files that are not in the repo like start_Masterbot.sh and you shouldn't be running the bot in this way. If you clone the repo and follow the readme you will get the bot running in a short time

**Comment by TrueMB** [comment]
Yes, I followed the instructions as far as I could understand it.
I copied the values from the .env file also in a new copy of the .env.example, since I wasn't sure, if it was the newest. Ofc I renamed it again .env.
I also use in my tests the named command above. I plan on the future to start the bot through a screen command (this is what the file does), but not yet.

**Comment by Bacon-Fixation** [comment]
been trying to match the Errors more exact, 
i was able to get both sets of errors to appear when there is a `$` in the `NEXT_PUBLIC_INVITE_URL` url string.
https://pastebin.com/TJwnD9qm (Replicated Error with .env in proper place and followed README as presented)


I'm not sure if this info is helpful,

Much Love
-Bacon

**Comment by TrueMB** [comment]
> I'm not sure if this info is helpful,
> Sidenote - `$` in the url will trigger both these errors, BUT `${whatever}`, `${}`, or `\$` in the url will not trigger any errors at build
> , oddly if there is a `$` in the `DATABASE_URL` will still give these errors for the `NEXT_PUBLIC_INVITE_URL`, despite the `$` being in the DB URL string

This Information was very helpful. The links there alright, but the password contained a $. After removing it, it worked like it should. Thank you very much once again Bacon!

**Comment by galnir** [comment]
> > I'm not sure if this info is helpful,
> > Sidenote - `$` in the url will trigger both these errors, BUT `${whatever}`, `${}`, or `\$` in the url will not trigger any errors at build
> > , oddly if there is a `$` in the `DATABASE_URL` will still give these errors for the `NEXT_PUBLIC_INVITE_URL`, despite the `$` being in the DB URL string
> 
> This Information was very helpful. The links were alright, but the password contained a $. After removing it, it worked like it should. Thank you very much once again Bacon!

Awesome, enjoy!
@Bacon-Fixation great stuff!
