### ISSUE TITLE
Having trouble running the bot on Windows 10

### ISSUE THREAD

**Issue by PhantomNimbi** [galnir/Master-Bot#751]
docker compose doesn't work in debian stretch on WSL in Windows 10.

`compose` isn't a subcommand of `docker` and `--env-file` isn't even an option in `docker-compose` on debian 9 for WSL.

 * **Screenshot**:
![image](https://user-images.githubusercontent.com/17615050/190040991-f2075183-ca84-4bc9-906d-997b1aecd0df.png)

**Comment by galnir** [comment]
I'm pretty sure you need to install [docker compose](https://www.digitalocean.com/community/tutorials/how-to-install-docker-compose-on-debian-10) in addition, that's at least how I did it once

**Comment by Bacon-Fixation** [comment]
i updated the commands from that url, as it installs v1 legacy, should technically work but i only tested on v2 of compose
(tested the following inside deb 9 stretch Docker container)
```
sudo curl -L https://github.com/docker/compose/releases/download/v2.11.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
```

Much Love
-Bacon

**Comment by galnir** [comment]
@PhantomNimbi Did you manage to get it working?

**Comment by PhantomNimbi** [comment]
> @PhantomNimbi Did you manage to get it working?

Yolo, sorry for the late reply haven't been able to access my PC in a while. Bout to test it now.

**Comment by PhantomNimbi** [comment]
Got it to run in a Debian 10 Docker image .. however the only thing I can't access this way is the Dashboard. Although the ports are definitely open my browser is ubale to find the webpage when trying to access it.

**Comment by PhantomNimbi** [comment]
and i got it to work. Had to swap a few things over. Instead of hosting a Debian Docker container for it I simply ran redis and postgres in their own docker containers and used those for the bot. 

Now both the bot and the dashboard are working perfectly =)

**Comment by Bacon-Fixation** [comment]
im sorta confused, are you running the master-bot docker container inside a Debian 10 container ?

the Dockerfile in the root folder was set up to be run without docker-compose

Dockerfile (in root) Lines 10 - 15 for Non compose uses
```
# Install for Docker-Compose (Excluding "postinstall")
# RUN npm ci --development --ignore-scripts
# RUN ["npx", "prisma", "generate", "dev"]

# Install for Standalone Dockerfile use (comment out the 2 lines above and uncomment the line below)
RUN npm ci --development 
```

Much Love
-Bacon
