### ISSUE TITLE
Welcome Message still there?

### ISSUE THREAD

**Issue by TrueMB** [galnir/Master-Bot#758]
Hello!

Am I missing the feature or did it change?
I found the listener, but I cant find the command to set the message again. And also found nothing about adding thr feature back.

**Comment by Bacon-Fixation** [comment]
Howdy, welcome message settings are in the dashboard  `http://localhost:3000` (orwhat ever you `NEXTAUTH_URL` is ) you can select your guild and the welcome message setting should be the top option on the left

![image](https://user-images.githubusercontent.com/12632936/192148220-bcb1fb2b-fc4e-435e-bc48-e9ed53498113.png)

Hope this helps

Much Love
-Bacon

**Comment by TrueMB** [comment]
Ahh that explains it. I already looked once into the website, but only could find adding the bot to the discord server.

Now there is nothing:
![image](https://user-images.githubusercontent.com/25579052/192153009-8fb05c65-1708-4aef-a5cb-8defdf038056.png)

**Comment by Bacon-Fixation** [comment]
Click on dashboard again after you login to see the guild selection page, what once said "invite" should now say "go", clicking on "go" should take you to your bot settings for that guild.


Much Love
-Bacon

**Comment by TrueMB** [comment]
![image](https://user-images.githubusercontent.com/25579052/192163377-bb1a1c09-07a7-4aa7-9c46-5acb7d433e64.png)
Nothing there :(

**Comment by galnir** [comment]
> ![image](https://user-images.githubusercontent.com/25579052/192163377-bb1a1c09-07a7-4aa7-9c46-5acb7d433e64.png)
> Nothing there :(

Yeah this is a bug I'm working on, to solve this now:
Keep the bot running, kick it out of your server and then invite it

**Comment by galnir** [comment]
@TrueMB 
Hey, make sure your NEXT_PUBLIC_INVITE_URL looks like this:
```
NEXT_PUBLIC_INVITE_URL="https://discord.com/api/oauth2/authorize?client_id=yourclientid&permissions=8&scope=identify+guilds+email+applications.commands.permissions.update"
```
switch yourclientid with your client id

Let me know if it solves the issue

**Comment by TrueMB** [comment]
Changing only this didn't seem to work.

I would like to refresh the database.
Recreating was not the issue in Postgres, but the tables seem now to be missing. 
Did I forget something?

**Comment by galnir** [comment]
> Changing only this didn't seem to work.
> 
> I would like to refresh the database. Recreating the database was not the issue in Postgres, but the tables seem now to be missing. The Bot was restarted afterwards.
> 
> Did I forget something?

If you have a fresh DB, kick the bot from your server, start the bot and then invite it again.
The issue is related to Discord's access tokens I'll see what I can do about it

**Comment by TrueMB** [comment]
I kicked the Bot from the Server, but the errors doesn't seem to be related with it.
https://pastebin.com/gvVNgrNQ

**Comment by TrueMB** [comment]
Seems to work now.

What doesn't work, is the oauth Link:
![grafik](https://user-images.githubusercontent.com/25579052/192741417-9123ee89-e052-44d0-a4ec-f2073fb8d2cc.png)

My Discordname, if relevant: JacksonUndercover#7801

**Comment by TrueMB** [comment]
https://discord.com/api/oauth2/authorize?client_id=%clienid%&permissions=8&scope=bot

Fixed the Issue for now.
