### ISSUE TITLE
Alternative Postgres Hosting

### ISSUE THREAD

**Issue by phantomic12** [galnir/Master-Bot#766]
As you may know, Heroku's free tier will be discontinued as of November 28th, are there any other alternate means to host a postgres database without being charged?

**Comment by Bacon-Fixation** [comment]
you can run a PostgreSQL DB locally via their Application or in a Docker Container

#### has a free options (with limitations)
- HelioHost
- ElephantSQL
- Amazon RDS 
- Bit.io
- Fly.io
- CockroachDB

Much Love
-Bacon

**Comment by phantomic12** [comment]
I will definitely look into these, I appreciate it!

**Comment by galnir** [comment]
> I will definitely look into these, I appreciate it!

I can also recommend Railway
