### ISSUE TITLE
Unable to run BOT after following setup bot guides

### ISSUE THREAD

**Issue by amirshah2935** [galnir/Master-Bot#767]
Hi im unable to run the bot after i followed all the instructions, i guess i have misses something but im not sure how to tackle this.

attached below is my errors i received, after a few trial ..i think i may have missed it on the REDIS part where it just said download  so im not sure what i need to do there if you can help me with this step . really appreciated.

[error after run.txt](https://github.com/galnir/Master-Bot/files/9806789/error.after.run.txt)

**Comment by Bacon-Fixation** [comment]
Howdy @amirshah2935 

First things first, I highly recommend regenerating your tokens for your `.env` file, as they are private credentials and should not be shared.

For windows, I recommend installing [docker desktop](https://www.docker.com/products/docker-desktop/) 
after installation, 
launch docker desktop,
installing the redis server by running `docker run --name master-bot-redis -d redis redis-server --save 60 1 --loglevel warning` in your console.

now when you bring back up Docker Desktop you should see `master-bot-redis` appear in the containers tab you, can use this to confirm that the redis server is installed and/or running.

i hope this helps 

Much Love
-Bacon

**Comment by amirshah2935** [comment]
Hi, 

thanks for your promp reply, im gonna test it and update if this is working for me, and yeap i just thought about it yesterday , will be regenerating new token, thanks again for the advise.

regards

**Comment by amirshah2935** [comment]
Hi @Bacon-Fixation,

I manage to install Docker Desktop and run The Master-Bot-Redis, shown as running in the container, how do i go on after this, as im trying again, to npm run dev from my terminal, it shows the same error like its not connected with the Docker-Redis

please advise.

**Comment by Bacon-Fixation** [comment]
I have a couple of questions, maybe help narrow down the issue a bit better

Are you running the bot on the same pc as the Redis server?

Is the Redis server running before you run the `npm run dev` command?

In docker desktop is there a port listed? 
![image](https://user-images.githubusercontent.com/12632936/196899723-fc3d96b7-f6a2-466a-bbdf-a4255dcc871c.png)

Much Love
-Bacon

**Comment by amirshah2935** [comment]
yes im running the bot on the same place as the redis server/ docker desktop.

it is shown as running as per ur image there...somehow the ports number is not there and i have fixed it with other command, somehow its works. Thanks a lot..but more error coming..

after running the bots and try to send some /play query, i got some prisma:query error as below image. saying guild not found,  i think is due to my bot permission or something but not sure if its correct or not.

![image](https://user-images.githubusercontent.com/38003845/197119569-fc480a29-ec23-4c50-8969-d1ece6c58ac5.png)

**Comment by galnir** [comment]
> Managed to replicate your error
> 
> ```
> [0] prisma:query SELECT 1
> [0] prisma:query SELECT "public"."Guild"."id", "public"."Guild"."disabled_commands" FROM "public"."Guild" WHERE "public"."Guild"."id" = $1 LIMIT $2 OFFSET $3
> [1] 10-21-2022 07:53:15 error: Client Listener TRPCClientError: Guild not found
> [1] 10-21-2022 07:53:15 error: Client Listener TRPCClientError: Guild not found
> ```
> 
> Seems that the bot was invited to your discord server when the bot wasn't running,
> 
> with Master-Bot running, kick the bot for your discord server and re-inviting the bot through the bots dashboard http://localhost:3000
> 
> or
> 
> with Master-Bot running, kick the bot for your discord server and re-inviting the bot with the `NEXT_PUBLIC_INVITE_URL` that you made for the `.env` file
> 
> Much Love -Bacon

Yeah I hope to overcome this issue, Discord's API giving me a hard time with this one and I'm also short on time to figure it out quickly

**Comment by amirshah2935** [comment]
Hi Bacon, 

I love you so much muahh.. Thanks and appreciate your time in guiding me ..

regards,

**Comment by Bacon-Fixation** [comment]
You are very welcome my friend, if you have any other issues, feel free to open a new post, and we will try and figure it out.

Much Love
-Bacon
