### ISSUE TITLE
Unable to start up bot

### ISSUE THREAD

**Issue by zFlashPvPz** [galnir/Master-Bot#768]
Hey, I'm having issues with starting up the bot where I'll run into multiple errors in regards to dependencies and have to manually install them sometimes  which are normally easily resolved after i force install them but the main issue here is this one. I've been stuck on this for about a day and half now and not sure on what to do here.

![image](https://user-images.githubusercontent.com/66215562/203391300-2157f652-112c-49a5-ae47-c8877d611ee3.png)

Manually made the .env file and did the Readme steps properly after cloning the git and unable to start bot on npm run dev.

Expected behavior:
Bot should've started up as per normal and I'm not sure on why this is happening. I
- OS: Ubuntu 20.04 LTS
- Node.js Version: 19.1.0
- Is python 2.7 installed?: Yes
- How are you hosting the bot): Oracle Cloud's Free tier Arm A1 Ampere compute.

**Comment by galnir** [comment]
Can you try running the bot in Node 16 or 18?

**Comment by zFlashPvPz** [comment]
Hey I was running on NodeJs 18 for the first attempts anyways and mistakenly thought that I was using NodeJs v19.1.0 because of the lines nearing the end of the crash, and I've attached a screenshot of all 3 versions of NodeJS (16,18 and 19) respectively and the same error occurs, not sure on why.

![image](https://user-images.githubusercontent.com/66215562/203500665-8ec50e6c-b63f-4c8f-b8b1-c0754cb736f3.png)
![image](https://user-images.githubusercontent.com/66215562/203501248-ac8769da-5921-4735-b4b5-486ea80361cd.png)
![image](https://user-images.githubusercontent.com/66215562/203501678-b55739cb-2570-4a06-8314-92484dcfd502.png)

**Comment by Bacon-Fixation** [comment]
Make sure Nodejs 19 is fully uninstalled, in all of the logs posted node 19.1.0 was used, it is strange that `node -v` say different versions, but the Version that tried to run `npm run dev` was 19.1.0.

``` 
Node.js v19.1.0
[1] npm ERR! Lifcycle script `start` failed with error:
```


Hope this helps

Much Love 
-Bacon

**Comment by Bacon-Fixation** [comment]
another thing to try if you are still having issues is to specify the Node Version in the `/Master-Bot/packagge.json` by adding the following
```
  "engines": {
    "node": ">=16.0.0 <19.0.0"
  },
```

it will make sure that the Nodejs version is between 16 and 18, it will pick the highest version number that sits between those values

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
howdy @zFlashPvPz , just wanted to catch up with you and see if your issue was resolved, or if you need additional assistance.

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Howdy @zFlashPvPz, gunna close this issue.
If you are still having troubles, please feel free to open new issue

Much Love
-Bacon
