### ISSUE TITLE
Bot kicked from Voice channel

### ISSUE THREAD

**Issue by R3rt0** [galnir/Master-Bot#77]
Hi,
I found issue relying on kicking bot (by admin) from voice channel. Bot think that he's in channel and he's playing a music. I think that command "Join" will help. Btw Thanks for creating bot and public his code. 

PS. Bot is running on other computer with Windows, I think that run Ubuntu on VM.

**Comment by galnir** [comment]
I'm aware of this issue, will be fixed

**Comment by galnir** [comment]
fixed in 3213865
