### ISSUE TITLE
bot cannot respond from container

### ISSUE THREAD

**Issue by LilJohnDee** [galnir/Master-Bot#771]
**Describe the bug**
the bot will run flawlessly with npm run dev while using public lavalink. 
when i try to containerize the bot, none of the commands work. have tried lavalink with the container and public server but i figure this is not the issue. 

**To Reproduce**
completed steps to bring up the bot with npm - launched and operational
ran $ sudo docker compose --env-file docker.env up -d -build 
containers build without error, bot launches but will not respond to any commands.  

1. Use any command
2. provide any argument

**Expected behavior**
expected the bot to run as it did with npm  run

**Screenshots**
n/a

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Ubuntu...]: Ubuntu 20.04
- Node.js Version(Should be v16 at least): v16.19.0
- Is python 2.7 installed?: yes
- How are you hosting the bot(Locally, on a vps, heroku, glitch...): locally

**Additional context**
i really didnt want to open an issue but it seems i require some assistance as i am not well versed in docker as of yet. i have an older version of master-bot running in a container on my unraid server and was hoping to do the same with the new discord api version... Sorry to bother!!!

**Comment by Bacon-Fixation** [comment]
Howdy my friend,

it is not a bother, happy to help. 
even with the container method of running the bot, there should still be a  `Master-Bot/logs` folder created,

highly likely to see something similar to the message below for the last few log entries
```
01-19-2023 11:58:43 error: Client Listener TRPCClientError: Guild not found
01-19-2023 11:58:43 error: Client Listener TRPCClientError: Guild not found
```

guild not found can happen when the bot container was build/created with the bot still in the discord server,
kick the bot from the discord server,then start the docker container, then reinvite the bot to the discord server, should be good to go.

i hope this helps, if you have a different error in the log file, post it here and we can work on getting ya running

Much Love
-Bacon

**Comment by LilJohnDee** [comment]
sorry it took so long... i accidentally wrecked the VM i had it running on and had to rebuild the environment after rescuing my files but that was exactly it!! Thank you so very much!! i have tested a couple of times now and it is exactly as you stated, error and all :) 

I am going to try to push/pull the composite container over to my [unraid server ](https://unraid.net/) but i figured i would ask: Can the composite container now be moved to another location without having to drag the accompanying containers along with it?

**Comment by Bacon-Fixation** [comment]
No worries,
That's a good question, I'm not sure.
I personally haven't used unraid or tried to move a composite container.

Let me know how it goes, I'm curious.
Best of luck my friend

Much Love
-Bacon

**Comment by LilJohnDee** [comment]
after a bit of reading and testing, it seems i will need to mess with the Dockerfile to have all 4 images built within the same container.... if i manage to figure it out would you like me to post the file here?

**Comment by Bacon-Fixation** [comment]
my apologise my friend for the delayed response, more than welcome to post a PR for review. 

`Master-Bot/Dockerfile` has a couple of lines for standalone use. 

i do believe it is possible to run the docker compose on unraid through the gui, 
or third possible option is to create a container for docker compose to run it.

Some more info can be found on the docker compose pr #742 

I hope this helps

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Howdy @LilJohnDee, 
Gonna go ahead close this issue, if you have any other issues or suggestion, please feel free to post them.

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Howdy, there is a small section [Here](https://github.com/galnir/Master-Bot#next-auth-discord-provider) on redirects


>Go to the OAuth2 tab in the developer portal, copy the Client ID to DISCORD_CLIENT_ID and generate a secret to place in >DISCORD_CLIENT_SECRET. Also, set the following URLs under 'Redirects':

> - http://localhost:3000/api/auth/callback/discord

> - http://domain:3000/api/auth/callback/discord
>Make sure to change 'domain' in http://domain:3000/api/auth/callback/discord to your domain or public ip.

double check that you have the redirect urls in your [Discord Dev Portal](https://discord.com/developers/applications) to the example above, in most cases `http://localhost:3000/api/auth/callback/discord` should work 

![image](https://user-images.githubusercontent.com/12632936/222347412-0b384283-5351-4652-8bbc-71774425ae5c.png)


 If you want to use an IP address, make sure the port is available to public

I hope this helps.
If you are still having issues, open a [new issue](https://github.com/galnir/Master-Bot/issues/new?assignees=&labels=bug&template=bug_report.md&title=), and we'll try to get ya running 

Much Love
-Bacon

**Comment by LilJohnDee** [comment]
Thanks, i have seen this bit and messed around with it a bit and think im getting closer.... but will play with it some more and open a ticket if i cant figure it out :) Thanks again for all your help!
