### ISSUE TITLE
Gif commands not working 

### ISSUE THREAD

**Issue by Natemo6348** [galnir/Master-Bot#773]
### IMPORTANT : _DO NOT SKIP THIS STEPS AND DO NOT DELETE THEM. WE CAN NOT HELP YOU IF YOU DO NOT PROVIDE INFORMATION AND STEPS TO REPRODUCE_

Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
No matter what gif command I use, I can't get any of them to work
**To Reproduce**

1. Use any gif command

**Expected behavior**
It should reply with the desired gif
**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Ubuntu...]:Ubuntu 22.04
- Node.js Version(Should be v16 at least): 16.19.1
- Is python 2.7 installed?:Yes
- How are you hosting the bot(Locally, on a vps, heroku, glitch...):Locally

**Additional context**
So far, both the cat and doggo gif commands hang up and it says "The application did not respond", and others reply with their respective "Something went wrong" message and a status code 400 error in terminal. I have checked my API key for tenor and it is still active, and I have been using it for a long time, so I don't think that's the issue. Any help would be much appreciated, thank you in advance!

**Comment by Bacon-Fixation** [comment]
Howdy @Natemo6348,

indeed a lot has changed :D , take a look a `Master-Bot/logs/` and see what the error is,
not sure how long ago you made tenor api key, but the gif commands shifted to a v2 key at some point,
it is highly likely it's something like the following below listed in the logs

```
02-21-2023 20:20:20 error: Request failed with status code 400
```
 you can create on by heading to https://developers.google.com/tenor/guides/quickstart 
and clicking "Tenor Api Key" and selecting your app and editing your `.env` file with the new key

i hope this helps

if that doesn't help, please send the error that is listed in the log file, and we can see what's up 

Much Love
-Bacon

**Comment by Natemo6348** [comment]
After changing API key, cat and doggo still hang on "The application did not respond", but the rest seem to be fixed, so that much is done.

**Comment by Bacon-Fixation** [comment]
@Natemo6348 
hahahah found a type in the /cat and /doggo commands, have a look at #774

Much Love
-Bacon

**Comment by Natemo6348** [comment]
Oh well that explains it all lol, guess I should've looked myself, but oh well, issue was located anyway, that is a lot!

**Comment by Bacon-Fixation** [comment]
It's no worries, my friend

let us know if you have any more issues, <3 soo good to hear from ya again

Much Love
-Bacon

**Comment by Natemo6348** [comment]
@Bacon-Fixation it's good to be back. Also it looks like the bot was shifted to tenor v2 just last month, so if I had been here earlier, I wouldn't have had this problem lol
