### ISSUE TITLE
Invalid enviroment Variables on startup

### ISSUE THREAD

**Issue by DraTrav** [galnir/Master-Bot#777]
**Describe the bug**
on startup the bot fails to load the config and prevents the bot from working at all

**To Reproduce**
1.Start the bot
2. Get error

**Screenshots**
<img width="930" alt="image" src="https://user-images.githubusercontent.com/42803478/221544605-05bebc59-4666-400d-b8a1-3a0b465f36fe.png">

**Desktop (please complete the following information):**

- OS: Debian 11
- Node.js Version(Should be v16 at least): 19.7
- Is python 2.7 installed?: yes
- How are you hosting the bot(Locally, on a vps, heroku, glitch...): Locally

**Comment by Bacon-Fixation** [comment]
Howdy @DraTrav,

double check and make sure "$" character is not used in the `.env`

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
The other thing to try if everything is correct in the `.env`, is using the LTS (Long Term Support) version of nodejs (18.14.2) instead of Latest (19.xx.x)

Much Love
-Bacon

**Comment by DraTrav** [comment]
I had a $ in the password for the database password, removing it fixed the "NEXT_PUBLIC_INVITE_URL" error and the bot started up properly!
