### ISSUE TITLE
Crash when attempting to play song

### ISSUE THREAD

**Issue by DraTrav** [galnir/Master-Bot#779]
### IMPORTANT : _DO NOT SKIP THIS STEPS AND DO NOT DELETE THEM. WE CAN NOT HELP YOU IF YOU DO NOT PROVIDE INFORMATION AND STEPS TO REPRODUCE_

Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
The bot crashes when I attempt to play a song

**To Reproduce**
attempt to play a youtube link
bot crashes and exits with code 1

**Expected behavior**

The song to play

**Screenshots**

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/42803478/229269309-ff8859e9-52a9-4fb3-8e74-40221a2a93c3.png">

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Ubuntu...]: Debian 11
- Node.js Version(Should be v16 at least): v16 and v19
- Is python 2.7 installed?: yes
- How are you hosting the bot(Locally, on a vps, heroku, glitch...):Locally

**Additional context**
I attempted it with several version of java as well as node version with no luck

**Comment by Bacon-Fixation** [comment]
Howdy DraTraV,

i also ran into this error last night, I am working on a solution. Just a heads-up, it may take a little while to resolve, so bare with me a bit. seems the framework needs to be updated.



Much Love
Bacon

**Comment by Bacon-Fixation** [comment]
Howdy again @DraTrav check out PR #780, should get you running while updates are being made

after cloning the PR i would recommend running `npm ci` in terminal, before doing the `npm run dev`

Much Love
-Bacon

**Comment by DraTrav** [comment]
That did fix the crashing and playing problem. However the songs are not skippable and it just says "Error: command chat input DiscordAPIError: Unknown Message" when attempting to run /skip

<img width="538" alt="image" src="https://user-images.githubusercontent.com/42803478/229439402-29ea1582-319e-4b57-b55a-f8adee84ef92.png">

**Comment by Bacon-Fixation** [comment]
i would try running `npm ci` then the `npm run dev`, 

also I'm having a hard time replicating this error, could you send a copy of the log file

there is a log file that is created in the `/Master-Bot/packages/bot/logs` folder (or `/Master-Bot/logs` for docker users)
it may have another error message that came with the `unknown message`


Much Love
-Bacon

**Comment by DraTrav** [comment]
I did update my node to the latest 19.8.1. Still no luck and the same problem


<img width="390" alt="image" src="https://user-images.githubusercontent.com/42803478/229612483-34824d1f-dc7b-42cb-9e22-ba7fd36d739a.png">
[Master-Bot-04-03-2023.log](https://github.com/galnir/Master-Bot/files/11141943/Master-Bot-04-03-2023.log)

**Comment by Bacon-Fixation** [comment]
Thank you my friend, forgive me if I keep repeating some stuff :D, just haven't been able to replicate either error `Client` or `Command Chat Input`, 
Try running `npm run clean-i` (should delete all the `node_modules` folders and do a regular `npm i` to install them)   

if the `npm run clean-i` fails to run, you can delete the following folders manually 
`/Master-Bot/node_modules` 
`/Master-Bot/packages/bot/node_modules`
then run `npm i` to reinstall them and try starting the bot again with `npm run dev`

Much Love
-Bacon

**Comment by DraTrav** [comment]
That did not solve my problem however I figured it out!

something apparently happened with redis, the service was running during my attempts so whatever happened I have no clue. rebooting redis didn't help, however, a full removal and reinstall of redis did.
