### ISSUE TITLE
Seek Command 

### ISSUE THREAD

**Issue by FirezzzZ** [galnir/Master-Bot#78]
Enhancement request for a seek command

**Comment by galnir** [comment]
What do you mean by "seek"? Seek something on YouTube?

**Comment by FirezzzZ** [comment]
like seek a particular time from a music video currently playing
eg - !seek 3:00 which will seek the song being played at 3:00 mins of the song. 
is it possible tho?

**Comment by galnir** [comment]
Ytdl-core doesn't support that, I'm looking into using lavalink which may support that

**Comment by FirezzzZ** [comment]
pls do

**Comment by FirezzzZ** [comment]
why closed?

**Comment by galnir** [comment]
@FirezzzZ  Ytdl-core doesn't support that and switching to lavalink will take some time(testing, learning it etc). It doesn't need to stay open, this feature was on my feature list even before you opened this issue :)

**Comment by FirezzzZ** [comment]
oh ok
