### ISSUE TITLE
Try signing in with a different account 

### ISSUE THREAD

**Issue by DraTrav** [galnir/Master-Bot#781]
**Describe the bug**
When attempting to login to the discord bot's webui I get the error "try signing with a diffrent account"

**To Reproduce**
start bot
go to webui 
attempt to sign in
authorize discord
 
**Expected behavior**
Able to sign in and use the web ui as intended 

**Screenshots**

<img width="802" alt="image" src="https://user-images.githubusercontent.com/42803478/229744976-d135e466-7a1d-43bb-9953-1f5594fd3729.png">

<img width="583" alt="229745006-0f3c6195-3cd6-4961-858a-da7a82740e6b" src="https://user-images.githubusercontent.com/12632936/230016954-3f357d3d-a176-47c5-a830-cfcda8ae55d7.png">

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Ubuntu...]: Debain 11
- Node.js Version(Should be v16 at least): v19.8.1
- Is python 2.7 installed?: yes
- How are you hosting the bot(Locally, on a vps, heroku, glitch...): Locally

**Additional context**
This is probably a miss configuration on my side, just a little lost on how to get the web ui to work.

<img width="892" alt="image" src="https://user-images.githubusercontent.com/42803478/229745313-27f37577-c395-40c6-a2d5-896e8404813a.png">

**Comment by Bacon-Fixation** [comment]
Howdy DraTrav,
I have encountered this one, your DB is missing its Schema, run `npx prisma db push` and run your `npm run dev` should be good to go, 

i should mention if your bot is already in a discord server, you may encounter a "Guild not found" message when running music commands, simply kick the bot from that server and then reinvite the bot, this will enter the info for the Database 

i hope this helps

Much Love
-Bacon

**Comment by DraTrav** [comment]
No such luck, "npx prisma db push" did not fix the issue same error and all, also tried removing the bot and readding and still nothing.

**Comment by DraTrav** [comment]
As you can tell I'm sure, I am great at breaking things, so Thank you for bearing with me through all my issues.

**Comment by Bacon-Fixation** [comment]
Howdy DraTrav, 
it is all good, my friend I've had those days when I break everything too :D, wonderful to hear that you got it going, I will close this issue

If you have any other issues or even suggestions, please feel free to post them and we can work on helping ya out.


Much Love
-Bacon
