### ISSUE TITLE
Twitch command not working

### ISSUE THREAD

**Issue by lITronusIl** [galnir/Master-Bot#787]
i created an .env with the twitch infos, bot says it doesnt know that command

**Comment by Bacon-Fixation** [comment]
Howdy @lITronusIl, 

are you getting an error message? (there is a log file that is created `/Master-Bot/packages/bot/logs/`)

make sure the info is correct in the `.env`

if the bot was initially running without twitch commands then were added after, it may take a while for Discords command registry to update for your client, can try closing your discord and relaunching it,

Hope this Help

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Howdy @lITronusIl,

wondering if you still needed assistance with the Twitch Commands

Much Love
-Bacon

**Comment by lITronusIl** [comment]
Oh sorry, missed that up, its working all fine now.

**Comment by Bacon-Fixation** [comment]
That's wonderful to hear, if you run into any issue please feel free to let us know <3

Much Love
-Bacon
