### ISSUE TITLE
Top and Controversial not working in Reddit command 

### ISSUE THREAD

**Issue by Natemo6348** [galnir/Master-Bot#789]
### IMPORTANT : _DO NOT SKIP THIS STEPS AND DO NOT DELETE THEM. WE CAN NOT HELP YOU IF YOU DO NOT PROVIDE INFORMATION AND STEPS TO REPRODUCE_

Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug**
Every time I try to sort posts with top or controversial, it continuously says that it is thinking, while console says error: Command Chat Input DiscordAPIError[50035]: Invalid Form Body [1] components[0].components[0][UNION_TYPE_CHOICES]: Value of field "type" must be one of (5, 8, 4, 7, 3, 2, 6).
**To Reproduce**

1. Use 'reddit' command
2. provide 'top' or 'controversial' argument for sort
3. Get error and never get response

**Expected behavior**
It should have sent response with top or controversial sort
**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Windows, Ubuntu...]: Ubuntu 22.04
- Node.js Version(Should be v16 at least): 18.16.0
- Is python 2.7 installed?: Yes
- How are you hosting the bot(Locally, on a vps, heroku, glitch...): Locally

**Additional context**
The other 'sort' options work just fine

**Comment by Bacon-Fixation** [comment]
Howdy @Natemo6348,

Thank you for reporting the bug, I have posted Pr #790 which should resolve this issue my friend


Much Love
-Bacon

**Comment by Natemo6348** [comment]
Thanks @Bacon-Fixation for the fix, I was gonna attempt to fix it myself, but I just couldn't make sense of it lol
