### ISSUE TITLE
npm run dev:bot exited with code -4058 & npm run dev:dashboard exited with code -4058

### ISSUE THREAD

**Issue by MichaelDA123** [galnir/Master-Bot#794]
Hello i want to asking for this error, i've follow all the instructions step by step but when i try to npm run dev. it show like this
**I'm using v18.17.0 Node**

> master-bot-mono@1.0.0 dev
> npm run copy-env && concurrently "npm run dev:dashboard" "npm run dev:bot"

> master-bot-mono@1.0.0 copy-env
> cpy .env ./packages/dashboard

[0] Error occurred when executing command: npm run dev:dashboard
[0] Error: spawn cmd.exe ENOENT
[0]     at ChildProcess._handle.onexit (node:internal/child_process:283:19)
[0]     at onErrorNT (node:internal/child_process:476:16)
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[1] Error occurred when executing command: npm run dev:bot
[1] Error: spawn cmd.exe ENOENT
[1]     at ChildProcess._handle.onexit (node:internal/child_process:283:19)
[1]     at onErrorNT (node:internal/child_process:476:16)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[1] npm run dev:bot exited with code -4058
[0] npm run dev:dashboard exited with code -4058

**Comment by Bacon-Fixation** [comment]
Howdy @MichaelDA123 , seem the node was unable to locate a file it was looking for, a few things that may help.

Make sure the `.env` is present in `/Master-Bot/` folder 

Run `cmd.exe` in administrator when running `npm run dev`




Much Love
-Bacon

**Comment by MichaelDA123** [comment]
![Master](https://github.com/galnir/Master-Bot/assets/111888654/456fa5ab-c9bb-4e44-b8d1-906fde672e7f)
![image](https://github.com/galnir/Master-Bot/assets/111888654/eba87a93-43e6-4e80-8f8b-c8299e8f5993)

@Bacon-Fixation Ah yes, for the `.env` file i've put it in root file but the error still same

**Comment by MichaelDA123** [comment]
There is 2 env, `.env.example and` `.docker.env`. im just setup `.env.example` because I'm never use docker before, and I'm planning to host the bot in hosting service.

**Comment by Bacon-Fixation** [comment]
Seems that the redis server is not running on localhost [More Info](https://github.com/galnir/Master-Bot#redis) bot looks for a redis connection at 127.0.0.1:6379 (localhost) by default it assumes redis is running on the same host as the nodejs instance, if you would like to assign a different location you can add `REDIS_HOST='url2redisServer'`
`REDIS_PORT=5679` to the bottom of the `.env` to connect to an outside redis server 

Redis options available through the `.env`
```
 REDIS_HOST="url2redis" 
 REDIS_PORT=6379
 REDIS_DB=0
 REDIS_PASSWORD="redisPassword"

```

I hope this helps


Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Howdy @MichaelDA123, 
Just wanted to catch up with you, and see if you were still having issues

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
@MichaelDA123 gunna go head and close this issue. If you are still having issues or have suggestions, please feel free to open a new tap


Much Love
-Bacon
