### ISSUE TITLE
TypeError: Cannot read property 'hours' of undefined

### ISSUE THREAD

**Issue by ShinoGFX** [galnir/Master-Bot#80]
Not sure how to fix this. Any ideas?

**Comment by zoranzoki21** [comment]
Hello @ShinoGFX can you provide us some details like when this happens, for which code?...

**Comment by ShinoGFX** [comment]
This happens when i attempt to play a song using the play command. Nothing happens and it pops up with this error. Nothing shows in console either

**Comment by zoranzoki21** [comment]
Have you installed all dependencies via `npm i`?
Also, there are any errors in command line/terminal when you run it..
And, which node.js/npm version you have?

**Comment by ShinoGFX** [comment]
I have the correct node version. AKA latest. Seems im missing windows build tools 5.2.2
Going to install that and check again.

**Comment by ShinoGFX** [comment]
When i do npm i, i get this error


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Yuna\Desktop\Bot\Master-Bot-master\node_modules\ref
gyp ERR! node -v v14.3.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

**Comment by ShinoGFX** [comment]
As well as tons of these errors before it 

c:\users\yuna\desktop\bot\master-bot-master\node_modules\ref\src\binding.cc(642): error C2661: 'v8::Object::Set': no ov
erloaded function takes 2 arguments [C:\Users\Yuna\Desktop\Bot\Master-Bot-master\node_modules\ref\build\binding.vcxproj
]

**Comment by galnir** [comment]
I recommend you to Google "node-gyp error", I can't help you solve that since it's a problem on your end :/
