### ISSUE TITLE
Not able to access website and bot not responding on discord.

### ISSUE THREAD

**Issue by RealAmethyst** [galnir/Master-Bot#806]
### IMPORTANT : _DO NOT SKIP THIS STEPS AND DO NOT DELETE THEM. WE CAN NOT HELP YOU IF YOU DO NOT PROVIDE INFORMATION AND STEPS TO REPRODUCE_

Do not open an issue if you simply "copied" code over to your bot/another bot. This is absolutely not recommended and will cause bugs. Also do not open an issue if you modified code and added features and now it's not working right. This is because I can't figure it out and don't have the time to read your code and find out what you did wrong.

**Describe the bug** The website does not load and the bot is not responding on discord. It starts as normal and is all fine, lavalink connects and the bot is online, but it's not working.

**To Reproduce** 

1. Start the bot with pnpm dev
2. the bot will start and nothing will be wrong in the console, but as soon as you try to do anything it doesn't work. argument

**Expected behavior** The bot should work fine on discord and the website should be accessible from my domain.

**Screenshots**

**Desktop (please complete the following information):**

- OS:Ubuntu 22.04 [e.g. Windows, Ubuntu...]:
- Node.js Version 18.18.0(Should be v16 at least):
- Is python 2.7 installed?: No
- How are you hosting the botOn a Linode VPS (Locally, on a vps, heroku, glitch...):

**Additional context**

**Comment by Bacon-Fixation** [comment]
Howdy @RealAmethyst
May need to be inside your Linode Server to bring up the webpage

in the `.env`  set `NEXTAUTH_URL=`http://localhost:3000/'`
SSH into your Linode session open a browser in the Linode Server and head to `http://localhost:3000` and should be able to invite the bot to your guild

im not exactly sure how to create a domain on Linode for people how are not ssh'd into the linode server

Much Love
-Bacon

**Comment by Bacon-Fixation** [comment]
Howdy @RealAmethyst ,


Just wanted to get back with you, and see if you were still having issues 


Much Love
-Bacon
