### ISSUE TITLE
Disable commands

### ISSUE THREAD

**Issue by GenryMg** [galnir/Master-Bot#81]
Is it possible to disable the help and gif commands? I want the bot to be solely music commands.

Thanks

**Comment by galnir** [comment]
Disable help - add **help: false** after line 45 in index.js, so registerDefaultCommands will look like: 
`
  .registerDefaultCommands({
    eval: false,
    prefix: false,
    commandState: false,
    help: false
  })
`

Disable gif commands - delete the gifs folder under the 'commands' directory, and delete line 37 in index.js

**Comment by GenryMg** [comment]
ah ok. Is it possible to disable the `Unknown command. Use !help or @dankservermusicbot help to view the command list.` as well?

**Comment by galnir** [comment]
You can set more built-in commands/prompts as false as well. Take a look [here](https://discord.js.org/#/docs/commando/master/class/CommandoRegistry?scrollTo=registerDefaultCommands). The one you're looking for is **unknownCommand**.
