### ISSUE TITLE
Guild member add

### ISSUE THREAD

**Issue by royalus** [galnir/Master-Bot#82]
![ap](https://user-images.githubusercontent.com/59321692/82764394-9bde7680-9e0e-11ea-8d0e-81950a91cc7b.png)
*

**Comment by FirezzzZ** [comment]
channel is not defined therefore not a function

**Comment by galnir** [comment]
@royalus did you change anything in index.js? Also make sure the channel name is correct(if you didn't change it it's 'general').

**Comment by royalus** [comment]
> @royalus did you change anything in index.js? Also make sure the channel name is correct(if you didn't change it it's 'general').

okay, i'll check the index

**Comment by royalus** [comment]
its working great now thank you for this amazing bot <3

**Comment by galnir** [comment]
Thanks, drop a star if you wanna show some appreciation :)

**Comment by royalus** [comment]
sure. one more question i have add the channel with # but each user join the channel didnt mention

**Comment by galnir** [comment]
Just the channel name without#
