### ISSUE TITLE
Bot keeps leaving channel after using (prefix)play

### ISSUE THREAD

**Issue by MrMudkip** [galnir/Master-Bot#88]
**Describe the bug**
The bot keeps leaving the voice channel after I use (prefix)play.

**To Reproduce**
1. Use 'play' while in a music voice channel
2. After that, put a YouTube link when it asks for one

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version(Should be v12 atleast): 13.9.0
 - Are python 2.7 and Ffmpeg installed?: Yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): Locally

**Additional context**
I was trying to rickroll myself xD

**Comment by galnir** [comment]
What do you mean? Does it leave the channel after it finishes playing the song?

**Comment by MrMudkip** [comment]
No, it just leaves the voice channel. After I do (prefix)play, it joins and leaves Leon Peter Keates / Year 9 Studentrealuprising2005@gmail.com / 07508412227  From: NirSent: 30 May 2020 12:21To: galnir/Master-BotCc: MrMudkip; AuthorSubject: Re: [galnir/Master-Bot] Bot keeps leaving channel after using (prefix)play (#88) What do you mean? Does it leave the channel after it finishes playing the song?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by galnir** [comment]
So check what I said about node opus build

**Comment by MrMudkip** [comment]
What do you mean? Leon Peter Keates / Year 9 Studentrealuprising2005@gmail.com / 07508412227  From: NirSent: 30 May 2020 13:37To: galnir/Master-BotCc: MrMudkip; AuthorSubject: Re: [galnir/Master-Bot] Bot keeps leaving channel after using (prefix)play (#88) So check what I said about node opus build—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by zoranzoki21** [comment]
I no understand there responds with private data and "font definitions"... :thinking:

**Comment by galnir** [comment]
@MrMudkip Like I told you in the first reply, your node-opus build probably failed... I said ```npm i ``` again and check for errors

**Comment by MrMudkip** [comment]
> I no understand there responds with private data and "font definitions"... 🤔

That's because I sent it via email

**Comment by MrMudkip** [comment]
Alright, I did do that, then node-gyp rebuild. Not ok

**Comment by galnir** [comment]
@MrMudkip , Yeah as I suspected. There are a many possibilities for why it happens, I can only help you by telling you to Google "node-gyp build error" and try one of the solutions.

**Comment by MrMudkip** [comment]
I also found out, that node-opus@0.3.3 is been deprecated. I also tried using the alternative. Still failed. I don't even know what the heck is happening :/

**Comment by galnir** [comment]
Playing around with packages won't do good. Yeah, node-opus had been deprecated but it still works, I'll replace it with @discordjs@opus after I make sure it doesn't break anything.

**Comment by MrMudkip** [comment]
Its done now! I fixed it, music plays awesome HD 4k 1080p jk I am just spamming xD
