### ISSUE TITLE
Music-trivia (timing)

### ISSUE THREAD

**Issue by Chamalaw** [galnir/Master-Bot#89]
Hello I would like to know if it's possible to start the songs in the music-trivia from a specific moment.
By simply adding the url with #t=0m30s nothing happens.
By the way, thank you for sharing this code.

**Comment by galnir** [comment]
Adding #t=0m30s won't work because ytdl-core returns a readable stream of the video regardless of what parameters are in its url. The only way to **songs** from a specific moment would be to add a "begin" property in line 94(musictrivia.js) and set a value of 30s.

**Comment by galnir** [comment]
Oh I'm sorry, I just read the "begin" option is deprecated due to unreliability :/
There is no other way I'm aware of to do so with ytdl-core (which the bot uses)
