### ISSUE TITLE
setup issue :/

### ISSUE THREAD

**Issue by Snoker87** [galnir/Master-Bot#90]
I'm having an issue with "npm i" if I deleted the package.json it will be installed but without the required modules.
I'm sure it's from the dependencies.
**Screenshots**
http://prntscr.com/stbisa

 - Windows
 - Node Version installed
 - python 2.7 Ffmpeg is installed.
 - Local server

Sorry if this sounds a stupid question to ask 😞.

**Comment by Sup-Sup123** [comment]
Can you show me the full error I might be able to help

>

**Comment by galnir** [comment]
Why would you delete package.json? This file tells npm which modules to install
