### ISSUE TITLE
TypeError: Cannot read property 'hits' of undefined

### ISSUE THREAD

**Issue by Lebyy** [galnir/Master-Bot#91]
It is a cannot read property error with the lyrics command
which says `TypeError: Cannot read property 'hits' of undefined` in logs and `Something when wrong, please try again or be more specific` in the guild.

**To Reproduce**
1) Play any song
2) and run the lyrics command

The discord.js-commando version is 0.10.0 and discord.js is latest too.

**Comment by galnir** [comment]
Make sure you generated and placed a correct API key in config.json , because that's the only way you'd get that error

**Comment by Lebyy** [comment]
Oh-

**Comment by Lebyy** [comment]
I verified my key twice.

**Comment by Lebyy** [comment]
Fixed I was dumb.
