### ISSUE TITLE
ECONNRESET on play command

### ISSUE THREAD

**Issue by Burday** [galnir/Master-Bot#93]
**Describe the bug**
The bot was working perfectly fine, when suddenly the play command would just result in 
`FetchError: request to https://discordapp.com/api/v7/channels/471454389693972480/messages failed, reason: read ECONNRESET`

Cannot be reproduced with any other command.

Steps I took to fix the issue:
- updated dependencies 

**To Reproduce**
1. Use !play

**Expected behavior**
Music to start playing

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version: 13.1 
 - Are python 2.7 and Ffmpeg installed?: Yes
 - How are you hosting the bot: Locally

**Comment by Burday** [comment]
Was able to reproduce with the latest release too.

**Comment by galnir** [comment]
That's probably an issue with your connection. ECONNRESET usually imply network issues/slow network.

**Comment by Burday** [comment]
My upload/download speeds seem good, however I don't have a device on another network on which I can attempt reproducing the issue. The bot ping is around 100ms. 

More information about the issue: The first time the issue occurred was when adding a song to the queue, while another song was already playing. I haven't had problems with internet at that time and since then.

**Comment by galnir** [comment]
ECONNRESET means your connection to discord was interrupted. I host the bot on a VPS and test it locally(on a good network), and never seen this error :/

**Comment by Burday** [comment]
Hmm, that's fairly weird. Only occurs in this command and can't reproduce in other commands from other projects I have. Gonna try to reproduce it on a different network, maybe a hosting site.

**Comment by Burday** [comment]
Okay, I was able to reproduce it on a different network, but only once. I assume it's a local issue, gonna let you know if I encounter it again and if I figure out for certain it's something caused by the code.

**Comment by galnir** [comment]
@Burday No problem, comment on this issue if it'll be relevant
