### ISSUE TITLE
Custom Prefixes cleared on restart

### ISSUE THREAD

**Issue by ThaddeusKKR** [galnir/Master-Bot#94]
**Describe the bug**
When someone sets the custom prefix of the bot for the server using <prefix>prefix <newPrefix>,
the custom prefix resets on the next restart. (May only happen on Heroku?)

**To Reproduce**
1. Use <prefix>prefix <newprefix>
2. Restart the bot (I don't know if this only happens on Heroku)

**Expected behavior**
All custom prefixes are saved and remains the same.

**Desktop (please complete the following information):**
 - OS: 
 - Node Version(Should be v12 atleast): v12.18.0
 - Are python 2.7 and Ffmpeg installed?: Yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): Heroku

**Additional context**
I don't know if this only happens on Heroku or on other hosting methods as well.

**Comment by galnir** [comment]
The prefix command comes built-in with Commando. I'm gonna disable it since as you said, it gets reset every time you restart the bot

**Comment by ThaddeusKKR** [comment]
Okay

**Comment by thomasthebro1** [comment]
Just adding to this (and I know that it has already been closed)
To add support for saving the prefixes, you need to initialise a SQLite database in the main file for the bot.

**Comment by galnir** [comment]
Yeah, I'm already writing a new feature with Mongo, so there's that
