### ISSUE TITLE
Cannot find and play songs 

### ISSUE THREAD

**Issue by Burday** [galnir/Master-Bot#96]
**Describe the bug**
Cannot play songs, issues when searching for songs.

**To Reproduce**
1. Use 'play' command
2. provide 'hands up macklemore' argument (for example, works with other arguments too)

**Expected behavior**
Song played.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version: 13.10
 - Are python 2.7 and Ffmpeg installed?: Yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): Heroku

**Additional context**
Whenever the command is used, it will respond with "There was a problem searching the video you requested :(" and with "Please pick a song - 1. exit 2. undefined 3. undefined 4. undefined 5. undefined". For reference, it fails to work on provided arguments that used to work yesterday. 

Some arguments work and play the song successfully so I can imagine it's something unrelated to my API key.

Tried hosting it locally to see if issues remain and they did. I assume it's an issue related to the YouTube API, but not sure.

**Comment by galnir** [comment]
I don't have any problem playing songs both locally and on a VPS(different operating systems). Did you modify anything in play.js? Is your api key correct?

**Comment by Burday** [comment]
I havent changed anything. It only happens on some specific ones that used to work before. Other songs play well so it's probably not API key

**Comment by galnir** [comment]
Did you API key hit its [quota limit](https://console.developers.google.com/iam-admin/quotas)?

**Comment by Burday** [comment]
Well under it. It works on some songs so I imagine it still connects to the API.

**Comment by galnir** [comment]
Does it output any error to the console?

**Comment by Burday** [comment]
Hey, I was just able to reproduce it again. It shows no errors in the console and sends no errors in chat. [Here is what it sends when you try to play a song](https://i.imgur.com/NbxG8L4.png). While it is near it's daily quota limit, it's not at the peak and worked just fine a few days ago with higher quotas per day. I imagine it's quota limit related, but the weird thing is, it happens to most queries for a song title but still works for some specific ones.

**Comment by galnir** [comment]
This issue usually happens when you search for something like "ajdbddndmmdblah" so the API returns no results (I need to fix that as well). But the weird thing is you say it happens when looking for a song. What are you searching?

**Comment by Burday** [comment]
Okay I was able to narrow it down to API quota being too close to the limit for it to work, despite not maxing out. That's why I was confused before, it wasn't on max but was close to it and still didn't work. It just reset and now it works so I imagine it's not a problem with the code. Sorry for the issue.

**Comment by galnir** [comment]
I'm looking into ways of reducing the amount of quota units used, so it may solve issues like this one

**Comment by galnir** [comment]
@Burday, btw you can contact YouTube through the quota page(somewhere there), fill a long form and you might get your quota limit raised(I got mine to 1m from 10k)
