### ISSUE TITLE
Help Command

### ISSUE THREAD

**Issue by l0vo** [galnir/Master-Bot#97]
Thank you for posting this, but I was wondering if there was a way to remove when the bot DM's you the commands for the bot, I have been spending so long to try and find it but I can't.

**Comment by galnir** [comment]
You mean disabling the help command?

**Comment by l0vo** [comment]
Yea I have spent so long looking for it but I can't find it

**Comment by l0vo** [comment]
Only when I delete the commands they go away

**Comment by galnir** [comment]
Read #81

**Comment by l0vo** [comment]
Thanks that worked, is there a way to disable the Unkown Command?

**Comment by l0vo** [comment]
Unknown command. Use $help or @Beat Box#4323 help to view the command list.

**Comment by galnir** [comment]
Do the same you did with help just with 'unknownCommand'

**Comment by l0vo** [comment]
unknownCommand: false

like this?

**Comment by l0vo** [comment]
I got it, thanks for the help!
