### ISSUE TITLE
Can't play any song

### ISSUE THREAD

**Issue by the-maty** [galnir/Master-Bot#98]
**Describe the bug**

**To Reproduce**
1. Use 'x' command
2. provide 'y' argument

**Expected behavior**
A clear and concise description of what you expected to happen. I wanted to start playing song but this appeared An error occurred while running the command: TypeError: fields.flat is not a function
You shouldn't ever receive an error like this.
Please contact (my discord name)

**Screenshots**
![image](https://user-images.githubusercontent.com/52372122/84879373-6b939c00-b08b-11ea-803a-6c1e46b7ab03.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu...]: Ubuntu 20.4
 - Node Version(Should be v12 atleast): 12.18
 - Are python 2.7 and Ffmpeg installed?: Yes
 - How are you hosting the bot(Locally, on a vps, heroku, glitch...): VPS

**Additional context**

**Comment by galnir** [comment]
Update your Node version to v12 atleast

**Comment by the-maty** [comment]
I will try reinstalling node and update it to latest

**Comment by galnir** [comment]
This is the solution to this problem, comment here if it doesn't work

**Comment by the-maty** [comment]
Reinstalled node, installed version 14 and its working now... Thanks for your quick response. :)
